### ISSUE TITLE
Multiple issues render theia >= 1.17 unusable

### ISSUE THREAD

**Issue by Jarthianur** [eclipse-theia/theia#10042]
### Bug Description:

Multiple issues appeared with version 1.17 in theia web-UI:
- top menu bar is not displayed
- file explorer misses refresh/collapse-all buttons
- right-click context menu misses almost all entries
- settings cog in lower left corner does not open a dialog
- key bindings do not work anymore, eg. ctrl-s open the browsers save dialog instead of saving the file opened in editor

### Steps to Reproduce:

1. build a theia application using provided Dockerfile
2. Visit the app in browser
3. Find above issues

Honestly, I can't imagine all these issues are caused by faulty theia code. Hence I'm searching for mistakes on my side...

What I did so far to test:
- Built theia version 1.17.0/1/2, next (master)
- remove all custom plugins, extensions
- use different base images
- try several node versions of 12 and 14 (14 of course not working)
- use all minor versions of builtin extensions from 1.49 to 1.59
- tried firefox and chromium with cleared browsing data
- compared my package.json to those in examples/browser, theia-apps, and theia-blueprint
- building docker images in a clean environment

None of these permutations changed anything. Theia version 1.16 works flawlessly though. Maybe I missed some important change of version 1.17?

#### Dockerfile

```Dockerfile
FROM debian:buster

ARG THEIA_UID=1337

RUN apt update && \
    apt dist-upgrade -y -qq && \
    apt install -y -qq \
      tar grep mawk wget git openssh-client make gcc python2 vim bash-completion binutils build-essential libssl-dev libsecret-1-0 && \
    apt autoremove -y -qq && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -s /bin/bash -m -d /home/theia -U -u $THEIA_UID -c '' theia && \
    chmod g+rw /home && \
    mkdir -p /home/project && \
    chown -R theia:theia /home/theia && \
    chown -R theia:theia /home/project

ADD settings.json /home/theia/.theia/
ADD .gitconfig /home/theia/

RUN chown -R theia:theia /home/theia

USER theia
WORKDIR /home/theia
ADD package.json ./package.json

RUN wget -q https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh -O /tmp/nvm-install.sh && \
    bash /tmp/nvm-install.sh && \
    rm -f /tmp/nvm-install.sh && \
    export NVM_DIR="/home/theia/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && \
    nvm install 12 && \
    nvm use 12 && \
    mkdir bin && \
    ln -s "$(echo -n $PATH | tr ':' '\n' | grep nvm)/node" /home/theia/bin/node && \
    ln -s "$(echo -n $PATH | tr ':' '\n' | grep nvm)/npm" /home/theia/bin/npm && \
    npm config set python /usr/bin/python2 --global && \
    npm config set python /usr/bin/python2

ENV PATH=/home/theia/bin:/home/theia/.local/bin:$PATH

RUN mkdir yarn && cd yarn && \
    npm install --no-save --prefix ./ yarn && cd .. && \
    YARN=/home/theia/yarn/node_modules/.bin/yarn && \
    $YARN --pure-lockfile && \
    NODE_OPTIONS="--max_old_space_size=4096" $YARN theia build && \
    $YARN theia download:plugins && \
    $YARN --production && \
    $YARN autoclean --init && \
    echo *.ts >> .yarnclean && \
    echo *.ts.map >> .yarnclean && \
    echo *.spec.* >> .yarnclean && \
    $YARN autoclean --force && \
    $YARN cache clean && \
    rm -rf .yarnclean yarn

ENV THEIA_DEFAULT_PLUGINS=local-dir:/home/theia/plugins \
    SHELL=/bin/bash \
    VISUAL=vim \
    EDITOR=vim

EXPOSE 3000

ENTRYPOINT [ "node", "/home/theia/src-gen/backend/main.js", "/home/project", "--hostname=0.0.0.0" ]
```

#### package.json

```json
{
  "dependencies": {
    "@theia/bulk-edit": "next",
    "@theia/callhierarchy": "next",
    "@theia/console": "next",
    "@theia/core": "next",
    "@theia/cpp-debug": "next",
    "@theia/debug": "next",
    "@theia/editor": "next",
    "@theia/editor-preview": "next",
    "@theia/file-search": "next",
    "@theia/filesystem": "next",
    "@theia/getting-started": "next",
    "@theia/git": "next",
    "@theia/keymaps": "next",
    "@theia/markers": "next",
    "@theia/messages": "next",
    "@theia/metrics": "next",
    "@theia/mini-browser": "next",
    "@theia/monaco": "next",
    "@theia/navigator": "next",
    "@theia/outline-view": "next",
    "@theia/output": "next",
    "@theia/plugin-dev": "next",
    "@theia/plugin-ext": "next",
    "@theia/plugin-ext-vscode": "next",
    "@theia/plugin-metrics": "next",
    "@theia/preferences": "next",
    "@theia/preview": "next",
    "@theia/process": "next",
    "@theia/property-view": "next",
    "@theia/scm": "next",
    "@theia/scm-extra": "next",
    "@theia/search-in-workspace": "next",
    "@theia/task": "next",
    "@theia/terminal": "next",
    "@theia/timeline": "next",
    "@theia/typehierarchy": "next",
    "@theia/userstorage": "next",
    "@theia/variable-resolver": "next",
    "@theia/workspace": "next"
  },
  "devDependencies": {
    "@theia/cli": "next"
  },
  "license": "Apache-2.0",
  "name": "@theia/theia-my-app",
  "private": true,
  "scripts": {
    "preinstall": "node-gyp install"
  },
  "theia": {
    "frontend": {
      "config": {
        "applicationName": "MyApp",
        "preferences": {
          "files.enableTrash": false
        }
      }
    }
  },
  "theiaPlugins": {
    "vscode-builtin-bat": "https://open-vsx.org/api/vscode/bat/1.49.3/file/vscode.bat-1.49.3.vsix",
    "vscode-builtin-clojure": "https://open-vsx.org/api/vscode/clojure/1.49.3/file/vscode.clojure-1.49.3.vsix",
    "vscode-builtin-coffeescript": "https://open-vsx.org/api/vscode/coffeescript/1.49.3/file/vscode.coffeescript-1.49.3.vsix",
    "vscode-builtin-configuration-editing": "https://open-vsx.org/api/vscode/configuration-editing/1.49.3/file/vscode.configuration-editing-1.49.3.vsix",
    "vscode-builtin-cpp": "https://open-vsx.org/api/vscode/cpp/1.49.3/file/vscode.cpp-1.49.3.vsix",
    "vscode-builtin-csharp": "https://open-vsx.org/api/vscode/csharp/1.49.3/file/vscode.csharp-1.49.3.vsix",
    "vscode-builtin-css": "https://open-vsx.org/api/vscode/css/1.49.3/file/vscode.css-1.49.3.vsix",
    "vscode-builtin-css-language-features": "https://open-vsx.org/api/vscode/css-language-features/1.49.3/file/vscode.css-language-features-1.49.3.vsix",
    "vscode-builtin-debug-auto-launch": "https://open-vsx.org/api/vscode/debug-auto-launch/1.49.3/file/vscode.debug-auto-launch-1.49.3.vsix",
    "vscode-builtin-docker": "https://open-vsx.org/api/vscode/docker/1.49.3/file/vscode.docker-1.49.3.vsix",
    "vscode-builtin-emmet": "https://open-vsx.org/api/vscode/emmet/1.49.3/file/vscode.emmet-1.49.3.vsix",
    "vscode-builtin-fsharp": "https://open-vsx.org/api/vscode/fsharp/1.49.3/file/vscode.fsharp-1.49.3.vsix",
    "vscode-builtin-go": "https://open-vsx.org/api/vscode/go/1.49.3/file/vscode.go-1.49.3.vsix",
    "vscode-builtin-groovy": "https://open-vsx.org/api/vscode/groovy/1.49.3/file/vscode.groovy-1.49.3.vsix",
    "vscode-builtin-grunt": "https://open-vsx.org/api/vscode/grunt/1.49.3/file/vscode.grunt-1.49.3.vsix",
    "vscode-builtin-gulp": "https://open-vsx.org/api/vscode/gulp/1.49.3/file/vscode.gulp-1.49.3.vsix",
    "vscode-builtin-handlebars": "https://open-vsx.org/api/vscode/handlebars/1.49.3/file/vscode.handlebars-1.49.3.vsix",
    "vscode-builtin-hlsl": "https://open-vsx.org/api/vscode/hlsl/1.49.3/file/vscode.hlsl-1.49.3.vsix",
    "vscode-builtin-html": "https://open-vsx.org/api/vscode/html/1.49.3/file/vscode.html-1.49.3.vsix",
    "vscode-builtin-html-language-features": "https://open-vsx.org/api/vscode/html-language-features/1.49.3/file/vscode.html-language-features-1.49.3.vsix",
    "vscode-builtin-icon-theme-seti": "https://open-vsx.org/api/vscode/vscode-theme-seti/1.49.3/file/vscode.vscode-theme-seti-1.49.3.vsix",
    "vscode-builtin-image-preview": "https://open-vsx.org/api/vscode/image-preview/1.49.3/file/vscode.image-preview-1.49.3.vsix",
    "vscode-builtin-ini": "https://open-vsx.org/api/vscode/ini/1.49.3/file/vscode.ini-1.49.3.vsix",
    "vscode-builtin-jake": "https://open-vsx.org/api/vscode/jake/1.49.3/file/vscode.jake-1.49.3.vsix",
    "vscode-builtin-java": "https://open-vsx.org/api/vscode/java/1.49.3/file/vscode.java-1.49.3.vsix",
    "vscode-builtin-javascript": "https://open-vsx.org/api/vscode/javascript/1.49.3/file/vscode.javascript-1.49.3.vsix",
    "vscode-builtin-json": "https://open-vsx.org/api/vscode/json/1.49.3/file/vscode.json-1.49.3.vsix",
    "vscode-builtin-json-language-features": "https://open-vsx.org/api/vscode/json-language-features/1.49.3/file/vscode.json-language-features-1.49.3.vsix",
    "vscode-builtin-less": "https://open-vsx.org/api/vscode/less/1.49.3/file/vscode.less-1.49.3.vsix",
    "vscode-builtin-log": "https://open-vsx.org/api/vscode/log/1.49.3/file/vscode.log-1.49.3.vsix",
    "vscode-builtin-lua": "https://open-vsx.org/api/vscode/lua/1.49.3/file/vscode.lua-1.49.3.vsix",
    "vscode-builtin-make": "https://open-vsx.org/api/vscode/make/1.49.3/file/vscode.make-1.49.3.vsix",
    "vscode-builtin-markdown": "https://open-vsx.org/api/vscode/markdown/1.49.3/file/vscode.markdown-1.49.3.vsix",
    "vscode-builtin-markdown-language-features": "https://open-vsx.org/api/vscode/markdown-language-features/1.39.2/file/vscode.markdown-language-features-1.39.2.vsix",
    "vscode-builtin-merge-conflict": "https://open-vsx.org/api/vscode/merge-conflict/1.49.3/file/vscode.merge-conflict-1.49.3.vsix",
    "vscode-builtin-npm": "https://open-vsx.org/api/vscode/npm/1.49.3/file/vscode.npm-1.49.3.vsix",
    "vscode-builtin-objective-c": "https://open-vsx.org/api/vscode/objective-c/1.49.3/file/vscode.objective-c-1.49.3.vsix",
    "vscode-builtin-perl": "https://open-vsx.org/api/vscode/perl/1.49.3/file/vscode.perl-1.49.3.vsix",
    "vscode-builtin-php": "https://open-vsx.org/api/vscode/php/1.49.3/file/vscode.php-1.49.3.vsix",
    "vscode-builtin-php-language-features": "https://open-vsx.org/api/vscode/php-language-features/1.49.3/file/vscode.php-language-features-1.49.3.vsix",
    "vscode-builtin-powershell": "https://open-vsx.org/api/vscode/powershell/1.49.3/file/vscode.powershell-1.49.3.vsix",
    "vscode-builtin-pug": "https://open-vsx.org/api/vscode/pug/1.49.3/file/vscode.pug-1.49.3.vsix",
    "vscode-builtin-python": "https://open-vsx.org/api/vscode/python/1.49.3/file/vscode.python-1.49.3.vsix",
    "vscode-builtin-r": "https://open-vsx.org/api/vscode/r/1.49.3/file/vscode.r-1.49.3.vsix",
    "vscode-builtin-razor": "https://open-vsx.org/api/vscode/razor/1.49.3/file/vscode.razor-1.49.3.vsix",
    "vscode-builtin-ruby": "https://open-vsx.org/api/vscode/ruby/1.49.3/file/vscode.ruby-1.49.3.vsix",
    "vscode-builtin-rust": "https://open-vsx.org/api/vscode/rust/1.49.3/file/vscode.rust-1.49.3.vsix",
    "vscode-builtin-scss": "https://open-vsx.org/api/vscode/scss/1.49.3/file/vscode.scss-1.49.3.vsix",
    "vscode-builtin-search-result": "https://open-vsx.org/api/vscode/search-result/1.49.3/file/vscode.search-result-1.49.3.vsix",
    "vscode-builtin-shaderlab": "https://open-vsx.org/api/vscode/shaderlab/1.49.3/file/vscode.shaderlab-1.49.3.vsix",
    "vscode-builtin-shellscript": "https://open-vsx.org/api/vscode/shellscript/1.49.3/file/vscode.shellscript-1.49.3.vsix",
    "vscode-builtin-sql": "https://open-vsx.org/api/vscode/sql/1.49.3/file/vscode.sql-1.49.3.vsix",
    "vscode-builtin-swift": "https://open-vsx.org/api/vscode/swift/1.49.3/file/vscode.swift-1.49.3.vsix",
    "vscode-builtin-theme-abyss": "https://open-vsx.org/api/vscode/theme-abyss/1.49.3/file/vscode.theme-abyss-1.49.3.vsix",
    "vscode-builtin-theme-defaults": "https://open-vsx.org/api/vscode/theme-defaults/1.49.3/file/vscode.theme-defaults-1.49.3.vsix",
    "vscode-builtin-theme-kimbie-dark": "https://open-vsx.org/api/vscode/theme-kimbie-dark/1.49.3/file/vscode.theme-kimbie-dark-1.49.3.vsix",
    "vscode-builtin-theme-monokai": "https://open-vsx.org/api/vscode/theme-monokai/1.49.3/file/vscode.theme-monokai-1.49.3.vsix",
    "vscode-builtin-theme-monokai-dimmed": "https://open-vsx.org/api/vscode/theme-monokai-dimmed/1.49.3/file/vscode.theme-monokai-dimmed-1.49.3.vsix",
    "vscode-builtin-theme-quietlight": "https://open-vsx.org/api/vscode/theme-quietlight/1.49.3/file/vscode.theme-quietlight-1.49.3.vsix",
    "vscode-builtin-theme-red": "https://open-vsx.org/api/vscode/theme-red/1.49.3/file/vscode.theme-red-1.49.3.vsix",
    "vscode-builtin-theme-solarized-dark": "https://open-vsx.org/api/vscode/theme-solarized-dark/1.49.3/file/vscode.theme-solarized-dark-1.49.3.vsix",
    "vscode-builtin-theme-solarized-light": "https://open-vsx.org/api/vscode/theme-solarized-light/1.49.3/file/vscode.theme-solarized-light-1.49.3.vsix",
    "vscode-builtin-theme-tomorrow-night-blue": "https://open-vsx.org/api/vscode/theme-tomorrow-night-blue/1.49.3/file/vscode.theme-tomorrow-night-blue-1.49.3.vsix",
    "vscode-builtin-typescript": "https://open-vsx.org/api/vscode/typescript/1.49.3/file/vscode.typescript-1.49.3.vsix",
    "vscode-builtin-typescript-language-features": "https://open-vsx.org/api/vscode/typescript-language-features/1.49.3/file/vscode.typescript-language-features-1.49.3.vsix",
    "vscode-builtin-vb": "https://open-vsx.org/api/vscode/vb/1.49.3/file/vscode.vb-1.49.3.vsix",
    "vscode-builtin-xml": "https://open-vsx.org/api/vscode/xml/1.49.3/file/vscode.xml-1.49.3.vsix",
    "vscode-builtin-yaml": "https://open-vsx.org/api/vscode/yaml/1.49.3/file/vscode.yaml-1.49.3.vsix",
    "vscode-editorconfig": "https://open-vsx.org/api/EditorConfig/EditorConfig/0.16.4/file/EditorConfig.EditorConfig-0.16.4.vsix",
    "vscode-eslint": "https://open-vsx.org/api/dbaeumer/vscode-eslint/2.1.1/file/dbaeumer.vscode-eslint-2.1.1.vsix",
    "vscode-references-view": "https://open-vsx.org/api/ms-vscode/references-view/0.0.77/file/ms-vscode.references-view-0.0.77.vsix"
  },
  "theiaPluginsDir": "plugins",
  "version": "1.4.0"
}
```

#### Browser Console Log

```
root ERROR TypeError: Class constructor h cannot be invoked without 'new'
    at new i (https://redacted/bundle.js:2:1936926)
    at Object.t.resolveInstance (https://redacted/bundle.js:2:5147900)
    at https://redacted/bundle.js:2:5149838
    at Object.t.resolve (https://redacted/bundle.js:2:5150101)
    at https://redacted/bundle.js:2:5133497
    at e._get (https://redacted/bundle.js:2:5133263)
    at e.get (https://redacted/bundle.js:2:5131906)
    at e.dynamicValue (https://redacted/bundle.js:2:5155500)
    at https://redacted/bundle.js:2:5149327
    at c (https://redacted/bundle.js:2:5148343)
e.log @ logger-protocol.ts:110
logger-protocol.ts:110 root ERROR Could not start contribution TypeError: Cannot read property 'resolved' of undefined
    at n.resolveKeybinding (https://redacted/bundle.js:2:1481329)
    at n.acceleratorFor (https://redacted/bundle.js:2:1481899)
    at n.getKeyCommand (https://redacted/bundle.js:2:2277586)
    at n.getPlaceHolder (https://redacted/bundle.js:2:2280663)
    at n.registerQuickAccessProvider (https://redacted/bundle.js:2:2276840)
    at c.registerQuickAccessProvider (https://redacted/bundle.js:2:2275404)
    at https://redacted/bundle.js:2:1588462
    at Array.forEach (<anonymous>)
    at c.onStart (https://redacted/bundle.js:2:1588447)
    at https://redacted/bundle.js:2:1467547
e.log @ logger-protocol.ts:110
2logger-protocol.ts:110 root ERROR Child node 'file-change-tree-root' does not belong to this 'file-change-tree-root' tree.
e.log @ logger-protocol.ts:110
2logger-protocol.ts:110 root ERROR TypeError: Cannot read property 'resolved' of undefined
    at n.resolveKeybinding (https://redacted/bundle.js:2:1481329)
    at n.acceleratorFor (https://redacted/bundle.js:2:1481899)
    at n.renderInput (https://redacted/bundle.js:2:3619710)
    at n.render (https://redacted/bundle.js:2:3619375)
    at n.onUpdateRequest (https://redacted/bundle.js:2:1797889)
    at n.e.processMessage (https://redacted/bundle.js:2:1190233)
    at h (https://redacted/bundle.js:2:1026304)
    at Object.t [as sendMessage] (https://redacted/bundle.js:2:1025280)
    at n.onUpdateRequest (https://redacted/bundle.js:2:3669895)
    at n.e.processMessage (https://redacted/bundle.js:2:1190233)
e.log @ logger-protocol.ts:110
%24%28references%29:1 Failed to load resource: the server responded with a status of 404 (Not Found)
logger-protocol.ts:110 root ERROR TypeError: Cannot read property 'resolved' of undefined
    at n.resolveKeybinding (https://redacted/bundle.js:2:1481329)
    at n.acceleratorFor (https://redacted/bundle.js:2:1481899)
    at n.renderInput (https://redacted/bundle.js:2:3619710)
    at n.render (https://redacted/bundle.js:2:3619375)
    at n.onUpdateRequest (https://redacted/bundle.js:2:1797889)
    at n.e.processMessage (https://redacted/bundle.js:2:1190233)
    at h (https://redacted/bundle.js:2:1026304)
    at Object.t [as sendMessage] (https://redacted/bundle.js:2:1025280)
    at n.onUpdateRequest (https://redacted/bundle.js:2:3669895)
    at n.updateImmediately (https://redacted/bundle.js:2:3669818)
e.log @ logger-protocol.ts:110
logger-protocol.ts:110 root ERROR TypeError: Cannot read property 'resolved' of undefined
    at n.resolveKeybinding (https://redacted/bundle.js:2:1481329)
    at n.acceleratorFor (https://redacted/bundle.js:2:1481899)
    at n.renderInput (https://redacted/bundle.js:2:3619710)
    at n.render (https://redacted/bundle.js:2:3619375)
    at n.onUpdateRequest (https://redacted/bundle.js:2:1797889)
    at n.e.processMessage (https://redacted/bundle.js:2:1190233)
    at h (https://redacted/bundle.js:2:1026304)
    at Object.t [as sendMessage] (https://redacted/bundle.js:2:1025280)
    at n.onUpdateRequest (https://redacted/bundle.js:2:3669895)
    at n.e.processMessage (https://redacted/bundle.js:2:1190233)
e.log @ logger-protocol.ts:110
logger-protocol.ts:110 root ERROR TypeError: Cannot read property 'resolved' of undefined
    at n.resolveKeybinding (https://redacted/bundle.js:2:1481329)
    at n.acceleratorFor (https://redacted/bundle.js:2:1481899)
    at n.renderInput (https://redacted/bundle.js:2:3619710)
    at n.render (https://redacted/bundle.js:2:3619375)
    at n.onUpdateRequest (https://redacted/bundle.js:2:1797889)
    at n.e.processMessage (https://redacted/bundle.js:2:1190233)
    at h (https://redacted/bundle.js:2:1026304)
    at t (https://redacted/bundle.js:2:1025280)
    at p (https://redacted/bundle.js:2:1026475)
e.log @ logger-protocol.ts:110
command.ts:312 Uncaught (in promise) Error: The command 'output:append' cannot be executed. There are no active handlers available for the command.
    at h.executeCommand (command.ts:312)
    at l.$append (output-channel-registry-main.ts:29)
    at l.$append (plugin-metrics-output-registry.ts:34)
    at t.RPCProtocolImpl.doInvokeHandler (rpc-protocol.ts:288)
    at t.RPCProtocolImpl.invokeHandler (rpc-protocol.ts:273)
    at t.RPCProtocolImpl.receiveRequest (rpc-protocol.ts:232)
    at t.RPCProtocolImpl.receiveOneMessage (rpc-protocol.ts:193)
    at rpc-protocol.ts:102
    at event.ts:117
    at n.invoke (event.ts:125)
logger-protocol.ts:110 root ERROR data provider for 'clangd.typeHierarchyView' view is already registered
e.log @ logger-protocol.ts:110
6command.ts:312 Uncaught (in promise) Error: The command 'output:append' cannot be executed. There are no active handlers available for the command.
    at h.executeCommand (command.ts:312)
    at l.$append (output-channel-registry-main.ts:29)
    at l.$append (plugin-metrics-output-registry.ts:34)
    at t.RPCProtocolImpl.doInvokeHandler (rpc-protocol.ts:288)
    at t.RPCProtocolImpl.invokeHandler (rpc-protocol.ts:273)
    at t.RPCProtocolImpl.receiveRequest (rpc-protocol.ts:232)
    at t.RPCProtocolImpl.receiveOneMessage (rpc-protocol.ts:193)
    at rpc-protocol.ts:102
    at event.ts:117
    at n.invoke (event.ts:125)
logger-protocol.ts:110 root ERROR TypeError: Cannot read property 'resolved' of undefined
    at n.resolveKeybinding (https://redacted/bundle.js:2:1481329)
    at n.acceleratorFor (https://redacted/bundle.js:2:1481899)
    at n.renderInput (https://redacted/bundle.js:2:3619710)
    at n.render (https://redacted/bundle.js:2:3619375)
    at n.onUpdateRequest (https://redacted/bundle.js:2:1797889)
    at n.e.processMessage (https://redacted/bundle.js:2:1190233)
    at h (https://redacted/bundle.js:2:1026304)
    at t (https://redacted/bundle.js:2:1025280)
    at p (https://redacted/bundle.js:2:1026475)
e.log @ logger-protocol.ts:110
9command.ts:312 Uncaught (in promise) Error: The command 'output:append' cannot be executed. There are no active handlers available for the command.
    at h.executeCommand (command.ts:312)
    at l.$append (output-channel-registry-main.ts:29)
    at l.$append (plugin-metrics-output-registry.ts:34)
    at t.RPCProtocolImpl.doInvokeHandler (rpc-protocol.ts:288)
    at t.RPCProtocolImpl.invokeHandler (rpc-protocol.ts:273)
    at t.RPCProtocolImpl.receiveRequest (rpc-protocol.ts:232)
    at t.RPCProtocolImpl.receiveOneMessage (rpc-protocol.ts:193)
    at rpc-protocol.ts:102
    at event.ts:117
    at n.invoke (event.ts:125)
4923629b0b928d2deab5b4a3e246b94b:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
3command.ts:312 Uncaught (in promise) Error: The command 'output:append' cannot be executed. There are no active handlers available for the command.
    at h.executeCommand (command.ts:312)
    at l.$append (output-channel-registry-main.ts:29)
    at l.$append (plugin-metrics-output-registry.ts:34)
    at t.RPCProtocolImpl.doInvokeHandler (rpc-protocol.ts:288)
    at t.RPCProtocolImpl.invokeHandler (rpc-protocol.ts:273)
    at t.RPCProtocolImpl.receiveRequest (rpc-protocol.ts:232)
    at t.RPCProtocolImpl.receiveOneMessage (rpc-protocol.ts:193)
    at rpc-protocol.ts:102
    at event.ts:117
    at n.invoke (event.ts:125)
2command.ts:312 Uncaught (in promise) Error: The command 'output:append' cannot be executed. There are no active handlers available for the command.
    at h.executeCommand (command.ts:312)
    at l.$append (output-channel-registry-main.ts:29)
    at l.$append (plugin-metrics-output-registry.ts:34)
    at t.RPCProtocolImpl.doInvokeHandler (rpc-protocol.ts:288)
    at t.RPCProtocolImpl.invokeHandler (rpc-protocol.ts:273)
    at t.RPCProtocolImpl.receiveRequest (rpc-protocol.ts:232)
    at t.RPCProtocolImpl.receiveOneMessage (rpc-protocol.ts:193)
    at rpc-protocol.ts:102
    at event.ts:117
    at n.invoke (event.ts:125)
```

- Operating System: Debian/Archlinux in docker
- Theia Version: 1.17.x

**Comment by vince-fugnitto** [comment]
@Jarthianur I was able to reproduce the issue in a dockerfile, can you confirm that removing `"@theia/cpp-debug": "next"` from your `package.json` (for test purposes) works? I believe the issue is simply that `@theia/cpp-debug` targets the older `es5` while the rest of the theia extensions now target `ES2017`.

**Comment by Jarthianur** [comment]
Thanks @vince-fugnitto  and @msujew for taking a look into this! I can definitely confirm  that removing `@theia/cpp-debug` solves all said issues. I've checked this by building the theia-cpp-docker application in theia-apps, which suffered the same thing. I'll rebuild my custom applications and check them, but the fix should apply there too.
Is cpp-debug deprecated in general, or does it require an update? If it's deprecated, I would recommend to adjust the migration guide and theia-apps.

**Comment by vince-fugnitto** [comment]
@Jarthianur `@theia/cpp-debug` is not deprecated, a newer version is scheduled to be published soon (to make use of the new [memory-view](https://github.com/eclipse-theia/theia-cpp-extensions/pull/119). I have another [pull-request](https://github.com/eclipse-theia/theia-cpp-extensions/pull/123) which updates the extension to resolve the build issues. I believe the next publish should make use of both changes and resolve any potential issues :+1:

**Comment by Jarthianur** [comment]
That sounds great. Good job, all apps work again now. :+1:

**Comment by vince-fugnitto** [comment]
Thank you for reporting the issue, I've opened the upstream https://github.com/theia-ide/theia-apps/issues/494 to track the fix in the docker images :+1:
