### ISSUE TITLE
output: `OutputChannelManager` incorrectly imports browser code

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#10119]
#### Bug Description:

The `OutputChannelManager` incorrectly imports `browser` code meaning that the backend cannot use the manager:

https://github.com/eclipse-theia/theia/blob/0221c6179f7ea16673861fa1f602868a1f54d986/packages/output/src/common/output-channel.ts#L23-L24

The `OutputChannelManager` exists in `common` (can be used by both the browser and node) and `common` should not import anything:
- https://github.com/eclipse-theia/theia/wiki/Code-Organization

### Steps to Reproduce:

1. attempt to import `OutputChannelManager` in the backend (`node`)
2. the application will fail to start with the error:

```
Failed to start the backend application:
ReferenceError: navigator is not defined
    at /home/evinfug/workspaces/theia/node_modules/@phosphor/domutils/lib/platform.js:18:25
    at Object.<anonymous> (/home/evinfug/workspaces/theia/node_modules/@phosphor/domutils/lib/platform.js:46:3)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/evinfug/workspaces/theia/node_modules/@phosphor/domutils/lib/index.js:15:10)
```

**Comment by kittaakos** [comment]
Related https://github.com/eclipse-theia/theia/issues/4306?

**Comment by kittaakos** [comment]
> The `OutputChannelManager` incorrectly imports `browser`

The import is correct; the module is incorrectly in `common`.
