### ISSUE TITLE
[vscode ext API] GitLens, ESLint: globalState.setKeysForSync is not a function

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#10204]
### Bug Description:
I have noticed that couple of relatively popular vscode extensions do not activate correctly, since we bumped our `VSCODE_DEFAULT_API_VERSION` to `1.53.2`: `GitLens` and `ESLint`

Because of the bump, we are picking later version of these extensions, that presumably use an API that we do not yet support: `setKeysForSync`, that seems related to keeping the app's state synchronised between different machines where vscode is used. 

### Steps to Reproduce:

1. build the example app based on master
2. in the extension's view, install one of these extensions (first uninstall previous version if already installed)
3. a toaster pop-up error should appear, telling about the activation problem. The full stack trace should be in the backend log.

### Additional Information

GitLens log:
```
root ERROR [hosted-plugin: 25401] Activating extension 'GitLens — Git supercharged' failed: TypeError: X.globalState.setKeysForSync is not a function
at te (/home/lmcmcds/.theia/extensions/eamodio.gitlens-11.2.1/extension/dist/gitlens.js:2:676251)
at J (/home/lmcmcds/.theia/extensions/eamodio.gitlens-11.2.1/extension/dist/gitlens.js:2:672192)
at PluginManagerExtImpl.startPlugin (/home/lmcmcds/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:288:81)
at /home/lmcmcds/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:215:32
at processTicksAndRejections (internal/process/task_queues.js:94:5)
at async PluginManagerExtImpl.$activatePlugin (/home/lmcmcds/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:255:13)
at async Promise.all (index 0)
at async PluginManagerExtImpl.$activateByEvent (/home/lmcmcds/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:250:9)
at async PluginManagerExtImpl.$start (/home/lmcmcds/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:146:13)
```
ESLint log:
```root ERROR [hosted-plugin: 9041] Activating extension 'ESLint' failed: TypeError: e.globalState.setKeysForSync is not a function
at t.activate (/home/lmcmcds/.theia-blueprint/extensions/dbaeumer.vscode-eslint-2.1.20/extension/client/out/extension.js:1:267140)
at PluginManagerExtImpl.startPlugin (/tmp/.mount_TheiaB4bIb9x/resources/app/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:304:81)
at /tmp/.mount_TheiaB4bIb9x/resources/app/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:215:32
at processTicksAndRejections (internal/process/task_queues.js:94:5)
at async PluginManagerExtImpl.$activatePlugin (/tmp/.mount_TheiaB4bIb9x/resources/app/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:271:13)
at async Promise.all (index 0)
at async PluginManagerExtImpl.activateBySingleEvent (/tmp/.mount_TheiaB4bIb9x/resources/app/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:266:9)
at async PluginManagerExtImpl.$activateByEvent (/tmp/.mount_TheiaB4bIb9x/resources/app/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:246:13)
at async PluginManagerExtImpl.$start (/tmp/.mount_TheiaB4bIb9x/resources/app/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:146:13)

```

- Operating System:
- Theia Version:

**Comment by marcdumais-work** [comment]
This is a pretty big issue, IMHO. I have not tested many extensions, so more could be affected.
