### ISSUE TITLE
tabnine plugin bug(can not see tabnine hub)

### ISSUE THREAD

**Issue by jiungbaek** [eclipse-theia/theia#10447]
#### Bug Description:

I'm use theia vs-code by web.
When i install tabnine plugin, it works well, and can use in editor.
But i can see tabnine hub in tabnine plugin menu.

![image](https://user-images.githubusercontent.com/7424183/142816701-a48d84e8-92de-4731-9f6b-fccb61f14d50.png)

Could you solve this issue?
Thank you

Error Log:

```
root ERROR [hosted-plugin: 161] (node:161) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
root ERROR [hosted-plugin: 161] Binary child process exited with code 0 signal unknown
root ERROR [hosted-plugin: 161] validating ~/.theia/globalStorage/tabnine.tabnine-vscode/binaries/4.0.9/x86_64-unknown-linux-musl/TabNine timeout
root ERROR [hosted-plugin: 161] Error: Command with id 'vscode.executeCodeActionProvider' is not registered.
    at t.CommandRegistryMainImpl.$executeCommand (https://url/bundle.js:2:3065298)
    at t.RPCProtocolImpl.doInvokeHandler (https://url/bundle.js:2:3026936)
    at t.RPCProtocolImpl.invokeHandler (https://url/bundle.js:2:3026687)
    at t.RPCProtocolImpl.receiveRequest (https://url/bundle.js:2:3026080)
    at t.RPCProtocolImpl.receiveOneMessage (https://url/bundle.js:2:3025573)
    at https://url/bundle.js:2:3024077
    at https://url/bundle.js:2:1861418
    at n.invoke (https://url/bundle.js:2:1861508)
    at r.fire (https://url/bundle.js:2:1863247)
    at https://url/bundle.js:2:3027730
```

### Additional Information

- Operating System: ubuntu 18.04
- Theia Version: 1.19.0

<details>

<summary>package.json</summary>

<br />

```json
  "dependencies": {
    "@theia/core": "1.19.0",
    "@theia/callhierarchy": "1.19.0",
    "@theia/debug": "1.19.0",
    "@theia/editor-preview": "1.19.0",
    "@theia/file-search": "1.19.0",
    "@theia/getting-started": "1.19.0",
    "@theia/git": "1.19.0",
    "@theia/keymaps": "1.19.0",
    "@theia/markers": "1.19.0",
    "@theia/messages": "1.19.0",
    "@theia/mini-browser": "1.19.0",
    "@theia/navigator": "1.19.0",
    "@theia/outline-view": "1.19.0",
    "@theia/plugin": "1.19.0",
    "@theia/plugin-ext": "1.19.0",
    "@theia/plugin-ext-vscode": "1.19.0",
    "@theia/preferences": "1.19.0",
    "@theia/preview": "1.19.0",
    "@theia/search-in-workspace": "1.19.0",
    "@theia/terminal": "1.19.0",
    "@theia/vsx-registry": "1.19.0",
    "@types/node": "16.11.9",
    "@theia/bulk-edit": "1.19.0",
    "@theia/console": "1.19.0",
    "@theia/editor": "1.19.0",
    "@theia/external-terminal": "1.19.0",
    "@theia/filesystem": "1.19.0",
    "@theia/metrics": "1.19.0",
    "@theia/monaco": "1.19.0",
    "@theia/output": "1.19.0",
    "@theia/plugin-dev": "1.19.0",
    "@theia/plugin-metrics": "1.19.0",
    "@theia/process": "1.19.0",
    "@theia/property-view": "1.19.0",
    "@theia/scm": "1.19.0",
    "@theia/scm-extra": "1.19.0",
    "@theia/task": "1.19.0",
    "@theia/timeline": "1.19.0",
    "@theia/typehierarchy": "1.19.0",
    "@theia/userstorage": "1.19.0",
    "@theia/variable-resolver": "1.19.0",
    "@theia/ovsx-client": "1.19.0",
    "@theia/application-package": "1.19.0",
    "@theia/application-manager": "1.19.0",
    "@theia/plugin-metrics": "1.19.0",
    "@theia/electron": "1.19.0",
    "@theia/task": "1.19.0",
    "@theia/localization-manager": "1.19.0",
    "@theia/api-tests": "1.19.0",
    "@theia/workspace": "1.19.0"
}
```

</details>

**Comment by msujew** [comment]
@jiungbaek thanks for reporting this issue.

It seems to be this error in particular that causes the hub not to show up:

```
root ERROR [hosted-plugin: 161] Binary child process exited with code 0 signal unknown
```

Everything else seems to have no effect on the functionality. When running Theia in browser mode on Windows, it seems to work:

![image](https://user-images.githubusercontent.com/4377073/142850202-db31242d-1178-4025-a0af-8688ada1b2de.png)

Running it in electron mode however, the same error occurs.

@vince-fugnitto Could you test this on Ubuntu? (browser/electron)

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Could you test this on Ubuntu? (browser/electron)

@msujew I can confirm that on Ubuntu it works well for the browser, but not on electron.

**Comment by msujew** [comment]
The Tabnine VS Code extension hub is now opening as expected.
