### ISSUE TITLE
repo: fix `typedoc` documentation generation

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#10727]
#### Bug Description:

The script `yarn docs` fails:

<details>

<summary>Output</summary>

<br />

```
$ yarn docs
yarn run v1.22.4
$ rimraf gh-pages/docs/next && typedoc --tsconfig tsconfig.json --options configs/typedoc.json .
Info: Loaded plugin /home/evinfug/workspaces/theia/node_modules/typedoc-plugin-external-module-map
Warning: You are running with an unsupported TypeScript version! TypeDoc supports 3.9, 4.0, 4.1, 4.2
INFO: applying regexp  .*/packages/([\w\-_]+)/  to calculate module names
INFO: Enabled true
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/bulk-edit/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/callhierarchy/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/console/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/electron-shared/@electron/remote/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/electron-shared/@electron/remote/main/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/electron-shared/electron/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/electron-shared/electron-store/index.d.ts
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/electron-shared/electron-store/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/electron-shared/fix-path/index.d.ts
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/electron-shared/fix-path/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/electron-shared/native-keymap/index.d.ts
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/electron-shared/native-keymap/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/scripts/generate-layout.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@phosphor/algorithm/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@phosphor/commands/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@phosphor/coreutils/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@phosphor/domutils/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@phosphor/dragdrop/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@phosphor/messaging/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@phosphor/properties/index.d.ts
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@phosphor/properties/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@phosphor/signaling/index.d.ts
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@phosphor/signaling/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@phosphor/virtualdom/index.d.ts
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@phosphor/virtualdom/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@phosphor/widgets/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@theia/application-package/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@theia/application-package/lib/api/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/@theia/application-package/lib/environment/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/ajv/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/dompurify/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/express/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/fs-extra/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/fuzzy/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/inversify/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/lodash.debounce/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/lodash.throttle/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/markdown-it/index.d.ts
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/markdown-it/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/markdown-it.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/nsfw/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/react/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/react-dom/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/react-virtualized/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/vscode-languageserver-protocol/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/vscode-languageserver-types/index.d.ts
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/vscode-languageserver-types/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/vscode-uri/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/vscode-ws-jsonrpc/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/ws/index.d.ts
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/ws/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/core/shared/yargs/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/debug/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/debug/bin/download-adapters.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/editor/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/editor-preview/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/electron/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/electron/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/electron/shared/@electron/remote/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/electron/shared/@electron/remote/main/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/electron/shared/electron/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/electron/shared/electron-store/index.d.ts
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/electron/shared/electron-store/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/electron/shared/fix-path/index.d.ts
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/electron/shared/fix-path/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/electron/shared/native-keymap/index.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/external-terminal/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/file-search/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/filesystem/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/getting-started/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/git/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/keymaps/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/markers/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/messages/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/metrics/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/mini-browser/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/monaco/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/navigator/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/outline-view/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/output/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/plugin/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/plugin-dev/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/plugin-ext/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/plugin-ext/src/main/browser/webview/pre/host.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/plugin-ext/src/main/browser/webview/pre/main.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/plugin-ext/src/main/browser/webview/pre/service-worker.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/plugin-ext-vscode/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/plugin-metrics/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/preferences/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/preview/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/process/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/process/src/common/tests/$weird(),file=name.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/process/src/common/tests/white space.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/process/src/node/test/process-fork-test.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/property-view/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/scm/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/scm-extra/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/search-in-workspace/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/task/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/task/test-resources/compare.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/task/test-resources/test-arguments-0.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/task/test-resources/test-arguments-1.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/task/test-resources/test-arguments-2.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/terminal/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/timeline/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/typehierarchy/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/userstorage/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/variable-resolver/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/vsx-registry/.eslintrc.js
Warning: Unable to locate entry point: /home/evinfug/workspaces/theia/packages/workspace/.eslintrc.js
 Mapping  /home/evinfug/workspaces/theia/packages/bulk-edit/src/browser/bulk-edit-commands.ts  ==>  bulk-edit
 Mapping  /home/evinfug/workspaces/theia/packages/bulk-edit/src/browser/bulk-edit-contribution.ts  ==>  bulk-edit
TypeDoc exiting with unexpected error:
TypeError: Cannot read property 'kind' of undefined
    at Object.isDeclaration (/home/evinfug/workspaces/theia/node_modules/typescript/lib/typescript.js:13851:18)
    at Object.isDeclarationName (/home/evinfug/workspaces/theia/node_modules/typescript/lib/typescript.js:16918:75)
    at getTypeOfSymbolAtLocation (/home/evinfug/workspaces/theia/node_modules/typescript/lib/typescript.js:69571:20)
    at Object.getTypeOfSymbolAtLocation (/home/evinfug/workspaces/theia/node_modules/typescript/lib/typescript.js:47035:35)
    at Object.convertProperty (/home/evinfug/workspaces/theia/node_modules/typedoc/dist/lib/converter/symbols.js:330:176)
    at convertSymbol (/home/evinfug/workspaces/theia/node_modules/typedoc/dist/lib/converter/symbols.js:80:79)
    at convertSymbols (/home/evinfug/workspaces/theia/node_modules/typedoc/dist/lib/converter/symbols.js:86:9)
    at Object.convertClassOrInterface (/home/evinfug/workspaces/theia/node_modules/typedoc/dist/lib/converter/symbols.js:264:5)
    at Object.convertSymbol (/home/evinfug/workspaces/theia/node_modules/typedoc/dist/lib/converter/symbols.js:80:79)
    at Converter.convertExports (/home/evinfug/workspaces/theia/node_modules/typedoc/dist/lib/converter/converter.js:182:23)
error Command failed with exit code 5.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

#### Steps to Reproduce:

1. perform `yarn` on the repo
2. increase the memory limit - `export NODE_OPTIONS=--max-old-space-size=8196`
3. execute the script - `yarn docs`

**Comment by vince-fugnitto** [comment]
It seems like with https://github.com/eclipse-theia/theia/pull/10729 the generation hangs ([build output](https://github.com/eclipse-theia/theia/runs/5128756947?check_suite_focus=true)). If others can help out it'd be greatly appreciated.

**Comment by vince-fugnitto** [comment]
@msujew @JonasHelming @tsmaeder I'm wondering if we should move our CI step to publish `next` packages before the generation of the documentation so we can benefit from having `next` in blueprint and our generators (CI purposes). I was unable to find a solution as to why typedoc is not working (currently hangs), and thought we should at least publish next irregardless of if the documentation generation fails.
