### ISSUE TITLE
Preference Markdown renderer fails for complex localizations

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#11038]
### Bug Description:

Newer versions of the `typescript-language-features` plugin include object values for localization. When those values reach the preference rendering system, they cause errors in markdown.

### Steps to Reproduce:

1. Download and install the most recent version of `typescript-language` and `typescript-language-features` from Open VSX.
2. Start the application.
3. In the frontend logs, see messages like this:

```log
TypeError: state.src.replace is not a function
    at Array.normalize (.../theia/examples/electron/lib/vendors-node_modules_markdown-it_index_js.js:5559:19)
    at Core.process (.../theia/examples/electron/lib/vendors-node_modules_markdown-it_index_js.js:2341:13)
    at MarkdownIt.parseInline (.../theia/examples/electron/lib/vendors-node_modules_markdown-it_index_js.js:2125:13)
    at MarkdownIt.renderInline (.../theia/examples/electron/lib/vendors-node_modules_markdown-it_index_js.js:2142:36)
    at PreferenceBooleanInputRenderer.createDomNode (.../theia/examples/electron/lib/node_modules_valid-filename_index_js-packages_preferences_lib_browser_preference-frontend-mod-9d1576.js:2532:71)
    at PreferenceBooleanInputRenderer.init (.../theia/examples/electron/lib/node_modules_valid-filename_index_js-packages_preferences_lib_browser_preference-frontend-mod-9d1576.js:2452:33)
    at _postConstruct (.../theia/examples/electron/lib/bundle.js:40393:31)
    at Object.resolveInstance (.../theia/examples/electron/lib/bundle.js:40413:5)
    at .../theia/examples/electron/lib/bundle.js:40502:42
    at Object.resolve (.../theia/examples/electron/lib/bundle.js:40526:12)
```

It points to this line:

https://github.com/eclipse-theia/theia/blob/e6b57ba4edabf797f3b4e67bc2968cdb8cc25b1e/packages/preferences/src/browser/views/components/preference-node-renderer.ts#L284

And a little bit of digging will show that the value of `markdownDescription` when the error occurs is something like:

```typescript
{
  message: 'Enable/disable inlay hints for implicit return types on function signatures:\n' +
    '```typescript\n' +
    '\n' +
    'function foo() /* :number */ {\n' +
    '\treturn Date.now();\n' +
    '} \n' +
    ' \n' +
    '```\n' +
    'Requires using TypeScript 4.4+ in the workspace.',
  comment: 'The text inside the ``` block is code and should not be localized.'
}
```

Here are the preference schemata affected:

https://github.com/microsoft/vscode/blob/ad5ef7ea85b8a622f73b96394507d98809e68861/extensions/typescript-language-features/package.json#L321-L372

And here are the values inserted into the preference schemas:

https://github.com/microsoft/vscode/blob/ad5ef7ea85b8a622f73b96394507d98809e68861/extensions/typescript-language-features/package.nls.json#L87-L114

### Additional Information

- Operating System: MacOS
- Theia Version: 1.24.0 (4381be37a65f1be9d11d22391753e0c82aca5cea)

**Comment by colin-grant-work** [comment]
@msujew, it looks like this is likely something that's supposed to be handled on the internationalization side? On the preference schema / JSON schema side, I don't see any indication that VSCode ever expects anything but a `string` for `markdownDescription`.
