### ISSUE TITLE
code action command with arguments parameter execute fail

### ISSUE THREAD

**Issue by hyy215** [eclipse-theia/theia#11059]
#### Bug Description: 
code action command with arguments parameter execute fail except the first time and throw error `command not found`. 

When I debug. I found the following information:
code action command with arguments parameter add to `commandsMap` when we register a code action provider
https://github.com/eclipse-theia/theia/blob/034a9f3b799e1b36a79c55e1f0302104af7180a3/packages/plugin-ext/src/plugin/command-registry.ts#L185-L191

but delete before command execute
https://github.com/eclipse-theia/theia/blob/034a9f3b799e1b36a79c55e1f0302104af7180a3/packages/plugin-ext/src/plugin/languages/code-action.ts#L117-L126

#### Steps to Reproduce:

1. include the following test extension in your application ([extension](https://github.com/eclipse-theia/theia/files/8548855/vsix.zip))
2. open editor，select code，click a light bulb，choose `test code action command`，and command execute success.
3. do 2nd step again，and throw error `root ERROR command X not found`

![codeAction](https://user-images.githubusercontent.com/34715914/164650676-8252d5fa-d9d6-4292-ad38-b1ff44cd4862.gif)

#### Additional Information

- Operating System: win10
- Theia Version: 1.24.0

**Comment by vince-fugnitto** [comment]
@hyy215 thank you for reporting the issue, do you mind sharing the `vsix` directly for your extension in order to test, it makes it easier for others to confirm the bug without the need for them to each rewrite the extension (it also seems to steps are not thorough enough to re-create the extension). Sharing the `vsix` in the issue would be simpler.

**Comment by hyy215** [comment]
@vince-fugnitto
[vsix.zip](https://github.com/eclipse-theia/theia/files/8548855/vsix.zip)

**Comment by colin-grant-work** [comment]
I don't have much more information. I've replicated your example extension [here](https://github.com/colin-grant-work/demo-extensions/tree/main/code-action-demo), and when I debug, it looks like the following happens:
1. The first time code actions are provided...
    1. The editor calls for code actions
    2. The provider provides code actions
    3. User clicks on lightbulb, selects action.
    4. Action is run
2. Immediately after the action is run...
    1. The editor calls for code actions again
    2. Those actions are immediately disposed of
3. Thereafter, every time the editor calls for code actions, they are immediately disposed of, even if the GUI is active.

Here are the logs with <--- marking the sequence of events:

```log
root INFO [hosted-plugin: 1065] SENTINEL FOR PROVIDING SOME CODE ACTIONS... <--- Select some text
root INFO [hosted-plugin: 1065] SENTINEL FOR ADDING A COMMAND TO THE MAP 0 [ 'test' ]
root INFO [hosted-plugin: 1065] SENTINEL FOR TRYING TO EXECUTE SAFE COMMAND 0 { <--- Execute action
  title: 'Test code action command',
  command: 'test.code.action.command',
  arguments: [ 'test' ]
}
root INFO SENTINEL FOR PROVIDING CODE ACTIONS Error <--- Provide actions called immediately after execution
    at LanguagesMainImpl.provideCodeActions (file:///Users/cjg/code/open/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:5743:60)
    at Object.provideCodeActions (file:///Users/cjg/code/open/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:5734:29)
    at Object.provideCodeActions (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:152994:29)
    at file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:111207:56
    at Generator.next (<anonymous>)
    at file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:111111:71
    at new Promise (<anonymous>)
    at push.../../node_modules/@theia/monaco-editor-core/esm/vs/editor/contrib/codeAction/browser/codeAction.js.__awaiter (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:111107:12)
    at file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:111204:50
    at Array.map (<anonymous>)
root INFO [hosted-plugin: 1065] SENTINEL FOR PROVIDING SOME CODE ACTIONS...
root INFO [hosted-plugin: 1065] SENTINEL FOR ADDING A COMMAND TO THE MAP 1 [ 'test' ]
root INFO SENTINEL FOR DISPOSING OF SOME CODE ACTIONS Error <--- Actions immediately disposed of
    at Object.dispose (file:///Users/cjg/code/open/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:5751:76)
    at dispose (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36152:23)
    at DisposableStore.clear (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36219:13)
    at DisposableStore.dispose (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36206:14)
    at dispose (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36152:23)
    at DisposableStore.clear (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36219:13)
    at DisposableStore.dispose (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36206:14)
    at ManagedCodeActionSet.dispose (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36254:21)
    at CodeActionUi.<anonymous> (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:112326:29)
    at Generator.next (<anonymous>)
root INFO [hosted-plugin: 1065] SENTINEL FOR DELETING A COMMAND WITH ID 1 AND ARGS Error
    at _.disposable (/Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/command-registry.js:151:136)
    at _.dispose (/Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/types-impl.js:134:18)
    at _.disposable.dispose (/Users/cjg/code/open/theia/packages/core/lib/common/disposable.js:96:13)
    at DisposableCollection.dispose (/Users/cjg/code/open/theia/packages/core/lib/common/disposable.js:73:40)
    at /Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/languages/code-action.js:103:27
    at Array.forEach (<anonymous>)
    at CodeActionAdapter.releaseCodeActions (/Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/languages/code-action.js:99:18)
    at /Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/languages.js:314:86
    at LanguagesExtImpl.withAdapter (/Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/languages.js:112:20)
    at LanguagesExtImpl.$releaseCodeActions (/Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/languages.js:314:14)
root INFO SENTINEL FOR PROVIDING CODE ACTIONS Error
    at LanguagesMainImpl.provideCodeActions (file:///Users/cjg/code/open/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:5743:60)
    at Object.provideCodeActions (file:///Users/cjg/code/open/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:5734:29)
    at Object.provideCodeActions (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:152994:29)
    at file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:111207:56
    at Generator.next (<anonymous>)
    at file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:111111:71
    at new Promise (<anonymous>)
    at push.../../node_modules/@theia/monaco-editor-core/esm/vs/editor/contrib/codeAction/browser/codeAction.js.__awaiter (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:111107:12)
    at file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:111204:50
    at Array.map (<anonymous>)
root INFO SENTINEL FOR PROVIDING CODE ACTIONS Error <--- Select
    at LanguagesMainImpl.provideCodeActions (file:///Users/cjg/code/open/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:5743:60)
    at Object.provideCodeActions (file:///Users/cjg/code/open/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:5734:29)
    at Object.provideCodeActions (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:152994:29)
    at file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:111207:56
    at Generator.next (<anonymous>)
    at file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:111111:71
    at new Promise (<anonymous>)
    at push.../../node_modules/@theia/monaco-editor-core/esm/vs/editor/contrib/codeAction/browser/codeAction.js.__awaiter (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:111107:12)
    at file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:111204:50
    at Array.map (<anonymous>)
root INFO [hosted-plugin: 1065] SENTINEL FOR PROVIDING SOME CODE ACTIONS... <--- Code actions provided
root INFO [hosted-plugin: 1065] SENTINEL FOR ADDING A COMMAND TO THE MAP 2 [ 'test' ]
root INFO SENTINEL FOR DISPOSING OF SOME CODE ACTIONS Error <--- Code actions immediately disposed of
    at Object.dispose (file:///Users/cjg/code/open/theia/examples/electron/lib/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:5751:76)
    at dispose (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36152:23)
    at DisposableStore.clear (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36219:13)
    at DisposableStore.dispose (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36206:14)
    at dispose (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36152:23)
    at DisposableStore.clear (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36219:13)
    at DisposableStore.dispose (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36206:14)
    at ManagedCodeActionSet.dispose (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:36254:21)
    at CodeActionUi.<anonymous> (file:///Users/cjg/code/open/theia/examples/electron/lib/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:112326:29)
    at Generator.next (<anonymous>)
root INFO [hosted-plugin: 1065] SENTINEL FOR DELETING A COMMAND WITH ID 2 AND ARGS Error
    at _.disposable (/Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/command-registry.js:151:136)
    at _.dispose (/Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/types-impl.js:134:18)
    at _.disposable.dispose (/Users/cjg/code/open/theia/packages/core/lib/common/disposable.js:96:13)
    at DisposableCollection.dispose (/Users/cjg/code/open/theia/packages/core/lib/common/disposable.js:73:40)
    at /Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/languages/code-action.js:103:27
    at Array.forEach (<anonymous>)
    at CodeActionAdapter.releaseCodeActions (/Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/languages/code-action.js:99:18)
    at /Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/languages.js:314:86
    at LanguagesExtImpl.withAdapter (/Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/languages.js:112:20)
    at LanguagesExtImpl.$releaseCodeActions (/Users/cjg/code/open/theia/packages/plugin-ext/lib/plugin/languages.js:314:14)
```

@lucas-koehler, it looks like the disposal of the code actions is triggered by the editor, but it runs through the `$releaseCodeActions` method introduced in #10730. Did you observe any strange life cycle issues when you were working on that PR?

**Comment by lucas-koehler** [comment]
> @lucas-koehler, it looks like the disposal of the code actions is triggered by the editor, but it runs through the $releaseCodeActions method introduced in https://github.com/eclipse-theia/theia/pull/10730. Did you observe any strange life cycle issues when you were working on that PR?

Hi @colin-grant-work , no I did not observe such issues during implementation or testing the PR, sorry.
