### ISSUE TITLE
CommentThread support no longer works

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipse-theia/theia#11064]
### Bug Description:

When using an extension to use CommentThreads (e.g. vscode-comment-api-example from https://github.com/microsoft/vscode-extension-samples), trying to open the Comments section from the gutter throws an exception:

```
root ERROR TypeError: Cannot read properties of undefined (reading 'offsetX')
    at CommentsContribution.onEditorMouseDown (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:1708:36)
    at http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:1655:63
    at http://localhost:3000/bundle.js:133954:69
    at CallbackList.invoke (http://localhost:3000/bundle.js:133960:26)
    at Emitter.fire (http://localhost:3000/bundle.js:134075:29)
    at http://localhost:3000/packages_monaco_lib_browser_monaco-workspace_js.js:207:37
    at Listener.invoke (http://localhost:3000/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:28435:23)
    at Emitter.fire (http://localhost:3000/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:28579:30)
    at ViewUserInputEvents.viewUserInputEvents.onMouseDown (http://localhost:3000/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:66678:68)
    at ViewUserInputEvents.emitMouseDown (http://localhost:3000/vendors-node_modules_theia_monaco-editor-core_esm_vs_editor_editor_main_js.js:58155:18)
```

As far as I can tell, the event target details is no longer set (undefined).

The regression seems to have been introduced in https://github.com/eclipse-theia/theia/pull/10736 (While working on https://github.com/eclipse-theia/theia/pull/11062, I've been able to make the test extension work on the commit immediately before this one, but anything more recent breaks).

### Steps to Reproduce:

1. Install the Comment Sample Extension, e.g.: https://github.com/microsoft/vscode-extension-samples/tree/main/comment-sample
2. Open a Diff Editor (Theia doesn't seem to support Comments in other editors), e.g. by comparing 2 files
3. On the right side of the Diff Editor, click on the + in the gutter to open Comments

Expected behavior: the Comment editor should show up
Current behavior: the above exception is thrown and the Comment editor doesn't show up

### Additional Information

- Operating System: Linux
- Theia Version: 1.24.0

**Comment by CamilleLetavernier** [comment]
@colin-grant-work Since you worked on #10736, do you think this would be an easy fix?

**Comment by colin-grant-work** [comment]
I'm happy to take a look to see why the event doesn't have the expected shape.

**Comment by colin-grant-work** [comment]
@CamilleLetavernier, I've put up a PR restoring the details field: #11065.
