### ISSUE TITLE
There is no document for breakpointinput:vs.editor.ICodeEditor%3A26

### ISSUE THREAD

**Issue by FinnChen** [eclipse-theia/theia#11238]
To reproduce this problem, follow the steps below.

step 1: install the `GitLens` VS Code extension
step 2: open any file

```
Error: There is no document for breakpointinput:vs.editor.ICodeEditor%3A26
    at LinkProviderAdapter.provideLinks (:3000/Users/finn/CloudIDE/theia/packages/plugin-ext/lib/plugin/languages/link-provider.js:31:35)
    at :3000/Users/finn/CloudIDE/theia/packages/plugin-ext/lib/plugin/languages.js:281:97
    at LanguagesExtImpl.withAdapter (:3000/Users/finn/CloudIDE/theia/packages/plugin-ext/lib/plugin/languages.js:112:20)
    at LanguagesExtImpl.$provideDocumentLinks (:3000/Users/finn/CloudIDE/theia/packages/plugin-ext/lib/plugin/languages.js:281:21)
    at RPCProtocolImpl.doInvokeHandler (:3000/Users/finn/CloudIDE/theia/packages/plugin-ext/lib/common/rpc-protocol.js:232:23)
    at RPCProtocolImpl.invokeHandler (:3000/Users/finn/CloudIDE/theia/packages/plugin-ext/lib/common/rpc-protocol.js:217:41)
    at RPCProtocolImpl.receiveRequest (:3000/Users/finn/CloudIDE/theia/packages/plugin-ext/lib/common/rpc-protocol.js:181:33)
    at RPCProtocolImpl.receiveOneMessage (:3000/Users/finn/CloudIDE/theia/packages/plugin-ext/lib/common/rpc-protocol.js:145:26)
    at :3000/Users/finn/CloudIDE/theia/packages/plugin-ext/lib/common/rpc-protocol.js:69:48
    at :3000/Users/finn/CloudIDE/theia/packages/core/lib/common/event.js:103:69
    at errors.ts:26:12
```

_Originally posted by @FinnChen in https://github.com/eclipse-theia/theia/issues/7671#issuecomment-1143189117_

**Comment by vince-fugnitto** [comment]
> Should I remove this issue？

No problem, I closed it for you :)
