### ISSUE TITLE
Cannot use recent version of the ms-python extension

### ISSUE THREAD

**Issue by HedgehogCode** [eclipse-theia/theia#11413]
### Bug Description

Recent versions of the [ms-python.python](https://open-vsx.org/extension/ms-python/python) (tried 2022.10.0 and 2022.8.1) extension do not work:
![image](https://user-images.githubusercontent.com/6631116/178517287-8b1fbbd0-58ff-4405-b363-c6ccb7510355.png)

Log:
```
2022-07-12T14:31:29.907Z root INFO [hosted-plugin: 142595] PLUGIN_HOST(142595): PluginManagerExtImpl/loadPlugin(/home/benjamin/misc/code-editor-war/theia/theia-ms-python/plugins/ms-python.python/extension/out/client/extension)
2022-07-12T14:31:30.144Z root ERROR [hosted-plugin: 142595] Activating extension 'Python' failed: TypeError: Class extends value undefined is not a constructor or null
    at Object.41365 (/home/benjamin/misc/code-editor-war/theia/theia-ms-python/plugins/ms-python.python/extension/out/client/extension.js:2:2304277)
    at r (/home/benjamin/misc/code-editor-war/theia/theia-ms-python/plugins/ms-python.python/extension/out/client/extension.js:2:2605416)
    at Object.10071 (/home/benjamin/misc/code-editor-war/theia/theia-ms-python/plugins/ms-python.python/extension/out/client/extension.js:2:2197400)
    at r (/home/benjamin/misc/code-editor-war/theia/theia-ms-python/plugins/ms-python.python/extension/out/client/extension.js:2:2605416)
    at Object.14384 (/home/benjamin/misc/code-editor-war/theia/theia-ms-python/plugins/ms-python.python/extension/out/client/extension.js:2:2163747)
    at r (/home/benjamin/misc/code-editor-war/theia/theia-ms-python/plugins/ms-python.python/extension/out/client/extension.js:2:2605416)
    at Object.92850 (/home/benjamin/misc/code-editor-war/theia/theia-ms-python/plugins/ms-python.python/extension/out/client/extension.js:2:2338531)
    at r (/home/benjamin/misc/code-editor-war/theia/theia-ms-python/plugins/ms-python.python/extension/out/client/extension.js:2:2605416)
    at Object.52847 (/home/benjamin/misc/code-editor-war/theia/theia-ms-python/plugins/ms-python.python/extension/out/client/extension.js:2:2349430)
    at r (/home/benjamin/misc/code-editor-war/theia/theia-ms-python/plugins/ms-python.python/extension/out/client/extension.js:2:2605416)
```

Version 2020.10.332292344 (randomly picked) worked.

### Steps to Reproduce

1. Add the `ms-python.python` plugin to the ["Build your own IDE/Tool"](https://theia-ide.org/docs/composing_applications/) example:
```json
{
    "private": true,
    "dependencies": {
        "@theia/callhierarchy": "latest",
        "@theia/file-search": "latest",
        "@theia/git": "latest",
        "@theia/markers": "latest",
        "@theia/messages": "latest",
        "@theia/navigator": "latest",
        "@theia/outline-view": "latest",
        "@theia/plugin-ext-vscode": "latest",
        "@theia/preferences": "latest",
        "@theia/preview": "latest",
        "@theia/search-in-workspace": "latest",
        "@theia/terminal": "latest",
        "@theia/vsx-registry": "latest"
    },
    "devDependencies": {
        "@theia/cli": "latest"
    },
    "scripts": {
        "prepare": "yarn run clean && yarn build && yarn run download:plugins",
        "clean": "theia clean",
        "build": "theia build --mode development",
        "start": "theia start --plugins=local-dir:plugins",
        "download:plugins": "theia download:plugins"
    },
    "theiaPluginsDir": "plugins",
    "theiaPlugins": {
        "vscode-builtin-extensions-pack": "https://open-vsx.org/api/eclipse-theia/builtin-extension-pack/1.50.1/file/eclipse-theia.builtin-extension-pack-1.50.1.vsix",
        "ms-python.python": "https://open-vsx.org/api/ms-python/python/2022.10.0/file/ms-python.python-2022.10.0.vsix"
    },
    "theiaPluginsExcludeIds": [
        "vscode.extension-editing",
        "vscode.git",
        "vscode.git-ui",
        "vscode.github",
        "vscode.markdown-language-features",
        "vscode.microsoft-authentication",
        "ms-vscode.js-debug-companion",
        "ms-python.vscode-pylance",
        "ms-toolsai.jupyter"
    ]
}
```
2. Install the dependencies, build and download the plugins (`yarn`)
3. Start (`yarn start`) and open the browser at http://localhost:3000/

### Additional Information

- Operating System: Linux
- Theia Version: 1.27.0

**Comment by msujew** [comment]
@HedgehogCode The vscode version required by both of these extension versions is higher than we currently provide (1.53.2). They probably rely on API that doesn't exist in Theia at the moment.

We have a few issues open ([this one](https://github.com/eclipse-theia/theia/issues/9863) in particular) for tracking vscode extension support. This stuff is always work in progress. If you find out which API is exactly missing, you can create a dedicated issue for that. I'll close this for now, as the behavior you experienced is expected.

**Comment by HedgehogCode** [comment]
Thank you for the clarification.
