### ISSUE TITLE
JS Proxy error in plugin preference access

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#11501]
### Bug Description:

After the latest changes from https://github.com/eclipse-theia/theia/pull/11393, when trying to start the Python extension, the plugin fails to activate due to an proxy error (see below).

### Steps to Reproduce:

1. Install the newest available `ms-python.python` extension
2. Open a `.py` file
3. The following error appears

```
2022-08-03T11:47:52.875Z root ERROR [hosted-plugin: 20508] Activating extension 'Python' failed: TypeError: 'get' on proxy: property 'flake8CategorySeverity' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '#<Object>')
    at c:\Users\Mark\AppData\Local\Temp\vscode-unpacked\ms-python.python-2020.10.332292344.vsix\extension\out\client\extension.js:1:393861
    at Array.forEach (<anonymous>)
    at t.SystemVariables.__resolveAnyLiteral (c:\Users\Mark\AppData\Local\Temp\vscode-unpacked\ms-python.python-2020.10.332292344.vsix\extension\out\client\extension.js:1:393840)
    at t.SystemVariables.resolveAny (c:\Users\Mark\AppData\Local\Temp\vscode-unpacked\ms-python.python-2020.10.332292344.vsix\extension\out\client\extension.js:1:393471)
    at b.update (c:\Users\Mark\AppData\Local\Temp\vscode-unpacked\ms-python.python-2020.10.332292344.vsix\extension\out\client\extension.js:32:710792)
    at b.initialize (c:\Users\Mark\AppData\Local\Temp\vscode-unpacked\ms-python.python-2020.10.332292344.vsix\extension\out\client\extension.js:32:717320)
    at new b (c:\Users\Mark\AppData\Local\Temp\vscode-unpacked\ms-python.python-2020.10.332292344.vsix\extension\out\client\extension.js:32:707508)
    at Function.getInstance (c:\Users\Mark\AppData\Local\Temp\vscode-unpacked\ms-python.python-2020.10.332292344.vsix\extension\out\client\extension.js:32:708115)
    at f.getSettings (c:\Users\Mark\AppData\Local\Temp\vscode-unpacked\ms-python.python-2020.10.332292344.vsix\extension\out\client\extension.js:56:1206850)
    at c:\Users\Mark\AppData\Local\Temp\vscode-unpacked\ms-python.python-2020.10.332292344.vsix\extension\out\client\extension.js:47:278725
```

### Additional Information

- Operating System: Windows
- Theia Version: https://github.com/eclipse-theia/theia/commit/7e177f92c6d3f32dbc876d25ec380bd403e13858

**Comment by msujew** [comment]
cc @colin-grant-work

**Comment by colin-grant-work** [comment]
Thanks, @msujew, I'll check this out. There's code that's supposed to prevent this, so I'll look into why it's failing in this case.
