### ISSUE TITLE
[vscode] Support `TerminalProfileProvider`

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11503]
A [`TerminalProfileProvider`](https://code.visualstudio.com/api/references/vscode-api#TerminalProfileProvider) can be registered via `window.registerTerminalProfileProvider(id, provider)` and eventually provides a [`TerminalProfile`](https://code.visualstudio.com/api/references/vscode-api#TerminalProfile) defining how a terminal will be launched. All those types and their support in Theia are currently missing.

The types of the options with which a terminal can be provided already exist:

- [`TerminalOptions`](https://code.visualstudio.com/api/references/vscode-api#TerminalOptions)
- [`ExtensionTerminalOptions`](https://code.visualstudio.com/api/references/vscode-api#ExtensionTerminalOptions)

Related VSCode API issues:
- #11504
- #11138
- #11506

**Comment by tsmaeder** [comment]
Theia seems to have no support for terminal profiles at all at the moment. Implementing the API correctly would also entail support for configuration in the preferences and a UI to select profiles.

**Comment by tsmaeder** [comment]
My plan of attack for this issue looks like this:

1. Introcuce a `ProfileManagerService` in the front end
2. Read the "legacy" preference values to add default profiles to the profile manager
4. Make TerminalService use the default profiles 
5. Add schema info for terminal profiles in `settings.json`
6. Add code to merge profiles from `setttings.json` into the profile manager
7. Add UI to select profiles and default profiles when creating a terminal
8. Add API support for contributing profiles
9. Add support for `contributes` terminal profiles in `package.json`

Because we might want to declare VS Code `1.64.2` support (even if we lack full functionality), I'm starting with 1. and 8. and proceed from there.

**Comment by marcdumais-work** [comment]
@tsmaeder You can probably test using extension `ms-vscode.js-debug`, installable from the `extensions` view. 


2022-12-16T16:45:06.372Z root ERROR [hosted-plugin: 1993873] Activating extension 'JavaScript Debugger' failed: TypeError: a.window.registerTerminalProfileProvider is not a function
    at t.registerDebugTerminalUI (/tmp/vscode-unpacked/ms-vscode.js-debug-1.65.0.vsix/extension/src/extension.js:2:1279548)
    at t.activate (/tmp/vscode-unpacked/ms-vscode.js-debug-1.65.0.vsix/extension/src/extension.js:2:1073785)
    at PluginManagerExtImpl.startPlugin (/home/lmcmcds/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:308:81)
    at /home/lmcmcds/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:218:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PluginManagerExtImpl.$activatePlugin (/home/lmcmcds/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:270:13)
    at async Promise.all (index 0)
    at async PluginManagerExtImpl.activateBySingleEvent (/home/lmcmcds/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:265:9)
    at async PluginManagerExtImpl.$activateByEvent (/home/lmcmcds/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:249:13)
    at async PluginManagerExtImpl.$start (/home/lmcmcds/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:149:13)
