### ISSUE TITLE
Theia cannot be started properly without LocalHost binding

### ISSUE THREAD

**Issue by bjzhangtao** [eclipse-theia/theia#11578]
### Bug Description:
Theia cannot be started properly without LocalHost binding，

### Steps to Reproduce:
`yarn run v1.22.18
$ yarn rebuild:electron && yarn --cwd electron start
$ theia rebuild:electron
native node modules are already rebuilt for electron
$ electron scripts/theia-electron-main.js

DevTools listening on ws://127.0.0.1:9522/devtools/browser/aeaa7b94-2e2e-4044-ac10-f2ec3544b01f
Configuring to accept webviews on '^.+\.webview\..+$' hostname.
root INFO Configuration directory URI: 'file:///Users/zhangtao272/.theia'
root INFO Backend Object.initialize: 9.5 ms [Finished 1.691 s after backend start]
root INFO Backend Object.configure: 7.9 ms [Finished 1.691 s after backend start]
root INFO Backend MessagingContribution.onStart: 2.8 ms [Finished 1.691 s after backend start]
root INFO Backend LocalizationBackendContribution.configure: 0.8 ms [Finished 1.693 s after backend start]
root INFO Backend ElectronTokenBackendContribution.configure: 0.1 ms [Finished 1.693 s after backend start]
root ERROR Could not initialize contribution Error: Cannot find module '../../../i18n/nls.cs.json'
Require stack:
- /Users/zhangtao272/Documents/work/jdmp_ide/node_modules/@theia/core/lib/node/i18n/theia-localization-contribution.js
- /Users/zhangtao272/Documents/work/jdmp_ide/node_modules/@theia/core/lib/node/i18n/i18n-backend-module.js
- /Users/zhangtao272/Documents/work/jdmp_ide/electron/src-gen/backend/server.js
- /Users/zhangtao272/Documents/work/jdmp_ide/electron/src-gen/backend/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:934:15)
    at Module._load (node:internal/modules/cjs/loader:779:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at TheiaLocalizationContribution.registerLocalizations (/Users/zhangtao272/Documents/work/jdmp_ide/node_modules/@theia/core/lib/node/i18n/theia-localization-contribution.js:28:56)
    at /Users/zhangtao272/Documents/work/jdmp_ide/node_modules/@theia/core/lib/node/i18n/localization-contribution.js:35:98
    at Array.map (<anonymous>)
    at LocalizationRegistry.initialize (/Users/zhangtao272/Documents/work/jdmp_ide/node_modules/@theia/core/lib/node/i18n/localization-contribution.js:35:65)
    at LocalizationBackendContribution.initialize (/Users/zhangtao272/Documents/work/jdmp_ide/node_modules/@theia/core/lib/node/i18n/localization-backend-contribution.js:33:41)
root INFO Backend PluginDeployerContribution.initialize: 0.8 ms [Finished 1.694 s after backend start]
root INFO Backend NodeFileUploadService.configure: 2.0 ms [Finished 1.696 s after backend start]
root INFO Backend WebviewBackendSecurityWarnings.initialize: 0.3 ms [Finished 1.696 s after backend start]
root INFO Backend FileDownloadEndpoint.configure: 1.3 ms [Finished 1.698 s after backend start]
root INFO Backend MiniBrowserBackendSecurityWarnings.initialize: 0.6 ms [Finished 1.698 s after backend start]
root INFO Backend PluginApiContribution.configure: 1.6 ms [Finished 1.700 s after backend start]
root INFO Backend HostedPluginReader.configure: 0.2 ms [Finished 1.700 s after backend start]
root INFO Backend HostedPluginReader.configure: 0.2 ms [Finished 1.701 s after backend start]
root INFO Backend MiniBrowserEndpoint.configure: 0.6 ms [Finished 1.702 s after backend start]
root ERROR Uncaught Exception:  Error: getaddrinfo ENOTFOUND localhost
root ERROR Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
root WARN The local plugin referenced by local-dir:/Users/zhangtao272/.theia/plugins does not exist.`

### Additional Information

- Operating System: macOS Monterey ：12.5  MacBook Pro (16-inch, 2019)
- Theia Version:  "@theia/cli": "1.23.0"

**Comment by paul-marechal** [comment]
This is the first time I hear about the `localhost` host not being defined, how did that happen?

**Comment by bjzhangtao** [comment]
您的邮件已收到，我会尽快回复，谢谢，祝：平安!

**Comment by bjzhangtao** [comment]
> This is the first time I hear about the `localhost` host not being defined, how did that happen?

Official Git Repository，application with Electron

- [yangster-electron](https://github.com/theia-ide/yangster-electron.git)  （or use [dmg](https://github.com/theia-ide/yangster-electron/releases/tag/v0.1.1)）
- [theia.git](https://github.com/eclipse-theia/theia.git)

**Comment by bjzhangtao** [comment]
We are trying to run the following Repos on Electron,

**Comment by paul-marechal** [comment]
`localhost` not being a valid host on your system should be independent from those applications/repositories, I would be more interested with how you ended up in that state with your system?

**Comment by bjzhangtao** [comment]
Actually we develop an application based on Theia. Some users gave us feedback that the applicaiton could not be started without `localhost` defined.  We are seeking for an solution to support starting Theia without `localhost` defined in user's platform. Appreciate any help you provide. Thanks!

**Comment by kittaakos** [comment]
Moved from [here](https://github.com/eclipse-theia/theia/issues/11930#issue-1468035242):

> We have received reports of non-functional Theia electron apps from multiple users:
> 
> * [arduino/arduino-ide#1708](https://github.com/arduino/arduino-ide/issues/1708)
> * [arduino/arduino-ide#1527](https://github.com/arduino/arduino-ide/issues/1527)
> 
> Our users were friendly to help us, and [they could reproduce the bug with the TheiaBlueprint](https://github.com/arduino/arduino-ide/issues/1708#issuecomment-1330436208) application.
> 
> Relevant stack traces:
> 
> ```
> 2022-11-25 18:27:24 root ERROR Failed to start the backend application:
> 2022-11-25 18:27:24 root ERROR Error: getaddrinfo ENOTFOUND localhost
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
> 2022-11-25 18:27:24 root ERROR Uncaught Exception: 
> 2022-11-25 18:27:24 root ERROR Error: getaddrinfo ENOTFOUND localhost
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
> ```
> 
> ```
> root ERROR Failed to start the backend application: root ERROR Error: listen EADDRNOTAVAIL: address not available 127.0.0
> ```
