### ISSUE TITLE
"puppeteer" dependency in "@theia/cli" causes issues behind proxy with Node 16

### ISSUE THREAD

**Issue by luettmaSICKAG** [eclipse-theia/theia#11581]
### Bug Description:
The package `@theia/cli` depends on `puppeteer@^2.0.0`.
Since our update to `NodeJS 16.16.0` this dependency causes issues with our company proxy.

The problem might be because our HTTPS proxy uses the http protocol.

Since it seems to be used only internally, we added a yarn resolution to our repo.  
This seems to do the trick and the dependencies install without problems.

```json
{
    "resolutions": {
        "**/@theia/cli/puppeteer": "16.1.1"
    }
}
```

### Steps to Reproduce:

1. Make sure you don't have any node_modules installed: `git clean -fdX`
2. With node 14: Run `yarn install` behind a proxy (http)  
  → Should work
3. With node 16: Run `yarn install` behind a proxy (http)
  → Should fail

### Additional Information
- Operating System: Windows 10
- Theia Version: 1.26.0

Error during `yarn install`
```
[5/5] Building fresh packages...
error C:\PATH\TO\OUR\THEIA-REPO\node_modules\puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: C:\PATH\TO\OUR\THEIA-REPO\node_modules\puppeteer
Output:
ERROR: Failed to download Chromium r722234! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:372:5)
    at new ClientRequest (node:_http_client:164:11)
    at Object.request (node:https:353:10)
    at httpRequest (C:\PATH\TO\OUR\THEIA-REPO\node_modules\puppeteer\lib\BrowserFetcher.js:300:22)
    at downloadFile (C:\PATH\TO\OUR\THEIA-REPO\node_modules\puppeteer\lib\BrowserFetcher.js:230:19)
    at BrowserFetcher.download (C:\PATH\TO\OUR\THEIA-REPO\node_modules\puppeteer\lib\BrowserFetcher.js:140:13)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (C:\PATH\TO\OUR\THEIA-REPO\node_modules\puppeteer\lib\helper.js:111:15)
    at Object.<anonymous> (C:\PATH\TO\OUR\THEIA-REPO\node_modules\puppeteer\install.js:66:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ERR_INVALID_PROTOCOL'
}
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command. 
```

**Comment by vince-fugnitto** [comment]
@luettmaSICKAG thank you for reporting the issue, are you interested in bumping `puppeteer` from `^2.0.0` to `^16.1.1` as you've highlighted?

**Comment by Alexander-Taran** [comment]
Maybe swap it with playwright instead?
