### ISSUE TITLE
[preferences]: _Unable to write into user settings because the file has unsaved changes_ when toggling auto-save with dirty preferences (JSON) editor 

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#11614]
### Bug Description:

Unexpected error when toggling auto-save with dirty settings (JSON) editor.

```
Uncaught (in promise) Canceled: Canceled
    at new g (file:///Applications/TheiaBlueprint.app/Contents/Resources/app/lib/bundle.js:2:7103556)
    at new f (file:///Applications/TheiaBlueprint.app/Contents/Resources/app/lib/bundle.js:2:7105119)
    at Object.t.resolveInstance (file:///Applications/TheiaBlueprint.app/Contents/Resources/app/lib/bundle.js:2:8167529)
    at file:///Applications/TheiaBlueprint.app/Contents/Resources/app/lib/bundle.js:2:8169467
    at Object.t.resolve (file:///Applications/TheiaBlueprint.app/Contents/Resources/app/lib/bundle.js:2:8169730)
    at file:///Applications/TheiaBlueprint.app/Contents/Resources/app/lib/bundle.js:2:8153136
    at e._get (file:///Applications/TheiaBlueprint.app/Contents/Resources/app/lib/bundle.js:2:8152902)
    at e.get (file:///Applications/TheiaBlueprint.app/Contents/Resources/app/lib/bundle.js:2:8151545)
    at h.transactionFactory (file:///Applications/TheiaBlueprint.app/Contents/Resources/app/lib/bundle.js:2:7107734)
    at h.doSetPreference (file:///Applications/TheiaBlueprint.app/Contents/Resources/app/lib/bundle.js:2:7088146)
```

### Steps to Reproduce:

1. Open IDE,
2. Disable auto-save
3. Execute `Preferences: Open Settings (JSON)`,
4. Touch the file so that it will be dirty,
5. Enable auto-save

https://user-images.githubusercontent.com/1405703/186843801-f56c97a4-6c68-4081-9dce-86e54fa404df.mp4

### Additional Information

- Operating System: macOS 12.5.1
- Theia Version: TheiaBlueprint 1.28.0

**Comment by vince-fugnitto** [comment]
@kittaakos the same use case also happens in vscode, I believe it is by design.

**Comment by kittaakos** [comment]
Thank you for checking! Feel free to close it as invalid if this is the expected behavior.
