### ISSUE TITLE
Rpc Message prompts a "Maximum call stack size exceeded" error when processing too much data

### ISSUE THREAD

**Issue by likesubject** [eclipse-theia/theia#11624]
### Bug Description:
I use the Theia framework to build my own integrated development environment, when I upgrade the framework to version 1.29.0 after launching the electron application prompted the following error, using version 1.28.0 will not appear to correct the error.
```
[2022-08-31T16:18:02.628] [ERROR] AxIde - RangeError: Maximum call stack size exceeded  
    at Array.eval [as read] (eval at readObject (file:///H:/work/axio-one-ide/new-axio-one-ide/lib/bundle.js:150913:39), <anonymous>:3:19)
    at read (file:///H:/work/axio-one-ide/new-axio-one-ide/lib/bundle.js:150677:23)
    at Array.eval [as read] (eval at readObject (file:///H:/work/axio-one-ide/new-axio-one-ide/lib/bundle.js:150913:39), <anonymous>:3:39)
    at read (file:///H:/work/axio-one-ide/new-axio-one-ide/lib/bundle.js:150677:23)
    at Array.eval [as read] (eval at readObject (file:///H:/work/axio-one-ide/new-axio-one-ide/lib/bundle.js:150913:39), <anonymous>:3:37)
    at read (file:///H:/work/axio-one-ide/new-axio-one-ide/lib/bundle.js:150677:23)
    at Array.eval [as read] (eval at readObject (file:///H:/work/axio-one-ide/new-axio-one-ide/lib/bundle.js:150913:39), <anonymous>:3:45)
    at read (file:///H:/work/axio-one-ide/new-axio-one-ide/lib/bundle.js:150677:23)
    at Array.eval [as read] (eval at readObject (file:///H:/work/axio-one-ide/new-axio-one-ide/lib/bundle.js:150913:39), <anonymous>:3:32)
at read (file:///H:/work/axio-one-ide/new-axio-one-ide/lib/bundle.js:150677:23) []
```
The final error is located `this.msgPack.decode(bytes)`, guessing if there is a problem with the msgpackr library parsing some data?
```
export class MsgPackMessageDecoder implements RpcMessageDecoder {
    constructor(protected readonly msgPack: MsgPack = defaultMsgPack) {

    }
    decode<T = any>(buf: ReadBuffer): T {
        const bytes = buf.readBytes();
        return this.msgPack.decode(bytes);
    }

    parse(buffer: ReadBuffer): RpcMessage {
        return this.decode(buffer);
    }

}
```

### Steps to Reproduce:
based on how the msgpackr library is used in Theia, a small demo was written to reproduce this problem, testing the data in a compressed package  ([test.zip](https://github.com/eclipse-theia/theia/files/9461702/test.zip)).
```
const MsgPack = require('msgpackr').Packr;
const fs =  require('fs');

const data = fs.readFileSync('./test.json', 'utf-8');
const testObject = JSON.parse(data);
const defaultMsgPack = new MsgPack({ moreTypes: true, encodeUndefinedAsNil: false, bundleStrings: true });
const buffer = defaultMsgPack.encode(testObject);
const result = defaultMsgPack.decode(buffer);

```
1. read the test.json file and convert it to an object;
2. use the msgpackr library to encode the object;
3. use the msgpackr library for decoding;
4. an error occurred;
```
RangeError: Maximum call stack size exceeded
    at Array.eval [as read] (eval at readObject (H:\work\axio-one-ide\new-axio-one-ide\node_modules\msgpackr\dist\node.cjs:462:39), <anonymous>:3:19)
    at read (H:\work\axio-one-ide\new-axio-one-ide\node_modules\msgpackr\dist\node.cjs:226:23)
    at Array.eval [as read] (eval at readObject (H:\work\axio-one-ide\new-axio-one-ide\node_modules\msgpackr\dist\node.cjs:462:39), <anonymous>:3:32)
    at read (H:\work\axio-one-ide\new-axio-one-ide\node_modules\msgpackr\dist\node.cjs:226:23)
    at Array.eval [as read] (eval at readObject (H:\work\axio-one-ide\new-axio-one-ide\node_modules\msgpackr\dist\node.cjs:462:39), <anonymous>:3:32)
    at read (H:\work\axio-one-ide\new-axio-one-ide\node_modules\msgpackr\dist\node.cjs:226:23)
    at Array.eval [as read] (eval at readObject (H:\work\axio-one-ide\new-axio-one-ide\node_modules\msgpackr\dist\node.cjs:462:39), <anonymous>:3:48)
    at read (H:\work\axio-one-ide\new-axio-one-ide\node_modules\msgpackr\dist\node.cjs:226:23)
    at Array.eval [as read] (eval at readObject (H:\work\axio-one-ide\new-axio-one-ide\node_modules\msgpackr\dist\node.cjs:462:39), <anonymous>:3:37)
    at read (H:\work\axio-one-ide\new-axio-one-ide\node_modules\msgpackr\dist\node.cjs:226:23) {
  incomplete: true
}
```

### Additional Information

- Operating System: Windows 10 electron
- Theia Version: 1.29.0

#### The problem appears to be here:
if it is changed to `const defaultMsgPack = new MsgPack({ moreTypes: true, encodeUndefinedAsNil: false, bundleStrings: false});` , **bundleStrings=false** it will not prompt for the above error.

**Comment by zhaomenghuan** [comment]
I also encountered the same problem, and the editor syntax highlighting does not work.
