### ISSUE TITLE
Build theia extension on Windows fails (ffmep)

### ISSUE THREAD

**Issue by bhufmann** [eclipse-theia/theia#11981]
### Bug Description:
When build the [theia-trace-extension](https://github.com/eclipse-cdt-cloud/theia-trace-extension) on Windows 11 it fails (see log below). I followed the instructions [here](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites) to setup the development environment.

### Steps to Reproduce:

1. Clone [theia-trace-extension](https://github.com/eclipse-cdt-cloud/theia-trace-extension) 
2. [Setup environment](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites) for Windows 
3. yarn

### Additional Information
- Error log:
```error C:\Users\user\git\theia-trace-extension\node_modules\@theia\ffmpeg: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\user\git\theia-trace-extension\node_modules\@theia\ffmpeg
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.15.1 | win32 | x64
gyp info find Python using Python version 3.11.0 found at "C:\Users\user\bin\python.exe"
gyp info find VS using VS2017 (15.9.33027.88) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
(node:13024) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn C:\Users\user\bin\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\user\\git\\theia-trace-extension\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user\\git\\theia-trace-extension\\node_modules\\@theia\\ffmpeg\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user\\git\\theia-trace-extension\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user\\AppData\\Local\\node-gyp\\Cache\\16.15.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\user\\AppData\\Local\\node-gyp\\Cache\\16.15.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\user\\git\\theia-trace-extension\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\user\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.15.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\user\\git\\theia-trace-extension\\node_modules\\@theia\\ffmpeg',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\user\\git\\theia-trace-extension\\node_modules\\@theia\\ffmpeg\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "C:\Users\user\git\theia-trace-extension\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\gyp_main.py", line 51, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\git\theia-trace-extension\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 670, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\git\theia-trace-extension\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 662, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "C:\Users\user\git\theia-trace-extension\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 629, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "C:\Users\user\git\theia-trace-extension\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 150, in Load
    result = gyp.input.Load(
             ^^^^^^^^^^^^^^^
  File "C:\Users\user\git\theia-trace-extension\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 3021, in Load
    LoadTargetBuildFile(
  File "C:\Users\user\git\theia-trace-extension\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 411, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\git\theia-trace-extension\node_modules\@npmcli\run-script\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 239, in LoadOneBuildFile
    build_file_contents = open(build_file_path, "rU").read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\user\git\theia-trace-extension\node_modules\@npmcli\run-script\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\user\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\node.exe" "C:\\Users\\user\\git\\theia-trace-extension\\node_modules\\@npmcli\\run-script\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" 
gyp ERR! cwd C:\Users\user\git\theia-trace-extension\node_modules\@theia\ffmpeg`
```

- Operating System: Windows 11
- Theia Version: Theia 1.29

**Comment by msujew** [comment]
Hey @bhufmann,

for some reason nodejs wants to use `node-gyp@7.1.2` to build the native dependencies. I believe we had a similar issue in https://github.com/eclipse-theia/theia/issues/11235. Can you try to force yarn to download a newer version (like `9.3.0`)?

**Comment by msujew** [comment]
Glad I could help :)
