### ISSUE TITLE
"Browser Test" PR Check Seems Flaky

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#12081]
The step "Browser Test" that runs as part of the CI build on Ubuntu in our PR Checks sometimes fails, sometimes it succeeds. The build job runs `yarn browser test`. Strangely, these tests are only run on Ubuntu, but not on Windows.

Beyond being flaky, the tests also spew out a lot of error messages, which seem unrelated to any actual failures in the tests, for example:
```
2023-01-13T14:29:38.875Z root ERROR Error: view container is disposed
    at ViewContainer.get containerLayout [as containerLayout] (http://127.0.0.1:3000/bundle.js:135611:15)
    at ViewContainer.getParts (http://127.0.0.1:3000/bundle.js:135595:21)
    at NavigatorTabBarDecorator.decorate (http://127.0.0.1:3000/packages_navigator_lib_browser_navigator-frontend-module_js-packages_variable-resolver_lib_br-8447b0.js:455:63)
    at TabBarDecoratorService.getDecorations (http://127.0.0.1:3000/bundle.js:126961:43)
    at TabBarRenderer.getDecorations (http://127.0.0.1:3000/bundle.js:127917:86)
    at TabBarRenderer.getDecorationData (http://127.0.0.1:3000/bundle.js:127929:21)
    at TabBarRenderer.renderIcon (http://127.0.0.1:3000/bundle.js:128041:37)
    at TabBarRenderer.renderTab (http://127.0.0.1:3000/bundle.js:127803:82)
    at SideTabBar.renderTabs (http://127.0.0.1:3000/bundle.js:128497:35)
    at SideTabBar.renderTabBar (http://127.0.0.1:3000/bundle.js:128442:18)
```

In the current state, the tests don't serve to catch real failures anymore, since developers will just ignore them, assuming the failures are spurious. If a developer _does_ take the failures seriously, he will wast a lot of time to conclude that it's not a problem in the PR in many instances.

**Comment by tsmaeder** [comment]
@marcdumais
