### ISSUE TITLE
WorkspaceExtImpl.findFiles() not compatible with vscode's?  

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#12227]
### Bug Description
When running the browser tests (preferences test suite), I noticed the following exception:

```
2023-02-24T17:14:51.818Z root INFO     ✅ Handles many synchronous settings of preferences gracefully (132ms)
2023-02-24T17:14:51.911Z root INFO   Saveable
2023-02-24T17:14:52.017Z root ERROR [hosted-plugin: 755563] Promise rejection not handled in one second: TypeError: Cannot read properties of undefined (reading 'toString') , reason: TypeError: Cannot read properties of undefined (reading 'toString')
2023-02-24T17:14:52.018Z root ERROR [hosted-plugin: 755563] With stack trace: TypeError: Cannot read properties of undefined (reading 'toString')
    at WorkspaceExtImpl.findFiles (/home/\<user\>/theia/packages/plugin-ext/lib/plugin/workspace.js:144:52)
    at Object.findFiles (/home/\<user\>/theia/packages/plugin-ext/lib/plugin/plugin-context.js:443:37)
    at v.getJsTsFileBeingMoved (/home/\<user\>/theia/plugins/vscode.typescript-language-features/extension/dist/extension.js:1:418657)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/\<user\>/theia/plugins/vscode.typescript-language-features/extension/dist/extension.js:1:416744
```
The call originates from the vscode builtin extension `vscode.typescript-language-features`. Here are the places in the typescript extension where this function is called, vscode v1.70.2 (looks more likely the second case is the one triggering the exception): 

```
$ grep -R findFiles vscode/extensions/typescript-language-features/*
vscode/extensions/typescript-language-features/src/task/tsconfigProvider.ts:		return await vscode.workspace.findFiles('**/tsconfig*.json', '**/{node_modules,.*}/**', undefined, token);
vscode/extensions/typescript-language-features/src/languageFeatures/updatePathsOnRename.ts:			const files = await vscode.workspace.findFiles(new vscode.RelativePattern(resource, '**/*.{ts,tsx,js,jsx}'), '**/node_modules/**', 1);
```

### Steps to Reproduce:

1. build the Theia repo: `yarn && yarn browser build && yarn download:plugins`
2. run the broser test suite: `yarn browser test`
3. watch for the exception during the `preferences` tests

### Additional Information

- Operating System:
- Theia Version:

**Comment by marcdumais-work** [comment]
The problem disappeared when we tested with a slightly newer version of the typescript vscode builtin extension.
