### ISSUE TITLE
vscode.git plugin issue in latest Theia

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#12238]
### Bug Description:
Hi,
I am using the 'vscode.git' and the 'vscode.git-base' plugins (version 1.66.2), I see that the toolbar buttons of the source control tree are not working, also the button on the nodes themselves. Moreover file changes or new files in the project tree, are not reflected/refreshed in the source control (needs a page reload or Git: Refresh command).

### Steps to Reproduce:

1. open a project with git, using Theia with the above plugins (instead of the built-in git extension).
2. try the source control refresh/commit buttons 
3. you will see the following error in the console.
4. try doing some file changes in the project tree, you will see those changes i the source control tree !!!

### Additional Information
One of the errors:
```
Uncaught TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function
    at PluginMenuCommandAdapter.executeCommand (plugin-menu-command-adapter.ts:125:37)
    at MenuCommandExecutorImpl.delegate (menu-adapter.ts:68:30)
    at MenuCommandExecutorImpl.executeCommand (menu-adapter.ts:50:21)
    at TabBarToolbar.executeCommand (tab-bar-toolbar.tsx:264:38)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
executeCommand @ plugin-menu-command-adapter.ts:125
delegate @ menu-adapter.ts:68
executeCommand @ menu-adapter.ts:50
TabBarToolbar.executeCommand @ tab-bar-toolbar.tsx:264
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
react-dom.development.js:4312 Uncaught TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function
    at PluginMenuCommandAdapter.executeCommand (plugin-menu-command-adapter.ts:125:37)
    at MenuCommandExecutorImpl.delegate (menu-adapter.ts:68:30)
    at MenuCommandExecutorImpl.executeCommand (menu-adapter.ts:50:21)
    at TabBarToolbar.executeCommand (tab-bar-toolbar.tsx:264:38)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
```

- Operating System: Windows 10
- Theia Version: 1.35.0

**Comment by marcdumais-work** [comment]
This may be related to #12173
