### ISSUE TITLE
SCM package mishandles submodules

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#12302]
### Bug Description:

If a submodule is present in a repo and it is modified relative to the HEAD state of the parent repo, the submodule appears in the 'changes' tree of the SCM widget, but clicking on it throws an error and produces no visible effect.

### Steps to Reproduce:

1. Create a repo with a submodule.
2. Checkout a commit in the submodule other than the one specified by the current HEAD
3. Click on the corresponding item in the SCM tree.
4. Observe an error like this:
```
2023-03-14T17:05:53.667Z root ERROR Request show failed with error: fatal: bad object HEAD:<submodule name>
 GitError: fatal: bad object HEAD:<submodule name>

    at new GitError (.../node_modules/dugite-extra/lib/core/git.js:91:28)
    at .../dugite-extra/lib/core/git.js:266:27
    at step (.../dugite-extra/lib/core/git.js:59:23)
    at Object.next (.../dugite-extra/lib/core/git.js:40:53)
    at fulfilled (.../dugite-extra/lib/core/git.js:31:58)
```

### Additional Information

- Operating System: RHEL
- Theia Version: 1.34.2

**Comment by colin-grant-work** [comment]
Agreed 👍
