### ISSUE TITLE
TabAPI throws Error when Closing

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#12392]
### Bug Description:
I get exceptions in the browser log when closing editor tabs: 
```
rpc-message-encoder.ts:184 Uncaught (in promise) Error: Tab close updated received for index 4 which does not exist
    at TabGroupExt.acceptTabOperation (C:\Users\thomas\code\EclipseSource\theia\packages\plugin-ext\lib\plugin\tabs.js:156:23)
    at TabsExtImpl.$acceptTabOperation (C:\Users\thomas\code\EclipseSource\theia\packages\plugin-ext\lib\plugin\tabs.js:286:27)
    at C:\Users\thomas\code\EclipseSource\theia\packages\plugin-ext\lib\common\proxy-handler.js:91:71
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RpcProtocol.handleRequest (C:\Users\thomas\code\EclipseSource\theia\packages\core\lib\common\message-rpc\rpc-protocol.js:167:28)
```

### Steps to Reproduce:

1. Open 4 editors
2. Close the second-to-last (third) tab
3. Close the last tab
4. Observe: you get the above exception

From a cursory inspection of the code, it seems that the `TabInfo.tabIndex` field is not updated upon deletion. So when I delete for the second time, it notifies the deletion with index `3`, which doesn't exist.

### Additional Information

- Operating System: Windows Electron
- Theia Version: master

**Comment by tsmaeder** [comment]
Tagging @jonah-iden, because he might know what's up.

**Comment by jonah-iden** [comment]
oh yeah, that seems like an inconsistency arises between the model in `tabs-main` and the actual tabs from phosphor. I can probably take a look at it tomorrow. Should be easy to fix
