### ISSUE TITLE
Error during encoding:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ctownshend** [eclipse-theia/theia#12403]
### Bug Description:
When clicking on our extensions GUI, there should be a screen that appears which contains all versions of a library including vulnerability data. When used in VScode this works, when used in theia we get a runtime error. 
2023-04-12T11:29:35.986Z root ERROR [hosted-plugin: 33224] Promise rejection not handled in one second: Error: Error during encoding: ‘Maximum call stack size exceeded’ , reason: Error: Error during encoding: ‘Maximum call stack size exceeded’
With stack trace: Error: Error during encoding: ‘Maximum call stack size exceeded’
    at MsgPackMessageEncoder.encode (/Users/camerontownshend/Dropbox/Mac/Documents/Cameron/dev/learnNPM/theia/theia/theia/packages/core/lib/common/message-rpc/rpc-message-encoder.js:72:23)
    at MsgPackMessageEncoder.request (/Users/camerontownshend/Dropbox/Mac/Documents/Cameron/dev/learnNPM/theia/theia/theia/packages/core/lib/common/message-rpc/rpc-message-encoder.js:58:14)
    at RpcProtocol.sendRequest (/Users/camerontownshend/Dropbox/Mac/Documents/Cameron/dev/learnNPM/theia/theia/theia/packages/core/lib/common/message-rpc/rpc-protocol.js:124:22)
    at /Users/camerontownshend/Dropbox/Mac/Documents/Cameron/dev/learnNPM/theia/theia/theia/packages/plugin-ext/lib/common/proxy-handler.js:55:45
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Steps to Reproduce:

1. Install the Sonatype Nexus IQ Plugin https://marketplace.visualstudio.com/items?itemName=SonatypeCommunity.vscode-iq-plugin
2. Open a project which contains packages e.g. an npm project
3. You should see the list of packages and an icon with their vulnerability score
4. When you click on the package, you should see a writeup of the package and its vulneabilities and alternative versions
5. Instead you only get the outer window appearing and no content
6. In debug mode  you can see the error above is thrown

Correct behaviour can be seen on our marketplace and github readme.
The incorrect behaviour can be seen below.
![image](https://user-images.githubusercontent.com/155307/231459153-f9ea8d5d-fdd6-41ea-a0ed-7a11705d481f.png)

### Additional Information

- Operating System: N/A I am using mac, but appears to be a problem on all browsers regardless of OS
- Theia Version: 1.36, also Eclipse Che and Redhat codeready

**Comment by tortmayr** [comment]
@ctownshend  
Thanks for raising this issue. I did a little testing at it seems like our RPC implementation is not capable of properly serializing the messages that your plugin is sending to the webview. Our RPC system is implemented based on the assumption that it can serialize any message that is also serializable  in VS Code. Unfortunately this is not the case here.  At first inspection I could not find anything unusual in your messages and I have to do a little bit more testing to understand the problem i.e. find out which part of the message actually causes the serialization issue. I will come back to you once I know more.
