### ISSUE TITLE
[proposed API][builtins] Theia misses proposed API: ExternalUriOpener

### ISSUE THREAD

**Issue by alvsan09** [eclipse-theia/theia#12523]
### Bug Description:
The following exception was encountered while activating built-in extensions in `theia`  coming from `vscode` `1.77.3`

`
2023-05-11T19:40:54.698Z root ERROR [hosted-plugin: 9798] Activating extension 'Simple Browser' failed: TypeError: vscode.window.registerExternalUriOpener is not a function
`
The extension uses the proposed API: [ExternalUriOpener](https://github.com/microsoft/vscode/blob/704ed70d4fd1c6bd6342c436f1ede30d1cff4710/src/vscode-dts/vscode.proposed.externalUriOpener.d.ts#L142-L143)

### Steps to Reproduce:

[simple-browser-1.77.2-next.e344f1f539a.zip](https://github.com/eclipse-theia/theia/files/11456444/simple-browser-1.77.2-next.e344f1f539a.zip)

1. Download and change the extension of the file above to `vsix`
2. Install it in 'theia', either via  the `Extensions` view or by placing it inside the `plugins` folder
3. Attempt to activate the extension by running the command `Simple Browser: Show`
4. You will see a toast message stating that the activation of the `Simple Browser (built-in)` extension failed.

### Additional Information
```
2023-05-11T19:40:54.698Z root ERROR [hosted-plugin: 9798] Activating extension 'Simple Browser' failed: TypeError: vscode.window.registerExternalUriOpener is not a function
    at activate (/home/lmcalvs/git/vscode4/extensions/simple-browser/out/extension.js:49:46)
    at PluginManagerExtImpl.startPlugin (/home/lmcalvs/git/theia2/packages/plugin-ext/lib/plugin/plugin-manager.js:310:81)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/lmcalvs/git/theia2/packages/plugin-ext/lib/plugin/plugin-manager.js:219:21
    at async PluginManagerExtImpl.$activatePlugin (/home/lmcalvs/git/theia2/packages/plugin-ext/lib/plugin/plugin-manager.js:271:13)
    at async Promise.all (index 14)
    at async PluginManagerExtImpl.activateBySingleEvent (/home/lmcalvs/git/theia2/packages/plugin-ext/lib/plugin/plugin-manager.js:266:9)
    at async PluginManagerExtImpl.$activateByEvent (/home/lmcalvs/git/theia2/packages/plugin-ext/lib/plugin/plugin-manager.js:250:13)
    at async PluginManagerExtImpl.$start (/home/lmcalvs/git/theia2/packages/plugin-ext/lib/plugin/plugin-manager.js:148:9)
    at async RpcProtocol.handleRequest (/home/lmcalvs/git/theia2/packages/core/lib/common/message-rpc/rpc-protocol.js:167:28)
   ```

- Operating System:
- Theia Version:

**Comment by alvsan09** [comment]
Fixed by: https://github.com/eclipse-theia/theia/pull/12539
