### ISSUE TITLE
Error: No matching bindings found for serviceIdentifier: Symbol(RequestService)

### ISSUE THREAD

**Issue by thewbuk** [eclipse-theia/theia#12549]
### Bug Description:
`Error: No matching bindings found for serviceIdentifier: Symbol(RequestService)` on yarn theia start

### Steps to Reproduce:

1. Clone repo
2. Install dependencies and build
3. `yarn theia start`

### Additional Information

- Operating System: Google Cloud VM and local
- Theia Version: 1.37.1

Troubleshooting steps tried:

- remove `yarn.lock` and reinstall dependencies 
- update dependencies to the latest

### Console log

```
    at _validateActiveBindingCount (C:\path\node_modules\inversify\lib\planning\planner.js:63:23)
    at _getActiveBindings (C:\path\node_modules\inversify\lib\planning\planner.js:49:5)
    at _createSubRequests (C:\path\node_modules\inversify\lib\planning\planner.js:92:26)
    at C:\path\node_modules\inversify\lib\planning\planner.js:116:17
    at Array.forEach (<anonymous>)
    at C:\path\node_modules\inversify\lib\planning\planner.js:115:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (C:\path\node_modules\inversify\lib\planning\planner.js:95:20)
    at Object.plan (C:\path\node_modules\inversify\lib\planning\planner.js:137:9)
    at C:\path\node_modules\inversify\lib\container\container.js:333:37
```

### ```package.json```

```
{
  "private": true,
  "name": "@theia/monorepo",
  "version": "0.0.0",
  "engines": {
    "yarn": ">=1.7.0 <2",
    "node": ">=16.14.0 <17"
  },
  "resolutions": {
    "**/@types/node": "16"
  },
  "devDependencies": {
    "@types/chai": "4.3.0",
    "@types/chai-spies": "1.0.3",
    "@types/chai-string": "^1.4.0",
    "@types/jsdom": "^21.1.1",
    "@types/node": "16",
    "@types/sinon": "^10.0.6",
    "@types/temp": "^0.8.29",
    "@types/uuid": "^7.0.3",
    "@typescript-eslint/eslint-plugin": "^4.8.1",
    "@typescript-eslint/eslint-plugin-tslint": "^4.8.1",
    "@typescript-eslint/parser": "^4.8.1",
    "chai": "4.3.4",
    "chai-spies": "1.0.0",
    "chai-string": "^1.4.0",
    "chalk": "4.0.0",
    "concurrently": "^3.5.0",
    "debug": "^4.3.2",
    "electron-mocha": "^11.0.2",
    "eslint": "7",
    "eslint-plugin-deprecation": "~1.2.1",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-no-null": "latest",
    "eslint-plugin-no-unsanitized": "latest",
    "eslint-plugin-react": "^7.31.10",
    "glob": "^7.1.7",
    "if-env": "^1.0.4",
    "ignore-styles": "^5.0.1",
    "improved-yarn-audit": "^3.0.0",
    "jsdom": "^21.1.1",
    "lerna": "^6.0.1",
    "mkdirp": "^0.5.0",
    "node-gyp": "^9.0.0",
    "nsfw": "^2.2.4",
    "nyc": "^15.0.0",
    "puppeteer": "^19.7.2",
    "puppeteer-core": "^19.7.2",
    "puppeteer-to-istanbul": "^1.4.0",
    "rimraf": "^2.6.1",
    "sinon": "^12.0.0",
    "temp": "^0.8.3",
    "tslint": "^5.12.0",
    "typedoc": "^0.22.11",
    "typedoc-plugin-external-module-map": "1.3.2",
    "typescript": "~4.5.5",
    "uuid": "^8.0.0",
    "yargs": "^15.3.1"
  },
  "scripts": {
    "all": "yarn -s install && yarn -s lint && yarn -s build",
    "browser": "yarn -s --cwd examples/browser",
    "build": "yarn -s compile && yarn -s build:examples",
    "build-p": "yarn -s compile && lerna run --scope=\"@theia/example-*\" bundle --parallel",
    "build:examples": "lerna run --scope=\"@theia/example-*\" bundle --parallel",
    "clean": "yarn -s rebuild:clean && yarn -s lint:clean && node scripts/run-reverse-topo.js yarn -s clean",
    "compile": "echo Compiling TypeScript sources... && yarn -s compile:clean && yarn -s compile:tsc",
    "compile:clean": "ts-clean dev-packages/* packages/*",
    "compile:references": "node scripts/compile-references.js",
    "compile:tsc": "tsc -b",
    "docs": "rimraf gh-pages/docs/next && typedoc --tsconfig tsconfig.json --options configs/typedoc.json .",
    "download:plugins": "theia download:plugins",
    "electron": "yarn -s --cwd examples/electron",
    "license:check": "node scripts/check_3pp_licenses.js",
    "license:check:review": "node scripts/check_3pp_licenses.js --review",
    "lint": "lerna run lint",
    "lint:clean": "rimraf .eslintcache",
    "lint:oneshot": "node --max-old-space-size=4096 node_modules/eslint/bin/eslint.js --cache=true \"{dev-packages,packages,examples}/**/*.{ts,tsx}\"",
    "preinstall": "node-gyp install",
    "prepare": "yarn -s compile:references && lerna run prepare && yarn -s compile",
    "publish:latest": "lerna publish --exact --yes --no-push && yarn -s publish:check",
    "publish:next": "lerna publish preminor --exact --canary --preid next --dist-tag next --no-git-reset --no-git-tag-version --no-push --yes && yarn -s publish:check",
    "publish:check": "node scripts/check-publish.js",
    "rebuild:clean": "rimraf .browser_modules",
    "test": "yarn -s test:theia && yarn -s electron test && yarn -s browser test",
    "test:theia": "lerna run --scope \"@theia/!(example-)*\" test --stream --concurrency=1",
    "test:playwright": "yarn -s --cwd examples/playwright ui-tests",
    "version": "lerna run version",
    "watch": "concurrently --kill-others -n tsc,browser,electron -c red,yellow,blue \"tsc -b -w --preserveWatchOutput\" \"yarn -s --cwd examples/browser watch:bundle\" \"yarn -s --cwd examples/electron watch:bundle\"",
    "watch:compile": "concurrently --kill-others -n cleanup,tsc -c magenta,red \"ts-clean dev-packages/* packages/* -w\" \"tsc -b -w --preserveWatchOutput\"",
    "performance:startup": "yarn -s performance:startup:browser && yarn -s performance:startup:electron",
    "performance:startup:browser": "concurrently --success first -k -r \"cd scripts/performance && node browser-performance.js --name 'Browser Frontend Startup' --folder browser --runs 10\" \"yarn -s --cwd examples/browser start\"",
    "performance:startup:electron": "yarn -s electron rebuild && cd scripts/performance && node electron-performance.js --name 'Electron Frontend Startup' --folder electron --runs 10"
  },
  "workspaces": [
    "dev-packages/*",
    "examples/*",
    "packages/*"
  ],
  "theiaPluginsDir": "plugins",
  "theiaPlugins": {
    "vscode.markdown-language-features": "https://open-vsx.org/api/vscode/markdown-language-features/1.64.2/file/vscode.markdown-language-features-1.64.2.vsix",
    "eclipse-theia.builtin-extension-pack": "https://open-vsx.org/api/eclipse-theia/builtin-extension-pack/1.70.2/file/eclipse-theia.builtin-extension-pack-1.70.2.vsix",
    "EditorConfig.EditorConfig": "https://open-vsx.org/api/EditorConfig/EditorConfig/0.14.4/file/EditorConfig.EditorConfig-0.14.4.vsix",
    "dbaeumer.vscode-eslint": "https://open-vsx.org/api/dbaeumer/vscode-eslint/2.1.20/file/dbaeumer.vscode-eslint-2.1.20.vsix"
  },
  "theiaPluginsExcludeIds": [
    "ms-vscode.js-debug-companion",
    "vscode.extension-editing",
    "vscode.git",
    "vscode.git-base",
    "vscode.github",
    "vscode.github-authentication",
    "vscode.ipynb",
    "vscode.microsoft-authentication",
    "ms-vscode.references-view"
  ]
}
```

**Comment by vince-fugnitto** [comment]
@thewbuk thank you for reporting the issue, unfortunately I am unable to reproduce:

- clone the repository
- perform `yarn`
- perform `yarn browser build` (build examples/browser application)
- perform `yarn browser start` (start the examples/browser application)

**Comment by thewbuk** [comment]
@vince-fugnitto, thanks for a speedy reply

1. What is the difference between `yarn browser start` and `yarn theia start`
2. Running `yarn browser start` results in:

```
native node modules are already rebuilt for browser
Configuration directory URI: 'file:///c%3A/path/.theia'
Configuring to accept webviews on '^.+\.webview\..+$' hostname.
2023-05-19T12:00:23.841Z root INFO Backend Object.initialize: 18.4 ms [Finished 1.183 s after backend start]
2023-05-19T12:00:23.841Z root INFO Backend Object.configure: 16.6 ms [Finished 1.184 s after backend start]
2023-05-19T12:00:23.841Z root INFO Backend MessagingContribution.onStart: 2.8 ms [Finished 1.184 s after backend start]
2023-05-19T12:00:23.842Z root INFO Backend OSBackendApplicationContribution.configure: 1.0 ms [Finished 1.210 s after backend start]
2023-05-19T12:00:23.844Z root INFO Backend PluginLocalizationBackendContribution.configure: 0.2 ms [Finished 1.210 s after backend start]
2023-05-19T12:00:23.846Z root INFO Backend PluginLocalizationBackendContribution.initialize: 26.3 ms [Finished 1.210 s after backend start]
2023-05-19T12:00:23.848Z root INFO Backend PluginDeployerContribution.initialize: 0.4 ms [Finished 1.212 s after backend start]
2023-05-19T12:00:23.849Z root INFO Backend NodeFileUploadService.configure: 2.9 ms [Finished 1.213 s after backend start]
2023-05-19T12:00:23.850Z root INFO Backend WebviewBackendSecurityWarnings.initialize: 0.6 ms [Finished 1.214 s after backend start]
2023-05-19T12:00:23.851Z root INFO Backend FileDownloadEndpoint.configure: 1.6 ms [Finished 1.216 s after backend start]
2023-05-19T12:00:23.852Z root INFO Backend HostedPluginLocalizationService.initialize: 0.7 ms [Finished 1.217 s after backend start]
2023-05-19T12:00:23.852Z root INFO Backend PluginApiContribution.configure: 0.9 ms [Finished 1.218 s after backend start]
2023-05-19T12:00:23.852Z root INFO Backend MiniBrowserBackendSecurityWarnings.initialize: 0.6 ms [Finished 1.220 s after backend start]
2023-05-19T12:00:23.853Z root INFO Backend HostedPluginReader.configure: 0.6 ms [Finished 1.221 s after backend start]
2023-05-19T12:00:23.854Z root INFO Backend HostedPluginReader.initialize: 0.8 ms [Finished 1.222 s after backend start]
2023-05-19T12:00:23.854Z root INFO Backend HostedPluginReader.configure: 0.4 ms [Finished 1.222 s after backend start]
2023-05-19T12:00:23.854Z root INFO Backend MetricsBackendApplicationContribution.configure: 0.6 ms [Finished 1.223 s after backend start]
2023-05-19T12:00:23.855Z root INFO Backend MiniBrowserEndpoint.configure: 1.1 ms [Finished 1.224 s after backend start]
Done in 3.90s.
```

3. Is it the desired outcome? Does it start the backend, and the front end must be started in some other way? 
4. Why does the [documentation ](https://theia-ide.org/docs/composing_applications/) only refer to `yarn theia start`? 

Thanks in advance

**Comment by vince-fugnitto** [comment]
@thewbuk 

> Why does the [documentation ](https://theia-ide.org/docs/composing_applications/)only refer to yarn theia start?

You're looking at the documentation when building your own Theia-based application, not the steps to build this repository:
- https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md

> Is it the desired outcome? Does it start the backend, and the front end must be started in some other way?

You can connect to the frontend by going to http://localhost:3000/.
