### ISSUE TITLE
Electron app from package.json builds the browser native modules instead of electron's version

### ISSUE THREAD

**Issue by hexa00** [eclipse-theia/theia#1258]
With package.json:

```
{
  "private": true,
  "name": "@theia/example-electron",
  "version": "0.3.4",
  "theia": {
    "target": "electron"
  },
  "dependencies": {
    "@theia/core": "next",
    "@theia/cpp": "next",
    "@theia/editor": "next",
    "@theia/extension-manager": "next",
    "@theia/file-search": "next",
    "@theia/filesystem": "next",
    "@theia/git": "next",
    "@theia/java": "next",
    "@theia/keymaps": "next",
    "@theia/languages": "next",
    "@theia/markers": "next",
    "@theia/messages": "next",
    "@theia/metrics": "next",
    "@theia/monaco": "next",
    "@theia/navigator": "next",
    "@theia/outline-view": "next",
    "@theia/output": "next",
    "@theia/preferences": "next",
    "@theia/preview": "next",
    "@theia/process": "next",
    "@theia/python": "next",
    "@theia/search-in-workspace": "next",
    "@theia/task": "next",
    "@theia/terminal": "next",
    "@theia/typescript": "next",
    "@theia/userstorage": "next",
    "@theia/workspace": "next"
  },
  "scripts": {
    "prepare": "yarn run clean && yarn build",
    "clean": "theia clean",
    "build": "theia build",
    "watch": "yarn build --watch",
    "start": "theia start",
    "start:debug": "yarn start --loglevel=debug",
    "test": "electron-mocha --timeout 60000 --require ts-node/register \"./test/**/*.espec.ts\"",
    "test:ui": "wdio wdio.conf.js"
  },
  "devDependencies": {
    "@theia/cli": "next"
  }
}
```

You get:

```
yarn
yarn start                                

yarn run v1.3.2
$ theia start
Starting server worker...

Server worker has been started. [ID: 1 | PID: 1580]

Failed to start the backend application.

Error: The module '/home/eantotr/test-electron/node_modules/node-pty/build/Release/pty.node'

was compiled against a different Node.js version using

NODE_MODULE_VERSION 57. This version of Node.js requires

NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)

    at Object.Module._extensions..node (module.js:598:18)

    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)

    at Module.load (module.js:488:32)

    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)

    at require (internal/module.js:20:19)

    at Object.<anonymous> (/home/eantotr/test-electron/node_modules/node-pty/lib/unixTerminal.js:21:11)
    at Object.<anonymous> (/home/eantotr/test-electron/node_modules/node-pty/lib/unixTerminal.js:252:3)

/home/eantotr/test-electron/node_modules/@theia/core/lib/node/cluster/main.js:49
    throw reason;
    ^

Error: The module '/home/eantotr/test-electron/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/eantotr/test-electron/node_modules/node-pty/lib/unixTerminal.js:21:11)
    at Object.<anonymous> (/home/eantotr/test-electron/node_modules/node-pty/lib/unixTerminal.js:252:3)

Server worker has been disconnected. [ID: 1 | PID: 1580]

Server worker has been stopped. [ID: 1 | PID: 1580]

```

**Comment by vince-fugnitto** [comment]
I don't believe it is a problem since it is only present in main repo, is only for Theia developers and the workflow is defined in the [`quick start`](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#quick-start). If a developer builds the application using `yarn` from the main root of the application it builds the `browser` target. In order to build the `electron` target, the native modules must be rebuilt for it (which is documented).
