### ISSUE TITLE
"Invalid Tab" Error Messages in Log

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#12702]
### Bug Description:
While trying to self-host, I occasionally get the following exception in the log. Not sure what causes it.

```
Uncaught (in promise) Error: INVALID tab
    at d.acceptTabOperation (/C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\618.js:1:488323)
    at t.TabsExtImpl.$acceptTabOperation (/C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\618.js:1:490637)
    at /C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\557.js:1:78593
    at process.processTicksAndRejections (VM33 task_queues:95:5)
    at async c.handleRequest (/C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\19.js:1:46888)
```` 

### Additional Information

- Operating System: Win 11
- Theia Version: Blueprint 1.39.0

**Comment by tsmaeder** [comment]
I'm also getting error replies with no corresponding request ids. The stack trace in the error reply says:
```
"Error: Update Tabs IPC call received before group creation.
    at t.TabsExtImpl.$acceptTabOperation (C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\618.js:1:490561)
    at C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\557.js:1:78593
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async c.handleRequest (C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\19.js:1:46888)"
``

**Comment by meisenbarth-work** [comment]
I get the INVALID tab error as well. It appears when I have the editor split in two groups and switch between the documents in the 2nd group. I've tested with the Theia IDE Release 1.50.100.

![image](https://github.com/eclipse-theia/theia/assets/144816090/caa1b679-d0f7-4856-9ef0-c73360afcefa)
