### ISSUE TITLE
Stale Problem Markers and Errors in Log after Long Editing Session

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#12701]
### Bug Description:
When editing Typescript files in the Theia code base, sometimes I get into a state where the squiggly error lines are clearly out of date. There is no clear scenario how to provoke this.

### Steps to Reproduce:

1. Edit typescript file
2. ?
3. Stale Error markers and exceptions in log

Note that closing and reopening the editor fixes the problem.

<details>

```

logger-protocol.ts:113 2023-07-11T15:10:52.758Z root ERROR Error: No reply handler for error reply with id: 665
    at l.handleReplyErr (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2313238)
    at l.handleMessage (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2312855)
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2312218
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2261081
    at r.invoke (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2261171)
    at s.fire (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2262965)
    at t.ChannelMultiplexer.handleData (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2308030)
    at t.ChannelMultiplexer.handleMessage (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2307311)
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2306475
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2261081
e.log @ logger-protocol.ts:113
(anonymous) @ logger-frontend-module.ts:42
(anonymous) @ logger.ts:310
(anonymous) @ logger.ts:302
Promise.then (async)
log @ logger.ts:297
i @ logger.ts:45
invoke @ event.ts:138
fire @ event.ts:279
handleData @ channel.ts:251
handleMessage @ channel.ts:209
(anonymous) @ channel.ts:167
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleMessages @ rpc-protocol.ts:217
(anonymous) @ rpc-protocol.ts:161
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ hosted-plugin.ts:560
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
postMessage @ hosted-plugin-watcher.ts:36
onRequest @ proxy-factory.ts:166
(anonymous) @ proxy-factory.ts:145
handleRequest @ rpc-protocol.ts:216
handleMessage @ rpc-protocol.ts:101
(anonymous) @ rpc-protocol.ts:85
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleData @ channel.ts:251
handleMessage @ channel.ts:209
(anonymous) @ channel.ts:167
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ web-socket-channel.ts:38
(anonymous) @ ws-connection-provider.ts:84
n.emit @ index.mjs:136
emitEvent @ socket.js:519
onevent @ socket.js:506
onpacket @ socket.js:474
n.emit @ index.mjs:136
(anonymous) @ manager.js:237
Promise.then (async)
(anonymous) @ websocket-constructor.browser.js:8
ondecoded @ manager.js:236
n.emit @ index.mjs:136
add @ index.js:167
ondata @ manager.js:223
n.emit @ index.mjs:136
onPacket @ socket.js:363
n.emit @ index.mjs:136
onPacket @ transport.js:107
onData @ transport.js:99
ws.onmessage @ websocket.js:76
logger-protocol.ts:113 2023-07-11T15:10:52.759Z root ERROR Error: No reply handler for error reply with id: 597
    at l.handleReplyErr (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2313238)
    at l.handleMessage (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2312855)
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2312218
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2261081
    at r.invoke (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2261171)
    at s.fire (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2262965)
    at t.ChannelMultiplexer.handleData (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2308030)
    at t.ChannelMultiplexer.handleMessage (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2307311)
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2306475
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2261081
e.log @ logger-protocol.ts:113
(anonymous) @ logger-frontend-module.ts:42
(anonymous) @ logger.ts:310
(anonymous) @ logger.ts:302
Promise.then (async)
log @ logger.ts:297
i @ logger.ts:45
invoke @ event.ts:138
fire @ event.ts:279
handleData @ channel.ts:251
handleMessage @ channel.ts:209
(anonymous) @ channel.ts:167
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleMessages @ rpc-protocol.ts:217
(anonymous) @ rpc-protocol.ts:161
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ hosted-plugin.ts:560
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
postMessage @ hosted-plugin-watcher.ts:36
onRequest @ proxy-factory.ts:166
(anonymous) @ proxy-factory.ts:145
handleRequest @ rpc-protocol.ts:216
handleMessage @ rpc-protocol.ts:101
(anonymous) @ rpc-protocol.ts:85
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleData @ channel.ts:251
handleMessage @ channel.ts:209
(anonymous) @ channel.ts:167
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ web-socket-channel.ts:38
(anonymous) @ ws-connection-provider.ts:84
n.emit @ index.mjs:136
emitEvent @ socket.js:519
onevent @ socket.js:506
onpacket @ socket.js:474
n.emit @ index.mjs:136
(anonymous) @ manager.js:237
Promise.then (async)
(anonymous) @ websocket-constructor.browser.js:8
ondecoded @ manager.js:236
n.emit @ index.mjs:136
add @ index.js:167
ondata @ manager.js:223
n.emit @ index.mjs:136
onPacket @ socket.js:363
n.emit @ index.mjs:136
onPacket @ transport.js:107
onData @ transport.js:99
ws.onmessage @ websocket.js:76
rpc-message-encoder.ts:184 Uncaught (in promise) Error: INVALID tab
    at d.acceptTabOperation (/C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\618.js:1:488323)
    at t.TabsExtImpl.$acceptTabOperation (/C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\618.js:1:490637)
    at /C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\557.js:1:78593
    at process.processTicksAndRejections (VM33 task_queues:95:5)
    at async c.handleRequest (/C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\19.js:1:46888)
deserialize @ rpc-message-encoder.ts:184
D @ unpack.js:406
i @ unpack.js:504
Y @ unpack.js:965
D @ unpack.js:400
k @ unpack.js:195
unpack @ unpack.js:102
decode @ unpack.js:174
decode @ rpc-message-encoder.ts:163
parse @ rpc-message-encoder.ts:167
(anonymous) @ rpc-protocol.ts:85
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleData @ channel.ts:251
handleMessage @ channel.ts:209
(anonymous) @ channel.ts:167
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleMessages @ rpc-protocol.ts:217
(anonymous) @ rpc-protocol.ts:161
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ hosted-plugin.ts:560
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
postMessage @ hosted-plugin-watcher.ts:36
onRequest @ proxy-factory.ts:166
(anonymous) @ proxy-factory.ts:145
handleRequest @ rpc-protocol.ts:216
handleMessage @ rpc-protocol.ts:101
(anonymous) @ rpc-protocol.ts:85
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleData @ channel.ts:251
handleMessage @ channel.ts:209
(anonymous) @ channel.ts:167
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ web-socket-channel.ts:38
(anonymous) @ ws-connection-provider.ts:84
n.emit @ index.mjs:136
emitEvent @ socket.js:519
onevent @ socket.js:506
onpacket @ socket.js:474
n.emit @ index.mjs:136
(anonymous) @ manager.js:237
logger-protocol.ts:113 2023-07-11T15:11:00.625Z root ERROR onWillSave listeners should provide edits, not directly alter the document.
e.log @ logger-protocol.ts:113
(anonymous) @ logger-frontend-module.ts:42
(anonymous) @ logger.ts:310
(anonymous) @ logger.ts:302
Promise.then (async)
log @ logger.ts:297
i @ logger.ts:45
(anonymous) @ monaco-editor-model.ts:617
await in (anonymous) (async)
sequence @ event.ts:290
await in sequence (async)
fireWillSaveModel @ monaco-editor-model.ts:579
doSave @ monaco-editor-model.ts:542
(anonymous) @ monaco-editor-model.ts:478
(anonymous) @ monaco-editor-model.ts:374
Promise.then (async)
run @ monaco-editor-model.ts:372
scheduleSave @ monaco-editor-model.ts:478
save @ monaco-editor-model.ts:364
e.save @ saveable.ts:91
save @ save-resource-service.ts:46
save @ common-frontend-contribution.ts:1114
execute @ common-frontend-contribution.ts:894
executeCommand @ command.ts:337
await in executeCommand (async)
executeKeyBinding @ keybinding.ts:478
run @ keybinding.ts:598
o @ keybinding.ts:555
logger-protocol.ts:113 2023-07-11T15:11:00.651Z root ERROR Error: No reply handler for error reply with id: 666
    at l.handleReplyErr (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2313238)
    at l.handleMessage (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2312855)
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2312218
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2261081
    at r.invoke (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2261171)
    at s.fire (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2262965)
    at t.ChannelMultiplexer.handleData (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2308030)
    at t.ChannelMultiplexer.handleMessage (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2307311)
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2306475
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2261081
e.log @ logger-protocol.ts:113
(anonymous) @ logger-frontend-module.ts:42
(anonymous) @ logger.ts:310
(anonymous) @ logger.ts:302
Promise.then (async)
log @ logger.ts:297
i @ logger.ts:45
invoke @ event.ts:138
fire @ event.ts:279
handleData @ channel.ts:251
handleMessage @ channel.ts:209
(anonymous) @ channel.ts:167
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleMessages @ rpc-protocol.ts:217
(anonymous) @ rpc-protocol.ts:161
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ hosted-plugin.ts:560
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
postMessage @ hosted-plugin-watcher.ts:36
onRequest @ proxy-factory.ts:166
(anonymous) @ proxy-factory.ts:145
handleRequest @ rpc-protocol.ts:216
handleMessage @ rpc-protocol.ts:101
(anonymous) @ rpc-protocol.ts:85
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleData @ channel.ts:251
handleMessage @ channel.ts:209
(anonymous) @ channel.ts:167
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ web-socket-channel.ts:38
(anonymous) @ ws-connection-provider.ts:84
n.emit @ index.mjs:136
emitEvent @ socket.js:519
onevent @ socket.js:506
onpacket @ socket.js:474
n.emit @ index.mjs:136
(anonymous) @ manager.js:237
Promise.then (async)
(anonymous) @ websocket-constructor.browser.js:8
ondecoded @ manager.js:236
n.emit @ index.mjs:136
add @ index.js:167
ondata @ manager.js:223
n.emit @ index.mjs:136
onPacket @ socket.js:363
n.emit @ index.mjs:136
onPacket @ transport.js:107
onData @ transport.js:99
ws.onmessage @ websocket.js:76
logger-protocol.ts:113 2023-07-11T15:11:00.651Z root ERROR Error: No reply handler for error reply with id: 598
    at l.handleReplyErr (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2313238)
    at l.handleMessage (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2312855)
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2312218
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2261081
    at r.invoke (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2261171)
    at s.fire (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2262965)
    at t.ChannelMultiplexer.handleData (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2308030)
    at t.ChannelMultiplexer.handleMessage (file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2307311)
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2306475
    at file:///C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/bundle.js:2:2261081
e.log @ logger-protocol.ts:113
(anonymous) @ logger-frontend-module.ts:42
(anonymous) @ logger.ts:310
(anonymous) @ logger.ts:302
Promise.then (async)
log @ logger.ts:297
i @ logger.ts:45
invoke @ event.ts:138
fire @ event.ts:279
handleData @ channel.ts:251
handleMessage @ channel.ts:209
(anonymous) @ channel.ts:167
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleMessages @ rpc-protocol.ts:217
(anonymous) @ rpc-protocol.ts:161
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ hosted-plugin.ts:560
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
postMessage @ hosted-plugin-watcher.ts:36
onRequest @ proxy-factory.ts:166
(anonymous) @ proxy-factory.ts:145
handleRequest @ rpc-protocol.ts:216
handleMessage @ rpc-protocol.ts:101
(anonymous) @ rpc-protocol.ts:85
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleData @ channel.ts:251
handleMessage @ channel.ts:209
(anonymous) @ channel.ts:167
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ web-socket-channel.ts:38
(anonymous) @ ws-connection-provider.ts:84
n.emit @ index.mjs:136
emitEvent @ socket.js:519
onevent @ socket.js:506
onpacket @ socket.js:474
n.emit @ index.mjs:136
(anonymous) @ manager.js:237
Promise.then (async)
(anonymous) @ websocket-constructor.browser.js:8
ondecoded @ manager.js:236
n.emit @ index.mjs:136
add @ index.js:167
ondata @ manager.js:223
n.emit @ index.mjs:136
onPacket @ socket.js:363
n.emit @ index.mjs:136
onPacket @ transport.js:107
onData @ transport.js:99
ws.onmessage @ websocket.js:76
rpc-message-encoder.ts:184 Uncaught (in promise) Error: INVALID tab
    at d.acceptTabOperation (/C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\618.js:1:488323)
    at t.TabsExtImpl.$acceptTabOperation (/C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\618.js:1:490637)
    at /C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\557.js:1:78593
    at process.processTicksAndRejections (VM33 task_queues:95:5)
    at async c.handleRequest (/C:/Users/thomas/software/blueprint/1.20.0/TheiaBlueprint/resources/app/lib/frontend/C:\Users\thomas\software\blueprint\1.20.0\TheiaBlueprint\resources\app\lib\backend\19.js:1:46888)
deserialize @ rpc-message-encoder.ts:184
D @ unpack.js:406
i @ unpack.js:504
Y @ unpack.js:965
D @ unpack.js:400
k @ unpack.js:195
unpack @ unpack.js:102
decode @ unpack.js:174
decode @ rpc-message-encoder.ts:163
parse @ rpc-message-encoder.ts:167
(anonymous) @ rpc-protocol.ts:85
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleData @ channel.ts:251
handleMessage @ channel.ts:209
(anonymous) @ channel.ts:167
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleMessages @ rpc-protocol.ts:217
(anonymous) @ rpc-protocol.ts:161
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ hosted-plugin.ts:560
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
postMessage @ hosted-plugin-watcher.ts:36
onRequest @ proxy-factory.ts:166
(anonymous) @ proxy-factory.ts:145
handleRequest @ rpc-protocol.ts:216
handleMessage @ rpc-protocol.ts:101
(anonymous) @ rpc-protocol.ts:85
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
handleData @ channel.ts:251
handleMessage @ channel.ts:209
(anonymous) @ channel.ts:167
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ web-socket-channel.ts:38
(anonymous) @ ws-connection-provider.ts:84
n.emit @ index.mjs:136
emitEvent @ socket.js:519
onevent @ socket.js:506
onpacket @ socket.js:474
n.emit @ index.mjs:136
(anonymous) @ manager.js:237
<!-- Please provide any additional information available. -->
<!-- Additional information can be in the form of logs, screenshots, screencasts. -->
```
</details>

### Additional Information

- Operating System: Windows 11
- Theia Version: Blueprint 1.39.0

**Comment by msujew** [comment]
Maybe related to https://github.com/eclipse-theia/theia/pull/12408, which was the most recent change dealing with problem markers.

**Comment by tsmaeder** [comment]
As the problem only occurs after a while, I'm more than willing to believe it has been around for a while.

**Comment by JonasHelming** [comment]
@martin-fleck-at Is there a chance that you just fixed this?

**Comment by martin-fleck-at** [comment]
@JonasHelming I don't think so. I opened a [PR](https://github.com/eclipse-theia/theia/pull/12802) to ensure that the problems view is properly updated if it is not visible (we do an update on activation now) but I don't think it has anything to do with the error markers and line decorations inside the editor. Hard to tell what's going on if the problem only occurs sometimes after a while. Would be interesting to see if this is also happening in VS Code, i.e., whether it could be something inside the Typescript server or whether it happens on all languages.

**Comment by tsmaeder** [comment]
Might be fixed by https://github.com/eclipse-theia/theia/pull/13082/files

**Comment by JonasHelming** [comment]
@tsmaeder Did you experience this again? Otherwise I suggest to close this
