### ISSUE TITLE
Terminal profile contribution from VS Code extension throws exception if vscode.TerminalOptions.shellPath lacks ".exe" extension on Windows

### ISSUE THREAD

**Issue by jcortell68** [eclipse-theia/theia#12734]
### Bug Description:
I'm trying to contribute a terminal profile from a VS Code extension. If in the provider I fail to specify the ".exe" executable in `vscode.TerminalOptions.shellPath`, a "File not found" exception is thrown. In VS Code, it works fine without specifying the extension.

```
2023-07-19T22:04:58.500Z terminal ERROR Error: File not found: 
    at WindowsPtyAgent (C:\j.cortell\git\theiasandbox\node_modules\node-pty\src\windowsPtyAgent.ts:103:49)
    at WindowsTerminal (C:\j.cortell\git\theiasandbox\node_modules\node-pty\src\windowsTerminal.ts:51:19)
    at spawn (C:\j.cortell\git\theiasandbox\node_modules\node-pty\src\index.ts:30:10)
    at TerminalProcess (C:\j.cortell\git\theiasandbox\node_modules\@theia\process\src\node\terminal-process.ts:83:34)
    at ShellProcess (C:\j.cortell\git\theiasandbox\node_modules\@theia\terminal\src\node\shell-process.ts:64:9)
    at createInstanceWithInjections (C:\j.cortell\git\theiasandbox\node_modules\inversify\src\resolution\instantiation.ts:67:17)
    at _createInstance (C:\j.cortell\git\theiasandbox\node_modules\inversify\src\resolution\instantiation.ts:55:16)
    at resolveInstance (C:\j.cortell\git\theiasandbox\node_modules\inversify\src\resolution\instantiation.ts:145:18)
    at _getResolvedFromBinding (C:\j.cortell\git\theiasandbox\node_modules\inversify\src\resolution\resolver.ts:77:31)
    at <anonymous> (C:\j.cortell\git\theiasandbox\node_modules\inversify\src\resolution\resolver.ts:111:18)
```

Note that working around this bug by specifying the extension unfortunately leads you into the more general bug that opening a terminal in Theia hangs the app: https://github.com/eclipse-theia/theia/issues/12733

### Additional Information

- Operating System: Windows
- Theia Version: 1.39

**Comment by cdamus** [comment]
I'll be happy to look into this.

**Comment by jcortell68** [comment]
@cdamus Thanks for fixing this!
