### ISSUE TITLE
vscode: implement support for `file/newFile` menu contributions

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#12755]
#### Feature Description:

The goal is to add support for the `file/newFile` menu path which extension authors can reference when declaring their [menu contributions](https://code.visualstudio.com/api/references/contribution-points#contributes.menus).

> The New File item in the File menu and Get Started page - `file/newFile`

#### Additional Information

The `vscode.ipynb` for reference makes use of the menu path:

```
2023-07-25T18:49:43.379Z root WARN Failed to register a menu item for plugin vscode.ipynb contributed to file/newFile {command: 'ipynb.newUntitledIpynb', submenu: undefined, alt: undefined, group: 'notebook', when: undefined} Error: Could not find submenu with id file/newFile
    at MenuModelRegistry.getMenuNode (http://localhost:3000/bundle.js:147792:23)
    at http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:5826:66
    at Array.forEach (<anonymous>)
    at MenusContributionPointHandler.handle (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:5820:37)
    at http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:6563:71
    at pushContribution (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:6458:32)
    at PluginContributionHandler.handleContributions (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:6563:9)
    at HostedPluginSupport.loadContributions (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:577:61)
    at HostedPluginSupport.doLoad (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:488:42)
    at async ProgressService.withProgress (http://localhost:3000/bundle.js:151138:20)
```

**Comment by jonah-iden** [comment]
Hi, could someone assign me, i'll probably try to implement this later today
