### ISSUE TITLE
Theia Blueprint fails to delete file to the trash

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#12780]
### Bug Description:

When I delete a file with Theia Blueprint 1.39.0, I get an exception, and the file deletion to the trash fails. I think this is a build problem. This is likely due to some missing executes in the webpacked backend application.

Originally reported [here](https://github.com/arduino/arduino-ide/pull/2144#pullrequestreview-1553632302):

> Caused by: EntryNotFound (FileSystemError): Error: spawn E:\incoming\review\2144\1-090098d\resources\app\lib\backend\windows-trash.exe ENOENT
>     at u (E:\incoming\review\2144\1-090098d\resources\app\lib\backend\main.js:2:1306074)

I could reproduce it on macOS with the Theia Blueprint (1.39.0) app:

<img width="786" alt="Screenshot 2023-07-30 at 17 58 12" src="https://github.com/eclipse-theia/theia/assets/1405703/aa1ea3fc-0bea-48bf-aefe-a06893f622fe">

```
023-07-30T15:58:04.844Z root ERROR Error deleting with trash: Error: Request 'delete' failed
    at Proxy.<anonymous> (file:///Applications/TheiaBlueprint%201.39.0.app/Contents/Resources/app/lib/frontend/bundle.js:2:2325688)
    at b.delete (file:///Applications/TheiaBlueprint%201.39.0.app/Contents/Resources/app/lib/frontend/bundle.js:2:3041806)
    at x.doDelete (file:///Applications/TheiaBlueprint%201.39.0.app/Contents/Resources/app/lib/frontend/bundle.js:2:2964609)
    at async x.delete (file:///Applications/TheiaBlueprint%201.39.0.app/Contents/Resources/app/lib/frontend/bundle.js:2:2963744)
    at async p.moveFileToTrash (file:///Applications/TheiaBlueprint%201.39.0.app/Contents/Resources/app/lib/frontend/bundle.js:2:8366190)
    at async Promise.all (index 1)
    at async p.delete (file:///Applications/TheiaBlueprint%201.39.0.app/Contents/Resources/app/lib/frontend/bundle.js:2:8365936)
    at async Promise.all (index 0)
    at async p.execute (file:///Applications/TheiaBlueprint%201.39.0.app/Contents/Resources/app/lib/frontend/bundle.js:2:8364422)
    at async g.executeCommand (file:///Applications/TheiaBlueprint%201.39.0.app/Contents/Resources/app/lib/frontend/bundle.js:2:2247983)
Caused by: EntryNotFound (FileSystemError): Error: spawn /Applications/TheiaBlueprint 1.39.0.app/Contents/Resources/app/lib/backend/macos-trash ENOENT
    at u (/Applications/TheiaBlueprint 1.39.0.app/Contents/Resources/app/lib/backend/557.js:1:61635)
    at A.toFileSystemProviderError (/Applications/TheiaBlueprint 1.39.0.app/Contents/Resources/app/lib/backend/987.js:2:118859)
    at A.delete (/Applications/TheiaBlueprint 1.39.0.app/Contents/Resources/app/lib/backend/987.js:2:113571)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async g.onRequest (/Applications/TheiaBlueprint 1.39.0.app/Contents/Resources/app/lib/backend/19.js:1:53110)
    at async c.handleRequest (/Applications/TheiaBlueprint 1.39.0.app/Contents/Resources/app/lib/backend/19.js:1:46888)
```

I see the same problem downstream, starting the app from the sources. Quick fix: https://github.com/arduino/arduino-ide/pull/2144/commits/129436bc8a77336fdd0c14444bbd3486b04f4579.

### Steps to Reproduce:

https://github.com/eclipse-theia/theia/assets/1405703/b2448756-cfab-4941-accd-cca1a60b531c

1. Start The Blueprint 1.39.0
2. Open a workspace with at least one file
3. Delete the file

### Additional Information

- Operating System: macOS 13.4.1
- Theia Version: 1.39.0 Theia Blueprint

**Comment by JonasHelming** [comment]
@msujew Is this something we should patch on the community release?

**Comment by msujew** [comment]
@JonasHelming This issue is only relevant for users that are bundling their backend. But yes, I imagine it makes sense to put into the community release, especially since the fix is pretty small.

**Comment by JonasHelming** [comment]
@tsmaeder Please patch!
