### ISSUE TITLE
Web extensions no longer load

### ISSUE THREAD

**Issue by sdirix** [eclipse-theia/theia#12786]
### Bug Description:

VS Code web extensions fail to load. 

```
root ERROR Failed to start plugins for 'frontend' host
Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:3000/context/plugin-vscode-init-fe.js' failed to load.
    at initialize (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_worker_worker-main_js.js:9770:13)
    at http://localhost:3000/packages_plugin-ext_lib_hosted_browser_worker_worker-main_js.js:9819:21
    at Array.map (<anonymous>)
    at Object.init (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_worker_worker-main_js.js:9813:57)
    at PluginManagerExtImpl.$start (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_worker_worker-main_js.js:19499:59)
    at http://localhost:3000/packages_plugin-ext_lib_common_plugin-api-rpc_js.js:994:71
    at async RpcProtocol.handleRequest (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_worker_worker-main_js.js:3852:28)
```

The code mentioning `plugin-vscode-init-fe.js` can be found [here](https://github.com/eclipse-theia/theia/blob/6607185e37361b7251a5ef3df3016348bfa75fc9/packages/plugin-ext-vscode/src/node/scanner-vscode.ts#L104).
Executing a manual `GET` on `http://localhost:3000/context/plugin-vscode-init-fe.js` also fails.

The error is very likely related to the backend bundling. When deleting `examples/browser/lib/backend` directory and thereby forcing the non-bundling code path, the `http://localhost:3000/context/plugin-vscode-init-fe.j` is available again and the VS Code web extension loads.

The [file is served here](https://github.com/eclipse-theia/theia/blob/6607185e37361b7251a5ef3df3016348bfa75fc9/packages/plugin-ext-vscode/src/node/plugin-reader.ts#L26) which fails in the bundling case.

### Steps to Reproduce:

1. Add a VS Code web extension to the `plugins` directory (for example generated via `yo code --extensionType web`)
2. Build and start Theia browser example
3. Check error in the logs

### Additional Information

- Operating System: Linux
- Theia Version: [6607185](https://github.com/eclipse-theia/theia/commit/6607185e37361b7251a5ef3df3016348bfa75fc9)

**Comment by sdirix** [comment]
Thank you @msujew for the quick fix!
