### ISSUE TITLE
CI: Windows builds must pin Python to 3.11

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#13008]
### Bug Description:

Currently, the builds are failing on Windows: https://github.com/eclipse-theia/theia/actions/runs/6559938239/job/17816557467#step:5:90

```
gyp info spawn args ]
Traceback (most recent call last):
  File "D:\a\theia\theia\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "D:\a\theia\theia\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
    import gyp.input
  File "D:\a\theia\theia\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
```

We had the same issue downstream, and we had to pin the Python version.
Upstream issue: https://github.com/nodejs/node-gyp/issues/2869
Our change: https://github.com/arduino/arduino-ide/commit/97b0bc014c641be66e5153a1b232ef800fe940b4
See PR: https://github.com/arduino/arduino-ide/pull/2261

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System: Windows
- Theia Version:

**Comment by kittaakos** [comment]
I have opened the issue for greater visibility. Ideally, a future `node-gyp` version update in Theia must unlock projects downstream to pin the minor Python version and stick to `3.x` instead of `3.11.`
