### ISSUE TITLE
Theia reports an error when opening the Settings screen

### ISSUE THREAD

**Issue by zx616456607** [eclipse-theia/theia#13183]
### Steps to Reproduce:

1.Enter Chinese comma
2.Click the comma to prompt the content to jump to the setting screen
![theia打开设置界面报错](https://github.com/eclipse-theia/theia/assets/19658190/e6d99643-41dc-4291-a14f-f1f8e188e74f)

logger-protocol.ts:113 2023-12-18T12:10:34.511Z root ERROR Fail to open 'command:editor.action.unicodeHighlight.showExcludeOptions?%7B%22codePoint%22%3A65292%2C%22reason%22%3A%7B%22kind%22%3A0%2C%22confusableWith%22%3A%22%2C%22%2C%22notAmbiguousInLocales%22%3A%5B%22zh-hans%22%2C%22zh-hant%22%5D%7D%2C%22inComment%22%3Afalse%2C%22inString%22%3Afalse%7D': RangeError: Invalid code point NaN
    at Function.fromCodePoint (<anonymous>)
    at V.<anonymous> (file:///D:/TheiaBlueprint/resources/app/lib/bundle.js:2:6197359)
    at Generator.next (<anonymous>)
    at file:///D:/TheiaBlueprint/resources/app/lib/bundle.js:2:6183381
    at new Promise (<anonymous>)
    at r (file:///D:/TheiaBlueprint/resources/app/lib/bundle.js:2:6183126)
    at V.run (file:///D:/TheiaBlueprint/resources/app/lib/bundle.js:2:6197263)
    at V.runEditorCommand (file:///D:/TheiaBlueprint/resources/app/lib/bundle.js:2:4284120)
    at file:///D:/TheiaBlueprint/resources/app/lib/bundle.js:2:4503978
    at d.invokeFunction (file:///D:/TheiaBlueprint/resources/app/lib/bundle.js:2:6501366)
e.log @ logger-protocol.ts:113
(anonymous) @ logger-frontend-module.ts:42
(anonymous) @ logger.ts:312
(anonymous) @ logger.ts:304
Promise.then (async)
log @ logger.ts:299
i @ logger.ts:45
interceptOpen @ monaco-editor-provider.ts:208
await in interceptOpen (async)
open @ monaco-editor-provider.ts:150
(anonymous) @ openerService.ts:173
(anonymous) @ markerDecorations.ts:26
r @ markerDecorations.ts:26
open @ openerService.ts:160
callback @ markdownRenderer.ts:105
(anonymous) @ markdownRenderer.ts:182
(anonymous) @ event.ts:129
invoke @ event.ts:626
deliver @ event.ts:828
fire @ event.ts:789
o @ event.ts:37
errors.ts:30 Uncaught Error: Invalid code point NaN

RangeError: Invalid code point NaN
    at Function.fromCodePoint (<anonymous>)
    at V.<anonymous> (unicodeHighlighter.ts:694:23)
    at Generator.next (<anonymous>)
    at bannerController.ts:50:7
    at new Promise (<anonymous>)
    at r (bannerController.ts:50:7)
    at V.run (unicodeHighlighter.ts:691:80)
    at V.runEditorCommand (editorExtensions.ts:336:15)
    at codeEditorWidget.ts:363:37
    at d.invokeFunction (instantiationService.ts:65:11)
    at errors.ts:30:12

### Additional Information

- Operating System: windows
- Theia Version: 1.41.0

**Comment by msujew** [comment]
I've taken a short look at this. I can reproduce this, but note that this does not attempt to open the preferences widget. Instead, it should run a command defined in monaco, which seems to fail. In vscode, a quick pick opens:

![image](https://github.com/eclipse-theia/theia/assets/4377073/76acfa45-1bcd-4803-a722-e060d06484d4)

**Comment by zx616456607** [comment]
I tested it again on Theia IDE version 1.59.1, and the problem no longer recurs. The prompt content removed the entry to the jump settings interface. Is it fixed?

![Image](https://github.com/user-attachments/assets/d5cdb797-19ff-4edf-a3bf-618e1e79b866)

**Comment by msujew** [comment]
This has not been fixed. What you see is just the error from clangd.
