### ISSUE TITLE
Web socket disconnection: writing to output channel on connection status change causes an error in the console log

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#13246]
### Bug Description:
Hi,

In the latest Theia 1.45, with the new front-end connection timeout improvement, I am seeing the following error that is caused from writing to the output channel on connection status change:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'substring')
    at DocumentDataExt.acceptInsertText (<>/node_modules/@theia/plugin-ext/lib/plugin/document-data.js:111:78)
    at DocumentDataExt.onEvents (<>/node_modules/@theia/plugin-ext/lib/plugin/document-data.js:60:18)
    at DocumentsExtImpl.$acceptModelChanged (<>/node_modules/@theia/plugin-ext/lib/plugin/documents.js:156:14)
    at <>/node_modules/@theia/plugin-ext/lib/common/proxy-handler.js:93:71
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RpcProtocol.handleRequest (<>/node_modules/@theia/core/lib/common/message-rpc/rpc-protocol.js:166:28)
```

Sometimes I see the error also on the DocumentDataExt.acceptDeleteRange...

### Steps to Reproduce:

1. on frontend application contribution add in onDidInitializeLayout, add this code: 
```
this.connectionStatusService.onStatusChange((s) => {
  const channel = this.outputChannelManager.getChannel('test');
  channel.appendLine(`${new Date().toLocaleString()} - Connection Status Changed: ${s}`);
});
``` 
2. do a disconnection and a reconnect
3. you will see the above error in the browser console log.
4. remove the onStatusChange handler, the error will disappear.

### Additional Information

- Operating System: Mac
- Theia Version: 1.45

**Comment by safisa** [comment]
Hi @tsmaeder,

This is the last issue I found so far related to the web-socket disconnection fix, I hope it is the last one.
This was not happening before this change.

Thanks
