### ISSUE TITLE
Theia on Alpine - Terminal is not working

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#13386]
### Bug Description:
Hi
We tried to build an image of Theia (web) on Alpine, it seems that every thing is working for us, except the Terminal.
Once we open it we get this error:

```
2024-01-22T12:17:38.769Z terminal ERROR Error: posix_spawn failed: No such file or directory
    at new UnixTerminal (/opt/apps/theia/node_modules/node-pty/lib/unixTerminal.js:103:24)
    at spawn (/opt/apps/theia/node_modules/node-pty/lib/index.js:29:12)
    at new TerminalProcess (/opt/apps/theia/node_modules/@theia/process/lib/node/terminal-process.js:73:50)
    at new ShellProcess (/opt/apps/theia/node_modules/@theia/terminal/lib/node/shell-process.js:55:9)
    at createInstanceWithInjections (/opt/apps/theia/node_modules/inversify/lib/resolution/instantiation.js:119:20)
    at _createInstance (/opt/apps/theia/node_modules/inversify/lib/resolution/instantiation.js:109:22)
    at resolveInstance (/opt/apps/theia/node_modules/inversify/lib/resolution/instantiation.js:200:18)
    at _getResolvedFromBinding (/opt/apps/theia/node_modules/inversify/lib/resolution/resolver.js:109:58)
    at /opt/apps/theia/node_modules/inversify/lib/resolution/resolver.js:127:22
    at _resolveInScope (/opt/apps/theia/node_modules/inversify/lib/resolution/resolver.js:121:14)
2024-01-22T12:17:38.769Z root ERROR Error: pty process did not start correctly
    at ShellProcess.checkTerminal (/opt/apps/theia/node_modules/@theia/process/lib/node/terminal-process.js:166:19)
    at ShellProcess.get pid [as pid] (/opt/apps/theia/node_modules/@theia/process/lib/node/terminal-process.js:135:14)
    at /opt/apps/theia/node_modules/@theia/terminal/lib/node/base-terminal-server.js:129:53
    at /opt/apps/theia/node_modules/@theia/core/lib/common/event.js:103:69
    at CallbackList.invoke (/opt/apps/theia/node_modules/@theia/core/lib/common/event.js:109:26)
    at Emitter.fire (/opt/apps/theia/node_modules/@theia/core/lib/common/event.js:224:29)
    at ShellProcess.emitOnError (/opt/apps/theia/node_modules/@theia/process/lib/node/process.js:101:27)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Additional Information

- Operating System: Alpine
- Theia Version: 1.45

**Comment by msujew** [comment]
> 2024-01-22T12:17:38.769Z terminal ERROR Error: posix_spawn failed: No such file or directory
    at new UnixTerminal (/opt/apps/theia/node_modules/node-pty/lib/unixTerminal.js:103:24)

Seems to be a node-pty issue. I'm not sure what we can do here except to recommend to install `posix_spawn` on alpine.

**Comment by msujew** [comment]
As commented above, I don't think there's anything we can do here, since this is an upstream issue of node-pty. Closing the issue.
