### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by matkuki** [eclipse-theia/theia#13603]
### Bug Description:
When using the build instructions for `Windows` (https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#building-on-windows), the procedure fails at the step after cloning the repository:
```
git clone https://github.com/eclipse-theia/theia.git \
    && cd theia \
    && yarn \      <-   HERE IS WHERE THE ERROR OCCURS
    && yarn browser build \
    && yarn browser start
```
with this error:
```
...
[4/5] Linking dependencies...
warning " > @theia/electron@1.48.0" has unmet peer dependency "electron@^23.2.4".
warning "workspace-aggregator-be564bbb-db96-49b8-a062-2948397d5c8d > @theia/messages > react-perfect
-scrollbar@1.5.8" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-be564bbb-db96-49b8-a062-2948397d5c8d > @theia/messages > react-perfect
-scrollbar@1.5.8" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-be564bbb-db96-49b8-a062-2948397d5c8d > @theia/preview > markdown-it-an
chor@5.0.2" has unmet peer dependency "markdown-it@^8.4.1".
warning "workspace-aggregator-be564bbb-db96-49b8-a062-2948397d5c8d > @theia/process > node-pty@0.11.
0-beta17" has incorrect peer dependency "node-gyp@^8.3.0".
warning "workspace-aggregator-be564bbb-db96-49b8-a062-2948397d5c8d > @theia/scm > react-autosize-tex
tarea@7.1.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-be564bbb-db96-49b8-a062-2948397d5c8d > @theia/scm > react-autosize-tex
tarea@7.1.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
[5/5] Building fresh packages...
[10/19] ⢀ drivelist
[11/19] ⢀ keytar
[13/19] ⢀ node-pty
[9/19] ⢀ native-keymap
error E:\NodeJS\theia\node_modules\node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: E:\NodeJS\theia\node_modules\node-pty
Output:
node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
    ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at Object.<anonymous> (E:\NodeJS\theia\node_modules\node-pty\scripts\install.js:11:20)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
```

### Steps to Reproduce:

1. Follow the procedure described at: https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#building-on-windows

### Additional Information

- Operating System: Windows 10 x64
- Theia Version: Development (cloned from Github)

**Comment by msujew** [comment]
Hey @matkuki, which version of Node are you using?

**Comment by matkuki** [comment]
Hey @msujew , thanks for the quick reply.
Here is my Node version:
```
$ node --version
v20.12.2
```

**Comment by msujew** [comment]
While that version is supposed to be supported, with node-pty being a natively compiled node package, it might be worthwhile to test whether it works with the latest version of node v18. Can you try that? Otherwise, since the error appears in the install script of node-pty, it might make sense to [ask them](https://github.com/microsoft/node-pty/discussions) directly.

**Comment by matkuki** [comment]
Thanks @msujew ,
Changed to `18.17.0`, now I get:
```
...
[5/5] Building fresh packages...
[14/19] ⠁ @vscode/ripgrep
[10/19] ⠁ drivelist
[13/19] ⠁ node-pty
[11/19] ⠁ keytar
error E:\NodeJS\theia\node_modules\@vscode\ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments:
Directory: E:\NodeJS\theia\node_modules\@vscode\ripgrep
Output:
Finding release for v13.0.0-10
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v13.0.0-10
Deleting invalid download cache
Downloading ripgrep failed: Error: Request failed: 401
    at ClientRequest.<anonymous> (E:\NodeJS\theia\node_modules\@vscode\ripgrep\lib\download.js:109:24)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:514:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:541:22)
    at TLSSocket.emit (node:events:514:28)
```

**Comment by msujew** [comment]
@matkuki Are you behind a proxy that blocks the GitHub API? I can curl/access that URL just fine.

**Comment by matkuki** [comment]
@msujew No. Just did a clean `git clone` again, same error.
Opening the page in a browser shows this:
![image](https://github.com/eclipse-theia/theia/assets/10289651/b6f95af7-053c-45bd-9a36-2c12e225cbbc)

**Comment by msujew** [comment]
Sounds like https://github.com/eclipse-theia/theia/issues/7837, maybe running `yarn cache clean` works for you as well?

**Comment by matkuki** [comment]
Thank you for your patience. Tried that, same result.
Here is the full process output:
```
PS E:\NodeJS\theia> yarn cache clean
yarn cache v1.22.4
success Cleared cache.
Done in 0.09s.
PS E:\NodeJS\theia> yarn
yarn install v1.22.4
$ node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.1
gyp info using node@18.17.0 | win32 | x64
gyp http GET https://nodejs.org/download/release/v18.17.0/node-v18.17.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v18.17.0/node-v18.17.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v18.17.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v18.17.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v18.17.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v18.17.0/win-x64/node.lib
undefined
gyp info ok
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.3: The platform "win32" is incompatible with this module.
info "fsevents@2.3.3" is an optional dependency and failed compatibility check. Excluding it from in
stallation.
info @nx/nx-darwin-arm64@16.10.0: The platform "win32" is incompatible with this module.
info "@nx/nx-darwin-arm64@16.10.0" is an optional dependency and failed compatibility check. Excludi
ng it from installation.
info @nx/nx-darwin-arm64@16.10.0: The CPU architecture "x64" is incompatible with this module.
info @nx/nx-darwin-x64@16.10.0: The platform "win32" is incompatible with this module.
info "@nx/nx-darwin-x64@16.10.0" is an optional dependency and failed compatibility check. Excluding
 it from installation.
info @nx/nx-freebsd-x64@16.10.0: The platform "win32" is incompatible with this module.
info "@nx/nx-freebsd-x64@16.10.0" is an optional dependency and failed compatibility check. Excludin
g it from installation.
info @nx/nx-linux-arm-gnueabihf@16.10.0: The platform "win32" is incompatible with this module.
info "@nx/nx-linux-arm-gnueabihf@16.10.0" is an optional dependency and failed compatibility check.
Excluding it from installation.
info @nx/nx-linux-arm-gnueabihf@16.10.0: The CPU architecture "x64" is incompatible with this module
.
info @nx/nx-linux-arm64-gnu@16.10.0: The platform "win32" is incompatible with this module.
info "@nx/nx-linux-arm64-gnu@16.10.0" is an optional dependency and failed compatibility check. Excl
uding it from installation.
info @nx/nx-linux-arm64-gnu@16.10.0: The CPU architecture "x64" is incompatible with this module.
info @nx/nx-linux-arm64-musl@16.10.0: The platform "win32" is incompatible with this module.
info "@nx/nx-linux-arm64-musl@16.10.0" is an optional dependency and failed compatibility check. Exc
luding it from installation.
info @nx/nx-linux-arm64-musl@16.10.0: The CPU architecture "x64" is incompatible with this module.
info @nx/nx-linux-x64-gnu@16.10.0: The platform "win32" is incompatible with this module.
info "@nx/nx-linux-x64-gnu@16.10.0" is an optional dependency and failed compatibility check. Exclud
ing it from installation.
info @nx/nx-linux-x64-musl@16.10.0: The platform "win32" is incompatible with this module.
info "@nx/nx-linux-x64-musl@16.10.0" is an optional dependency and failed compatibility check. Exclu
ding it from installation.
info @nx/nx-win32-arm64-msvc@16.10.0: The CPU architecture "x64" is incompatible with this module.
info "@nx/nx-win32-arm64-msvc@16.10.0" is an optional dependency and failed compatibility check. Exc
luding it from installation.
warning plugin-a@1.48.0: The engine "vscode" appears to be invalid.
warning plugin-b@1.48.0: The engine "vscode" appears to be invalid.
warning plugin-gotd@1.48.0: The engine "vscode" appears to be invalid.
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from in
stallation.
info @msgpackr-extract/msgpackr-extract-darwin-arm64@3.0.2: The platform "win32" is incompatible wit
h this module.
info "@msgpackr-extract/msgpackr-extract-darwin-arm64@3.0.2" is an optional dependency and failed co
mpatibility check. Excluding it from installation.
info @msgpackr-extract/msgpackr-extract-darwin-arm64@3.0.2: The CPU architecture "x64" is incompatib
le with this module.
info @msgpackr-extract/msgpackr-extract-darwin-x64@3.0.2: The platform "win32" is incompatible with
this module.
info "@msgpackr-extract/msgpackr-extract-darwin-x64@3.0.2" is an optional dependency and failed comp
atibility check. Excluding it from installation.
info @msgpackr-extract/msgpackr-extract-linux-arm@3.0.2: The platform "win32" is incompatible with t
his module.
info "@msgpackr-extract/msgpackr-extract-linux-arm@3.0.2" is an optional dependency and failed compa
tibility check. Excluding it from installation.
info @msgpackr-extract/msgpackr-extract-linux-arm@3.0.2: The CPU architecture "x64" is incompatible
with this module.
info @msgpackr-extract/msgpackr-extract-linux-arm64@3.0.2: The platform "win32" is incompatible with
 this module.
info "@msgpackr-extract/msgpackr-extract-linux-arm64@3.0.2" is an optional dependency and failed com
patibility check. Excluding it from installation.
info @msgpackr-extract/msgpackr-extract-linux-arm64@3.0.2: The CPU architecture "x64" is incompatibl
e with this module.
info @msgpackr-extract/msgpackr-extract-linux-x64@3.0.2: The platform "win32" is incompatible with t
his module.
info "@msgpackr-extract/msgpackr-extract-linux-x64@3.0.2" is an optional dependency and failed compa
tibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @theia/electron@1.48.0" has unmet peer dependency "electron@^23.2.4".
warning "workspace-aggregator-bdcba8fa-487d-47fc-90a3-dc9ecb4f0f50 > @theia/messages > react-perfect
-scrollbar@1.5.8" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-bdcba8fa-487d-47fc-90a3-dc9ecb4f0f50 > @theia/messages > react-perfect
-scrollbar@1.5.8" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-bdcba8fa-487d-47fc-90a3-dc9ecb4f0f50 > @theia/preview > markdown-it-an
chor@5.0.2" has unmet peer dependency "markdown-it@^8.4.1".
warning "workspace-aggregator-bdcba8fa-487d-47fc-90a3-dc9ecb4f0f50 > @theia/process > node-pty@0.11.
0-beta17" has incorrect peer dependency "node-gyp@^8.3.0".
warning "workspace-aggregator-bdcba8fa-487d-47fc-90a3-dc9ecb4f0f50 > @theia/scm > react-autosize-tex
tarea@7.1.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-bdcba8fa-487d-47fc-90a3-dc9ecb4f0f50 > @theia/scm > react-autosize-tex
tarea@7.1.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
[5/5] Building fresh packages...
[14/19] ⠐ @vscode/ripgrep
[10/19] ⠐ drivelist
[13/19] ⠐ node-pty
[11/19] ⠐ keytar
error E:\NodeJS\theia\node_modules\@vscode\ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments:
Directory: E:\NodeJS\theia\node_modules\@vscode\ripgrep
Output:
Finding release for v13.0.0-10
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v13.0.0-10
Deleting invalid download cache
Downloading ripgrep failed: Error: Request failed: 401
    at ClientRequest.<anonymous> (E:\NodeJS\theia\node_modules\@vscode\ripgrep\lib\download.js:109:2
4)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:514:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:541:22)
    at TLSSocket.emit (node:events:514:28)
```

**Comment by tsmaeder** [comment]
@matkuki are you running in Powershell? Can you try cmd.exe?

**Comment by matkuki** [comment]
Hi @tsmaeder , tried it, same error:
![image](https://github.com/eclipse-theia/theia/assets/10289651/0e675451-ee5f-4ea9-999b-172eedb4d719)

**Comment by matkuki** [comment]
I'm trying now on a clean `Windows` machine, but I cannot seem to install the `windows-build-tools`, described in the instructions here:
https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#installing-windows-build-tools
Are these instructions up-to-date?

**Comment by msujew** [comment]
@matkuki Windows Build Tools are now atuomatically installed with node.js. No need to install them manually anymore. Our documentation says so as well.

**Comment by matkuki** [comment]
@msujew , @tsmaeder 
Thanks of all the suggestions. Ok, got `Theia` built and running in `Electron` on the clean `Windows` machine.
The build procedure works, but for `Python 3.12` `setuptools` needs to be manually installed.

The differences between the `old` and `clean` `Windows` machines are:
- old machine has multiple `Visual Studio build tools` installed (2017, 2019, 2022)
- old machine has multiple `Python 3`'s installed (`3.7`, `3.10` and `3.12`: `3.10` is active and on the `PATH`)
- old machine has various VS C++ runtimes installed

This are the differences of the top of my head, could anything else be relevant?

**Comment by tsmaeder** [comment]
For what it's worth, I just got the following on a Build and Test (windows-2019, node-18.x) PR-check job:

```
[3/5] Fetching packages...
warning plugin-a@1.48.0: The engine "vscode" appears to be invalid.
warning plugin-b@1.48.0: The engine "vscode" appears to be invalid.
warning plugin-gotd@1.48.0: The engine "vscode" appears to be invalid.
[4/5] Linking dependencies...
warning " > @theia/electron@1.48.0" has unmet peer dependency "electron@^23.2.4".
warning "workspace-aggregator-f335d5e4-b98c-45d1-a7c9-6b7bf63ec5ef > @theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-f335d5e4-b98c-45d1-a7c9-6b7bf63ec5ef > @theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-f335d5e4-b98c-45d1-a7c9-6b7bf63ec5ef > @theia/preview > markdown-it-anchor@5.0.2" has unmet peer dependency "markdown-it@^8.4.1".
warning "workspace-aggregator-f335d5e4-b98c-45d1-a7c9-6b7bf63ec5ef > @theia/process > node-pty@0.11.0-beta17" has incorrect peer dependency "node-gyp@^8.3.0".
warning "workspace-aggregator-f335d5e4-b98c-45d1-a7c9-6b7bf63ec5ef > @theia/scm > react-autosize-textarea@7.1.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-f335d5e4-b98c-45d1-a7c9-6b7bf63ec5ef > @theia/scm > react-autosize-textarea@7.1.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
[5/5] Building fresh packages...
error D:\a\theia\theia\node_modules\node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: D:\a\theia\theia\node_modules\node-pty
Output:
node:internal/child_process:414
    throw errnoException(err, 'spawn');
    ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:414:11)
    at spawn (node:child_process:761:9)
    at Object.<anonymous> (D:\a\theia\theia\node_modules\node-pty\scripts\install.js:11:20)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

Node.js v18.20.2
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by msujew** [comment]
@tsmaeder I've created an issue for this, see https://github.com/eclipse-theia/theia/issues/13613. It's related to a security "fix" in Node.js that breaks all of our build processes :)

**Comment by tsmaeder** [comment]
This should be fixed no, right, @msujew ?

**Comment by msujew** [comment]
Yes, since the original poster was able to successfully build on a clean install, I think we can close this.
