### ISSUE TITLE
Exception in log with `vscode-typescript-language-features` 1.88.1

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#13674]
### Bug Description:
The extension writes out an exception when the last editor is closed. There seem to be no negative consequences from the exception, though.

### Steps to Reproduce:

1. Make sure you have the 1.88.1 level built-ins
2. Open a typescript file
3. Close all editors
4. Observe: you get the exception below.

My suspicion is that we set the active tab group to `undefined` when there are not open editors. Probably a difference with VS Code and IMO not correct: an empty tab group is still a tab group and can be active.

### Additional Information
<details>

```
2024-05-02T08:08:37.293Z root ERROR [hosted-plugin: 13360] Error: Assertion Failed: argument is undefined or null
    at assertIsDefined (C:\Users\thomas\code\EclipseSource\theia\examples\electron\lib\backend\packages_plugin-ext_lib_common_plugin-api-rpc_js.js:2487:15)
    at get activeTabGroup [as activeTabGroup] (C:\Users\thomas\code\EclipseSource\theia\examples\electron\lib\backend\node_modules_theia_monaco-editor-core_esm_vs_base_common_sync_recursive-packages_core_shared_-54ebfc.js:17515:72)
    at d.getEditorCandidatesForActiveTab (C:\Users\thomas\code\EclipseSource\theia\plugins\vscode.typescript-language-features\extension\dist\extension.js:1:529555)
    at d.update (C:\Users\thomas\code\EclipseSource\theia\plugins\vscode.typescript-language-features\extension\dist\extension.js:1:529301)
    at C:\Users\thomas\code\EclipseSource\theia\plugins\vscode.typescript-language-features\extension\dist\extension.js:1:529200
    at C:\Users\thomas\code\EclipseSource\theia\examples\electron\lib\backend\packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:1410:69
    at CallbackList.invoke (C:\Users\thomas\code\EclipseSource\theia\examples\electron\lib\backend\packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:1416:26)
    at Emitter.fire (C:\Users\thomas\code\EclipseSource\theia\examples\electron\lib\backend\packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:1531:36)
    at C:\Users\thomas\code\EclipseSource\theia\examples\electron\lib\backend\node_modules_theia_monaco-editor-core_esm_vs_base_common_sync_recursive-packages_core_shared_-54ebfc.js:19891:105
    at C:\Users\thomas\code\EclipseSource\theia\examples\electron\lib\backend\packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:1410:69

```
</details>

- Operating System: Windows
- Theia Version: 1.49 master

**Comment by msujew** [comment]
Resolved in #13730
