### ISSUE TITLE
VSX extension: Disposable.dispose() is not a function

### ISSUE THREAD

**Issue by arnaudvergnet** [eclipse-theia/theia#13906]
### Bug Description:

When using the [Mercurial extension](https://github.com/mrcrowl/vscode-hg) in the Theia IDE from the [Open Vsx registry](https://open-vsx.org/extension/mrcrowl/hg), the extension fails to start with the message `Activating extension 'Hg' failed: TypeError: _a.dispose is not a function` (see below for detailed stack trace).

The same extension from the same registry works on [VSCodium](https://vscodium.com/).

### Steps to Reproduce:

1. Open the Theia IDE
2. Install the extension https://open-vsx.org/extension/mrcrowl/hg
3. Restart Theia IDE
4. See the error popup on the bottom right
![image](https://github.com/eclipse-theia/theia/assets/80701113/68bdd051-445a-4d2b-aa91-784044de8995)

### Stack trace

Opening the IDE with the console provides the following stack trace:

```
2024-07-10T09:11:32.835Z root ERROR [hosted-plugin: 22540] Activating extension 'Hg' failed: TypeError: _a.dispose is not a function
    at CurrentLineAnnotationProvider.stop (/home/avergnet/.theia-ide/deployedPlugins/mrcrowl.hg-1.8.1/extension/out/annotations.js:100:72)
    at CurrentLineAnnotationProvider.applyConfiguration (/home/avergnet/.theia-ide/deployedPlugins/mrcrowl.hg-1.8.1/extension/out/annotations.js:111:18)
    at new BaseAnnotationProvider (/home/avergnet/.theia-ide/deployedPlugins/mrcrowl.hg-1.8.1/extension/out/annotations.js:71:14)
    at new CurrentLineAnnotationProvider (/home/avergnet/.theia-ide/deployedPlugins/mrcrowl.hg-1.8.1/extension/out/annotations.js:105:1)
    at /home/avergnet/.theia-ide/deployedPlugins/mrcrowl.hg-1.8.1/extension/out/main.js:55:136
    at Generator.next (<anonymous>)
    at fulfilled (/home/avergnet/.theia-ide/deployedPlugins/mrcrowl.hg-1.8.1/extension/out/main.js:10:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Looking at the extensions's code, it seems [this line](https://github.com/mrcrowl/vscode-hg/blob/master/src/annotations.ts#L137) is throwing the error, which means Theia does not properly implement the `Disposable` class.

But looking at the [extension API support report](https://eclipse-theia.github.io/vscode-theia-comparator/status.html), it seems the Disposable class should be fully supported. 

### Additional Information

- Operating System: Manjaro Linux
- Theia Version: 1.51.0
- VS Code API Version: 1.90.2
- Mercurial extension Version: 1.8.1

I can provide more information if necessary, thank you for this project.

**Comment by sgraband** [comment]
I can take a look
