### ISSUE TITLE
Undefined `keySequence` in MonacoResolvedKeybinding

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#13988]
### Bug Description:
When testing the 1.52.0 IDE preview, I found a bunch of these error messages in the log: 

```

Uncaught Error: Cannot read properties of undefined (reading 'keyCode')

TypeError: Cannot read properties of undefined (reading 'keyCode')
    at d.toKeybinding (bundle.js:2:7344410)
    at bundle.js:2:7343684
    at Array.map (<anonymous>)
    at d.getDispatchChords (bundle.js:2:7343627)
    at Le.softDispatch (bundle.js:2:6926144)
    at n._onKeyDown (bundle.js:2:6046908)
    at m.value (bundle.js:2:6043521)
    at Q._deliver (bundle.js:2:3966399)
    at Q._deliverQueue (bundle.js:2:3966505)
    at Q.fire (bundle.js:2:3966935)
    at bundle.js:2:3954382
(anonymous) @ bundle.js:2

```

I didn't observe any immediate negative effects.

### Steps to Reproduce:
n/a

### Additional Information

- Operating System: Windows 11
- Theia Version: 1.52.0 preview

**Comment by zhouxinghong** [comment]
Keyboard Settings Error:
[Video_2024-08-02_163111.zip](https://github.com/user-attachments/files/16467909/Video_2024-08-02_163111.zip)
Theia Version: 1.51

**Comment by tsmaeder** [comment]
@zhouxinghong what are you trying to tell us?

**Comment by zhouxinghong** [comment]
@tsmaeder Thank you for your reply! I am just reporting on a related issue....

**Comment by tsmaeder** [comment]
@zhouxinghong could you please open an issue with a description?

**Comment by zhouxinghong** [comment]
@tsmaeder 
https://github.com/eclipse-theia/theia/issues/13991
