### ISSUE TITLE
"Invalid Tab" Messages in Log

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#13987]
### Bug Description:
While testing the 1.52.0 release, I found a bunch of error messages of the following for in the browser log:

`` 
bundle.js:2 Uncaught (in promise) Error: INVALID tab
    at u.acceptTabOperation (/C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/C:\Users\thomas\AppData\Local\Programs\TheiaIDE\resources\app\lib\backend\339.js:1:519975)
    at t.TabsExtImpl.$acceptTabOperation (/C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/C:\Users\thomas\AppData\Local\Programs\TheiaIDE\resources\app\lib\backend\339.js:1:522339)
    at /C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/C:\Users\thomas\AppData\Local\Programs\TheiaIDE\resources\app\lib\backend\366.js:1:35962
    at process.processTicksAndRejections (VM1720 task_queues:95:5)
    at async c.handleRequest (/C:/Users/thomas/AppData/Local/Programs/TheiaIDE/resources/app/lib/frontend/C:\Users\thomas\AppData\Local\Programs\TheiaIDE\resources\app\lib\backend\638.js:1:46979)
```

Errors in tab tracking are more relevant than they may appear because the typescript language server relies on tracking the active tab to decide which files to error check, for example.

<!-- Please provide clear steps to reproduce the bug. -->
### Steps to Reproduce:
n/a

<!-- Please provide any additional information available. -->
<!-- Additional information can be in the form of logs, screenshots, screencasts. -->

### Additional Information

- Operating System: Windows 11
- Theia Version: 1.52.0 preview

**Comment by tsmaeder** [comment]
I was able to reproduce the issue in the electron sample app, but only after working for a couple of hours. The editor I closed was a new file, I believe.

**Comment by tsmaeder** [comment]
I added some debug logging and it seems the invalid tab messages always come from `TabOperation.UPDATED` operations, which get invoked upon the `Title.changed` signal.
```
Error: INVALID tab {"kind":2,"index":-1,"tabDto":{"id":"11~code-editor-opener:file:///c%3A/Users/thomas/code/theia/packages/core/src/browser/shell/tab-bar-toolbar/tab-bar-toolbar-registry.ts:1","label":"tab-bar-toolbar-registry.ts","input":{"kind":1,"uri":{"$mid":1,"path":"/c:/Users/thomas/code/theia/packages/core/src/browser/shell/tab-bar-toolbar/tab-bar-toolbar-registry.ts","scheme":"file"}},"isActive":false,"isPinned":false,"isDirty":false,"isPreview":false},"groupId":11}
```

**Comment by tsmaeder** [comment]
I suspect the `-1` index comes from `tabs-main.ts#updateTabIndices#349`. It's the only place I could find where -1 might be set as the index.

**Comment by tsmaeder** [comment]
I was able to catch the moment the -1 index happens in the debugger. It happened when I was closing a tab: The situation was as follows: 

* Open Tabs: promise-util.ts | lib.es5.d.ts | tab-bar-toolbar-registry.ts | tab-bar-toolbar.tsx | tab-bar-toolbar-types.ts | widget.d.ts
* Tab being closed was "lib.es5.d.ts"
* In `updateTabIndices, the `tabInfo` is the tabe being closed (`lib.es5.d.ts`), 
* the `tab` being updated is `tab-bar-toolbar-registry.ts`
* `tab.group.tabs` at this point contains twice the tab for `tab-bar-toolbar.tsx` instead of `tab-bar-toolbar-registry.ts | tab-bar-toolbar.tsx`
 
=> so the tabInfo.group.tabs values are already corrupt that this point. Not clear whether the structure has been rebuilt or if it was corrupted incrementally.

**Comment by tsmaeder** [comment]
Since I did not move any tabs, I think the duplicat tab must come from `tabs-main.ts#onTabTitleChanged()`, there, it says:
```
if (!this.tabDtosEqual(oldTabDto, newTabDto)) {
            tabInfo.group.tabs[tabInfo.tabIndex] = newTabDto;
```

What if `tabInfo.tabIndex` is not the same as the previous index in the group? Is that even possible?
