### ISSUE TITLE
[BUG] Stage/Unstage/Revert selected changes does nothing in commit diff view.

### ISSUE THREAD

**Issue by Guusggg** [eclipse-theia/theia#14144]
### Bug Description:

While trying to stage only some lines of a file that has multiple changes throughout, I'm unable to stage only the lines that I've selected. I use this a lot to split out my commits.

### Steps to Reproduce:

1. Make a couple changes in a file. 
2. Select (for example) only one line you would like to stage for commit.
3. Right-click and select "Stage selected changes".
4. Nothing happens.

### Additional Information

- Operating System: Windows 11
- Theia Version: Version 1.52.0, VS Code API Version: 1.91.1

I'm sorry if this is not the right place, I just really love this project and would like to be able to use it as my main editor.

Thank you to all the contributors for an amazing product!

**Comment by tsmaeder** [comment]
Browser log says 
```
plugin-contribution-handler.ts:491 Uncaught (in promise) Error: command 'git.stageSelectedRanges' not found
    at Object.execute (plugin-contribution-handler.ts:491:27)
    at u.executeCommand (command.ts:341:42)
execute	@	plugin-contribution-handler.ts:491
executeCommand	@	command.ts:341
```

**Comment by Guusggg** [comment]
Thank you @tsmaeder, I hadn't thought to put a log in there.

Would this be an issue that could be picked up by someone who would be new to contributing to this project? I wouldn't mind taking a stab to see if I can make a fix for this.

Cheers,
