### ISSUE TITLE
Unable to build on Windows 11 using v1.53.x branch

### ISSUE THREAD

**Issue by pchuong** [eclipse-theia/theia#14214]
, please read SECURITY.md in the repository root -->
### Bug Description:
I am not able to build Theia on Windows 11 using the 1.53.x branch. I used PowerShell with Administrator permission to run `yarn` and I am getting the errors below.

### Steps to Reproduce:
1. Clone the github repo
2. Checkout the release/1.53.x branch
3. Open PowerShell with Administrator permission
4. Run `yarn`

### Additional Information
```
error C:\Works\git\theia_v1.53.2\node_modules\native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Works\git\theia_v1.53.2\node_modules\native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.1
gyp info using node@22.9.0 | win32 | x64
(node:17812) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info find Python using Python version 3.11.6 found at "C:\Users\userid\AppData\Local\Programs\Python\Python311\python.exe"
gyp info find VS using VS2017 (15.9.35229.15) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\userid\AppData\Local\Programs\Python\Python311\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Works\\git\\theia_v1.53.2\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Works\\git\\theia_v1.53.2\\node_modules\\native-keymap\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Works\\git\\theia_v1.53.2\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\userid\\AppData\\Local\\node-gyp\\Cache\\22.9.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\userid\\AppData\\Local\\node-gyp\\Cache\\22.9.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Works\\git\\theia_v1.53.2\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\userid\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\22.9.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Works\\git\\theia_v1.53.2\\node_modules\\native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Works\\git\\theia_v1.53.2\\node_modules\\native-keymap\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
  string_conversion.cc
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
  keymapping.cc
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-internal.h(490): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-internal.h(491): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-internal.h(596): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-internal.h(597): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-internal.h(889): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-internal.h(890): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-internal.h(891): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-internal.h(1163): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-internal.h(1242): note: see reference to class template instantiation 'v8::internal::WrappedIterator<Iterator,ElementType>' being compiled
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-handle-base.h(10): error C2429: language feature 'nested-namespace-definition' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\a0792userid82\appdata\local\node-gyp\cache\22.9.0\include\node\v8-function-callback.h(167): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-function-callback.h(174): note: see reference to class template instantiation 'v8::FunctionCallbackInfo<T>' being compiled
  string_view is only available with C++17 or later.
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-template.h(1214): error C2039: 'string_view': is not a member of 'std' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\array(17): note: see declaration of 'std'
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-template.h(1214): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-template.h(1214): error C2146: syntax error: missing '>' before identifier 'string_view' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-typed-array.h(65): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-typed-array.h(93): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-typed-array.h(122): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-typed-array.h(150): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-typed-array.h(178): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-typed-array.h(206): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-typed-array.h(234): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-typed-array.h(286): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-typed-array.h(314): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-typed-array.h(342): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\v8-typed-array.h(370): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
  class template optional is only available with C++17 or later.
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\node.h(540): error C2039: 'string_view': is not a member of 'std' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\array(17): note: see declaration of 'std'
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\node.h(540): error C2061: syntax error: identifier 'string_view' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\node.h(696): error C2039: 'optional': is not a member of 'std' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\array(17): note: see declaration of 'std'
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\node.h(696): error C2143: syntax error: missing ';' before '<' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\node.h(696): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\node.h(696): error C2238: unexpected token(s) preceding ';' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\node.h(768): error C2039: 'string_view': is not a member of 'std' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
  c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\array(17): note: see declaration of 'std'
c:\users\userid\appdata\local\node-gyp\cache\22.9.0\include\node\node.h(768): error C2061: syntax error: identifier 'string_view' [C:\Works\git\theia_v1.53.2\node_modules\native-keymap\build\keymapping.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Works\git\theia_v1.53.2\node_modules\node-gyp\lib\build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Works\\git\\theia_v1.53.2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Works\git\theia_v1.53.2\node_modules\native-keymap




warning Error running install script for optional dependency: "C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features: Command failed.
Exit code: 1
Command: node buildcheck.js > buildcheck.gypi && node-gyp rebuild
Arguments:
Directory: C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.1
gyp info using node@22.9.0 | win32 | x64
(node:17424) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info find Python using Python version 3.11.6 found at \"C:\\Users\\userid\\AppData\\Local\\Programs\\Python\\Python311\\python.exe\"
gyp info find VS using VS2017 (15.9.35229.15) found at:
gyp info find VS \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\\Users\\userid\\AppData\\Local\\Programs\\Python\\Python311\\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\\\Works\\\\git\\\\theia_v1.53.2\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Works\\\\git\\\\theia_v1.53.2\\\\node_modules\\\\cpu-features\\\\build\\\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Works\\\\git\\\\theia_v1.53.2\\\\node_modules\\\\node-gyp\\\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\userid\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\22.9.0\\\\include\\\\node\\\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\userid\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\22.9.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\Works\\\\git\\\\theia_v1.53.2\\\\node_modules\\\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\\\\\Users\\\\\\\\userid\\\\\\\\AppData\\\\\\\\Local\\\\\\\\node-gyp\\\\\\\\Cache\\\\\\\\22.9.0\\\\\\\\<(target_arch)\\\\\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\\Works\\\\git\\\\theia_v1.53.2\\\\node_modules\\\\cpu-features',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\\Works\\\\git\\\\theia_v1.53.2\\\\node_modules\\\\cpu-features\\\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the \"/m\" switch.
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\deps\\cpu_features\\cpu_features.vcxproj]
  impl_aarch64_linux_or_android.c
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\deps\\cpu_features\\cpu_features.vcxproj]
  impl_aarch64_macos_or_iphone.c
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\deps\\cpu_features\\cpu_features.vcxproj]
  impl_arm_linux_or_android.c
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\deps\\cpu_features\\cpu_features.vcxproj]
  impl_mips_linux_or_android.c
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\deps\\cpu_features\\cpu_features.vcxproj]
  impl_ppc_linux.c
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\deps\\cpu_features\\cpu_features.vcxproj]
  impl_x86_freebsd.c
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\deps\\cpu_features\\cpu_features.vcxproj]
  impl_x86_linux_or_android.c
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\deps\\cpu_features\\cpu_features.vcxproj]
  impl_x86_macos.c
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\deps\\cpu_features\\cpu_features.vcxproj]
  impl_x86_windows.c
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\deps\\cpu_features\\cpu_features.vcxproj]
  filesystem.c
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\deps\\cpu_features\\cpu_features.vcxproj]
  stack_line_reader.c
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\deps\\cpu_features\\cpu_features.vcxproj]
  string_view.c
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\deps\\cpu_features\\cpu_features.vcxproj]
  win_delay_load_hook.cc
  cpu_features.vcxproj -> C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\Release\\\\cpu_features.lib
cl : Command line warning D9002: ignoring unknown option '-std:c++20' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
  binding.cc
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-internal.h(490): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-internal.h(491): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-internal.h(596): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-internal.h(597): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-internal.h(889): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-internal.h(890): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-internal.h(891): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-internal.h(1163): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
  c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-internal.h(1242): note: see reference to class template instantiation 'v8::internal::WrappedIterator<Iterator,ElementType>' being compiled
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-handle-base.h(10): error C2429: language feature 'nested-namespace-definition' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-function-callback.h(167): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
  c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-function-callback.h(174): note: see reference to class template instantiation 'v8::FunctionCallbackInfo<T>' being compiled
  string_view is only available with C++17 or later.
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-template.h(1214): error C2039: 'string_view': is not a member of 'std' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
  c:\\program files (x86)\\microsoft visual studio\\2017\\buildtools\\vc\\tools\\msvc\\14.16.27023\\include\\array(17): note: see declaration of 'std'
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-template.h(1214): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-template.h(1214): error C2146: syntax error: missing '>' before identifier 'string_view' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-typed-array.h(65): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-typed-array.h(93): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-typed-array.h(122): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-typed-array.h(150): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-typed-array.h(178): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-typed-array.h(206): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-typed-array.h(234): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-typed-array.h(286): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-typed-array.h(314): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-typed-array.h(342): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\v8-typed-array.h(370): error C2429: language feature 'terse static assert' requires compiler flag '/std:c++17' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
  class template optional is only available with C++17 or later.
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\node.h(540): error C2039: 'string_view': is not a member of 'std' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
  c:\\program files (x86)\\microsoft visual studio\\2017\\buildtools\\vc\\tools\\msvc\\14.16.27023\\include\\array(17): note: see declaration of 'std'
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\node.h(540): error C2061: syntax error: identifier 'string_view' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\node.h(696): error C2039: 'optional': is not a member of 'std' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
  c:\\program files (x86)\\microsoft visual studio\\2017\\buildtools\\vc\\tools\\msvc\\14.16.27023\\include\\array(17): note: see declaration of 'std'
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\node.h(696): error C2143: syntax error: missing ';' before '<' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\node.h(696): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\node.h(696): error C2238: unexpected token(s) preceding ';' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\node.h(768): error C2039: 'string_view': is not a member of 'std' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
  c:\\program files (x86)\\microsoft visual studio\\2017\\buildtools\\vc\\tools\\msvc\\14.16.27023\\include\\array(17): note: see declaration of 'std'
c:\\users\\userid\\appdata\\local\\node-gyp\\cache\\22.9.0\\include\\node\\node.h(768): error C2061: syntax error: identifier 'string_view' [C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features\\build\\cpufeatures.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\Works\\git\\theia_v1.53.2\\node_modules\\node-gyp\\lib\\build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Works\\\\git\\\\theia_v1.53.2\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Works\\git\\theia_v1.53.2\\node_modules\\cpu-features
gyp ERR! node -v v22.9.0
gyp ERR! node-gyp -v v9.4.1
gyp ERR! not ok"
```

- Operating System: Windows 11
- Theia Version: 1.53.2

**Comment by msujew** [comment]
Theia does not build on node > 20 due to its native dependencies. We have [documented this limitation](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites). See also https://github.com/eclipse-theia/theia/issues/14026.
