### ISSUE TITLE
Theia Electron failed to build on Mac x86_64 due to libffmpeg.dylib library is incompatible

### ISSUE THREAD

**Issue by pchuong** [eclipse-theia/theia#14339]
### Bug Description:
When running the `yarn electron build` command, the build stop at getting the libffmpeg.dylib. See the logs below. The issue is due to the downloaded libffmpeg.dylib library is compiled for AMD64 when using Electron version v30.3.1. Earlier version of Electron or latest version v33.0.1 has the correct libffmpeg.dylib binary. This is an Electron bug, but it is affecting Theia.

### Steps to Reproduce:
1. Clone the theia repo using the Master branch
2. In the root of the repo, run `yarn`
3. Run `yarn electron build`

### Additional Information
- Operating System: Mac Intel v13.6.3
- Theia Version: v1.54

Build log:
Found cached ffmpeg library.
Successfully replaced "/Users/tmpuser/git/theia_github/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries/libffmpeg.dylib".
Error: dlopen(/Users/tmpuser/git/theia_github/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries/libffmpeg.dylib, 0x0002): tried: '/Users/tmpuser/git/theia_github/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries/libffmpeg.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/tmpuser/git/theia_github/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries/libffmpeg.dylib' (no such file), '/Users/tmpuser/git/theia_github/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries/libffmpeg.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/Users/tmpuser/git/theia_github/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/tmpuser/git/theia_github/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib' (no such file), '/Users/tmpuser/git/theia_github/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
    at Object.getFfmpegCodecs (/Users/tmpuser/git/theia_github/dev-packages/ffmpeg/lib/ffmpeg.js:84:37)
    at Object.checkFfmpeg (/Users/tmpuser/git/theia_github/dev-packages/ffmpeg/lib/check-ffmpeg.js:23:27)
    at ApplicationPackageManager.prepareElectron (/Users/tmpuser/git/theia_github/dev-packages/application-manager/lib/application-package-manager.js:184:22)
    at async ApplicationPackageManager.prepare (/Users/tmpuser/git/theia_github/dev-packages/application-manager/lib/application-package-manager.js:65:13)
    at async ApplicationPackageManager.generate (/Users/tmpuser/git/theia_github/dev-packages/application-manager/lib/application-package-manager.js:70:13)
    at async ApplicationPackageManager.build (/Users/tmpuser/git/theia_github/dev-packages/application-manager/lib/application-package-manager.js:90:9)
    at async Object.handler (/Users/tmpuser/git/theia_github/dev-packages/cli/lib/theia.js:147:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by JonasHelming** [comment]
Thank you for the report. As you seem to already researched on this, do you have any suggestion on how to fix this for theia?

**Comment by pchuong** [comment]
The newer version of Electron has the libffmpeg.dylib built correctly for the x86_64 platform. I currently have my local Theia copy to pull in a newer version of the libffmpeg.dylib to workaround this issue. I applied the workaround in the dev-packages/ffmpeg/src/replace-ffmpeg.ts file by returning a newer version of Electron. I am currently using Electron v33.0.1.

I tried to use a newer Electron by updating the examples/Electron/package.json file, there were some build errors. I didn't spend time looking into those errors.

**Comment by JonasHelming** [comment]
@tsmaeder Haven't you recently looked at updating Electron or am I mistaken?

**Comment by tsmaeder** [comment]
So here's the deal: I updated electron to 30.1.2 in https://github.com/eclipse-theia/theia/pull/14041/files, but the version spec says `^30.1.2`. Since then someone seems to have updated the yarn.lock so that we now use 30.3.1. We really need to use a single fixed version of electron. @pchuong if you add a resolution entry to your package.json, you should be able to force electron back to 30.1.2.
