### ISSUE TITLE
Cannot start dev-container

### ISSUE THREAD

**Issue by sgraband** [eclipse-theia/theia#14400]
### Bug Description:
With the current state i cannot get any devcontainer to start (minmal example attached below).
No matter the configuration the `Reopen in Container` command fails with this error:
```
2024-11-05T10:28:37.564Z root ERROR Error: Could not start remote system: 
    at RemoteSetupService.startApplication (/home/simon/Git/theia/theia/examples/electron/lib/backend/main.js:26924:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RemoteSetupService.setup (/home/simon/Git/theia/theia/examples/electron/lib/backend/main.js:26892:22)
    at async DevContainerConnectionProvider.connectToContainer (/home/simon/Git/theia/theia/examples/electron/lib/backend/main.js:10655:28)
    at async RpcProxyFactory.onRequest (/home/simon/Git/theia/theia/examples/electron/lib/backend/packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:4162:24)
    at async RpcProtocol.handleRequest (/home/simon/Git/theia/theia/examples/electron/lib/backend/packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:3625:28)
```

### Steps to Reproduce:
[devcontainer-example.zip](https://github.com/user-attachments/files/17630919/devcontainer-example.zip)

1. Open the zipped workspace
2. Reopen the workspace in container
3. Observe that the container is built, but you get the above error message

### Additional Information

- Operating System: Ubuntu 22.04
- Theia Version: Observed both in Theia IDE 1.55.0 and current master

**Comment by msujew** [comment]
@sgraband I've just updated the native dependency packages in the release. Can you retry it?

**Comment by JonasHelming** [comment]
@msujew Is there something we can do to prevent this for future releases?

**Comment by msujew** [comment]
@JonasHelming I've already submitted https://github.com/eclipse-theia/theia/pull/14402.
