### ISSUE TITLE
Issue in theia with after network disconnection

### ISSUE THREAD

**Issue by chamangurjardev** [eclipse-theia/theia#14516]
I'm facing following issue in theia with after network disconnection above version 1.45.0

When i'm using Once theia  after some time theia disconnect and connects again. After that theia is not working it stuck in reloading the plugins. Then i am facing following issues :-
1. If i'm writing any thing in theia it does not get synk, files remains unsaved even i have enabled auto save.
2. File explorer doesn't open show loader only.
3. If A java file is open, it shows Run And Debug options in the file but if i click any of the option nothing happens. It does not run.

In kind of a way i am totally stuck and the only option that works in reload. It's hard to reload again and again because this issue is happening very frequently.

**Additional Information :-** 

Theia - >=1.45.0
Node :- v18.20.4 and v20.18.1 - Issue on both node versions.

Same issue can be replicated on  https://theia-ide.org/  as well.

**Steps :-** 

1. Go to [https://theia-ide.org/](https://theia-ide.org/)
2. Click on Try Theia IDE online option, login and it will start theia latest version with latest plugin versions.
3. There will be a default project, open java file. Write something and play with this file for some time(5-10 minutes). You will face same issue.
4. P.S. -> If this issue not happening, then please move away from window for some time, then come back and you will face this issue.

**Comment by chamangurjardev** [comment]
@tsmaeder

**Comment by tsmaeder** [comment]
@chamangurjardev that you have to reload the window after a period of inactivity is normal behavior in the browser version of Theia. Are you saying this is happening even though your're actively developing in the window?
You are speaking of "network disconnection". How do you know the network disconnected and why does it disconnect?
You also say this is happening in Theia > 1.45.0. How do you get to this exact version number? Did you try this out locally?

**Comment by code-muralikrishna** [comment]
Need Support on the above issue. I am facing the same in the latest Theia version 1.55.0

**Comment by sdirix** [comment]
I am able to reproduce the issue. When using Theia Try Online, after 5-6 minutes the console is flooded with errors like this: 

```
rpc-protocol.ts:82 Uncaught (in promise) Error: reconnecting channel
    at rpc-protocol.ts:82:68
    at Map.forEach (<anonymous>)
    at rpc-protocol.ts:82:34
    at event.ts:176:42
    at CallbackList.invoke (event.ts:184:26)
    at Emitter.fire (event.ts:327:36)
    at channel.ts:185:44
    at Map.forEach (<anonymous>)
    at Object.<anonymous> (channel.ts:184:35)
    at disposable.dispose (disposable.ts:137:13)
```

```
root ERROR Error: No reply handler for reply with id: 1
root ERROR Error: No reply handler for reply with id: 2
root ERROR Error: No reply handler for reply with id: 3
etc. etc.
root ERROR Error: No reply handler for reply with id: 57
```

After 15 minutes I get a

```
root INFO initial connect received on 8mpFzfjTf97mopc1AAAK
channel.ts:283 Uncaught (in promise) Error: Another channel with the id '/localization-server' is already open.
    at ChannelMultiplexer.open (channel.ts:283:19)
    at ServiceConnectionProvider.openChannel (service-connection-provider.ts:137:58)
channel.ts:283 Uncaught (in promise) Error: Another channel with the id '/os' is already open.
    at ChannelMultiplexer.open (channel.ts:283:19)
    at ServiceConnectionProvider.openChannel (service-connection-provider.ts:137:58)
etc. etc.
```

And then again the
```
root ERROR Error: No reply handler for reply with id: 1
root ERROR Error: No reply handler for reply with id: 2
etc.
```

This repeats until the 30 minutes of Try Online are over

**Comment by tsmaeder** [comment]
@sdirix what's the setup for front end reconnection on the "Try Online" application?

**Comment by msujew** [comment]
@tsmaeder I believe it's this one [here](https://github.com/eclipse-theia/theia-ide/blob/57e3a13a237b86f06d8f08dfb7c60aff4eab0ca4/applications/browser/package.json#L21-L46). It doesn't seem to be enabled, so the behavior checks out :D

**Comment by tsmaeder** [comment]
We should really change that to user "reloadOnReconnect= true" and a reasonable "frontendConnectionTimeout". Not reloading the front end when connecting to a new back end is simply not reliable.

**Comment by sdirix** [comment]
@code-muralikrishna @chamangurjardev adding the options mentioned by @tsmaeder into your local application should also resolve them for you locally. [Here you can find an example on how to configure the options](https://github.com/eclipse-theia/theia/blob/8c638f2618cf907e8e38b46a37fa4e7527672542/examples/browser/package.json#L7-L22).

For Theia itself we should think about using these options per default for the Browser applications and only use different values if the adopter specifically overwrote them.
