### ISSUE TITLE
"Reload" hangs sometimes in Electron

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#14528]
### Bug Description:
When I reload the UI, sometimes the UI does not come back, but instead just hangs 

### Steps to Reproduce:

1. Start a workspace, open a typescript file
2. Hit `ctrl-r`
3. Repeat until the window gets stuck empty and white. Further `ctrl-r` does not reload the page.

### Additional Information

- Operating System: Window 11
- Theia Version: 1.55 master

**Comment by tsmaeder** [comment]
In the log, one can find messages like this:

```
2024-11-26T12:56:00.217Z root ERROR Error: reconnecting same front end
    at C:\Users\thomas\code\theia\theia5\examples\electron\lib\backend\packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:3492:68
    at Map.forEach (<anonymous>)
    at C:\Users\thomas\code\theia\theia5\examples\electron\lib\backend\packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:3492:34
    at C:\Users\thomas\code\theia\theia5\examples\electron\lib\backend\packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:1414:69
    at CallbackList.invoke (C:\Users\thomas\code\theia\theia5\examples\electron\lib\backend\packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:1420:26)
    at Emitter.fire (C:\Users\thomas\code\theia\theia5\examples\electron\lib\backend\packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:1535:36)
    at C:\Users\thomas\code\theia\theia5\examples\electron\lib\backend\packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:3100:44
    at Map.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\thomas\code\theia\theia5\examples\electron\lib\backend\packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:3099:35)
    at disposable.dispose (C:\Users\thomas\code\theia\theia5\examples\electron\lib\backend\packages_core_lib_common_index_js-node_modules_vscode-languageserver-types_lib_umd_sync_recursive.js:1212:13)
```

A bit of debugging revealed that these error stem from canceled requests. In particular, the requests seem to be `HostedPluginClient.postMessage()` requests. This is consistent with the fact that I could not reproduce the issue with no plugins installed. 

I have also never seen this behavior with the Theia IDE  1.55.0 release.

**Comment by tsmaeder** [comment]
Recent experience indicates that the hang occurs when reload is initiated before the windows is fully loaded, including plugin contributions. If running from the command line, you can wait until there is no more activity in the log before reloading to prevent the problem from happening.
