### ISSUE TITLE
 Error: Another channel with the id '/services/remote-filesystem' is already open.

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#14632]
### Bug Description:
The following exception appears at startup in the browser log:
```
channel.ts:283 Uncaught (in promise) Error: Another channel with the id '/services/remote-filesystem' is already open.
    at ChannelMultiplexer.open (channel.ts:283:19)
    at ServiceConnectionProvider.openChannel (service-connection-provider.ts:137:58)
```

### Steps to Reproduce:
1. Build Theia 1.55 master and download plugins
2. `yarn electron start`

### Additional Information

- Operating System: Windows
- Theia Version: 1.55 master

**Comment by zhangzejun123** [comment]
This is what happens after an error occurs。

> [@tsmaeder](https://github.com/tsmaeder) I also encountered this problem on theia-ide 1.62.200 version, which caused the toolbar style to be loaded abnormally.


This is what happens after an error occurs。

![Image](https://github.com/user-attachments/assets/d6603b61-ab18-4b6f-9f3c-701482068afc)

**Comment by zhangzejun123** [comment]
I tried to catch the exception in the following code and the problem was solved, but I don't know why the Channel with id '/services/remote-filesystem' was opened twice   

![Image](https://github.com/user-attachments/assets/4442289d-2cab-44fa-b5e5-250746d67c43)
