### ISSUE TITLE
ERROR Warning: Unknown event handler property `onPointerEnterCapture`. It will be ignored.

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#14633]
### Bug Description:
The following exception appears at startup in the browser log:
```
logger-protocol.ts:117 2024-12-16T09:16:46.997Z root ERROR Warning: Unknown event handler property `onPointerEnterCapture`. It will be ignored.
    at textarea
    at TextareaAutosizeClass (file:///C:/Users/thomas/code/theia/theia2/examples/electron/lib/frontend/vendors-node_modules_react-autosize-textarea_lib_index_js.js:488:47)
    at SearchInWorkspaceTextArea (file:///C:/Users/thomas/code/theia/theia2/examples/electron/lib/frontend/pa…es_search-in-workspace_lib_browser_search-in-workspace-factory_js.js:168:9)
    at div
    at div
    at div
    at div
    at div
```

### Steps to Reproduce:

1. Build Theia master
2. `yarn electron start`

### Additional Information

- Operating System: Windows 11
- Theia Version: 1.55. master

**Comment by drochgenius** [comment]
Getting this as well on Theia 1.57.
Web version of Theia
