### ISSUE TITLE
Request watchFileChanges failed with error: Connection is closed

### ISSUE THREAD

**Issue by zsmweb** [eclipse-theia/theia#1852]
can not open any file 

[2018-05-04T08:14:46.120Z] ERROR: Theia/45 on a05e2b78f0bc: Request watchFileChanges failed with error: Connection is closed. [ 'Error: Connection is closed.\n    at new ConnectionError (/home/theia/node_modules/vscode-jsonrpc/lib/main.js:138:28)\n    at throwIfClosedOrDisposed (/home/theia/node_modules/vscode-jsonrpc/lib/main.js:613:19)\n    at Object.sendRequest (/home/theia/node_modules/vscode-jsonrpc/lib/main.js:715:13)\n    at /home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:296:72\n    at new Promise (<anonymous>)\n    at /home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:289:24\n    at <anonymous>' ]

**Comment by akosyakov** [comment]
Could you clarify how one can reproduce it please?

**Comment by vince-fugnitto** [comment]
> Could you clarify how one can reproduce it please?

Closing due to inactivity from the author.
