### ISSUE TITLE
Error with my address?

### ISSUE THREAD

**Issue by Merith-TK** [eclipse-theia/theia#2950]
this is my first time using yarn, and im trying to get this set up as part of my website https://merith.tk/ under ide.merith.tk, 

I am using VirtualHosts with Apache to do this, but the only issue ive been having is it wont let me bind the program to anything but my servers LAN IP, which on my network is 10.0.0.101, and no, you cannot access it
this is what happens when i try to use 127.0.0.1 to loop it back to my server so i can use it with a virtualhost 

`bunny@codemerith:/home/nuse-software/theia$ yarn theia start theia_data/ --hostname 127.0.0.1 --port 8080
yarn run v1.9.4
$ /home/nuse-software/theia/node_modules/.bin/theia start theia_data/ --hostname 127.0.0.1 --port 8080
Starting server worker...
Server worker has been started. [ID: 1 | PID: 694]
Server worker is ready to accept messages. [ID: 1 | PID: 694]
root ERROR Uncaught Exception:  Error: bind EADDRINUSE 127.0.0.1:8080
root ERROR Error: bind EADDRINUSE 127.0.0.1:8080
    at listenOnMasterHandle (net.js:1420:16)
    at rr (internal/cluster/child.js:121:12)
    at Worker.send (internal/cluster/child.js:88:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
root ERROR Failed to start the backend application.
root ERROR Error: bind EADDRINUSE 127.0.0.1:8080
    at listenOnMasterHandle (net.js:1420:16)
    at rr (internal/cluster/child.js:121:12)
    at Worker.send (internal/cluster/child.js:88:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Server worker has been disconnected. [ID: 1 | PID: 694]
Server worker has been stopped. [ID: 1 | PID: 694]
Done in 1.48s.`

**Comment by akosyakov** [comment]
@DovaMerith Hi, it is not yarn error, but Node.js, it says that something is already running on `127.0.0.1:8080` 

See `EADDRINUSE` here: https://nodejs.org/api/net.html#net_server_listen

**Comment by vince-fugnitto** [comment]
I don't believe the error is specific to the application.
Since there has not been any activity for a while I will close the issue for the moment, please feel free to re-open the issue if you still have a problem.
