### ISSUE TITLE
Back-end stops after running JAVA langage server

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#3023]
I start Theia (BE-FE), open a JAVA file so the language server starts. Then I stop the BE, but keep the FE,  wait  until it goes off-line. Restart the BE to reconnect. 

For some reason, Theia  BE crash sometimes. It take a few seconds to ~ 30 minutes.
IN all cases, the end of the trace is shown below. 
Is it the Java LS causing it?
Is it just on the lastest Theia, used 0.3.15?
Is it the Theia re-connect functionality since there still exist a FE when trying to re-connect?
Up to now, I was enable to reproduce the crash with just typescript files.

**Error**:
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: false == true
    at RoundRobinHandle.add (internal/cluster/round_robin_handle.js:34:3)
    at queryServer (internal/cluster/master.js:318:10)
    at Worker.onmessage (internal/cluster/master.js:250:5)
    at ChildProcess.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Done in 599.32s

**Comment by marcdumais-work** [comment]
It seems that we should be able to recover from this scenario. Any process that was started in the B-E, like language servers, processes started in a Theia terminal, tasks, are killed along with the B-E, and are lost. 

Could the F-E detect that the B-E has restarted and itself restart, to clear any state that might not be valid anymore?

**Comment by marcdumais-work** [comment]
When reproducing the issue above, I used a big Java project. Until I killed and restarted the B-E, I had a single ```jdt.ls``` process running. After restarting the B-E, I had between ~ 6 and 14, trying about 5 times. Each one seemed active, taking CPU and RAM. Soon all my machine's RAM was allocated, and the swap was getting exhausted as well.

**Comment by marcdumais-work** [comment]
It might be that the issue is generic and afftect all languages, but that it's easier to notice it with a Java project, since the LS is quite heavy and does a lot (build stated automatically, markers reported for all files automatically, ...)

**Comment by kittaakos** [comment]
> AssertionError [ERR_ASSERTION]: false == true
> at RoundRobinHandle.add (internal/cluster/round_robin_handle.js:34:3)
> at queryServer (internal/cluster/master.js:318:10)
> at Worker.onmessage (internal/cluster/master.js:250:5)
> at ChildProcess.onInternalMessage (internal/cluster/utils.js:42:8)
> at emitTwo (events.js:131:20)
> at ChildProcess.emit (events.js:214:7)
> at emit (internal/child_process.js:762:12)
> at _combinedTickCallback (internal/process/next_tick.js:142:11)
> at process._tickCallback (internal/process/next_tick.js:181:9)
> Done in 599.32s

I can confirm this. It still happens from time to time. Then the backend crashes:
```
root INFO [nsfw-watcher: 5492] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls/.theia/settings.json
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: false == true
    at RoundRobinHandle.add (internal/cluster/round_robin_handle.js:34:3)
    at queryServer (internal/cluster/master.js:316:10)
    at Worker.onmessage (internal/cluster/master.js:248:5)
    at ChildProcess.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
✨  Done in 2130.69s.
```

I have used 68ff5f84.

**Comment by msujew** [comment]
Language servers are now running in the plugin host. We don't spawn them ourselves anymore.
