### ISSUE TITLE
[debug][electron] Multiple debug model related errors when starting the electron example application

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#3408]
```
git branch -vv && yarn --cwd ./examples/electron/ start
* master 1efad7cb [origin/master] Add process dependency to file-search
yarn run v1.10.1
$ theia start
```

```
/Users/akos.kitta/git/theia/examples/electron/lib/57.bundle.js:4058 Uncaught (in promise) TypeError: this.model.breakpoints.values is not a function
    at DebugBreakpointsSource.push.../../packages/debug/lib/browser/view/debug-breakpoints-source.js.DebugBreakpointsSource.getElements (/Users/akos.kitta/git/theia/examples/electron/lib/57.bundle.js:4058)
    at SourceTree.push.../../packages/core/lib/browser/source-tree/source-tree.js.SourceTree.resolveElements (/Users/akos.kitta/git/theia/examples/electron/lib/28.bundle.js:390)
    at SourceTree.<anonymous> (/Users/akos.kitta/git/theia/examples/electron/lib/28.bundle.js:363)
    at step (/Users/akos.kitta/git/theia/examples/electron/lib/28.bundle.js:334)
    at Object.next (/Users/akos.kitta/git/theia/examples/electron/lib/28.bundle.js:315)
    at /Users/akos.kitta/git/theia/examples/electron/lib/28.bundle.js:309
    at Promise (<anonymous>)
    at push.../../packages/core/lib/browser/source-tree/source-tree.js.__awaiter (/Users/akos.kitta/git/theia/examples/electron/lib/28.bundle.js:305)
    at SourceTree.push.../../packages/core/lib/browser/source-tree/source-tree.js.SourceTree.resolveChildren (/Users/akos.kitta/git/theia/examples/electron/lib/28.bundle.js:359)
    at SourceTree.<anonymous> (bundle.js:88588)
/Users/akos.kitta/git/theia/examples/electron/lib/57.bundle.js:5500 Uncaught (in promise) TypeError: scopes.values is not a function
    at DebugVariablesSource.<anonymous> (/Users/akos.kitta/git/theia/examples/electron/lib/57.bundle.js:5500)
    at step (/Users/akos.kitta/git/theia/examples/electron/lib/57.bundle.js:5459)
    at Object.next (/Users/akos.kitta/git/theia/examples/electron/lib/57.bundle.js:5440)
    at /Users/akos.kitta/git/theia/examples/electron/lib/57.bundle.js:5434
    at Promise (<anonymous>)
    at push.../../packages/debug/lib/browser/view/debug-variables-source.js.__awaiter (/Users/akos.kitta/git/theia/examples/electron/lib/57.bundle.js:5430)
    at DebugVariablesSource.push.../../packages/debug/lib/browser/view/debug-variables-source.js.DebugVariablesSource.getElements (/Users/akos.kitta/git/theia/examples/electron/lib/57.bundle.js:5484)
    at SourceTree.push.../../packages/core/lib/browser/source-tree/source-tree.js.SourceTree.resolveElements (/Users/akos.kitta/git/theia/examples/electron/lib/28.bundle.js:390)
    at SourceTree.<anonymous> (/Users/akos.kitta/git/theia/examples/electron/lib/28.bundle.js:363)
    at step (/Users/akos.kitta/git/theia/examples/electron/lib/28.bundle.js:334)
bundle.js:91178 task INFO Config file tasks.json does not exist under file:///Users/akos.kitta/Desktop/mini-browser
``

**Comment by akosyakov** [comment]
An error from the backend:
```
root ERROR TypeScript: /Users/kosyakov/git/theia/node_modules/vscode-languageserver/lib/main.js:405
    showErrorMessage(message, ...actions) {
                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kosyakov/git/theia/node_modules/typescript-language-server/lib/lsp-connection.js:9:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

root INFO [nsfw-watcher: 52495] Started watching: /Users/kosyakov/git/theia/packages/core/src/common/uri.spec.ts
/Users/kosyakov/git/theia/packages/debug-nodejs/download/node-debug2/extension/node_modules/vscode-debugadapter/lib/debugSession.js:12
    constructor(name, path, id = 0, origin, data) {
                               ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kosyakov/git/theia/packages/debug-nodejs/download/node-debug2/extension/node_modules/vscode-debugadapter/lib/main.js:7:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
root ERROR The ws channel does not exist 20
root ERROR The ws channel does not exist 20
2018-11-30 10:31:07.501 Electron[52007:19894157] *** WARNING: Textured window <EventDispatchingWindow: 0x7fed69cd4740> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
2018-11-30 10:31:07.933 Electron Helper[52533:19895635] Couldn't set selectedTextBackgroundColor from default ()
^C
```

It seesm that we spawn a Node.js process with the Node.js debug adapter with Node.js version which does not support the array spread operator.

**Comment by akosyakov** [comment]
It is somehow related to `yarn`, if I run without `yarn`, i.e. with `../../node_modules/.bin/electron ./src-gen/frontend/electron-main.js --log-level=debug` then it works fine

**Comment by akosyakov** [comment]
The same issue like here: https://github.com/theia-ide/theia/issues/3679#issuecomment-443207615

**Comment by colin-grant-work** [comment]
I can no longer reproduce this bug, so I'm going to close this issue for now. Please comment / reopen if you encounter this issue in the current version of Theia.
