### ISSUE TITLE
[ui] Rename a file when the file is opened in Preview mode.

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#3634]
When having a multi-selection in the file navigator and the user selects "Rename" from the context menu, it generates an error:

```
root ERROR Error: Reference widget is not in the layout.
    at DockLayout.../../node_modules/@phosphor/widgets/lib/docklayout.js.DockLayout.addWidget (http://localhost:3000/bundle.js:11879:19)
    at TheiaDockPanel.../../node_modules/@phosphor/widgets/lib/dockpanel.js.DockPanel.addWidget (http://localhost:3000/bundle.js:13441:25)
    at TheiaDockPanel.../../packages/core/lib/browser/shell/theia-dock-panel.js.TheiaDockPanel.addWidget (http://localhost:3000/bundle.js:87969:36)
    at ApplicationShell.../../packages/core/lib/browser/shell/application-shell.js.ApplicationShell.addWidget (http://localhost:3000/bundle.js:85205:32)
    at FileSystemFrontendContribution.<anonymous> (http://localhost:3000/42.bundle.js:255:36)
    at step (http://localhost:3000/42.bundle.js:135:23)
    at Object.next (http://localhost:3000/42.bundle.js:116:53)
    at fulfilled (http://localhost:3000/42.bundle.js:107:58)
```

**Comment by lmcbout** [comment]
After some investigation, the error happened when the selected file is open in Preview mode when we try to rename the file. Nothing to do with multiple selection from the file navigator.

**Comment by vince-fugnitto** [comment]
@caseyflynn-google would you know what would be needed in order to fix the issue?
To reproduce open a single file from the navigator as a preview, and attempt to `rename` the file.

**Comment by colin-grant-work** [comment]
The problem is in the filesystem's `applyMove` method:

https://github.com/eclipse-theia/theia/blob/38f176ad7176c3eb2b1edbd923132ba6d6e6b949/packages/filesystem/src/browser/filesystem-frontend-contribution.ts#L243-L254

That code assumes that the editor widget will definitely be an immediate child of the shell, and that isn't the case for editors wrapped in an editor preview.

Changing the code to something like this:
```typescript
        const newWidget = await open(this.openerService, newResourceUri, { ...options, uri: newResourceUri }) as NavigatableWidget;

        this.applyMoveSnapshot(newWidget, snapshot);

        await this.shell.closeWidget(widget.id, { save: false });
```
solves the problem described, but we lose the effect of keeping the renamed file's tab in the same place - this will just put it somewhere in the main area. It would also convert an editor preview to a normal widget, but that isn't so bad.
