### ISSUE TITLE
[plugin] race conditions because of late command registration

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#3994]
Reproducible with `debug-auto-launch` and `debug-node` VS Code extensions.
```
root ERROR [hosted-plugin: 19942] (node:19942) UnhandledPromiseRejectionWarning: Error: The command 'extension.node-debug.startAutoAttach' cannot be executed. There are no active handlers available for the command. (args: [0])
    at CommandRegistry.<anonymous> (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:95414:31)
    at step (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:95221:23)
    at Object.next (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:95202:53)
    at https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:95196:71
    at new Promise (<anonymous>)
    at ../../packages/core/lib/common/command.js.__awaiter (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:95192:12)
    at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:95401:16)
    at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/54.bundle.js:4527:72)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/54.bundle.js:752:23)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/54.bundle.js:737:41)
```

**Comment by akosyakov** [comment]
It seems to be because one extension is already deployed and try to invoke command, while extensions contributing commands are not installed yet. I will need to confirm it. @evidolob @benoitf could you confirm that it can happen?

**Comment by benoitf** [comment]
isn't a duplicate of https://github.com/theia-ide/theia/issues/3344 ?

**Comment by akosyakov** [comment]
@benoitf yes, the same issue, are you fine with https://github.com/theia-ide/theia/issues/3994#issuecomment-456749294 and if i look into it? or you have someone already looking?

**Comment by akosyakov** [comment]
@benoitf @evidolob I've noticed that Theia plugin API for command registration deviates from VS Code API:
- in VS Code commands are contributed via plugin.json, and their handlers via `registerCommand` call.
- in Theia plugin APIs commands are contributed via `registerCommand`, which is too late for menu registration.

Should we align it?

**Comment by benoitf** [comment]
@akosyakov well registering command programmatically was nicer than requiring to add something into package.json (like it's done in Theia extensions)

Aligning would be a huge step backward.

**Comment by akosyakov** [comment]
ok, i would look for a solution to keep both approaches together

**Comment by benoitf** [comment]
@akosyakov that would be really nice

**Comment by akosyakov** [comment]
@benoitf What is the contract for `registerHandler` if a command was not registered? From code it looks like it will register a command then. Is it expected?

For VS Code extensions i need a way to register a handler without a command. I though to use `registerHandler` but if it auto registers a new command it won't work.

**Comment by benoitf** [comment]
@akosyakov I don't see calls to proxy.$registerCommand at https://github.com/theia-ide/theia/blob/7ffdfe71bb63df88c69d3249a6fe05264556575b/packages/plugin-ext/src/plugin/command-registry.ts#L75-L83 

AFAIK vscode extensions register first the command (with no handlers) and then when it calls registerCommand from the code it's registering only the handler

https://github.com/theia-ide/theia/blob/master/packages/plugin-ext-vscode/src/node/plugin-vscode-init.ts#L37-L57

**Comment by akosyakov** [comment]
> AFAIK vscode extensions register first the command (with no handlers) and then when it calls registerCommand from the code it's registering only the handler

It seems to be a reason for https://github.com/theia-ide/theia/issues/4151

Calling `registerCommand` second time register a handler causes a warning: https://github.com/theia-ide/theia/blob/fa5810fbb58feb3f62fc007003b8c05a98e28c60/packages/plugin-ext-vscode/src/node/plugin-vscode-init.ts#L54

I want to call `vscode.commands.registerHandler` instead to register a handler.

**Comment by benoitf** [comment]
@akosyakov yes, no issue on that

**Comment by akosyakov** [comment]
The order of registering contributions was fixed and command execution awaits now activation of VS Code extensions. I don't think this issue is relevant anymore. Please reopen if it is not the case.
