### ISSUE TITLE
"Restart Now" button from VS Code extension doesn't do anything

### ISSUE THREAD

**Issue by garagatyi** [eclipse-theia/theia#4001]
When VS Code extension asks a user to reload VS Code (Theia in our case) nothing happens.
Button:
![image](https://user-images.githubusercontent.com/1851863/50957738-b8069f80-14c7-11e9-93f8-47a0f35724d9.png)
Even though found on Theia as part of Che this issue doesn't seem to be related to Che itself.
Trace from Theia container:
```
root ERROR [hosted-plugin: 37] (node:37) UnhandledPromiseRejectionWarning: Error: The command 'workbench.action.reloadWindow' cannot be executed. There are no active handlers available for the command.
--
  | at e.<anonymous> (http://route7wxisv1f-eclipse-che.172.17.0.1.nip.io/bundle.js:12:65524 )
  | at http://route7wxisv1f-eclipse-che.172.17.0.1.nip.io/bundle.js:12:62449
  | at Object.next (http://route7wxisv1f-eclipse-che.172.17.0.1.nip.io/bundle.js:12:62554 )
  | at http://route7wxisv1f-eclipse-che.172.17.0.1.nip.io/bundle.js:12:61467
  | at new Promise (<anonymous>)
  | at a (http://route7wxisv1f-eclipse-che.172.17.0.1.nip.io/bundle.js:12:61244 )
  | at e.executeCommand (http://route7wxisv1f-eclipse-che.172.17.0.1.nip.io/bundle.js:12:65257 )
  | at e.$executeCommand (http://route7wxisv1f-eclipse-che.172.17.0.1.nip.io/bundle.js:115:210635 )
  | at e.doInvokeHandler (http://route7wxisv1f-eclipse-che.172.17.0.1.nip.io/bundle.js:14:347340 )
  | at e.invokeHandler (http://route7wxisv1f-eclipse-che.172.17.0.1.nip.io/bundle.js:14:347068 )
```

**Comment by akosyakov** [comment]
The same for go extension if you try to enable language server.

**Comment by akosyakov** [comment]
The command was implemented. Pleas reopen if it is still the issue.
