### ISSUE TITLE
[LS] Better error handling for the LS

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#4152]
When my LS throws an error, I can see the good old `Internal error` message with the stack trace

```
messages.js:46 Uncaught (in promise) Error: Internal error.
    at new ResponseError (messages.js:46)
    at handleResponse (main.js:430)
    at processMessageQueue (main.js:258)
    at main.js:242
    at run (setImmediate.js:40)
    at runIfPresent (setImmediate.js:69)
    at onGlobalMessage (setImmediate.js:109)
```

but not the `data`. That would be the only interesting part for the developers, I guess.

```
"java.util.concurrent.CompletionException: org.eclipse.core.runtime.AssertionFailedException: null argument:name
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.eclipse.core.runtime.AssertionFailedException: null argument:name
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.jdt.ls.core.internal.handlers.TypeHierarchyHandler$Direction.getByName(TypeHierarchyHandler.java:331)
	at org.eclipse.jdt.ls.core.internal.handlers.TypeHierarchyHandler.typeHierarchy(TypeHierarchyHandler.java:86)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:773)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$29(JDTLanguageServer.java:824)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more
```

Logging the error would help a lot to identify any LS issues. Currently,
 - the Output for Java is empty. `< no output yet>`
 - the log file for the JDT LS is empty,
 - no errors in the backend log,
 - the only thing I see is the `Internal error` in the browser's console.

----

![screen shot 2019-01-23 at 16 05 33](https://user-images.githubusercontent.com/1405703/51615785-ffaa1400-1f28-11e9-976b-cd646f44210d.jpg)
![screen shot 2019-01-23 at 16 05 14](https://user-images.githubusercontent.com/1405703/51615790-0042aa80-1f29-11e9-8ec1-99f85e29372f.jpg)
![screen shot 2019-01-23 at 15 56 09](https://user-images.githubusercontent.com/1405703/51615849-1fd9d300-1f29-11e9-8834-908920fcaa3a.jpg)

**Comment by tsmaeder** [comment]
We no longer implement any LSP functionality. Closing.
