### ISSUE TITLE
[ts] `ERROR TypeScript: (node:19781) UnhandledPromiseRejectionWarning: Error: geterr timeout`

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#4366]
Steps to reproduce:
 - Start an empty WS and clone https://github.com/arunoda/learnnextjs-demo/
 - Switch to the `data-fetching` branch.
 - Run `npm i && npm run dev`.

```
root ERROR TypeScript: (node:19781) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/Users/akos.kitta/git/theia/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

root ERROR TypeScript: (node:19781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19781) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19781) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/Users/akos.kitta/git/theia/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:19781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

root ERROR TypeScript: (node:19781) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/Users/akos.kitta/git/theia/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

root ERROR TypeScript: (node:19781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:19781) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/Users/akos.kitta/git/theia/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:19781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:19781) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/Users/akos.kitta/git/theia/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:19781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:19781) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/Users/akos.kitta/git/theia/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:19781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

root ERROR TypeScript: (node:19781) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/Users/akos.kitta/git/theia/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:19781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)

root ERROR TypeScript: (node:19781) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/Users/akos.kitta/git/theia/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:19781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)

root ERROR TypeScript: (node:19781) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/Users/akos.kitta/git/theia/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:19781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)


```

**Comment by kittaakos** [comment]
Similar if not the same: https://github.com/theia-ide/theia/issues/3455

**Comment by akosyakov** [comment]
@kittaakos Does it cause any unexpected user behaviour, like missing ts support? There is a known issue for TS language server to remove timeouts and implement cancellation properly: https://github.com/theia-ide/typescript-language-server/issues/53

**Comment by kittaakos** [comment]
I did not experience any malfunction although I have seen the error.

**Comment by akosyakov** [comment]
We don't use typescript-language-server anymore.

**Comment by garyo** [comment]
I'm getting this same error; I know this issue is closed but perhaps it could be reopened. I'm using emacs with lsp-mode. Once the server gets into this state I usually have to restart it.

**Comment by kittaakos** [comment]
> I'm getting this same error; I know this issue is closed but perhaps it could be reopened.

@garyo, can you please open a [new issue](https://github.com/eclipse-theia/theia/issues/new) referencing this one?
