### ISSUE TITLE
packaging extension with electron

### ISSUE THREAD

**Issue by capacman** [eclipse-theia/theia#4904]
I am trying to package my extension with electron-builder but when i try to run it it says:
Class constructor AbstractMessageReader cannot be invoked without 'new'
though i can run it from electron module directory with 
yarn start
Am i doing something wrong? below are electron-builder.yml and package.json files

[electron-builder.zip](https://github.com/theia-ide/theia/files/3077909/electron-builder.zip)
[package.zip](https://github.com/theia-ide/theia/files/3077913/package.zip)

**Comment by akosyakov** [comment]
Do you mean packaging your app with electron? Packaging an individual extension does not make sense.

For packaging for the standalone app see https://github.com/theia-ide/theia-apps/tree/master/theia-electron

**Comment by kittaakos** [comment]
> Class constructor AbstractMessageReader cannot be invoked without 'new'
> though i can run it from electron module directory with
> yarn start

It is just a guess, but I would say, you have this error because incorrect versions are used in your bundled electron application. See [here](https://github.com/theia-ide/theia/pull/4896#issuecomment-482597019).

**Comment by capacman** [comment]
Hi Guys,
I meant packaging the standalone app. I will look at above links and try again. Thanks for quick response.

**Comment by capacman** [comment]
I tried some different configs but could not package application. When i choose electronVersion 3.1.7 by looking examples from the link  @kittaakos gave,  i got some more traces like:
`root ERROR TypeError: Class constructor AbstractMessageReader cannot be invoked without 'new'
    at new WebSocketMessageReader (/home/capacman/programlama/typescript/workspace/jointreact/henkan-app-electron/dist/linux-unpacked/resources/app/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:21:28)
    at Object.createWebSocketConnection (/home/capacman/programlama/typescript/workspace/jointreact/henkan-app-electron/dist/linux-unpacked/resources/app/node_modules/vscode-ws-jsonrpc/lib/socket/connection.js:11:25)
    at /home/capacman/programlama/typescript/workspace/jointreact/henkan-app-electron/dist/linux-unpacked/resources/app/node_modules/@theia/core/lib/node/messaging/messaging-contribution.js:218:47
    at /home/capacman/programlama/typescript/workspace/jointreact/henkan-app-electron/dist/linux-unpacked/resources/app/node_modules/@theia/core/lib/node/messaging/messaging-contribution.js:286:17
    at ConnectionHandlers.route (/home/capacman/programlama/typescript/workspace/jointreact/henkan-app-electron/dist/linux-unpacked/resources/app/node_modules/@theia/core/lib/node/messaging/messaging-contribution.js:296:38)
    at WebSocket.<anonymous> (/home/capacman/programlama/typescript/workspace/jointreact/henkan-app-electron/dist/linux-unpacked/resources/app/node_modules/@theia/core/lib/node/messaging/messaging-contribution.js:150:41)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (/home/capacman/programlama/typescript/workspace/jointreact/henkan-app-electron/dist/linux-unpacked/resources/app/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (/home/capacman/programlama/typescript/workspace/jointreact/henkan-app-electron/dist/linux-unpacked/resources/app/node_modules/ws/lib/receiver.js:414:14)
root ERROR Cannot find a service for the path: /services/commands`

When i searched for error i found this but dont know whether it is related. @kittaakos is this the behavior you mentioned? i mean electron application choosing wrong versions ?

https://github.com/TypeFox/vscode-ws-jsonrpc/issues/8

**Comment by msujew** [comment]
This seems pretty outdated, especially since we don't use `vscode-ws-jsonrpc` anymore.
