### ISSUE TITLE
"Browser Preview for VS Code" VSCode extension not working in Theia

### ISSUE THREAD

**Issue by jbenguira** [eclipse-theia/theia#4961]
### Description
I noticed that the popular extension "Browser Preview for VS Code " was not working on theia
Issue: as soon as you start Theia after deploying the extension there is a lot of browser windows opening in a loop
This is what I have in the theia debug console: https://pastebin.com/dnVDkR17

### Reproduction Steps
1) Download the extension here: https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview
2) Put it in your plugins folder of Theia
3) Restart Theia, open it in your browser, you will see tons of windows opening inside theia

**OS and Theia version:**
Ubuntu 18.04, Theia 0.5.0

**Diagnostics:** 
[hosted-plugin: 20052] (node:20052) UnhandledPromiseRejectionWarning:                                                                                                                                                              Error: The command 'workbench.view.explorer' cannot be executed. There are no a                                                                                                                                                             ctive handlers available for the command. (args: [{"_isCancelled":false}])
    at CommandRegistry.<anonymous> (http://127.0.0.1:4949/bundle.js:97680:31                                                                                                                                                             )
    at step (http://127.0.0.1:4949/bundle.js:97487:23)
    at Object.next (http://127.0.0.1:4949/bundle.js:97468:53)
    at http://127.0.0.1:4949/bundle.js:97462:71
    at new Promise (<anonymous>)
    at ../../packages/core/lib/common/command.js.__awaiter (http://127.0.0.1                                                                                                                                                             :4949/bundle.js:97458:12)
    at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry                                                                                                                                                             .executeCommand (http://127.0.0.1:4949/bundle.js:97667:16)
    at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/c                                                                                                                                                             ommand-registry-main.js.CommandRegistryMainImpl.$executeCommand (http://127.0.0.1:4949/82.bundle.js:4661:72)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RP                                                                                                                                                             CProtocolImpl.doInvokeHandler (http://127.0.0.1:4949/82.bundle.js:861:23)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RP                                                                                                                                                             CProtocolImpl.invokeHandler (http://127.0.0.1:4949/82.bundle.js:846:41)
(node:20052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This                                                                                                                                                              error originated either by throwing inside of an async function without a catch                                                                                                                                                              block, or by rejecting a promise which was not handled with .catch(). (rejectio                                                                                                                                                             n id: 33)

**Comment by akosyakov** [comment]
@jbenguira Support for webviews landed last week. It should work now, but a command which you mentioned in the stack trace probably still missing.

**Comment by eli88p** [comment]
@akosyakov hii, i tired to load Browser Preview in new version that have support to webview and i got...
also if i tried to load my custom html code that written in extension of vs code, in theia i have a same issue. 

![Capture](https://user-images.githubusercontent.com/11608934/73279265-886f2600-41f5-11ea-9d02-69dd6272a844.PNG)

**Comment by akosyakov** [comment]
Which browser? Firefox has issues with considering sub domains of localhost as secure.

**Comment by eli88p** [comment]
@akosyakov Thank it's work from chromium

**Comment by eli88p** [comment]
@akosyakov Anton i have another issue with run from my host IP instead of localhost
Browser: chromium.
Logs: 
root ERROR Failed to enable webview caching:  ReferenceError: caches is not defined
    at WebviewResourceCache.<anonymous> (http://10.206.41.134:8080/52.bundle.js:15962:46)
    at step (http://10.206.41.134:8080/52.bundle.js:15938:23)
    at Object.next (http://10.206.41.134:8080/52.bundle.js:15919:53)
    at http://10.206.41.134:8080/52.bundle.js:15913:71
    at new Promise (<anonymous>)
    at push.../../packages/plugin-ext/lib/main/browser/webview/webview-resource-cache.js.__awaiter (http://10.206.41.134:8080/52.bundle.js:15909:12)
    at WebviewResourceCache.push.../../packages/plugin-ext/lib/main/browser/webview/webview-resource-cache.js.WebviewResourceCache.resolveCache (http://10.206.41.134:8080/52.bundle.js:15955:16)
    at new WebviewResourceCache (http://10.206.41.134:8080/52.bundle.js:15952:14)
    at Object.resolveInstance (http://10.206.41.134:8080/bundle.js:46674:18)
    at http://10.206.41.134:8080/bundle.js:46767:42


![Capture](https://user-images.githubusercontent.com/11608934/73346396-768d9180-428e-11ea-80fe-141652ce410d.PNG)

**Comment by akosyakov** [comment]
@eli88p webview work only in secure context, localhost or https

**Comment by kulong0105** [comment]
i also meet the promble:
root ERROR Failed to enable webview caching: ReferenceError: caches is not defined

i try to set THEIA_WEBVIEW_EXTERNAL_ENDPOINT env with hostname, but it doesn't work

**Comment by liuyiqi1999** [comment]
@akosyakov Is there any workaround for the secure context issue? I meet the same problem of 'Failed to enable webview caching'. 

I visit my theia through an iframe with a http src visiting the container my theia is running on. It looks like this: 
`<iframe src="http://xx.xx.xx.xx(ip address):8000/" />`

The http+ip url is the only way I can connect to my theia now. I tried to set a https domain which rewrites to this http url by nginx rules, but the caching error still exists and all webviews still fail.

**Comment by msujew** [comment]
@liuyiqi1999 The workaround is to not use subdomains. Note that this is a security risk. See [here](https://github.com/eclipse-theia/theia/tree/master/packages/plugin-ext#environment-variables) for more info.

I'll close this, since the extension is now working.

**Comment by jbenguira** [comment]
Incredible! I opened this ticket in 2019, five years ago. :p

**Comment by msujew** [comment]
@jbenguira I sometimes find outdated issues while looking for something else. This one has probably been fixed 4 years or so ago :D
