### ISSUE TITLE
Keep debug terminal even when the debug session is terminated

### ISSUE THREAD

**Issue by a1994846931931** [eclipse-theia/theia#5250]
### Description

Here is the original question that I posted on spectrum:

>When deploying vscode-python-plugin on theia, I found that the debug console ( a terminal actually) would close automatically when the debug session is terminated, which is annoying because I can't see the output anymore. And it behaves differently from the vscode. I dug a while into the source code but ended with failing to figure out how this happens. Anyone has an idea on why the terminal ended when the debug session is over?

>Spectrum: https://spectrum.chat/theia/dev/keep-debug-terminal-even-when-the-debug-session-is-terminated~265c4b4d-8946-43d7-9eb2-bca2317d5618

And @tsmaeder suggests that it could be a feature. So here it is.

In addition, here is a short animation to clarify the situation:

![debug-console](https://user-images.githubusercontent.com/17487291/58363436-b4a00d80-7ed6-11e9-9b07-1fff98ed8fa3.gif)

### Reproduction Steps

- Run theia with ms-python-2019.3.6215 plugin deployed;
- Add debug configuration that either is of type "Terminal (external)" or "Terminal (integrated)";
- Start debugging, check "Python Debug Console"
- Stop debugging, check "Python Debug Console"

**OS and Theia version:**

OS: Linux
Theia: 0.6.0

**Diagnostics:** 
None

**Comment by akosyakov** [comment]
Sounds good, PRs are welcomed.

**Comment by GurpreetSran** [comment]
If someone wants to reproduce it, here is the code with plugin included.

https://github.com/GurpreetSran/theia-python

I'm also getting some additional errors. 

`root ERROR [hosted-plugin: 50687] (node:50798) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
root ERROR Couldn't resize terminal -1, because it doesn't exist.
root INFO [hosted-plugin: 50687] Info Python Extension: 2019-07-23 17:40:38: Terminal name 'Python Debug Console' identified as shell 'other'
root INFO [hosted-plugin: 50687] Info Python Extension: 2019-07-23 17:40:38: Shell path from user settings 'undefined'
root INFO [hosted-plugin: 50687] Info Python Extension: 2019-07-23 17:40:38: Shell path '/bin/bash'
Info Python Extension: 2019-07-23 17:40:38: Shell path identified as shell 'bash'
Info Python Extension: 2019-07-23 17:40:38: Shell path from user env '/bin/bash'
root INFO [hosted-plugin: 50687] Info Python Extension: 2019-07-23 17:40:38: Shell identified as 'bash'
root INFO [hosted-plugin: 50687] Info Python Extension: 2019-07-23 17:40:38: Cached data exists getEnvironmentVariables, /Users/gurpreetsingh/Desktop
root INFO [hosted-plugin: 50687] Info Python Extension: 2019-07-23 17:40:38: Cached data exists getEnvironmentVariables, /Users/gurpreetsingh/Desktop
root ERROR [hosted-plugin: 50687] Promise rejection not handled in one second: Error: the debug session connection is disposed, id: 249a91c3-5ddd-4481-a1bd-3916dcef1f21
root ERROR [hosted-plugin: 50687] With stack trace: Error: the debug session connection is disposed, id: 249a91c3-5ddd-4481-a1bd-3916dcef1f21
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.checkDisposed (http://localhost:3000/30.bundle.js:1048:19)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.newEmitter (http://localhost:3000/30.bundle.js:1244:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.getEmitter (http://localhost:3000/30.bundle.js:1238:55)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.doFire (http://localhost:3000/30.bundle.js:1235:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleEvent (http://localhost:3000/30.bundle.js:1218:22)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleMessage (http://localhost:3000/30.bundle.js:1165:18)
    at PluginMessageReader.callback (http://localhost:3000/30.bundle.js:1070:79)
    at PluginMessageReader.push.../../packages/plugin-ext/lib/common/plugin-message-reader.js.PluginMessageReader.readMessage (http://localhost:3000/90.bundle.js:1225:18)
    at ConnectionMainImpl.<anonymous> (http://localhost:3000/90.bundle.js:2474:53)
    at step (http://localhost:3000/90.bundle.js:2445:23)

**Comment by a1994846931931** [comment]
Solved by 0327a4d666ae2d5b8616e2603e672fb23ad7b0e3

But a problem remains: https://github.com/eclipse-theia/theia/issues/6618
