### ISSUE TITLE
[git] Error: Request 'resolveContent' failed when opening `"DD" conflict` from git view

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#5463]
This happens when trying to open a non-existing file marked as a (git) conflicting from the git view.

 - Open an empty workspace.
 - Open a terminal, initialize a git repository and make a DD conflict by running this: https://stackoverflow.com/questions/43702944/reproducing-git-merge-conflict-dd

Open `main.txt` in the editor:

<img width="285" alt="Screen Shot 2019-06-13 at 22 10 23" src="https://user-images.githubusercontent.com/1405703/59464529-f6aed600-8e28-11e9-9a05-46092e6e2ac4.png">

```
Uncaught (in promise) Error: Request 'resolveContent' failed
    at Proxy.<anonymous> (https://3000-aa7e5a81-2826-4b87-a71d-ac8997287f96.ws-eu0.gitpod.io/bundle.js:109424:33)
    at FileResource.<anonymous> (https://3000-aa7e5a81-2826-4b87-a71d-ac8997287f96.ws-eu0.gitpod.io/5.bundle.js:309:62)
    at step (https://3000-aa7e5a81-2826-4b87-a71d-ac8997287f96.ws-eu0.gitpod.io/5.bundle.js:243:23)
    at Object.next (https://3000-aa7e5a81-2826-4b87-a71d-ac8997287f96.ws-eu0.gitpod.io/5.bundle.js:224:53)
    at https://3000-aa7e5a81-2826-4b87-a71d-ac8997287f96.ws-eu0.gitpod.io/5.bundle.js:218:71
    at new Promise (<anonymous>)
    at push.../../packages/filesystem/lib/browser/file-resource.js.__awaiter (https://3000-aa7e5a81-2826-4b87-a71d-ac8997287f96.ws-eu0.gitpod.io/5.bundle.js:214:12)
    at FileResource.push.../../packages/filesystem/lib/browser/file-resource.js.FileResource.readContents (https://3000-aa7e5a81-2826-4b87-a71d-ac8997287f96.ws-eu0.gitpod.io/5.bundle.js:303:16)
    at new MonacoEditorModel (https://3000-aa7e5a81-2826-4b87-a71d-ac8997287f96.ws-eu0.gitpod.io/28.bundle.js:129:38)
    at MonacoTextModelService.<anonymous> (https://3000-aa7e5a81-2826-4b87-a71d-ac8997287f96.ws-eu0.gitpod.io/28.bundle.js:650:47)
Caused by: Error: 'file:///workspace/foo-bar/main.txt' has not been found.
    at FileSystemNode.<anonymous> (/workspace/theia/packages/filesystem/lib/node/node-filesystem.js:160:64)
    at step (/workspace/theia/packages/filesystem/lib/node/node-filesystem.js:59:23)
    at Object.next (/workspace/theia/packages/filesystem/lib/node/node-filesystem.js:40:53)
    at fulfilled (/workspace/theia/packages/filesystem/lib/node/node-filesystem.js:31:58)
```

**Comment by sgraband** [comment]
`@theia/git` is officially deprecated per README.
