### ISSUE TITLE
When debug session is stopped console is flooded with errors

### ISSUE THREAD

**Issue by tolusha** [eclipse-theia/theia#5504]
### Reproduction Steps

1. Start debug session
2. Stop debug session
3. A lot of stacktraces are observed in a console

**OS and Theia version:**
`Theia: 0.7.0`

**Assumption**
Events are send when session is disposed:
https://github.com/theia-ide/theia/blob/master/packages/debug/src/node/debug-adapter-session.ts#L53-L54

**Diagnostics:** 

```
root ERROR Couldn't resize terminal -1, because it doesn't exist.
root ERROR [hosted-plugin: 14754] (node:14754) UnhandledPromiseRejectionWarning: Error: the debug session connection is disposed, id: a80b415f-4a33-4d54-95ce-3ade3fa5196b
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.checkDisposed (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1048:19)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.newEmitter (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1244:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.getEmitter (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1238:55)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.doFire (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1235:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleEvent (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1218:22)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleMessage (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1165:18)
    at PluginMessageReader.callback (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1070:79)
    at PluginMessageReader.push.../../packages/plugin-ext/lib/common/plugin-message-reader.js.PluginMessageReader.readMessage (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/87.bundle.js:1225:18)
    at ConnectionMainImpl.<anonymous> (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/87.bundle.js:2163:53)
    at step (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/87.bundle.js:2134:23)

root ERROR [hosted-plugin: 14754] (node:14754) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

root ERROR [hosted-plugin: 14754] (node:14754) UnhandledPromiseRejectionWarning: Error: the debug session connection is disposed, id: a80b415f-4a33-4d54-95ce-3ade3fa5196b
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.checkDisposed (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1048:19)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.newEmitter (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1244:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.getEmitter (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1238:55)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.doFire (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1235:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleEvent (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1218:22)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleMessage (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1165:18)
    at PluginMessageReader.callback (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1070:79)
    at PluginMessageReader.push.../../packages/plugin-ext/lib/common/plugin-message-reader.js.PluginMessageReader.readMessage (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/87.bundle.js:1225:18)
    at ConnectionMainImpl.<anonymous> (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/87.bundle.js:2163:53)
    at step (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/87.bundle.js:2134:23)

root ERROR [hosted-plugin: 14754] (node:14754) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)

root ERROR [hosted-plugin: 14754] (node:14754) UnhandledPromiseRejectionWarning: Error: the debug session connection is disposed, id: a80b415f-4a33-4d54-95ce-3ade3fa5196b
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.checkDisposed (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1048:19)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.newEmitter (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1244:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.getEmitter (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1238:55)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.doFire (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1235:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleEvent (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1218:22)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleMessage (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1165:18)
    at PluginMessageReader.callback (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1070:79)
    at PluginMessageReader.push.../../packages/plugin-ext/lib/common/plugin-message-reader.js.PluginMessageReader.readMessage (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/87.bundle.js:1225:18)
    at ConnectionMainImpl.<anonymous> (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/87.bundle.js:2163:53)
    at step (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/87.bundle.js:2134:23)

root ERROR [hosted-plugin: 14754] (node:14754) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:14754) UnhandledPromiseRejectionWarning: Error: the debug session connection is disposed, id: a80b415f-4a33-4d54-95ce-3ade3fa5196b
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.checkDisposed (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1048:19)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.newEmitter (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1244:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.getEmitter (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1238:55)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.doFire (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1235:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleEvent (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1218:22)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleMessage (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1165:18)
    at PluginMessageReader.callback (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/29.bundle.js:1070:79)
    at PluginMessageReader.push.../../packages/plugin-ext/lib/common/plugin-message-reader.js.PluginMessageReader.readMessage (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/87.bundle.js:1225:18)
    at ConnectionMainImpl.<anonymous> (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/87.bundle.js:2163:53)
    at step (https://3000-baecf0db-1843-41fa-b7a8-f0890500ac44.ws-eu0.gitpod-staging.com/87.bundle.js:2134:23)
(node:14754) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
```

**Comment by colin-grant-work** [comment]
I can no longer reproduce this bug, so I'm going to close this issue for now. Please comment / reopen if you encounter this issue in the current version of Theia.
