### ISSUE TITLE
[debug][java][windows][vs-code] Cannot start debug `spring-petclinic`

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#5840]
Originally from here: https://github.com/theia-ide/theia/pull/5281#issuecomment-516741021

 - Removed `@theia/java` and `@theia/java-debug` from both the `browser` and `electron` `package.json` files.
 - Rebuilt the extensions without Theia Java.
 - Downloaded the two Java VS Code extensions.
```
root INFO unzipping the plugin ProxyPluginDeployerEntry {
  deployer:
   PluginVsCodeFileHandler {
     unpackedFolder: 'C:\\Users\\KITTAA~1\\AppData\\Local\\Temp\\vscode-unpacked' },
  delegate:
   PluginDeployerEntryImpl {
     originId: 'local-dir:../../plugins',
     pluginId: 'redhat.java-0.47.0.vsix',
     map: Map {},
     changes: [],
     acceptedTypes: [],
     currentPath:
      'C:\\Users\\kittaakos\\dev\\theia\\plugins\\redhat.java-0.47.0.vsix',
     initPath:
      'C:\\Users\\kittaakos\\dev\\theia\\plugins\\redhat.java-0.47.0.vsix',
     resolved: true,
     resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  deployerName: 'PluginVsCodeFileHandler' }
root INFO unzipping the plugin ProxyPluginDeployerEntry {
  deployer:
   PluginVsCodeFileHandler {
     unpackedFolder: 'C:\\Users\\KITTAA~1\\AppData\\Local\\Temp\\vscode-unpacked' },
  delegate:
   PluginDeployerEntryImpl {
     originId: 'local-dir:../../plugins',
     pluginId: 'vscjava.vscode-java-debug-0.20.0.vsix',
     map: Map {},
     changes: [],
     acceptedTypes: [],
     currentPath:
      'C:\\Users\\kittaakos\\dev\\theia\\plugins\\vscjava.vscode-java-debug-0.20.0.vsix',
     initPath:
      'C:\\Users\\kittaakos\\dev\\theia\\plugins\\vscjava.vscode-java-debug-0.20.0.vsix',
     resolved: true,
     resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  deployerName: 'PluginVsCodeFileHandler' }
root INFO PluginTheiaDirectoryHandler: accepting plugin with path C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked\r
edhat.java-0.47.0.vsix
root INFO Resolved "redhat.java-0.47.0.vsix" to a VS Code extension "java@0.47.0" with engines: { vscode: '^1.36.0' }
root INFO PluginTheiaDirectoryHandler: accepting plugin with path C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked\v
scjava.vscode-java-debug-0.20.0.vsix
root INFO Resolved "vscjava.vscode-java-debug-0.20.0.vsix" to a VS Code extension "vscode-java-debug@0.20.0" with engine
s: { vscode: '^1.32.0' }
root INFO Deploying backend plugin "java@0.47.0" from "C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked\redhat.java-
0.47.0.vsix\extension\dist\extension"
root INFO Deploying backend plugin "vscode-java-debug@0.20.0" from "C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked
\vscjava.vscode-java-debug-0.20.0.vsix\extension\dist\extension"
```
 - Cloned https://github.com/spring-projects/spring-petclinic and opened it as my workspace.
```
root INFO [nsfw-watcher: 2572] Started watching: c:\Users\kittaakos\dev\spring-petclinic\.vscode\launch.json
root INFO [nsfw-watcher: 2572] Started watching: c:\Users\kittaakos\dev\spring-petclinic\.vscode\settings.json
root INFO Started watching the git repository: file:///c%3A/Users/kittaakos/dev/spring-petclinic
```
 - Waited for the LS to start and build.
```
root INFO [hosted-plugin: 3152] PLUGIN_HOST(3152): PluginManagerExtImpl/init()
PLUGIN_HOST(3152): initializing(java@0.47.0 with C:\Users\kittaakos\dev\theia\packages\plugin-ext-vscode\lib\node/plugin
-vscode-init.js)
PLUGIN_HOST(3152): initializing(vscode-java-debug@0.20.0 with C:\Users\kittaakos\dev\theia\packages\plugin-ext-vscode\li
b\node/plugin-vscode-init.js)
Debugger contribution has been registered: java
root INFO [hosted-plugin: 3152] PLUGIN_HOST(3152): PluginManagerExtImpl/loadPlugin(C:\Users\KITTAA~1\AppData\Local\Temp\
vscode-unpacked\redhat.java-0.47.0.vsix\extension\dist\extension)
root INFO [hosted-plugin: 3152] { message:
   'Starting Java server with: C:\\PROGRA~1\\Java\\JDK18~1.0_1\\bin\\java -Declipse.application=org.eclipse.jdt.ls.core.
id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=UTF-8 -DwatchPa
rentProcess=false -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar C:\\Users\\KITTAA~1\\AppData\\Local\\Te
mp\\vscode-unpacked\\redhat.java-0.47.0.vsix\\extension\\server\\plugins\\org.eclipse.equinox.launcher_1.5.500.v20190715
-1310.jar -configuration C:\\Users\\KITTAA~1\\AppData\\Local\\Temp\\vscode-unpacked\\redhat.java-0.47.0.vsix\\extension\
\server\\config_win -data C:\\Users\\kittaakos\\AppData\\Roaming\\.theia\\workspace-storage\\b57d6bdc8a5ce6f798acacd19bf
4aa59\\redhat.java\\jdt_ws',
  level: 'info',
  timestamp: '2019-07-31 09:39:52.756' }
```
 - Started the `Debug (Launch)-PetClinicApplication<spring-petclinic>` launch configuiration.
 - Had an error:
```
root INFO [hosted-plugin: 3152] PLUGIN_HOST(3152): PluginManagerExtImpl/loadPlugin(C:\Users\KITTAA~1\AppData\Local\Temp\
vscode-unpacked\vscjava.vscode-java-debug-0.20.0.vsix\extension\dist\extension)
root INFO [hosted-plugin: 3152] Debug configuration provider has been registered: java
root INFO [hosted-plugin: 3152] Cannot update debug settings. { Error: No delegateCommandHandler for vscode.java.updateD
ebugSettings
    at C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked\redhat.java-0.47.0.vsix\extension\dist\extension.js:1:13690
    at C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked\redhat.java-0.47.0.vsix\extension\dist\extension.js:1:13984
    at Immediate.k.size.setImmediate (C:\Users\KITTAA~1\AppData\Local\Temp\vscode-unpacked\redhat.java-0.47.0.vsix\exten
sion\dist\extension.js:1:14345)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5) code: -32601, data: undefined }
root ERROR Error starting the debug session Error: It is not possible to provide debug adapter executable.
    at DebugExtImpl.<anonymous> (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\plugin\node\debug\debug.js:501:39)
    at step (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\plugin\node\debug\debug.js:32:23)
    at Object.next (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\plugin\node\debug\debug.js:13:53)
    at fulfilled (C:\Users\kittaakos\dev\theia\packages\plugin-ext\lib\plugin\node\debug\debug.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

![Screen Shot 2019-07-31 at 09 48 58](https://user-images.githubusercontent.com/1405703/62193973-326e1280-b379-11e9-906c-22ee8bdbca6f.jpg)

**Comment by tom-shan** [comment]
I have a similar error in ubuntu, after the extra process of cleaning some data(~/.theia and /tmp/vscode-unpacked), the error disappeared and the debug session could be started successfully.

**Comment by akosyakov** [comment]
@tolusha Maybe you have an idea what is going on?

**Comment by tolusha** [comment]
I was able to reproduce this issue once but after refreshing it is no longer there.

**Comment by kittaakos** [comment]
> after the extra process of cleaning some data(~/.theia and /tmp/vscode-unpacked), the error disappeared

This did not work for me on Windows.

**Comment by akosyakov** [comment]
I think it is a dup of https://github.com/eclipse-theia/theia/issues/6361

**Comment by akosyakov** [comment]
Please use `redhat.java@0.49.0` or never.
