### ISSUE TITLE
save file and auto format have error on console

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#5943]
### Description
save file and auto format
have error on console
```
root ERROR TypeError: Cannot read property 'startLineNumber' of null
    at TextModel.validateRange (https://3000-fbf4d029-9465-4765-9af3-0af7f7996600.ws-us0.gitpod.io/vs/editor/editor.main.js:57667:55)
    at TextModel._applyEdits (https://3000-fbf4d029-9465-4765-9af3-0af7f7996600.ws-us0.gitpod.io/vs/editor/editor.main.js:57901:47)
    at TextModel.applyEdits (https://3000-fbf4d029-9465-4765-9af3-0af7f7996600.ws-us0.gitpod.io/vs/editor/editor.main.js:57862:29)
    at MonacoEditorModel.push.../../packages/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.applyEdits (https://3000-fbf4d029-9465-4765-9af3-0af7f7996600.ws-us0.gitpod.io/26.bundle.js:449:31)
    at MonacoEditorModel.<anonymous> (https://3000-fbf4d029-9465-4765-9af3-0af7f7996600.ws-us0.gitpod.io/26.bundle.js:540:50)
    at step (https://3000-fbf4d029-9465-4765-9af3-0af7f7996600.ws-us0.gitpod.io/26.bundle.js:68:23)
    at Object.next (https://3000-fbf4d029-9465-4765-9af3-0af7f7996600.ws-us0.gitpod.io/26.bundle.js:49:53)
    at fulfilled (https://3000-fbf4d029-9465-4765-9af3-0af7f7996600.ws-us0.gitpod.io/26.bundle.js:40:58)
log @ logger-protocol.ts:112
(anonymous) @ logger-frontend-module.ts:41
(anonymous) @ logger.ts:312
(anonymous) @ logger.ts:304
Promise.then (async)
../../packages/core/lib/common/logger.js.Logger.log @ logger.ts:299
log @ logger.ts:45
(anonymous) @ monaco-editor-model.js:547
step @ monaco-editor-model.js:58
(anonymous) @ monaco-editor-model.js:39
rejected @ monaco-editor-model.js:31
Promise.then (async)
step @ monaco-editor-model.js:32
(anonymous) @ monaco-editor-model.js:33
push.../../packages/monaco/lib/browser/monaco-editor-model.js.__awaiter @ monaco-editor-model.js:29
push.../../packages/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.fireWillSaveModel @ monaco-editor-model.js:480
(anonymous) @ monaco-editor-model.js:455
step @ monaco-editor-model.js:58
(anonymous) @ monaco-editor-model.js:39
(anonymous) @ monaco-editor-model.js:33
push.../../packages/monaco/lib/browser/monaco-editor-model.js.__awaiter @ monaco-editor-model.js:29
push.../../packages/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.doSave @ monaco-editor-model.js:447
(anonymous) @ monaco-editor-model.js:396
(anonymous) @ monaco-editor-model.js:290
step @ monaco-editor-model.js:58
(anonymous) @ monaco-editor-model.js:39
(anonymous) @ monaco-editor-model.js:33
push.../../packages/monaco/lib/browser/monaco-editor-model.js.__awaiter @ monaco-editor-model.js:29
(anonymous) @ monaco-editor-model.js:284
Promise.then (async)
push.../../packages/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.run @ monaco-editor-model.js:284
push.../../packages/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.scheduleSave @ monaco-editor-model.js:396
push.../../packages/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.save @ monaco-editor-model.js:280
(anonymous) @ saveable.ts:69
step @ saveable.ts:15
(anonymous) @ saveable.ts:15
(anonymous) @ saveable.ts:15
../../packages/core/lib/browser/saveable.js.__awaiter @ saveable.ts:15
save @ saveable.ts:66
(anonymous) @ application-shell.ts:1461
step @ application-shell.ts:15
(anonymous) @ application-shell.ts:15
(anonymous) @ application-shell.ts:15
../../packages/core/lib/browser/shell/application-shell.js.__awaiter @ application-shell.ts:15
../../packages/core/lib/browser/shell/application-shell.js.ApplicationShell.save @ application-shell.ts:1460
execute @ common-frontend-contribution.ts:498
../../packages/core/lib/browser/keybinding.js.KeybindingRegistry.tryKeybindingExecution @ keybinding.ts:559
../../packages/core/lib/browser/keybinding.js.KeybindingRegistry.run @ keybinding.ts:608
(anonymous) @ frontend-application.ts:170
```

### Reproduction Steps

- Install VsCode Plugin `vscode:extension/EditorConfig.EditorConfig`
- Open file and edit
- Format it

**OS and Theia version:**
latest next version 2019-08-13
**Diagnostics:**

**Comment by akosyakov** [comment]
If someone can investigate why it is happening it would be helpful.

**Comment by 502647092** [comment]
@akosyakov 
![image](https://user-images.githubusercontent.com/10203793/69938287-d75f4e80-1517-11ea-841e-c11d0ab44b61.png)

**Comment by akosyakov** [comment]
Yes, it would be interesting what is the reason behind it

**Comment by vince-fugnitto** [comment]
I cannot reproduce the error anymore. If there is additional information please comment :+1:
