### ISSUE TITLE
copy file error don't have notify

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6054]
### Description
copy file error don't have notify

### Reproduction Steps

- create a file `temp.txt`
- copy file in explorer
- delete `temp.txt`
- paste file in explorer
- have error in console and don't have notify

**OS and Theia version:**
**Diagnostics:** 
```
Uncaught (in promise) Error: Request 'copy' failed
    at Proxy.<anonymous> (https://theia.miaowoo.cc/bundle.js:14:768220)
    at t.copy (https://theia.miaowoo.cc/bundle.js:14:161902)
    at n.handlePaste (https://theia.miaowoo.cc/bundle.js:1:694379)
    at HTMLDivElement.<anonymous> (https://theia.miaowoo.cc/bundle.js:1:693888)
    at HTMLDocument.r (https://theia.miaowoo.cc/bundle.js:1:485424)
Caused by: Error: 'file:///home/project/JavaWorkSpace/MiaoScript/src/main/resources/plugins/Debug.js' has not been found.
    at FileSystemNode.<anonymous> (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:416:64)
    at step (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:59:23)
    at Object.next (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:40:53)
    at fulfilled (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:31:58)
```

**Comment by akosyakov** [comment]
@502647092 Is your suggestion to report file errors as notifications?

**Comment by 502647092** [comment]
@akosyakov 
yes i think we need notify user error
#4907 Similar problem
