### ISSUE TITLE
http file miss highlight and codelens not effect

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6192]
### Description
recent versions cause http file miss highlight and codelens not effect

### Reproduction Steps

- Install ext `vscode:extension/humao.rest-client`
- create simple http file
```
GET http://google.com
```

![temp](https://user-images.githubusercontent.com/10203793/64930908-4b6a4e80-d867-11e9-80f5-0d0c03de5518.gif)

- here are two problem
  - 1. http file miss highlight
  - 2. codelens not effect , but after manual send request it will active

**OS and Theia version:**
**Diagnostics:**

**Comment by vince-fugnitto** [comment]
It works correctly initially, but once the application is reloaded it loses both the highlighting and codelens. 

**Initially**

<div align='center'>

<img width="1358" alt="Screen Shot 2019-09-19 at 9 42 32 AM" src="https://user-images.githubusercontent.com/40359487/65249478-0f7ef580-dac2-11e9-8241-539cc164518d.png">


</div>

**After Reload**

<div align='center'>

<img width="1358" alt="Screen Shot 2019-09-19 at 9 42 41 AM" src="https://user-images.githubusercontent.com/40359487/65249438-ff671600-dac1-11e9-9698-e4accc79fb76.png">



</div>

**Comment by akosyakov** [comment]
I see an error in console: 
> root ERROR An invalid preference schema was rejected: data.properties['rest-client.largeResponseBodySizeLimitInMB'].exclusiveMinimum should be number

Could be a bug in vscode extension? We should be more tolerant though and does not ignore the whole schema, but only bogus attribute.

**Comment by akosyakov** [comment]
I also see:
```
logger-protocol.ts:112 root ERROR TypeError: Cannot assign to read only property 'other' of object '#<Object>'
    at https://3000-f6ab6d92-f168-48b1-8d7e-7a90981b9e35.ws-eu0.gitpod.io/vs/editor/editor.main.js:14679:46
    at Array.forEach (<anonymous>)
    at mixin (https://3000-f6ab6d92-f168-48b1-8d7e-7a90981b9e35.ws-eu0.gitpod.io/vs/editor/editor.main.js:14672:33)
    at https://3000-f6ab6d92-f168-48b1-8d7e-7a90981b9e35.ws-eu0.gitpod.io/vs/editor/editor.main.js:14676:29
    at Array.forEach (<anonymous>)
    at Object.mixin (https://3000-f6ab6d92-f168-48b1-8d7e-7a90981b9e35.ws-eu0.gitpod.io/vs/editor/editor.main.js:14672:33)
    at Configuration.CommonEditorConfiguration.updateOptions (https://3000-f6ab6d92-f168-48b1-8d7e-7a90981b9e35.ws-eu0.gitpod.io/vs/editor/editor.main.js:81298:40)
    at StandaloneEditor.CodeEditorWidget.updateOptions (https://3000-f6ab6d92-f168-48b1-8d7e-7a90981b9e35.ws-eu0.gitpod.io/vs/editor/editor.main.js:103757:33)
    at StandaloneEditor.updateOptions (https://3000-f6ab6d92-f168-48b1-8d7e-7a90981b9e35.ws-eu0.gitpod.io/vs/editor/editor.main.js:126146:44)
    at MonacoEditorProvider.push.../../packages/monaco/lib/browser/monaco-editor-provider.js.MonacoEditorProvider.updateMonacoEditorOptions (https://3000-f6ab6d92-f168-48b1-8d7e-7a90981b9e35.ws-eu0.gitpod.io/29.bundle.js:1262:33)
```

Maybe caused by the new Monaco version or recent preferences refactoring.

**Comment by akosyakov** [comment]
@502647092 @vince-fugnitto Is it still the issue?

**Comment by 502647092** [comment]
@akosyakov not have
