### ISSUE TITLE
TypeError: Cannot read property 'widgets' of null

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6231]
### Description
 
```
root ERROR TypeError: Cannot read property 'widgets' of null
    at ViewContainer.../../packages/core/lib/browser/view-container.js.ViewContainer.getParts (http://localhost:3000/bundle.js:109955:37)
    at PluginViewRegistry.<anonymous> (http://localhost:3000/90.bundle.js:12956:81)
    at step (http://localhost:3000/90.bundle.js:12429:23)
    at Object.next (http://localhost:3000/90.bundle.js:12410:53)
    at fulfilled (http://localhost:3000/90.bundle.js:12401:58)
```

### Reproduction Steps

Start Theia from the source.

**OS and Theia version:**
macOS, 657bda85a

**Diagnostics:**

**Comment by elaihau** [comment]
I can see the same errors from Ubuntu 18.04. Example browser

**Comment by vince-fugnitto** [comment]
The method `get containerLayout` has an incorrect return type as `this.panel.layout` may be `null`.

https://github.com/eclipse-theia/theia/blob/a21dc550d852f8459f91ebd31d912df503133bf1/packages/core/src/browser/view-container.ts#L332-L334

When calling `getParts`, the null exception is therefore thrown.

https://github.com/eclipse-theia/theia/blob/a21dc550d852f8459f91ebd31d912df503133bf1/packages/core/src/browser/view-container.ts#L324-L326

**Comment by sgraband** [comment]
`ViewContainer.getParts()` now has proper lifecycle management and error handling.
