### ISSUE TITLE
 Unknown method $activateByEvent on actor PluginManagerExt

### ISSUE THREAD

**Issue by aaqaishtyaq** [eclipse-theia/theia#6246]
### Description

Hey, I built a custom extension which uses `taskService` to run some tasks. But recently I'm getting this error while executing task through that extension.

**OS and Theia version:**
Theia `v0.10.0` running on Eclipse Che

**Diagnostics:** 

```
root INFO error:  Error: Unknown method $activateByEvent on actor PluginManagerExt
    at RPCProtocolImpl.doInvokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:205:19)
    at RPCProtocolImpl.invokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:192:41)
    at RPCProtocolImpl.receiveRequest (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:154:45)
    at RPCProtocolImpl.receiveOneMessage (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:123:22)
    at /home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:55:89
    at /home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:233:17
    at /home/theia/node_modules/@theia/core/lib/common/event.js:161:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:176:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:264:29)
    at WebSocketClient.fire (/home/theia/lib/node/plugin-remote-init.js:319:26)
```

**Comment by akosyakov** [comment]
@aaqaishtyaq Could you share more details please in order to help us reproduce and fix the issue? If you can share your custom extension (or another sample) running against master state it would be the best.

**Comment by aaqaishtyaq** [comment]
Here is the [extension](https://github.com/aaqaishtyaq/theia-run).
This error message comes while running this extension with theia.
I am creating a custom menu, which runs the command matching the label.

**Comment by akosyakov** [comment]
@aaqaishtyaq And do you have any theia plugin or VS Code extension as well? Or only native Theia extensions?

**Comment by aaqaishtyaq** [comment]
I'm using Eclipse Che-Theia Plugins, Typescript Language Server (VS Code Extensions) and Native Theia extensions.
