### ISSUE TITLE
[vscode plugin] vscode-swift-development-environment

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#6329]
### Description
Activating the extension 

https://github.com/vknabel/vscode-swift-development-environment/releases (version 2.8.1)

results in:
```
  message: "[hosted-plugin: 7905] Error on activation of vscode-swift-development-environment TypeError: Cannot read property 'replace' of undefined
    at Object.absolutePath (/tmp/vscode-extensions/vknabel.vscode-swift-development-environment@2.8.1/extension/out/src/AbsolutePath.js:6:43)
    at checkToolsAvailability (/tmp/vscode-extensions/vknabel.vscode-swift-development-environment@2.8.1/extension/out/src/clientMain.js:226:35)
    at initConfig (/tmp/vscode-extensions/vknabel.vscode-swift-development-environment@2.8.1/extension/out/src/clientMain.js:161:5)
    at activate (/tmp/vscode-extensions/vknabel.vscode-swift-development-environment@2.8.1/extension/out/src/clientMain.js:100:5)
    at PluginManagerExtImpl.<anonymous> (/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:429:87)
    at step (/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:47:23)
    at Object.next (/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:28:53)
    at /theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:18:12)" 
```

**OS and Theia version:**

ubuntu, chrome, 'latest'

**Comment by akosyakov** [comment]
If would be helpful if someone tries to find out what is the root cause.
