### ISSUE TITLE
[preferences] Error why trying to edit and save user preferences on Windows

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6349]
### Description
 
Try to adjust `"application.confirmExit`, it does not work reliably. Sometimes the editor remains dirty. Sometimes it proposes to save the dirty content twice. Also, it does not work at all if I open Theia with an empty workspace.

```
root ERROR Error: Model is disposed!
    at TextModel._assertNotDisposed (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/vs/editor/editor.main.js
:64777:23)
    at TextModel.getVersionId (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/vs/editor/editor.main.js:65012
:18)
    at MonacoEditorModel.get [as version] (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/25.bundle.js:225:3
1)
    at MonacoEditorModel.<anonymous> (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/25.bundle.js:543:62)
    at step (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/25.bundle.js:68:23)
    at Object.next (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/25.bundle.js:49:53)
    at fulfilled (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/25.bundle.js:40:58)
root ERROR Error: command 'monaco.editor.action.formatDocument' not found
    at StandaloneCommandService.executeCommand (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/vs/editor/edi
tor.main.js:125588:39)
    at MonacoCommandService.<anonymous> (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:366:79)
    at step (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:299:23)
    at Object.next (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:280:53)
    at file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:274:71
    at new Promise (<anonymous>)
    at push.../../packages/monaco/lib/browser/monaco-command-service.js.__awaiter (file:///C:/Users/kittaakos/dev/theia/
examples/electron/lib/29.bundle.js:270:12)
    at MonacoCommandService.push.../../packages/monaco/lib/browser/monaco-command-service.js.MonacoCommandService.execut
eCommand (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:357:16)
    at MonacoEditorProvider.<anonymous> (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:1283:68
)
    at step (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:1057:23)
root ERROR Error: command 'monaco.editor.action.formatDocument' not found
    at StandaloneCommandService.executeCommand (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/vs/editor/edi
tor.main.js:125588:39)
    at MonacoCommandService.<anonymous> (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:366:79)
    at step (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:299:23)
    at Object.next (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:280:53)
    at file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:274:71
    at new Promise (<anonymous>)
    at push.../../packages/monaco/lib/browser/monaco-command-service.js.__awaiter (file:///C:/Users/kittaakos/dev/theia/
examples/electron/lib/29.bundle.js:270:12)
    at MonacoCommandService.push.../../packages/monaco/lib/browser/monaco-command-service.js.MonacoCommandService.execut
eCommand (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:357:16)
    at MonacoEditorProvider.<anonymous> (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:1283:68
)
    at step (file:///C:/Users/kittaakos/dev/theia/examples/electron/lib/29.bundle.js:1057:23)
root INFO [nsfw-watcher: 9840] Stopped watching: c:\Users\kittaakos\dev\theia\.theia\settings.json
```

### Reproduction Steps

**OS and Theia version:**
Windows aac19caa1
**Diagnostics:**

**Comment by marechal-p** [comment]
The first error from your log seems to come from https://github.com/eclipse-theia/theia/blob/a2d89c83245cdb894d35135f23d51139e374a447/packages/monaco/src/browser/monaco-editor-model.ts#L428. The model is already disposed when the `willSaveModel` event is fired?

**Comment by tsmaeder** [comment]
@kittaakos do you know if this is Windows-specific?

**Comment by kittaakos** [comment]
> do you know if this is Windows-specific?

I did not see the error on macOS; let me try this quickly once more...

**Comment by tsmaeder** [comment]
Never mind, the error is in the browser, so it's relevant for Che anyway :-( I'm trying to understand if this is a critical bug. As I understand it, preference editing is generally broken for Windows users. Sounds bad to me.
