### ISSUE TITLE
[electron] [plugin] plugin host crashes with installed version of Theia

### ISSUE THREAD

**Issue by thegecko** [eclipse-theia/theia#6384]
### Description
I've not seen this issue specifically, but it may be a duplicate.

With an installed electron version of Theia (0.6) using the plugin system, it crashes with the following errors:

```
[2019-10-14T16:54:30.124] [ERROR] - [hosted-plugin: 64846] /Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:346
        throw errtion({
        ^

Error: There were no suitable editions for package [/Applications/theia.app/Contents/Resources/app/node_modules/getmac/package.json]
    at errtion (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/util.js:24:15)
    at requireEditions (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:346:15)
    at requireEditions (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:284:14)
    at Object.requirePackage (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:382:10)
    at Object.<anonymous> (/Applications/theia.app/Contents/Resources/app/node_modules/getmac/index.js:4:38)
    at Object.<anonymous> (/Applications/theia.app/Contents/Resources/app/node_modules/getmac/index.js:6:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
↳ Error: Skipping edition [coffeescript source code with require for modules] because its engines field was false
    at errtion (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/util.js:24:15)
    at requireEditions (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:310:25)
    at requireEditions (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:284:14)
    at Object.requirePackage (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:382:10)
    at Object.<anonymous> (/Applications/theia.app/Contents/Resources/app/node_modules/getmac/index.js:4:38)
    at Object.<anonymous> (/Applications/theia.app/Contents/Resources/app/node_modules/getmac/index.js:6:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
↳ Error: Skipped edition [coffeescript compiled for node.js >=0.10 with require for modules] at entry [/Applications/theia.app/Contents/Resources/app/node_modules/getmac/edition-node-0.10/index.js] because it failed to load
    at errtion (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/util.js:24:15)
    at loadEdition (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:150:11)
    at requireEdition (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:247:10)
    at requireEditions (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:302:16)
    at requireEditions (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:284:14)
    at Object.requirePackage (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:382:10)
    at Object.<anonymous> (/Applications/theia.app/Contents/Resources/app/node_modules/getmac/index.js:4:38)
    at Object.<anonymous> (/Applications/theia.app/Contents/Resources/app/node_modules/getmac/index.js:6:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
↳ Error: There were no suitable editions for package [/Applications/theia.app/Contents/Resources/app/node_modules/extract-opts/package.json]
    at errtion (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/util.js:24:15)
    at requireEditions (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:346:15)
    at requireEditions (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:284:14)
    at Object.requirePackage (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:382:10)
    at Object.<anonymous> (/Applications/theia.app/Contents/Resources/app/node_modules/extract-opts/index.js:3:38)
    at Object.<anonymous> (/Applications/theia.app/Contents/Resources/app/node_modules/extract-opts/index.js:5:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
↳ Error: Each edition must have its [description, directory, entry, engines] fields defined, yet all it had was [description, entry, directory, syntaxes]
    at errtion (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/util.js:24:15)
    at requireEdition (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:170:11)
    at requireEditions (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:302:16)
    at requireEditions (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:284:14)
    at Object.requirePackage (/Applications/theia.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:382:10)
    at Object.<anonymous> (/Applications/theia.app/Contents/Resources/app/node_modules/extract-opts/index.js:3:38)
    at Object.<anonymous> (/Applications/theia.app/Contents/Resources/app/node_modules/extract-opts/index.js:5:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
 []
[2019-10-14T16:54:30.132] [DEBUG] - [hosted-plugin: 64846] IPC exited []

```

We don't use coffeescript, so not sure where that comes from, but subsequent calls to the plugin yields:

```
[2019-10-14T16:54:30.166] [ERROR] - Uncaught Exception:  [ 'Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed' ]
[2019-10-14T16:54:30.166] [ERROR] - Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
```

Works fine in development :)

Any ideas around this problem would be helpful, perhaps from the che team?

Looks like it may be a problem with `editions`

**OS and Theia version:**
Mac OS: 10.14.5
Theia: 0.6
Electron: 4

**Comment by thegecko** [comment]
cc @benoitf

**Comment by thegecko** [comment]
I think this is an electron builder issue not honouring multiple versions of `editions`. Investigation ongoing....

**Comment by akosyakov** [comment]
@thegecko I don't know anyone managed to run the plugin system in the bundled electron application. @jankeromnes looking right now into it for one of our customers but with next version of Theia.

**Comment by benoitf** [comment]
well based on https://editions.bevry.me/#how-do-i-define-an-edition and https://github.com/bevry/getmac/blob/master/package.json#L60-L83 it seems it's not compliant

seems it's requiring an older `editions` https://github.com/bevry/editions/blob/v1.3.4/package.json

https://github.com/eclipse-theia/theia/blob/v0.6.0/yarn.lock#L3391-L3395

so yes I assume it's related to electron builder

**Comment by thegecko** [comment]
@benoitf I see `getmac` was introduced in https://github.com/eclipse-theia/theia/commit/4a54abb6741672d291af1919ec610a51fa4e7556 to create a unique machine id. Do you see a problem with removing it in favour of only using `uuid` ?

Alternatively, [macaddress](https://www.npmjs.com/package/macaddress) looks like a more popular library with no dependencies which could fix this pickle.

**Comment by benoitf** [comment]
@thegecko it was to have a uuid that was the same across restart.
https://www.npmjs.com/package/macaddress can be used if you can't sort it out with `getmac`
