### ISSUE TITLE
[travis] windows build failing due to ffmpeg check

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6399]
**Description**

Recently, the _Travis for Windows CI_ check has been failing due to the `ffmpeg` test determining if any codecs are present which are not permitted.

```
Downloaded ffmpeg shared library { version: "4.2.11", dist: "C:\Users\travis\build\eclipse-theia\theia\node_modules\electron\dist" }.
Successfully replaced "C:\Users\travis\build\eclipse-theia\theia\node_modules\electron\dist\ffmpeg.dll".
Error: function not found in shared library
    at exports.libffmpegCodecs (C:\Users\travis\build\eclipse-theia\theia\dev-packages\electron\electron-ffmpeg-lib.js:105:19)
    at main (C:\Users\travis\build\eclipse-theia\theia\dev-packages\electron\electron-codecs-test.js:56:20)
    at Object.<anonymous> (C:\Users\travis\build\eclipse-theia\theia\dev-packages\electron\electron-codecs-test.js:70:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
Error: "electron-codecs-test.js" exited with 127
    at ChildProcess.subprocess.once (C:\Users\travis\build\eclipse-theia\theia\dev-packages\electron\scripts\post-install.js:36:40)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
The command "THEIA_SKIP_NPM_PREPARE=1 yarn install --skip-integrity-check" failed and exited with 1 during .
Your build has been stopped.
```

**Additional Information**
- https://travis-ci.com/eclipse-theia/theia/jobs/246122954#L345-L361

**Comment by vince-fugnitto** [comment]
It looks to have been introduced as of https://github.com/eclipse-theia/theia/runs/253447960
- PR: https://github.com/eclipse-theia/theia/pull/6307

**Comment by thegecko** [comment]
Apologies for that. The PR was small, shall we revert until fixed? Especially as a CQ has now been requested for the electron upgrade?

**Comment by marechal-p** [comment]
I don't think this needs a revert, but we should definitely fix the ffmpeg tests. This means finding which function is now missing in the `ffmpeg.dll` file.

**Comment by kittaakos** [comment]
FYI: it is not only a Travis issue. It is not possible to build Theia on Windows currently without the `THEIA_ELECTRON_SKIP_REPLACE_FFMPEG=1` env variable.

**Comment by marechal-p** [comment]
Yes, because a patch wasn't supposed to go through if it did not pass CI. We should not allow Windows test suite to fail silently, and find what changed with ffmpeg on Windows when upgrading to Electron 5.

**Comment by marechal-p** [comment]
The Windows job on Appveyor used to mark the overall CI as failed on error... I don't know for Mac, but Windows shouldn't be silent IMO.

**Comment by vince-fugnitto** [comment]
I think with the inclusion of Travis on Windows and the removal of AppVeyor, the CI has become more stable so I wouldn't be opposed to setting the `allow_failures` to false for all **three** operating systems.

**Comment by vince-fugnitto** [comment]
@marechal-p also it looks like the `absoultePath` when getting the codecs may be incorrectly computed and for that reason it cannot find the method.

**Comment by vince-fugnitto** [comment]
> > `allow_failures` to false for all **three**
> 
> Has anyone changed this?

Do you believe we should enforce that each operating system cannot fail their CI?
