### ISSUE TITLE
Enter key not working in Latex Workshop extension usage

### ISSUE THREAD

**Issue by dannaf** [eclipse-theia/theia#6408]
### Description
I encounter an issue where the enter key does not work inside the editor while using the [Latex Workshop vscode extension, v8.2.0](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop).

### Reproduction Steps
Launch Theia browser example
Load the plugin via the `Deploy plugin by id` command as described in the footnote [here](https://github.com/eclipse-theia/theia/wiki/Testing-VS-Code-Extensions).
Open a `.tex` file in the editor
Type some text, e.g. `\documentclass{article}`
Press enter, and observe lack of new line (and after some time, the error listed below in the server)

**OS and Theia version:**
Theia source 0.11.0 [5cd87b](https://github.com/eclipse-theia/theia/tree/5cd87bfad4a6187a797dee138120be0bca992521)
Theia backend: Ubuntu 18.04 LTS
Theia frontend: Windows 10, Chrome 77.0.3865.120, 

**Diagnostics:** 
The following error is printed repeatedly, some time after attempting to make a new line in the editor while a `.tex` file is open, by pressing enter:

```
root ERROR [hosted-plugin: 11730] Promise rejection not handled in one second: Error: The command 'type' cannot be executed. There are no active handlers available for the command. (args: [{"source":"keyboard","text":"\n"}])
root ERROR [hosted-plugin: 11730] With stack trace: Error: The command 'type' cannot be executed. There are no active handlers available for the command. (args: [{"source":"keyboard","text":"\n"}])
    at CommandRegistry.<anonymous> (https://mydomainname.com/bundle.js:112917:31)
    at step (https://mydomainname.com/bundle.js:112693:23)
    at Object.next (https://mydomainname.com/bundle.js:112674:53)
    at fulfilled (https://mydomainname/bundle.js:112665:58)
```

Prior to that the following printed while loading the plugin:

```
root INFO unzipping the VS Code extension 'James_Yu_latex_workshop.vsix' to directory: /tmp/vscode-unpacked/James_Yu_latex_workshop.vsix
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/James_Yu_latex_workshop.vsix
root INFO Resolved "vscode:extension/James-Yu.latex-workshop" to a VS Code extension "latex-workshop@8.2.0" with engines: { vscode: '^1.34.0' }
root INFO Deploying backend plugin "latex-workshop@8.2.0" from "/tmp/vscode-unpacked/James_Yu_latex_workshop.vsix/extension/out/src/main.js"
root INFO [hosted-plugin: 11730] PLUGIN_HOST(11730) starting instance
root INFO [f1fc959e-b059-4c14-97a3-5e386b82060b] Sync of 1 plugin took: 58.330000028945506 ms
root WARN Error: 'cpp' language is remapped from 'source.cpp' to 'source.cpp.embedded.latex' scope
    at TextmateRegistry.push.../../packages/monaco/lib/browser/textmate/textmate-registry.js.TextmateRegistry.mapLanguageIdToTextmateGrammar (https://mydomainname.com/35.bundle.js:815:26)
    at https://mydomainname.com/89.bundle.js:8506:125
    at pushContribution (https://mydomainname.com/89.bundle.js:8381:32)
    at _loop_3 (https:/mydomainname.com/89.bundle.js:8506:21)
    at PluginContributionHandler.push.../../packages/plugin-ext/lib/main/browser/plugin-contribution-handler.js.PluginContributionHandler.handleContributions (https://mydomainname.com/89.bundle.js:8517:21)
    at _loop_2 (https://mydomainname.com/89.bundle.js:1797:63)
    at HostedPluginSupport.push.../../packages/plugin-ext/lib/hosted/browser/hosted-plugin.js.HostedPluginSupport.loadContributions (https://mydomainname.com/89.bundle.js:1818:17)
    at HostedPluginSupport.<anonymous> (https://mydomainname.com/89.bundle.js:1667:52)
    at step (https://mydomainname.com/89.bundle.js:1502:23)
    at Object.next (https://mydomainname.com/89.bundle.js:1483:53)
root WARN Could not register keybinding:
  {"command":"latex-workshop.shortcut.textsubscript","keybinding":"ctrl+l ctrl+oem_minus"}
Error: Unrecognized key 'oem_minus' in 'ctrl+oem_minus'
root INFO [f1fc959e-b059-4c14-97a3-5e386b82060b][james-yu.latex-workshop]: Loaded contributions.
root INFO [f1fc959e-b059-4c14-97a3-5e386b82060b] Load contributions of 1 plugin took: 228.7550000473857 ms
root WARN Invalid embedded language found at scope source.asymptote: <<0>>
root WARN Invalid embedded language found at scope source.dot: <<0>>
root WARN Invalid embedded language found at scope source.gnuplot: <<0>>
root WARN Invalid embedded language found at scope source.js: <<0>>
root WARN Invalid embedded language found at scope source.scala: <<0>>
root WARN Invalid embedded language found at scope text.xtml: <<0>>
root WARN Invalid embedded language found at scope source.yaml: <<0>>
root INFO [hosted-plugin: 11730] PLUGIN_HOST(11730): PluginManagerExtImpl/init()
root INFO [hosted-plugin: 11730] PLUGIN_HOST(11730): initializing(latex-workshop@8.2.0 with /home/project/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
root INFO [hosted-plugin: 11730] PLUGIN_HOST(11730): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/James_Yu_latex_workshop.vsix/extension/out/src/main.js)
root INFO [f1fc959e-b059-4c14-97a3-5e386b82060b][james-yu.latex-workshop]: Started plugin.
root INFO [f1fc959e-b059-4c14-97a3-5e386b82060b] Start of 1 plugin took: 1010.939999949187 ms
```

**Comment by dannaf** [comment]
Any advice towards this?  Obviously LaTeX cannot be used at all effectively without the enter key... =/

I also experienced that with the [LaTeX Preview extension](https://marketplace.visualstudio.com/items?itemName=ajshort.latex-preview) loaded via `Load Plugin by Id` none of the typing keys worked in the Editor, not even the non-enter character keys...

**Comment by akosyakov** [comment]
@dannaf Could you try against this PR: https://github.com/eclipse-theia/theia/pull/5590?

**Comment by dannaf** [comment]
Same problem still..

**Comment by dannaf** [comment]
Any help on this would be appreciated.

Tried it again now this time through a docker container of `theiaide/theia-full` and it still fails in the same way.  (Docker is running on Ubuntu 18.04 and I'm accessing theia via Chrome on a fresh Windows 10 install).

When deploying the container it warns the following.  (I loaded the plugin via `vscode:extension/James-Yu.latex-workshop` in `Deploy plugin by id`).

```
theia-test_1               | root INFO unzipping the VS Code extension 'James_Yu_latex_workshop.vsix' to directory: /tmp/vscode-unpacked/James_Yu_latex_workshop.vsix
theia-test_1               | root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/James_Yu_latex_workshop.vsix
theia-test_1               | root INFO Resolved "vscode:extension/James-Yu.latex-workshop" to a VS Code extension "latex-workshop@8.5.0" with engines: { vscode: '^1.34.0' }
theia-test_1               | root INFO Deploying backend plugin "latex-workshop@8.5.0" from "/tmp/vscode-unpacked/James_Yu_latex_workshop.vsix/extension/out/src/main.js"
theia-test_1               | root INFO [7e7c9254-6c83-4807-9f25-063b09fdc092] Sync of 1 plugin took: 98.14000001642853 ms
theia-test_1               | root WARN Error: 'cpp' language is remapped from 'source.cpp' to 'source.cpp.embedded.latex' scope
theia-test_1               |     at e.mapLanguageIdToTextmateGrammar (https://test.com/bundle.js:14:199304)
theia-test_1               |     at https://test.com/bundle.js:14:531278
theia-test_1               |     at x (https://test.com/bundle.js:14:529003)
theia-test_1               |     at N (https://test.com/bundle.js:14:531207)
theia-test_1               |     at e.handleContributions (https://test.com/bundle.js:14:531754)
theia-test_1               |     at s (https://test.com/bundle.js:8:373983)
theia-test_1               |     at e.loadContributions (https://test.com/bundle.js:8:374464)
theia-test_1               |     at e.<anonymous> (https://test.com/bundle.js:8:372032)
theia-test_1               |     at https://test.com/bundle.js:8:367623
theia-test_1               |     at Object.next (https://test.com/bundle.js:8:367728)
theia-test_1               | root WARN Could not register keybinding:
theia-test_1               |   {"command":"latex-workshop.shortcut.textsubscript","keybinding":"ctrl+l ctrl+oem_minus"}
theia-test_1               | Error: Unrecognized key 'oem_minus' in 'ctrl+oem_minus'
theia-test_1               | root INFO [7e7c9254-6c83-4807-9f25-063b09fdc092][james-yu.latex-workshop]: Loaded contributions.
theia-test_1               | root INFO [7e7c9254-6c83-4807-9f25-063b09fdc092] Load contributions of 1 plugin took: 156.844999990426 ms
theia-test_1               | root INFO [hosted-plugin: 88] PLUGIN_HOST(88) starting instance
theia-test_1               | root INFO [hosted-plugin: 88] PLUGIN_HOST(88): PluginManagerExtImpl/init()
theia-test_1               | root INFO [hosted-plugin: 88] PLUGIN_HOST(88): initializing(latex-workshop@8.5.0 with /home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
theia-test_1               | root INFO [7e7c9254-6c83-4807-9f25-063b09fdc092][james-yu.latex-workshop]: Started plugin.
theia-test_1               | root INFO [7e7c9254-6c83-4807-9f25-063b09fdc092] Start of 1 plugin took: 233.36499999277294 ms
```

Then I made a file `test.tex` and the enter key does not work in it through the Editor.  It  gives the following error some time later:

```
theia-test_1               | root ERROR [hosted-plugin: 88] Promise rejection not handled in one second: Error: Command with id 'type' is not registered. , reason: Error: Command with id 'type' is not registered.
theia-test_1               | root ERROR [hosted-plugin: 88] With stack trace: Error: Command with id 'type' is not registered.
theia-test_1               |     at e.<anonymous> (https://test.com/bundle.js:125:1156410)
theia-test_1               |     at https://test.com/bundle.js:125:1154412
theia-test_1               |     at Object.next (https://test.com/bundle.js:125:1154517)
theia-test_1               |     at https://test.com/bundle.js:125:1153429
theia-test_1               |     at new Promise (<anonymous>)
theia-test_1               |     at r (https://test.com/bundle.js:125:1153203)
theia-test_1               |     at e.$executeCommand (https://test.com/bundle.js:125:1156281)
theia-test_1               |     at e.doInvokeHandler (https://test.com/bundle.js:1:901786)
theia-test_1               |     at e.invokeHandler (https://test.com/bundle.js:1:901519)
theia-test_1               |     at e.receiveRequest (https://test.com/bundle.js:1:900807)
```

**Comment by akosyakov** [comment]
It looks like a command is not registered with `type` id. Someone can have a look what it supposed to do in VS Code and implement accordingly in the plugin system.

**Comment by dannaf** [comment]
@vince-fugnitto can you please comment if you had the Enter key working when you tested it [here](https://github.com/eclipse-theia/theia/issues/5794#issuecomment-515235227), and if so please provide a reproducible setup

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto can you please comment if you had the Enter key working when you tested it [here](https://github.com/eclipse-theia/theia/issues/5794#issuecomment-515235227), and if so please provide a reproducible setup

I've verified it and I notice that the issue <kbd>ENTER</kbd> key does not work (to create newlines).
It did work however when executing <kbd>CMD</kbd>+<kbd>ENTER</kbd>.

**Comment by Amandarg** [comment]
Yeah, the enter key does not work for me. But shift + enter does on a mac.

**Comment by dannaf** [comment]
This issue is outdated and seems to have meanwhile solved itself.  The Enter key now works for me in the current [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop) vscode extension (installed at runtime in [Theia IDE](https://github.com/eclipse-theia/theia-blueprint) in the browser, followed by a page refresh after installing the extension).  It works even without `cmd+Enter` as mentioned in the comment above.

**Comment by dannaf** [comment]
Never mind to me closing this issue &mdash; this issue still persists.  In fact, it is even worse than I previously realized, because even with `cmd+Enter` as @vince-fugnitto [suggested above](https://github.com/eclipse-theia/theia/issues/6408#issuecomment-574812834) the behavior is not correct: `cmd+Enter` does not create a new line _where the cursor is_, at least not if the cursor is in the middle of a line.  Thus a new line cannot be made _within_ an existing line, it seems.  `Cmd+Enter` only appears to be _adding_ a new line after the existing line, with complete disregard to the cursor position.

I may have narrowed the issue a bit.  Earlier today when I closed this issue I thought it was working because when I briefly tried a fresh installation of the extension on Theia IDE in the browser the Editor portion _seemed_ to be working.  (The Viewer, however,  is completely broken, and I made an issue for that here: https://github.com/eclipse-theia/theia/issues/13522.)  Now later I tried to do actual writing and it was initially successful until I changed the `Editor: Word Wrap` setting from `off` to `on`.  Then the `Enter` key malfunction began, and it persists for me now even after I returned the `Editor: Word Wrap` setting back to `off`.

With this present situation this extension is completely unusable in my opinion, unfortunately, and Theia IDE in the browser is not currently able to properly replace vscode (or Overleaf) for LaTeX use with sophisticated IDE features.  It is unfortunate enough that the Viewer does not work (https://github.com/eclipse-theia/theia/issues/13522), which is the first step to benefiting from the highly desired [SyncTeX feature](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop#:~:text=Direct%20and%20reverse%20SyncTeX) of this vscode extension.  But without the Enter key, which this present issue is about, the extension is completely unusable.

**Comment by dannaf** [comment]
I guess refreshing the browser page can be a temporary workaround that can keep this extension somewhat usable for now.  Refreshing seems to reset the Enter key issue while retaining the new `Editor: Word Wrap` setting.  So it can be used to 'undo' the broken Enter key issue that persisted after I returned the setting to `off`, by refreshing after returning the setting to `off`.  Or, it can be used to keep the setting as `on` and regain the functionality of the Enter key.

So all-in-all I currently have a hacky half-working LaTeX Workshop extension on the Theia IDE in the browser: the Viewer is completely broken (https://github.com/eclipse-theia/theia/issues/13522) but I can benefit from the Editor features (e.g., syntax highlighting, error parsing, and auto build on save, etc.) if I refresh the browser window after changing the word wrap setting.  It's not ideal, but it's something.
