### ISSUE TITLE
[electron] I am still hitting codec test failures on Windows

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6433]
### Description
 
This happens from time to time when building the electron example from source on Windwos. I know, I can do `git clean -ffxqd` to fix the problem, but then I have an additional 15 minutes build penalty on my super slow Windows image. It would be great to figure out what's causing the problem and fix it.

```
error C:\Users\kittaakos\dev\theia\node_modules\@theia\electron: Command failed.
Exit code: 127
Command: node scripts/post-install.js
Arguments:
Directory: C:\Users\kittaakos\dev\theia\node_modules\@theia\electron
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | win32 | x64
gyp info spawn C:\Users\kittaakos\.windows-build-tools\python27\python.EXE
gyp info spawn args [ 'C:\\Users\\kittaakos\\dev\\theia\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\kittaakos\\dev\\theia\\node_modules\\@theia\\electron\\native\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\kittaakos\\dev\\theia\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\kittaakos\\.node-gyp\\10.16.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\kittaakos\\.node-gyp\\10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\kittaakos\\dev\\theia\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\kittaakos\\.node-gyp\\10.16.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\kittaakos\\dev\\theia\\node_modules\\@theia\\electron\\native',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\kittaakos\\dev\\theia\\node_modules\\@theia\\electron\\native\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ffmpeg.c
  win-ffmpeg.c
  win_delay_load_hook.cc
     Creating library C:\Users\kittaakos\dev\theia\node_modules\@theia\electron\native\build\Release\ffmpeg.lib and obje
ct C:\Users\kittaakos\dev\theia\node_modules\@theia\electron\native\build\Release\ffmpeg.exp
  Generating code
  All 6 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  ffmpeg.vcxproj -> C:\Users\kittaakos\dev\theia\node_modules\@theia\electron\native\build\Release\\ffmpeg.node
gyp info ok
Error: function not found in shared library
    at exports.libffmpegCodecs (C:\Users\kittaakos\dev\theia\dev-packages\electron\electron-ffmpeg-lib.js:105:19)
    at main (C:\Users\kittaakos\dev\theia\dev-packages\electron\electron-codecs-test.js:56:20)
    at Object.<anonymous> (C:\Users\kittaakos\dev\theia\dev-packages\electron\electron-codecs-test.js:70:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
Error: "electron-codecs-test.js" exited with 127
    at ChildProcess.subprocess.once (C:\Users\kittaakos\dev\theia\dev-packages\electron\scripts\post-install.js:36:40)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
```

### Reproduction Steps

**OS and Theia version:**
Windows 10, aebea67ab

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
cc @marechal-p

**Comment by kittaakos** [comment]
Related: https://github.com/eclipse-theia/theia/issues/6399?

**Comment by kittaakos** [comment]
> I know, I can do `git clean -ffxqd` to fix the problem

Apparently, I was wrong. I cannot build Theia on Windows anymore. Are there any dirty hacks to disable the codec tests?

```
$ git clean -ffxqd && git reset --hard && git rev-parse --short HEAD && yarn
Checking out files: 100% (1782/1782), done.
HEAD is now at f255f5a8c feat(OutputChannelRegistry): introduce interface and add it into rpc
f255f5a8c
yarn install v1.16.0
$ node-gyp install

C:\Users\kittaakos\dev\theia>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node
-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" install )  else (node "" install )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | win32 | x64
gyp http GET https://nodejs.org/download/release/v10.16.0/node-v10.16.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.16.0/node-v10.16.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.16.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v10.16.0/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v10.16.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v10.16.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.16.0/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v10.16.0/win-x64/node.lib
10.16.0
gyp info ok
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning monaco-languageclient@0.10.2: The engine "vscode" appears to be invalid.
warning vscode-languageclient@5.3.0-next.6: The engine "vscode" appears to be invalid.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
warning "workspace-aggregator-47fa361b-29f0-44a7-91ce-7e576a3d9f68 > @theia/application-manager > font-awesome-webpack@0
.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-47fa361b-29f0-44a7-91ce-7e576a3d9f68 > @theia/debug > requestretry@3.1.0" has unmet peer d
ependency "request@2.*.*".
warning "workspace-aggregator-47fa361b-29f0-44a7-91ce-7e576a3d9f68 > @theia/messages > react-perfect-scrollbar@1.5.3" ha
s unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-47fa361b-29f0-44a7-91ce-7e576a3d9f68 > @theia/messages > react-perfect-scrollbar@1.5.3" ha
s unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-47fa361b-29f0-44a7-91ce-7e576a3d9f68 > @theia/scm > react-autosize-textarea@7.0.0" has unm
et peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-47fa361b-29f0-44a7-91ce-7e576a3d9f68 > @theia/scm > react-autosize-textarea@7.0.0" has unm
et peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-47fa361b-29f0-44a7-91ce-7e576a3d9f68 > @theia/application-manager > font-awesome-webpack >
 less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
[6/14] ⠠ @theia/node-pty
[10/14] ⠠ vscode-ripgrep
[8/14] ⠠ oniguruma
[9/14] ⠠ @theia/electron
error C:\Users\kittaakos\dev\theia\node_modules\@theia\electron: Command failed.
Exit code: 127
Command: node scripts/post-install.js
Arguments:
Directory: C:\Users\kittaakos\dev\theia\node_modules\@theia\electron
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | win32 | x64
gyp info spawn C:\Users\kittaakos\.windows-build-tools\python27\python.EXE
gyp info spawn args [ 'C:\\Users\\kittaakos\\dev\\theia\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\kittaakos\\dev\\theia\\node_modules\\@theia\\electron\\native\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\kittaakos\\dev\\theia\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\kittaakos\\.node-gyp\\10.16.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\kittaakos\\.node-gyp\\10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\kittaakos\\dev\\theia\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\kittaakos\\.node-gyp\\10.16.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\kittaakos\\dev\\theia\\node_modules\\@theia\\electron\\native',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\kittaakos\\dev\\theia\\node_modules\\@theia\\electron\\native\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ffmpeg.c
  win-ffmpeg.c
  win_delay_load_hook.cc
     Creating library C:\Users\kittaakos\dev\theia\node_modules\@theia\electron\native\build\Release\ffmpeg.lib and obje
ct C:\Users\kittaakos\dev\theia\node_modules\@theia\electron\native\build\Release\ffmpeg.exp
  Generating code
  All 6 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  ffmpeg.vcxproj -> C:\Users\kittaakos\dev\theia\node_modules\@theia\electron\native\build\Release\\ffmpeg.node
Downloaded ffmpeg shared library { version: "4.2.11", dist: "C:\Users\kittaakos\dev\theia\node_modules\electron\dist" }.
Successfully replaced "C:\Users\kittaakos\dev\theia\node_modules\electron\dist\ffmpeg.dll".
gyp info ok
Error: function not found in shared library
    at exports.libffmpegCodecs (C:\Users\kittaakos\dev\theia\dev-packages\electron\electron-ffmpeg-lib.js:105:19)
    at main (C:\Users\kittaakos\dev\theia\dev-packages\electron\electron-codecs-test.js:56:20)
    at Object.<anonymous> (C:\Users\kittaakos\dev\theia\dev-packages\electron\electron-codecs-test.js:70:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
Error: "electron-codecs-test.js" exited with 127
    at ChildProcess.subprocess.once (C:\Users\kittaakos\dev\theia\dev-packages\electron\scripts\post-install.js:36:40)
```

**Comment by vince-fugnitto** [comment]
> > I know, I can do `git clean -ffxqd` to fix the problem
> 
> Apparently, I was wrong. I cannot build Theia on Windows anymore. Are there any dirty hacks to disable the codec tests?

Does the following still work to disable the tests? https://github.com/eclipse-theia/theia/issues/5787#issuecomment-515972732

**Comment by kittaakos** [comment]
> Does the following still work to disable the tests? [#5787 (comment)](https://github.com/eclipse-theia/theia/issues/5787#issuecomment-515972732)

Great, thank you! I always forget about this env variable.

Workaround:
```
kittaakos@DESKTOP-VJRAMKC MINGW64 ~/dev/theia (master)
$ THEIA_ELECTRON_SKIP_REPLACE_FFMPEG=1 yarn
```

**Comment by vince-fugnitto** [comment]
> > Does the following still work to disable the tests? [#5787 (comment)](https://github.com/eclipse-theia/theia/issues/5787#issuecomment-515972732)
> 
> Great, thank you! I always forget about this env variable.
> 
> Workaround:
> 
> ```
> kittaakos@DESKTOP-VJRAMKC MINGW64 ~/dev/theia (master)
> $ THEIA_ELECTRON_SKIP_REPLACE_FFMPEG=1 yarn
> ```

Perhaps it's worthwhile to document it somewhere along with other `env` variables if it is 
not already done so.

**Comment by kittaakos** [comment]
I am going to close this in favor of #6399.
