### ISSUE TITLE
[macOS] Cannot build Theia on macOS 10.15.1 (19B88)

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6524]
### Description
 
I updated to latest Catalina, 10.15.1, and the build does not work anymore.
```
akos.kitta@Akoss-MacBook-Pro theia % git clean -ffxqd && git rev-parse --short HEAD && node -v && yarn -v && python --version && yarn
2f3b2c353
v10.15.3
1.19.1
Python 2.7.15
yarn install v1.19.1
$ node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | darwin | x64
gyp http GET https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
10.15.3
gyp info ok 
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
warning monaco-languageclient@0.10.2: The engine "vscode" appears to be invalid.
warning vscode-languageclient@5.3.0-next.6: The engine "vscode" appears to be invalid.
[4/5] 🔗  Linking dependencies...
warning " > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
warning "workspace-aggregator-52c851b8-24a9-4fe9-9893-60d4f999fa7b > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-52c851b8-24a9-4fe9-9893-60d4f999fa7b > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-52c851b8-24a9-4fe9-9893-60d4f999fa7b > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-52c851b8-24a9-4fe9-9893-60d4f999fa7b > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-52c851b8-24a9-4fe9-9893-60d4f999fa7b > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-52c851b8-24a9-4fe9-9893-60d4f999fa7b > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-52c851b8-24a9-4fe9-9893-60d4f999fa7b > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
warning Workspaces can only be enabled in private projects.
[5/5] 🔨  Building fresh packages...
[6/15] ⠁ nsfw
[7/15] ⠁ @theia/node-pty
[3/15] ⠁ dtrace-provider
[4/15] ⠁ electron
error /Users/akos.kitta/git/theia/node_modules/native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/akos.kitta/git/theia/node_modules/native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.4
gyp info using node@10.15.3 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [ '/Users/akos.kitta/git/theia/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/akos.kitta/git/theia/node_modules/native-keymap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/akos.kitta/git/theia/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/akos.kitta/Library/Caches/node-gyp/10.15.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/akos.kitta/Library/Caches/node-gyp/10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/akos.kitta/git/theia/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/akos.kitta/Library/Caches/node-gyp/10.15.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/akos.kitta/git/theia/node_modules/native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/akos.kitta/git/theia/node_modules/electron-rebuild/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Users/akos.kitta/.nvm/versions/node/v10.15.3/bin/node" "/Users/akos.kitta/git/theia/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/akos.kitta/git/theia/node_modules/native-keymap




^C
akos.kitta@Akoss-MacBook-Pro theia % 
akos.kitta@Akoss-MacBook-Pro theia % 
akos.kitta@Akoss-MacBook-Pro theia % 
```

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by kittaakos** [comment]
Here is a possible solution: https://github.com/nodejs/node-gyp/issues/1927#issuecomment-548234995
