### ISSUE TITLE
Theia yang diagram does not work

### ISSUE THREAD

**Issue by RimShao** [eclipse-theia/theia#6588]
Hi Jan, Sven,

Recently we found Theia yang diagram does not work, it just open one empty diagram window.

there is no relevant console log from chrome we could analyze.

And I try to exclude our own application yang-extension from package.json, it does not make any change to the diagram feature.

Is this a know issue or can you give some hint/clew how to proceed the analysis?

Thanks.
[package.json.txt](https://github.com/eclipse-theia/theia/files/3868584/package.json.txt)

**Comment by akosyakov** [comment]
cc @JanKoehnlein

**Comment by kittaakos** [comment]
It seems to be a sprotty issue. I did the following with the attached `package.json` as no `scripts` were defined:
 - `yarn`,
 - `./node_modules/.bin/theia build`, and
 - `./node_modules/.bin/theia start`,

Then I opened [`augtest.yang`](https://github.com/theia-ide/yang-lsp/blob/master/yang-lsp/io.typefox.yang.ide/src/test/resources/good/augtest.yang) with `Open With` > `Yang Diagram` and I got the following error:

```
oot ERROR Yang: 

root INFO Registering scopes for language: yang.
root INFO The scopes have been successfully registered for yang.
root ERROR Yang: Nov 20, 2019 5:22:50 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "diagram/accept",
  "params": {
    "clientId": "yang-diagram_0",
    "action": {
      "kind": "computedBounds",
      "revision": 1,
      "bounds": [
        {
          "elementId": "augtest:at-label"
        },
        {
          "elementId": "augtest:at-expand"
        },
        {
          "elementId": "augtest:at-heading"
        },
        {
          "elementId": "augtest:at-node-header-tag-text"
        },
        {
          "elementId": "augtest:at-node-header-tag"
        },
        {
          "elementId": "augtest:at-node-header-header-label"
        },
        {
          "elementId": "augtest:at-node-header"
        },
        {
          "elementId": "augtest:at-node"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-container-inner-header-tag-text"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-container-inner-header-tag"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-container-inner-header-header-label"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-container-inner-header"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-container-inner-foo"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-container-inner-compartment"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-container-inner"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-header-tag-text"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-header-tag"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-header-header-label"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-header"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-compartment"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill-outer/inner-augmentation-header-tag-text"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill-outer/inner-augmentation-header-tag"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill-outer/inner-augmentation-header-header-label"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill-outer/inner-augmentation-header"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill-outer/inner-augmentation-bar"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill-outer/inner-augmentation-compartment"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill-outer/inner-augmentation"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill-heading-label"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill-heading"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-header-tag-text"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-header-tag"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-header-header-label"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-header"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-compartment"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-header-tag-text"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-header-tag"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-header-header-label"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-header"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-compartment"
        },
        {
          "elementId": "augtest:at-node-grouping-foobar"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-heading-label"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-heading"
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill"
        },
        {
          "elementId": "augtest:at"
        }
      ],
      "alignments": [
        {
          "elementId": "augtest:at-label",
          "newAlignment": {
            "x": 0.0,
            "y": 15.203125
          }
        },
        {
          "elementId": "augtest:at-node-header-tag-text",
          "newAlignment": {
            "x": 0.0,
            "y": 17.609375
          }
        },
        {
          "elementId": "augtest:at-node-header-header-label",
          "newAlignment": {
            "x": 0.0,
            "y": 15.203125
          }
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-container-inner-header-tag-text",
          "newAlignment": {
            "x": 0.0,
            "y": 17.609375
          }
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-container-inner-header-header-label",
          "newAlignment": {
            "x": 0.0,
            "y": 15.203125
          }
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-container-inner-foo",
          "newAlignment": {
            "x": 0.0,
            "y": 11.609375
          }
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-header-tag-text",
          "newAlignment": {
            "x": 0.0,
            "y": 17.609375
          }
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-container-outer-header-header-label",
          "newAlignment": {
            "x": 0.0,
            "y": 15.203125
          }
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill-outer/inner-augmentation-header-tag-text",
          "newAlignment": {
            "x": 0.109375,
            "y": 17.609375
          }
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill-outer/inner-augmentation-header-header-label",
          "newAlignment": {
            "x": 0.0,
            "y": 15.203125
          }
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill-outer/inner-augmentation-bar",
          "newAlignment": {
            "x": 0.0,
            "y": 11.609375
          }
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-uses foobar-pill-heading-label",
          "newAlignment": {
            "x": 0.0,
            "y": 15.609375
          }
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-input-header-tag-text",
          "newAlignment": {
            "x": 0.0,
            "y": 11.609375
          }
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-header-tag-text",
          "newAlignment": {
            "x": 0.0,
            "y": 17.609375
          }
        },
        {
          "elementId": "augtest:at-node-grouping-foobar-header-header-label",
          "newAlignment": {
            "x": 0.0,
            "y": 15.203125
          }
        },
        {
          "elementId": "augtest:at-node-rpc agoj-pill-heading-label",
          "newAlignment": {
            "x": 0.0,
            "y": 15.609375
          }
        }
 
root ERROR Yang:      ]
    }
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
        at org.eclipse.xtext.ide.server.LanguageServerImpl.notify(LanguageServerImpl.java:953)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:160)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
        at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.consume(ReflectiveMessageValidator.java:76)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
        ... 14 more
Caused by: java.lang.NullPointerException
        at io.typefox.sprotty.api.LayoutUtil.applyBounds(LayoutUtil.java:39)
        at io.typefox.sprotty.api.DefaultDiagramServer.handle(DefaultDiagramServer.java:343)
        at io.typefox.sprotty.api.DefaultDiagramServer.accept(DefaultDiagramServer.java:298)
        at io.typefox.sprotty.api.DefaultDiagramServer.accept(DefaultDiagramServer.java:21)
        at io.typefox.sprotty.server.xtext.DiagramLanguageServerExtension.accept(DiagramLanguageServerExtension.java:173)
        ... 19 more
```

**Comment by JanKoehnlein** [comment]
Here is what happens:
- The master state works as is thanks to the `yarn.lock` file (you can easily verify this with Gitpod)
- You cannot just add arbitrary Theia extensions with the bare `next` version qualifier. It will pull the most current `next-xxx` which is different from the one that's nailed down for the existing extensions in the `yarn.lock` file. `yarn` will then try some best effort to get a more or less valid config by pulling newer `next` releases for some dependencies. This caused an incompatible version of `sprotty-theia` to be pulled. 
- Instead you should explicitly specify `next-xxx` releases of the newly added extensions to match the existing ones in the `yarn.lock`. I'll add a PR for that.
- Theia has had eight breaking releases in the meantime and sprotty one (including the move to Eclipse and a complete namespace change for the server part). To benefit from the improvements and fixes that have been added in the meantime, it might be time to migrate to newer versions.

**Comment by JanKoehnlein** [comment]
Continued in yangster
