### ISSUE TITLE
[process] ERROR TypeError [ERR_INVALID_ARG_TYPE]: The "err" argument must be of type number. Received type undefined

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6654]
### Description
 

I have the changes from https://github.com/eclipse-theia/theia/pull/6595, I have a LS running in the electron-based application. The error happens when I close the app. See here: https://github.com/eclipse-theia/theia/pull/6595#discussion_r351699362

```
root INFO Changed application state from 'ready' to 'closing_window'.
root INFO >>> Storing the layout...
root INFO <<< The layout has been successfully stored.
root ERROR TypeError [ERR_INVALID_ARG_TYPE]: The "err" argument must be of type number. Received type undefined
    at validateNumber (internal/validators.js:130:11)
    at Object.getSystemErrorName (util.js:1435:3)
    at errnoException (internal/errors.js:303:21)
    at ChildProcess.kill (internal/child_process.js:430:26)
    at Object.<anonymous> (C:\Users\kittaakos\dev\my-project\node_modules\@theia\core\lib\node\messaging\ipc-connect
ion-provider.js:55:101)
    at Object.disposable.dispose (C:\Users\kittaakos\dev\my-project\node_modules\@theia\core\lib\common\disposable.j
s:95:13)
    at DisposableCollection.dispose (C:\Users\kittaakos\dev\my-project\node_modules\@theia\core\lib\common\disposabl
e.js:72:40)
    at DisposableCollection.disposable.dispose (C:\Users\kittaakos\dev\my-project\node_modules\@theia\core\lib\commo
n\disposable.js:95:13)
    at DisposableCollection.dispose (C:\Users\kittaakos\dev\my-project\node_modules\@theia\core\lib\common\disposabl
e.js:72:40)
    at FileSystemWatcherServerClient.dispose (C:\Users\kittaakos\dev\my-project\node_modules\@theia\filesystem\lib\n
ode\filesystem-watcher-client.js:55:24)
root INFO >>> Disposing my service...
root INFO <<< Disposed my service.
root ERROR TypeError [ERR_INVALID_ARG_TYPE]: The "err" argument must be of type number. Received type undefined
    at validateNumber (internal/validators.js:130:11)
    at Object.getSystemErrorName (util.js:1435:3)
    at errnoException (internal/errors.js:303:21)
    at ChildProcess.kill (internal/child_process.js:430:26)
    at RawProcess.kill (C:\Users\kittaakos\dev\my-project\node_modules\@theia\process\lib\node\raw-process.js:137:26
)
    at C:\Users\kittaakos\dev\my-project\node_modules\@theia\languages\lib\node\language-server-contribution.js:135:
151
    at Object.dispose (C:\Users\kittaakos\dev\my-project\node_modules\vscode-ws-jsonrpc\lib\server\connection.js:31:
24)
    at Object.clientConnection.onClose [as dispose] (C:\Users\kittaakos\dev\my-project\node_modules\vscode-ws-jsonrp
c\lib\server\connection.js:12:53)
    at DisposableCollection.dispose (C:\Users\kittaakos\dev\my-project\node_modules\vscode-ws-jsonrpc\lib\disposable
.js:15:36)
    at reader.onClose (C:\Users\kittaakos\dev\my-project\node_modules\vscode-ws-jsonrpc\lib\server\connection.js:18:
41)
Done in 363.54s.
```

Can you please look into this @marechal-p?

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
@marechal-p Could you have a look please?

**Comment by marechal-p** [comment]
The following 3 stack items make me think that this is not related to my change, since it comes from `ipc-connection-provider`, that uses bare child processes:

```
    at ChildProcess.kill (internal/child_process.js:430:26)
    at Object.<anonymous> (C:\Users\kittaakos\dev\my-project\node_modules\@theia\core\lib\node\messaging\ipc-connect
ion-provider.js:55:101)
    at Object.disposable.dispose (C:\Users\kittaakos\dev\my-project\node_modules\@theia\core\lib\common\disposable.j
s:95:13)
```

https://github.com/eclipse-theia/theia/blob/87df21b291883ad46dc00d53131fab109a6fbda5/packages/core/src/node/messaging/ipc-connection-provider.ts#L55

But I am looking into it.

**Comment by marechal-p** [comment]
Opened https://github.com/nodejs/node/issues/30702, might have to move it to Electron depending on the reason of the error.

**Comment by marcdumais-work** [comment]
@marechal-p were you able to determine if this issue is related to your recent PR (#6595)?

**Comment by marechal-p** [comment]
It seems to come from a place that uses bare child processes (the ones from Node directly), so think it is not related indeed. But maybe some side effect is at play? No clue.

**Comment by kittaakos** [comment]
> think it is not related

Yeah, perhaps the issue was always there, and your changes have revealed it.
