### ISSUE TITLE
Error: Possible Emitter memory leak detected

### ISSUE THREAD

**Issue by danidoedel** [eclipse-theia/theia#6659]
### Description
Not sure if that is the right place or too plugin specific, but I'll drop it here anyway.
Let me know if you need more information and I'll try to provide them.

**OS and Theia version:**
Chrome OS 79.0.3945.42
Che-Theia https://github.com/eclipse/che-theia/commit/4769b1a using Theia 84d8678

**Diagnostics:** 

```
Extension-Host:PLUGIN_HOST(3678) starting instance
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/init()
Extension-Host:PLUGIN_HOST(3678): initializing(@eclipse-che/ports-plugin@0.0.1 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(@eclipse-che/theia-containers-plugin@0.0.2 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(@eclipse-che/theia-factory-plugin@0.0.1 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(@eclipse-che/theia-ssh-plugin@0.0.1 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(@eclipse-che/welcome-plugin@0.0.1 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(task-plugin@0.0.1 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(@theia/yeoman-plugin@0.0.1-1562576566 with /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
Extension-Host:PLUGIN_HOST(3678): initializing(git@1.0.0 with /home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/main)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/theia_yeoman_plugin.theia/lib/theia-yeoman-plugin-backend-plugin.js)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/task_plugin.theia/lib/task-plugin-backend.js)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/eclipse_che_welcome_plugin.theia/lib/welcome-plugin.js)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/eclipse_che_theia_ssh_plugin.theia/lib/ssh-plugin-backend.js)
Extension-Host:Error parsing configurations: error: 4, length:  0, offset:  0
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/eclipse_che_theia_factory_plugin.theia/lib/factory-plugin.js)
Extension-Host:Error: Possible Emitter memory leak detected. 31 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:403:9)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 32 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at Object.onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at new AutoFetcher (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/autofetch.js:22:28)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:409:31)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 33 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new ProgressManager (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:310:9)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:422:33)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 34 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:403:9)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 35 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at Object.onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at new AutoFetcher (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/autofetch.js:22:28)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:409:31)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Error: Possible Emitter memory leak detected. 36 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new ProgressManager (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:310:9)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:422:33)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia/lib/containers-plugin.js)
Extension-Host:Error: Possible Emitter memory leak detected. 37 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:403:9)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 38 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at Object.onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at new AutoFetcher (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/autofetch.js:22:28)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:409:31)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 39 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new ProgressManager (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:310:9)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:422:33)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:PLUGIN_HOST(3678): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/eclipse_che_ports_plugin.theia/lib/ports-plugin.js)
Extension-Host:Error: Possible Emitter memory leak detected. 40 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:403:9)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 41 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at Object.onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at new AutoFetcher (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/autofetch.js:22:28)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:409:31)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
Extension-Host:Error: Possible Emitter memory leak detected. 42 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/home/theia/node_modules/@theia/core/lib/common/event.js:256:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/home/theia/node_modules/@theia/core/lib/common/event.js:223:27)
    at onDidChangeConfiguration (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:381:46)
    at /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/util.js:37:56
    at new ProgressManager (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:310:9)
    at new Repository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/repository.js:422:33)
    at Model.openRepository (/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/model.js:184:32)
```

**Comment by akosyakov** [comment]
@danidoedel Can you reproduce it with the vanilla Theia?

**Comment by akosyakov** [comment]
Ok, so now I see it almost in any PR. The issue is reproducible when you have enough VS Code extensions installed. I think we should scale allowed amount of max listeners with amount of extensions. 30 listeners is not enough. 

But first check whether leaks a real, if so we are better to open PRs for corresponding VS Code extensions as well. It seems for instance that vscode python extension does not clean up sometimes.

**Comment by akosyakov** [comment]
Checked that in Gitpod logs it is 2 of 3 most frequent errors in last 30 days.
<img width="1767" alt="Screenshot 2020-03-03 at 11 09 56" src="https://user-images.githubusercontent.com/3082655/75765360-ac1b1400-5d3f-11ea-9b2a-c1f587eda4df.png">
<img width="1761" alt="Screenshot 2020-03-03 at 11 10 05" src="https://user-images.githubusercontent.com/3082655/75765351-a8878d00-5d3f-11ea-8798-4b2714819403.png">

Additional stack traces to investigate:
```
[hosted-plugin: 1087] Error: Possible Emitter memory leak detected. 280 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/theia/node_modules/@theia/core/lib/common/event.js:253:26)
    at m._event.Object.assign.maxListeners (/theia/node_modules/@theia/core/lib/common/event.js:221:27)
    at r.setDocument (/tmp/vscode-extensions/ms-python.python@2019.11.50794/extension/out/client/extension.js:75:650481)
    at m.createNewCodeWatcher (/tmp/vscode-extensions/ms-python.python@2019.11.50794/extension/out/client/extension.js:75:648835)
    at matchWatcher (/tmp/vscode-extensions/ms-python.python@2019.11.50794/extension/out/client/extension.js:75:648725)
    at m.getCodeLens (/tmp/vscode-extensions/ms-python.python@2019.11.50794/extension/out/client/extension.js:75:648216)
    at m.getCodeLensTimed (/tmp/vscode-extensions/ms-python.python@2019.11.50794/extension/out/client/extension.js:75:647316)
    at m.provideCodeLenses (/tmp/vscode-extensions/ms-python.python@2019.11.50794/extension/out/client/extension.js:75:646879)
    at CodeLensAdapter.provideCodeLenses (/theia/node_modules/@theia/plugin-ext/lib/plugin/languages/lens.js:73:46)
    at /theia/node_modules/@theia/plugin-ext/lib/plugin/languages.js:357:101
```
```
[hosted-plugin: 1674] Error: Possible Emitter memory leak detected. 264 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/theia/node_modules/@theia/core/lib/common/event.js:253:26)
    at Object._event.Object.assign.maxListeners (/theia/node_modules/@theia/core/lib/common/event.js:221:27)
    at Object.setDocument (/tmp/vscode-extensions/ms-python.python@2019.8.30787/extension/out/client/extension.js:75:498308)
    at Object.createNewCodeWatcher (/tmp/vscode-extensions/ms-python.python@2019.8.30787/extension/out/client/extension.js:75:496661)
    at Object.matchWatcher (/tmp/vscode-extensions/ms-python.python@2019.8.30787/extension/out/client/extension.js:75:496551)
    at Object.getCodeLens (/tmp/vscode-extensions/ms-python.python@2019.8.30787/extension/out/client/extension.js:75:496042)
    at Object.getCodeLensTimed (/tmp/vscode-extensions/ms-python.python@2019.8.30787/extension/out/client/extension.js:75:495178)
    at Object.provideCodeLenses (/tmp/vscode-extensions/ms-python.python@2019.8.30787/extension/out/client/extension.js:75:494741)
    at CodeLensAdapter.provideCodeLenses (/theia/node_modules/@theia/plugin-ext/lib/plugin/languages/lens.js:73:46)
    at /theia/node_modules/@theia/plugin-ext/lib/plugin/languages.js:357:101
```
