### ISSUE TITLE
Error registering grammar configuration for @theia/vscode-builtin-php@0.2.1

### ISSUE THREAD

**Issue by tolusha** [eclipse-theia/theia#6672]
### Description
https://www.npmjs.com/package/@theia/vscode-builtin-php

Configuration:
```json
"grammars": [
      {
        "language": "php",
        "scopeName": "source.php",
        "path": "./syntaxes/php.tmLanguage.json"
      },
      {
        "language": "php",
        "scopeName": "text.html.php",
        "path": "./syntaxes/html.tmLanguage.json",
        "embeddedLanguages": {
          "text.html": "html",
          "source.php": "php",
          "source.sql": "sql",
          "text.xml": "xml",
          "source.js": "javascript",
          "source.json": "json",
          "source.css": "css"
        }
      }
    ]
```

Error:
```
root WARN Error: 'php' language is remapped from 'source.php' to 'text.html.php' scope
    at TextmateRegistry.push.../../packages/monaco/lib/browser/textmate/textmate-registry.js.TextmateRegistry.mapLanguageIdToTextmateGrammar (http://localhost:3000/43.bundle.js:1272:26)
    at http://localhost:3000/54.bundle.js:8256:125
    at pushContribution (http://localhost:3000/54.bundle.js:8131:32)
    at _loop_3 (http://localhost:3000/54.bundle.js:8256:21)
    at PluginContributionHandler.push.../../packages/plugin-ext/lib/main/browser/plugin-contribution-handler.js.PluginContributionHandler.handleContributions (http://localhost:3000/54.bundle.js:8267:21)
    at _loop_2 (http://localhost:3000/54.bundle.js:2339:63)
    at HostedPluginSupport.push.../../packages/plugin-ext/lib/hosted/browser/hosted-plugin.js.HostedPluginSupport.loadContributions (http://localhost:3000/54.bundle.js:2360:17)
    at HostedPluginSupport.<anonymous> (http://localhost:3000/54.bundle.js:2207:52)
    at step (http://localhost:3000/54.bundle.js:2013:23)
    at Object.next (http://localhost:3000/54.bundle.js:1994:53)
root WARN Error: a registered grammar configuration for 'php' language is overridden
    at TextmateRegistry.push.../../packages/monaco/lib/browser/textmate/textmate-registry.js.TextmateRegistry.registerGrammarConfiguration (http://localhost:3000/43.bundle.js:1310:26)
    at http://localhost:3000/54.bundle.js:8257:133
    at pushContribution (http://localhost:3000/54.bundle.js:8131:32)
    at _loop_3 (http://localhost:3000/54.bundle.js:8257:21)
    at PluginContributionHandler.push.../../packages/plugin-ext/lib/main/browser/plugin-contribution-handler.js.PluginContributionHandler.handleContributions (http://localhost:3000/54.bundle.js:8267:21)
    at _loop_2 (http://localhost:3000/54.bundle.js:2339:63)
    at HostedPluginSupport.push.../../packages/plugin-ext/lib/hosted/browser/hosted-plugin.js.HostedPluginSupport.loadContributions (http://localhost:3000/54.bundle.js:2360:17)
    at HostedPluginSupport.<anonymous> (http://localhost:3000/54.bundle.js:2207:52)
    at step (http://localhost:3000/54.bundle.js:2013:23)
```

**Comment by 502647092** [comment]
after I switch to builtin plugin
I got this warn
```
root WARN Error: 'cpp' language is remapped from 'source.cpp.embedded.macro' to 'source.cpp' scope
root WARN Error: a registered grammar configuration for 'cpp' language is overridden
root WARN Error: 'php' language is remapped from 'source.php' to 'text.html.php' scope
root WARN Error: a registered grammar configuration for 'php' language is overridden
root WARN Error: 'yaml' language is remapped from 'source.yaml' to 'source.yaml' scope
root WARN Error: a registered grammar configuration for 'yaml' language is overridden
```

**Comment by chkaos** [comment]
Same issue, any update?

**Comment by RedCMD** [comment]
yes VSCode assigns two different grammars to the php language

**Comment by sgraband** [comment]
`@theia/vscode-builtin-php` no longer exists; grammar registration rewritten.
