### ISSUE TITLE
[vscode] hosted-plugin error thrown when closing frontend instance

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6677]
**Description**

An uncaught error is thrown when a Theia instance is closed with a plugin present (due to the output channel):

```
root ERROR [hosted-plugin: 12222] Promise rejection not handled in one second: Error: Unknown actor OutputChannelRegistryMain , reason: Error: Unknown actor OutputChannelRegistryMain
```

```
root ERROR [hosted-plugin: 12222] With stack trace: Error: Unknown actor OutputChannelRegistryMain\n
    at RPCProtocolImpl.doInvokeHandler (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/common/rpc-protocol.js:249:19)\n
    at RPCProtocolImpl.invokeHandler (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/common/rpc-protocol.js:240:41)\n
    at RPCProtocolImpl.receiveRequest (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/common/rpc-protocol.js:204:31)\n
    at RPCProtocolImpl.receiveOneMessage (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/common/rpc-protocol.js:173:22)\n
    at /home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109\n
    at /home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/common/rpc-protocol.js:280:17\n
    at /home/evinfug/theia-workspace/theia/packages/core/lib/common/event.js:162:33\n
    at CallbackList.invoke (/home/evinfug/theia-workspace/theia/packages/core/lib/common/event.js:177:39)\n
    at Emitter.fire (/home/evinfug/theia-workspace/theia/packages/core/lib/common/event.js:265:29)\n
    at ChildProcess.<anonymous> (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)

```

**How to test:**
1. start the application using a plugin (ex: `@theia/vscode-builtin-git`)
2. close the browser instance
3. notice the logs on the backend

**Comment by akosyakov** [comment]
A dup of https://github.com/eclipse-theia/theia/issues/5839?

**Comment by RomanNikitenko** [comment]
Something similar to https://github.com/eclipse-theia/theia/issues/5019
