### ISSUE TITLE
[git] `Error occurred while synchronizing the status of the repository` after deleting the repository from the workspace

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6705]
### Description
 
Error when manually wiping  the `.git` folder from my workspace.
```
root ERROR The command `git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z` exited with an unexpected code: 128. The caller should either handle this error, or expect that exit code.
root ERROR fatal: not a git repository (or any of the parent directories): .git

root ERROR (The error was parsed as 27: This is not a git repository.)
root ERROR Error occurred while synchronizing the status of the repository. file:///Users/akos.kitta/Documents/Arduino/sketch_december5a GitError: This is not a git repository.
    at new GitError (/Users/akos.kitta/git/arduino-editor/node_modules/dugite-extra/lib/core/git.js:87:28)
    at Object.<anonymous> (/Users/akos.kitta/git/arduino-editor/node_modules/dugite-extra/lib/core/git.js:262:27)
    at step (/Users/akos.kitta/git/arduino-editor/node_modules/dugite-extra/lib/core/git.js:56:23)
    at Object.next (/Users/akos.kitta/git/arduino-editor/node_modules/dugite-extra/lib/core/git.js:37:53)
    at fulfilled (/Users/akos.kitta/git/arduino-editor/node_modules/dugite-extra/lib/core/git.js:28:58)
```

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by sgraband** [comment]
`@theia/git` is deprecated; repository status is now managed by the VS Code built-in Git extension.
