### ISSUE TITLE
not able to add plugins in theia electron with electron-builder

### ISSUE THREAD

**Issue by NitinKhandelwal1947** [eclipse-theia/theia#6760]
### Description
i am trying to add a sample plugins in theia electron which is bundle with electron-builder.
It throws below error when i start the application
```
root INFO Theia app listening on http://localhost:53065.
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /Users/Documents/Project/theia/plugins/theia-hello-world-plugin
root INFO Deploying backend plugin "theia-hello-world-plugin@0.0.1" from "/Users/Documents/Project/theia/plugins/theia-hello-world-plugin/lib/theia-hello-world-plugin-backend.js"
root INFO Git askpass helper is listening on http://127.0.0.1:53080.
root INFO Using Git [2.20.1 (Apple Git-117)] from the PATH. (/usr/bin/git)
root INFO [nsfw-watcher: 1415] Started watching: /Users/.theia
root INFO [nsfw-watcher: 1415] Started watching: /Users/Documents/theia-hello-world-plugin/theia-hello-world-plugin
root INFO [nsfw-watcher: 1415] Started watching: /Users/Documents/theia-hello-world-plugin/theia-hello-world-plugin
root WARN e.onStart is slow, took: 197.0999999994092 ms
root INFO [e65034b1-7c99-48c7-a114-25045dc5202a] Sync of 1 plugin took: 205.100000001039 ms
root INFO [e65034b1-7c99-48c7-a114-25045dc5202a][theia.theia-hello-world-plugin]: Loaded contributions.
root INFO [e65034b1-7c99-48c7-a114-25045dc5202a] Load contributions of 1 plugin took: 0.5999999993946403 ms
root INFO Config file tasks.json does not exist under file:///Users//Documents/theia-hello-world-plugin/theia-hello-world-plugin
root INFO [nsfw-watcher: 1415] Started watching: /Users/Documents/theia-hello-world-plugin/theia-hello-world-plugin/.theia/launch.json
root INFO [nsfw-watcher: 1415] Started watching: /Users/Documents/theia-hello-world-plugin/theia-hello-world-plugin/.theia/settings.json
root ERROR [hosted-plugin: 1423] /Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:344
        throw errtion({
        ^

Error: There were no suitable editions for package [/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/getmac/package.json]
    at errtion (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/util.js:24:15)
    at requireEditions (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:344:15)
    at requireEditions (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:282:14)
    at Object.requirePackage (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:380:10)
    at Object.<anonymous> (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/getmac/index.js:4:38)
    at Object.<anonymous> (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/getmac/index.js:6:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
↳ Error: Skipping edition [coffeescript source code with require for modules] because its engines field was false
    at errtion (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/util.js:24:15)
    at requireEditions (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:308:25)
    at requireEditions (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:282:14)
    at Object.requirePackage (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:380:10)
    at Object.<anonymous> (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/getmac/index.js:4:38)
    at Object.<anonymous> (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/getmac/index.js:6:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
↳ Error: Skipped edition [coffeescript compiled for node.js >=0.10 with require for modules] at entry [/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/getmac/edition-node-0.10/index.js] because it failed to load
    at errtion (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/util.js:24:15)
    at loadEdition (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:148:11)
    at requireEdition (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:245:10)
    at requireEditions (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:300:16)
    at requireEditions (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:282:14)
    at Object.requirePackage (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:380:10)
    at Object.<anonymous> (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/getmac/index.js:4:38)
    at Object.<anonymous> (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/getmac/index.js:6:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
↳ Error: There were no suitable editions for package [/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/extract-opts/package.json]
    at errtion (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/util.js:24:15)
    at requireEditions (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:344:15)
    at requireEditions (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:282:14)
    at Object.requirePackage (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:380:10)
    at Object.<anonymous> (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/extract-opts/index.js:3:38)
    at Object.<anonymous> (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/extract-opts/index.js:5:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
↳ Error: Each edition must have its [description, directory, entry, engines] fields defined, yet all it had was [description, entry, directory, syntaxes]
    at errtion (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/util.js:24:15)
    at requireEdition (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:168:11)
    at requireEditions (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:300:16)
    at requireEditions (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:282:14)
    at Object.requirePackage (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/editions/edition-node-0.8/index.js:380:10)
    at Object.<anonymous> (/Users/Documents/Project/theia/examples/electron/dist/mac/Lite.app/Contents/Resources/app/node_modules/extract-opts/index.js:3:38)
    at Object.<anonymous> (/Users/Documents/Project/theia/examples/electron
```

### Reproduction Steps

added a sample plugins folder in root directory. Build the electron example with electron-builder.
Added an environment variable:
export THEIA_DEFAULT_PLUGINS=local-dir://absolute-path-to-plugins-folder

Then starting the application by clicking the generated dmg file.

**OS and Theia version:**

yarn version:- 1.7.0
node version:- 10.15.3
npm version:- 4.6.1
Mac System
Theia:- 0.11.0

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
Perhaps you can help @lmcbout since you got it working recently :)

**Comment by lmcbout** [comment]
From the trace, it looks like you don't read the plugin folder
You define the environment variable : THEIA_DEFAULT_PLUGINS   OK

In your package.json, do you include the following packages to build:
        "@theia/plugin": "latest",
        "@theia/plugin-ext": "latest",
        "@theia/plugin-ext-vscode": "latest",

**Comment by NitinKhandelwal1947** [comment]
> From the trace, it looks like you don't read the plugin folder
> You define the environment variable : THEIA_DEFAULT_PLUGINS OK
> 
> In your package.json, do you include the following packages to build:
> "@theia/plugin": "latest",
> "@theia/plugin-ext": "latest",
> "@theia/plugin-ext-vscode": "latest",

@lmcbout Even after adding following packages , its failing with same error as mentioned above.
"@theia/plugin": "latest",
"@theia/plugin-ext": "latest",
"@theia/plugin-ext-vscode": "latest",

package.json:-
```
{
  "private": true,
  "name": "@theia/example-electron",
  "version": "0.11.0",
  "license": "EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0",
  "author": "abc",
  "theia": {
    "target": "electron",
    "frontend": {
      "config": {
        "applicationName": "Theia Electron Example"
      }
    },
    "backend": {
      "config": {
        "startupTimeout": -1
      }
    }
  },
  "main": "./src-gen/frontend/electron-main.js",
  "dependencies": {
    "@theia/callhierarchy": "^0.11.0",
    "@theia/console": "^0.11.0",
    "@theia/core": "^0.11.0",
    "@theia/debug": "^0.11.0",
    "@theia/editor": "^0.11.0",
    "@theia/editor-preview": "^0.11.0",
    "@theia/editorconfig": "^0.11.0",
    "@theia/file-search": "^0.11.0",
    "@theia/filesystem": "^0.11.0",
    "@theia/getting-started": "^0.11.0",
    "@theia/git": "^0.11.0",
    "@theia/java": "^0.11.0",
    "@theia/java-debug": "^0.11.0",
    "@theia/json": "^0.11.0",
    "@theia/keymaps": "^0.11.0",
    "@theia/languages": "^0.11.0",
    "@theia/markers": "^0.11.0",
    "@theia/merge-conflicts": "^0.11.0",
    "@theia/messages": "^0.11.0",
    "@theia/metrics": "^0.11.0",
    "@theia/mini-browser": "^0.11.0",
    "@theia/monaco": "^0.11.0",
    "@theia/navigator": "^0.11.0",
    "@theia/outline-view": "^0.11.0",
    "@theia/output": "^0.11.0",
    "@theia/preferences": "^0.11.0",
    "@theia/preview": "^0.11.0",
    "@theia/process": "^0.11.0",
    "@theia/python": "^0.11.0",
    "@theia/search-in-workspace": "^0.11.0",
    "@theia/task": "^0.11.0",
    "@theia/terminal": "^0.11.0",
    "@theia/textmate-grammars": "^0.11.0",
    "@theia/tslint": "^0.11.0",
    "@theia/typehierarchy": "^0.11.0",
    "@theia/typescript": "^0.11.0",
    "@theia/userstorage": "^0.11.0",
    "@theia/variable-resolver": "^0.11.0",
    "@theia/workspace": "^0.11.0",
    "@theia/plugin": "^0.11.0",
    "@theia/plugin-ext": "^0.11.0",
    "@theia/plugin-ext-vscode": "^0.11.0",
    "electron-store": "^5.0.0",
    "fix-path": "2.1.0",
    "native-keymap": "^2.0.0",
    "oniguruma": "^7.2.0"
  },
  "scripts": {
    "start": "theia start --plugins=local-dir:../../plugins",
    "prepare": "yarn run build",
    "build": "theia build",
    "package": "electron-builder",
    "package:preview": "electron-builder --dir",
    "package:all": "electron-builder -mw"
  },
  "devDependencies": {
    "@theia/cli": "^0.11.0",
    "electron": "^4.0.2",
    "electron-builder": "20.44.4"
  }
}
```

**Comment by lmcbout** [comment]
@NitinKhandelwal1947 
I took you package.json to test :
    yarn
     yarn package:preview
      export THEIA_DEFAULT_PLUGINS="local-dir:$HOME/theia/pluginsJB"  // Where I put some plugins
Start the electron application with:
    yarn start   --> can see my plugins  OR 
    cd  dist/linux-unpacked  && ./@theiaexample-electron  --> electron started and I see all my plugins

I am on LINUX environment
 If I replace $HOME by a "~"
        export THEIA_DEFAULT_PLUGINS="local-dir:~/theia/pluginsJB"

  When I start the application, then I don't see the plugins from the plugins folder
So I guest your issue might be related to the way the environment variable is defined for you since the "package.json " works in LINUX.

**Comment by NitinKhandelwal1947** [comment]
> @NitinKhandelwal1947
> I took you package.json to test 👍
> 
> ```
>     yarn
>      yarn package:preview
>       export THEIA_DEFAULT_PLUGINS="local-dir:$HOME/theia/pluginsJB"  // Where I put some plugins
> ```
> 
> Start the electron application with:
> 
> ```
>     yarn start   --> can see my plugins  OR 
>     cd  dist/linux-unpacked  && ./@theiaexample-electron  --> electron started and I see all my plugins
> ```
> 
> I am on LINUX environment
> 
> ```
>  If I replace $HOME by a "~"
>         export THEIA_DEFAULT_PLUGINS="local-dir:~/theia/pluginsJB"
> ```
> 
> When I start the application, then I don't see the plugins from the plugins folder
> So I guest your issue might be related to the way the environment variable is defined for you since the "package.json " works in LINUX.

In MAC machine i am able to fix this issue by applying changes as suggested in below link.
https://github.com/eclipse-theia/theia/commit/e99735181e78d46ab6169eb9b74a7921989b24c9#diff-bba9137b90f183d0b3d5325d2547406a

Now a want add plugins in Windows machine where it again start throwing error when trying to start theia which was build with electron-builder in windows machine.
```root ERROR No plugin resolver found for the entry C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins```

I have set ```THEIA_DEFAULT_PLUGINS``` as below command
```setx THEIA_DEFAULT_PLUGINS "C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins\"```

yarn version:- 1.7.0
node version:- 10.15.3
npm version:- 4.6.1
Windows 10 System
Theia:- 0.11.0

**Comment by akosyakov** [comment]
You are missing `local-dir:` prefix in THEIA_DEFAULT_PLUGINS.

**Comment by NitinKhandelwal1947** [comment]
> You are missing `local-dir:` prefix in THEIA_DEFAULT_PLUGINS.

@akosyakov If i try to set  THEIA_DEFAULT_PLUGINS with ```local-dir``` prefix it throws below error in Windows machine
```root WARN The directory referenced by local-dir:\\C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins" does not exist.```

I have used below command to set THEIA_DEFAULT_PLUGINS variable
```setx THEIA_DEFAULT_PLUGINS "local-dir:\\C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins\"```

**Comment by akosyakov** [comment]
Should not it be `local-dir:C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins`, i.e. without double backslashes?

**Comment by NitinKhandelwal1947** [comment]
> Should not it be `local-dir:C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins`, i.e. without double backslashes?

If i tried without double backslashes, it throws same error.

```root WARN The directory referenced by local-dir:C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins" does not exist.```

**Comment by NitinKhandelwal1947** [comment]
> > Should not it be `local-dir:C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins`, i.e. without double backslashes?
> 
> If i tried without double backslashes, it throws same error.
> 
> `root WARN The directory referenced by local-dir:C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins" does not exist.`

The issue is resolved by setting THEIA_DEFAULT_PLUGINS as below
``` setx THEIA_DEFAULT_PLUGINS "local-dir:C:\\theia\\examples\\electron\\dist\\win-ia32-unpacked\\resources\\app\\plugins" ```
