### ISSUE TITLE
[nsfw] node_modules/nsfw/build/Release/nsfw.node: _ZN2v820EscapableHandleScope6EscapeEPPNS_8internal6ObjectE: symbol not found

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6792]
### Description

can't start theia at alpine

### Reproduction Steps
**OS and Theia version:**
docker alpine

**Diagnostics:** 
```
theia_1  | internal/modules/cjs/loader.js:1025
theia_1  |   return process.dlopen(module, path.toNamespacedPath(filename));
theia_1  |                  ^
theia_1  |
theia_1  | Error: Error relocating /home/theia/node_modules/nsfw/build/Release/nsfw.node: _ZN2v820EscapableHandleScope6EscapeEPPNS_8internal6ObjectE: symbol not found
theia_1  |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
theia_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
theia_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
theia_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
theia_1  |     at require (internal/modules/cjs/helpers.js:74:18)
theia_1  |     at Object.<anonymous> (/home/theia/node_modules/nsfw/lib/src/index.js:3:16)
theia_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
theia_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
theia_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
theia_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
```

**Comment by 502647092** [comment]
I create issue at https://github.com/Axosoft/nsfw/issues/97

**Comment by GNSubrahmanyam** [comment]
Hi @502647092 ,

How you fixed this ?
