### ISSUE TITLE
[preferences] Undo/redo is broken for the preferences

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7059]
### Description
 

When I try to undo after #7058, it does not work. 
```
root ERROR TypeError: Cannot read property 'startLineNumber' of null
    at TextModel.validateRange (file:///Users/akos.kitta/git/theia/examples/electron/lib/vs/editor/editor.main.js:65306:55)
    at TextModel._applyEdits (file:///Users/akos.kitta/git/theia/examples/electron/lib/vs/editor/editor.main.js:65513:47)
    at TextModel.applyEdits (file:///Users/akos.kitta/git/theia/examples/electron/lib/vs/editor/editor.main.js:65504:29)
    at MonacoEditorModel.push.../../packages/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.applyEdits (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:1308:31)
    at MonacoEditorModel.<anonymous> (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:1399:50)
    at step (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:919:23)
    at Object.next (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:900:53)
    at fulfilled (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:891:58)
root ERROR TypeError: Cannot read property 'startLineNumber' of null
    at TextModel.validateRange (file:///Users/akos.kitta/git/theia/examples/electron/lib/vs/editor/editor.main.js:65306:55)
    at TextModel._applyEdits (file:///Users/akos.kitta/git/theia/examples/electron/lib/vs/editor/editor.main.js:65513:47)
    at TextModel.applyEdits (file:///Users/akos.kitta/git/theia/examples/electron/lib/vs/editor/editor.main.js:65504:29)
    at MonacoEditorModel.push.../../packages/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.applyEdits (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:1308:31)
    at MonacoEditorModel.<anonymous> (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:1399:50)
    at step (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:919:23)
    at Object.next (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:900:53)
    at fulfilled (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:891:58)
root ERROR TypeError: Cannot read property 'startLineNumber' of null
    at TextModel.validateRange (file:///Users/akos.kitta/git/theia/examples/electron/lib/vs/editor/editor.main.js:65306:55)
    at TextModel._applyEdits (file:///Users/akos.kitta/git/theia/examples/electron/lib/vs/editor/editor.main.js:65513:47)
    at TextModel.applyEdits (file:///Users/akos.kitta/git/theia/examples/electron/lib/vs/editor/editor.main.js:65504:29)
    at MonacoEditorModel.push.../../packages/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.applyEdits (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:1308:31)
    at MonacoEditorModel.<anonymous> (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:1399:50)
    at step (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:919:23)
    at Object.next (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:900:53)
    at fulfilled (file:///Users/akos.kitta/git/theia/examples/electron/lib/31.bundle.js:891:58)
root WARN Widget was activated, but did not accept focus after 2000ms: code-editor-opener:user_storage:settings.json
```

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
I cannot reproduce it against https://github.com/eclipse-theia/theia/pull/7481

cc @kittaakos

**Comment by vince-fugnitto** [comment]
Confirmed that the issue is fixed, we can re-open if the issue persists.
