### ISSUE TITLE
Debugging toolbar disabled after start of debug

### ISSUE THREAD

**Issue by ishche** [eclipse-theia/theia#7095]
### Description

After a start of a debugging session, all buttons but restart are disabled. 
In Theia 13 version it worked.

### Reproduction Steps

n/a. Debugging prerequisites are not publicly available.

**OS and Theia version:**
Theia  from the master branch (d54c2f0d7307ef504e9c46e490f4ebd0ac06ef51)

**Diagnostics:** 
DAP log:
```
fe16fb8d theia -> adapter: {"seq":1,"type":"request","command":"initialize","arguments":{"clientID":"Theia","clientName":"Theia IDE","adapterID":"cbl","locale":"en-US","linesStartAt1":true,"columnsStartAt1":true,"pathFormat":"path","supportsVariableType":false,"supportsVariablePaging":false,"supportsRunInTerminalRequest":true}}
fe16fb8d theia <- adapter: {"type":"response","seq":1,"request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsStepBack":false,"supportsSetVariable":true,"supportsRestartRequest":false,"supportsValueFormattingOptions":true,"supportsLogPoints":true,"supportsTerminateRequest":true}}
fe16fb8d theia -> adapter: {"seq":2,"type":"request","command":"launch","arguments":{"type":"cbl","request":"launch","name":"Cobol Intertest CICS Debug","programName":"xxx","interTestHost":"xxx","interTestPort":xxx,"interTestUserName":"xxx","debugServer":xxx,"interTestSecure":false,"cicsApplId":"xxx","noDebug":false,"interTestPassword":"xxx","workspaceDirectory":"/Users/amagex/workspace-dap-tast"}}
83bbf535 theia <- adapter: {"type":"event","event":"exited","seq":-1,"body":{"exitCode":1}}
fe16fb8d theia <- adapter: {"type":"event","seq":2,"event":"initialized"}
fe16fb8d theia -> adapter: {"seq":3,"type":"request","command":"setExceptionBreakpoints","arguments":{"filters":[]}}
fe16fb8d theia <- adapter: {"type":"response","seq":3,"request_seq":2,"command":"launch","success":true}
```

Theia logs:
```
root ERROR [hosted-plugin: 6067] Promise rejection not handled in one second: Error: the debug session connection is disposed, id: 83bbf535-4cf2-45ba-bcf3-da22a611cd48 , reason: Error: the debug session connection is disposed, id: 83bbf535-4cf2-45ba-bcf3-da22a611cd48
root ERROR [hosted-plugin: 6067] With stack trace: Error: the debug session connection is disposed, id: 83bbf535-4cf2-45ba-bcf3-da22a611cd48
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.checkDisposed (http://localhost:3000/30.bundle.js:2135:19)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.newEmitter (http://localhost:3000/30.bundle.js:2346:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.getEmitter (http://localhost:3000/30.bundle.js:2340:55)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.doFire (http://localhost:3000/30.bundle.js:2337:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleEvent (http://localhost:3000/30.bundle.js:2320:22)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleMessage (http://localhost:3000/30.bundle.js:2267:18)
    at PluginMessageReader.callback (http://localhost:3000/30.bundle.js:2157:79)
    at PluginMessageReader.push.../../packages/plugin-ext/lib/common/plugin-message-reader.js.PluginMessageReader.readMessage (http://localhost:3000/58.bundle.js:456:18)
    at ConnectionMainImpl.<anonymous> (http://localhost:3000/58.bundle.js:2302:53)
    at step (http://localhost:3000/58.bundle.js:2268:23)
Promise rejection not handled in one second: Error: the debug session connection is disposed, id: 83bbf535-4cf2-45ba-bcf3-da22a611cd48 , reason: Error: the debug session connection is disposed, id: 83bbf535-4cf2-45ba-bcf3-da22a611cd48
With stack trace: Error: the debug session connection is disposed, id: 83bbf535-4cf2-45ba-bcf3-da22a611cd48
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.checkDisposed (http://localhost:3000/30.bundle.js:2135:19)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.newEmitter (http://localhost:3000/30.bundle.js:2346:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.getEmitter (http://localhost:3000/30.bundle.js:2340:55)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.doFire (http://localhost:3000/30.bundle.js:2337:14)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleEvent (http://localhost:3000/30.bundle.js:2320:22)
    at DebugSessionConnection.push.../../packages/debug/lib/browser/debug-session-connection.js.DebugSessionConnection.handleMessage (http://localhost:3000/30.bundle.js:2267:18)
    at PluginMessageReader.callback (http://localhost:3000/30.bundle.js:2157:79)
    at PluginMessageReader.push.../../packages/plugin-ext/lib/common/plugin-message-reader.js.PluginMessageReader.readMessage (http://localhost:3000/58.bundle.js:456:18)
```

**Comment by akosyakov** [comment]
@ishche is there a way to reproduce from sources?

**Comment by ishche** [comment]
I find the problem. It was in our debug adapter. It never answers on "setExceptionBreakpoints" request so DebugSession.initialized was always false.
Sorry for disturbing.
