### ISSUE TITLE
Error: kill ESRCH when starting, restarting frontend app with the go and yaml VS Code LS extension

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7113]
### Description
 

I can see occasional `kill ERSCH` error when running (start/restart) Theia with the `go` and `yaml` VS Code LS extensions:

```json
  "theiaPlugins": {
    "vscode-go": "https://github.com/microsoft/vscode-go/releases/download/0.12.0/Go-0.12.0.vsix",
    "redhat.vscode-yaml": "https://github.com/redhat-developer/vscode-yaml/releases/download/0.7.1-prerelease/redhat.vscode-yaml-0.7.1-prerelease.vsix"
}
```

Error:
```
root ERROR Uncaught Exception:  Error: kill ESRCH
root ERROR Error: kill ESRCH
    at process.kill (internal/process/per_thread.js:198:13)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:140:25
    at Array.forEach (<anonymous>)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:139:28
    at /Users/akos.kitta/path/to/my/project/node_modules/ps-tree/index.js:87:7
    at Stream.a.end (/Users/akos.kitta/path/to/my/project/node_modules/event-stream/index.js:87:5)
    at Stream.onend (internal/streams/legacy.js:42:10)
    at Stream.emit (events.js:194:15)
    at end (/Users/akos.kitta/path/to/my/project/node_modules/map-stream/index.js:116:39)
    at Stream.stream.end (/Users/akos.kitta/path/to/my/project/node_modules/map-stream/index.js:122:5)
root ERROR [hosted-plugin: 23847] Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
root ERROR [hosted-plugin: 23847] With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
root ERROR [hosted-plugin: 23847] Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
root ERROR [hosted-plugin: 23847] Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/path/to/my/project/node_modules/@theia/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/path/to/my/project/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
root INFO Detected keyboard layout from browser API: US (Mac)
root WARN Collided keybinding is ignored;  {"command":"editor.action.startFindReplaceAction","keybinding":"meta+alt+f","when":null}  collided with  {"command":"core.replace","keybinding":"ctrlcmd+alt+f"}
root WARN Could not register keybinding:
```

### Reproduction Steps

I do not have the exact steps for the issue, but it seems, we try to kill a process or process-group with a `PID` that does not exist.

**OS and Theia version:**

**Diagnostics:**

**Comment by kittaakos** [comment]
Steps: https://github.com/eclipse-theia/theia/pull/7126
