### ISSUE TITLE
Unable to build with Yarn v1.22.0

### ISSUE THREAD

**Issue by benoitf** [eclipse-theia/theia#7118]
### Description
Using the latest stable version of yarn (1.22 and not berry) I'm unable to build Theia.

### Reproduction Steps

Bump to yarn `with like (npm install -g yarn) or another way`

**OS and Theia version:**

**Diagnostics:** 

### Error

```log
...
@theia/electron last logs:
(Mon, 10 Feb 2020 12:41:34 GMT) info: Found cached ffmpeg library.
(Mon, 10 Feb 2020 12:41:34 GMT) info: Successfully replaced "/Users/benoitf/git/eclipse/theia/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries/libffmpeg.dylib".
(Mon, 10 Feb 2020 12:41:36 GMT) info: "/Users/benoitf/git/eclipse/theia/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Libraries/libffmpeg.dylib" does not contain proprietary codecs (0 found).
$ yarn prepare:travis && yarn prepare:build && yarn prepare:hoisting && yarn download:plugins
yarn run v1.22.0
$ node scripts/prepare-travis.js
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/Users/benoitf/git/eclipse/theia/scripts/prepare-travis.js:30:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

https://github.com/yarnpkg/yarn/issues/7881

**Comment by benoitf** [comment]
error is parsing output of
```
yarn workspaces info --json
```


with v1.22.0 we have something like
```
yarn workspaces v1.22.0
{
  "@theia/application-manager": {
    "location": "dev-packages/application-manager",
    "workspaceDependencies": [
....
    ],
    "mismatchedWorkspaceDependencies": []
  }
}
✨  Done in 0.12s.
```


while with 1.22.0
```
{"type":"log","data":"{\n  \"@theia/application-manager\": {\n    \"location\": \"dev-packages/application-manager\",\n    \"workspaceDependencies\": [\n      \"@theia/ext-scripts\",\n      \"@theia/application-package\"\n    ],\n    \"mismatchedWorkspaceDependencies\": []\n  },\n  \"@theia/application-package\": {\n    \"location\": \"dev-packages/application-package\",\n    \"workspaceDependencies\": [\n      \"@theia/ex
...
```



using `yarn workspaces --json info` is fixing the issue
