### ISSUE TITLE
Error: `Unknown actor YourServiceName` when refreshing the browser window

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7176]
### Description
 

Happened when verifying https://github.com/eclipse-theia/theia/pull/5167.
I can see a lot of `Unknown actor ServiceName` error in the console after refreshing the browser.

Steps to reproduce:
 - Build and start Theia from the source, open Theia in your workspace. I used this commit 00c1747c9.
 - Open `.node_modules/@theia/api-tests/src/browser-utils.spec.js` in an editor. Note, it's from `node_modules`.
 - I see the first error:
```
root ERROR [hosted-plugin: 92909] Error: Possible Emitter memory leak detected. 31 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:253:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:221:27)
    at Object.onDidChangeConfiguration (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/plugin/plugin-context.js:387:46)
    at b.hookConfigurationChanged (/Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:65825)
    at e.initialize.then.t (/Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:60594)
root ERROR [hosted-plugin: 92909] Error: Possible Emitter memory leak detected. 32 listeners added. Use event.maxListeners to increase the limit (30)
    at Emitter.checkMaxListeners (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:253:26)
    at PreferenceRegistryExtImpl._event.Object.assign.maxListeners [as onDidChangeConfiguration] (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:221:27)
    at Object.onDidChangeConfiguration (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/plugin/plugin-context.js:387:46)
    at V.register (/Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:48061)
    at Promise (/Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:68963)
    at new Promise (<anonymous>)
    at b.handleRegistrationRequest (/Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:68621)
    at e.onRequest.e (/Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:60165)
    at /Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:7804
    at /Users/akos.kitta/git/theia/plugins/vscode-eslint/extension/client/out/extension.js:1:8842
root ERROR [hosted-plugin: 92909] Promise rejection not handled in one second: TypeError: r.languages.registerSelectionRangeProvider is not a function , reason: TypeError: r.languages.registerSelectionRangeProvider is not a function
root ERROR [hosted-plugin: 92909] With stack trace: TypeError: r.languages.registerSelectionRangeProvider is not a function
    at s.VersionDependentRegistration [as _doRegister] (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165417)
    at s.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12072)
    at t.VersionDependentRegistration.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12541)
    at new t.VersionDependentRegistration (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12340)
    at Object.t.register (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165351)
    at Promise.all.Promise.resolve.then.then.t (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:122930)
    at process._tickCallback (internal/process/next_tick.js:68:7)
root ERROR [hosted-plugin: 92909] Promise rejection not handled in one second: TypeError: r.languages.registerSelectionRangeProvider is not a function , reason: TypeError: r.languages.registerSelectionRangeProvider is not a function
With stack trace: TypeError: r.languages.registerSelectionRangeProvider is not a function
    at s.VersionDependentRegistration [as _doRegister] (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165417)
    at s.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12072)
    at t.VersionDependentRegistration.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12541)
    at new t.VersionDependentRegistration (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12340)
    at Object.t.register (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165351)
    at Promise.all.Promise.resolve.then.then.t (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:122930)
    at process._tickCallback (internal/process/next_tick.js:68:7)
root ERROR [hosted-plugin: 92909] Promise rejection not handled in one second: undefined , reason: undefine
```

Close the editor and refresh the browser window:
```
Promise rejection not
root ERROR [hosted-plugin: 92812] handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor StatusBarMessageRegistryMain , reason: Error: Unknown actor StatusBarMessageRegistryMain
With stack trace: Error: Unknown actor StatusBarMessageRegistryMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plu
root ERROR [hosted-plugin: 92812] gin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor WorkspaceMain , reason: Error: Unknown actor WorkspaceMain
With stack trace: Error: Unknown actor WorkspaceMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor CommandRegistryMain , reason: Error: Unknown actor CommandRegistryMain
With stack trace: Error: Unknown actor CommandRegistryMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor CommandRegistryMain , reason: Error: Unknown actor CommandRegistryMain
With stack trace: Error: Unknown actor CommandRegistryMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
root ERROR [hosted-plugin: 92812] at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor LanguagesMain , reason: Error: Unknown actor LanguagesMain
With stack trace: Error: Unknown actor LanguagesMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor TasksMain , reason: Error: Unknown actor TasksMain
With stack trace: Error: Unknown actor TasksMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor TasksMain , reason: Error: Unknown actor TasksMain
With stack trace: Error: Unknown actor TasksMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
Promise rejection not handled in one second: Error: Unknown actor TasksMain , reason: Error: Unknown actor TasksMain
With stack trace: Error: Unknown actor TasksMain
    at RPCProtocolImpl.doInvokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:248:19)
    at RPCProtocolImpl.invokeHandler (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:239:41)
    at RPCProtocolImpl.receiveRequest (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:203:31)
    at RPCProtocolImpl.receiveOneMessage (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:172:22)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:64:109
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/common/rpc-protocol.js:279:17
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:121:21)
```

Note, I have truncated the stack trace 👆, it was more than 2k lines. I can consistently reproduce it.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
Unknwon actor is a dup of https://github.com/eclipse-theia/theia/issues/5839?

**Comment by RomanNikitenko** [comment]
Related to `unknown actor` issues:
- https://github.com/eclipse-theia/theia/issues/5019
- https://github.com/eclipse-theia/theia/issues/6677

**Comment by akosyakov** [comment]
Ok, looking into it. Initial errors are not related they are because of missing VS Code apis and too many configuration listeners from VS Code extensions. Unfortunately cannot reproduce following to given steps, but will try something else.

**Comment by akosyakov** [comment]
I can reproduce it with debugging Theia Browser Backend:
- change port to 3030 in launch configuration
- launch
- wait for massive log output from Theia
- reload the page

**Comment by akosyakov** [comment]
I think it comes from here: https://github.com/eclipse-theia/theia/blob/1ca3ec37c079a6b316278cf292609653e57b8151/packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts#L96-L112

The frontend is already gone, but to shutdown the plugin host process we create a new RPC which does not have any frontend services, so all requests from the plugin host process cased by deactivation are failing. I wonder what should be the proper way to handle them. Should we ignore messages produced by the plugin host process, i.e. `cp.on('message'`? There is no way we can handle them without frontend. cc @benoitf @tsmaeder

**Comment by akosyakov** [comment]
I assume this code is to handle abrupt shutdown of a client, like a browser crashed. We should consider the page reload as a normal situation and make sure that frontend context is not gone while the plugin process is not shutdown completely. In abrupt situations I'm not sure whether we should try to be smart and deactivate plugins, since it is not possible already. Probably it would be better just kill the process in such cases.
