### ISSUE TITLE
Missing command - 'SQLTools.getConnectionStatus'

### ISSUE THREAD

**Issue by ShimonBenYair** [eclipse-theia/theia#7212]
### Description

When running Theia locally, an error is shown in the console:

`root ERROR [hosted-plugin: 20233] Promise rejection not handled in one second: Error: Command with id 'SQLTools.getConnectionStatus' is not registered. , reason: Error: Command with id 'SQLTools.getConnectionStatus' is not registered.
With stack trace: Error: Command with id 'SQLTools.getConnectionStatus' is not registered.
    at CommandRegistryMainImpl.<anonymous> (http://localhost:3000/60.bundle.js:2027:35)
    at step (http://localhost:3000/60.bundle.js:1938:23)
    at Object.next (http://localhost:3000/60.bundle.js:1919:53)
    at http://localhost:3000/60.bundle.js:1913:71
    at new Promise (<anonymous>)
    at push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.__awaiter (http://localhost:3000/60.bundle.js:1909:12)
    at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (http://localhost:3000/60.bundle.js:2020:16)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (http://localhost:3000/39.bundle.js:849:23)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.invokeHandler (http://localhost:3000/39.bundle.js:834:41)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.receiveRequest (http://localhost:3000/39.bundle.js:798:31)
root INFO [hosted-plugin: 20233] PLUGIN_HOST(20233): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/helloworld-sample-1.0.51.vsix/extension/out/extension.js)`

### Reproduction Steps
1) run Theia locally : git clone https://github.com/eclipse-theia/theia \
&& cd theia \
&& yarn \
&& cd examples/browser \
&& yarn run start 

2) The above error will be shown

**Comment by akosyakov** [comment]
You need to have sql vscode extension installed and follow `How to test` steps from https://github.com/eclipse-theia/theia/pull/6803

**Comment by akosyakov** [comment]
@ShimonBenYair already fixed? :)
