### ISSUE TITLE
API tests does not fail when the initialisation block is broken

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7263]
From travis:
```
@theia/example-browser: Error: TypeError: Cannot destructure property 'GitHistoryContribution' of 'require(...)' as it is undefined.
at Suite.<anonymous> (/home/travis/build/eclipse-theia/theia/examples/api-tests/src/menus.spec.js:25:13)
at Object.create (/home/travis/build/eclipse-theia/theia/node_modules/mocha/mocha.js:1060:19)
at context.describe.context.context (/home/travis/build/eclipse-theia/theia/node_modules/mocha/mocha.js:842:27)
at /home/travis/build/eclipse-theia/theia/examples/api-tests/src/menus.spec.js:18:1
at addScriptContent (__puppeteer_evaluation_script__:7:21)
```

@westbury Could you have a look at `examples/api-tests/src/menus.spec.js`, it got broken by the scm-extra PR?

**Comment by akosyakov** [comment]
Test is fixed, but we should fix test scripts that ci fails when spec file cannot be loaded properly.
