### ISSUE TITLE
[keymaps] Support keymaps for armv7l arch

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7432]
### Description
 

I am not sure if this deserves the `keymaps` label, but I got this error when I start my electron application on Pi3. Arch is `armv7l`, the target is `AppImage`.

Error:
```
Error: /tmp/.mount_Arduin3p3sub/resources/app/node_modules/native-keymap/build/Release/keymapping.node: wrong ELF class: ELFCLASS64
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at NativeBinding._init (/tmp/.mount_Arduin3p3sub/resources/app/node_modules/native-keymap/index.js:15:22)
    at NativeBinding.onDidChangeKeyboardLayout (/tmp/.mount_Arduin3p3sub/resources/app/node_modules/native-keymap/index.js:37:10)
ELECTRON_ASAR.js:160
      if (!isAsar) return old.apply(this, arguments)
                              ^
Error: /tmp/.mount_Arduin3p3sub/resources/app/node_modules/nsfw/build/Release/nsfw.node: wrong ELF class: ELFCLASS64
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_Arduin3p3sub/resources/app/node_modules/nsfw/lib/src/index.js:3:16)
    at Object.<anonymous> (/tmp/.mount_Arduin3p3sub/resources/app/node_modules/nsfw/lib/src/index.js:130:3)
```

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by kittaakos** [comment]
It's most likely not a keymap issue, I am the idiot. The app was built on a 64 CI, and the Pi has 32bit arch:
```
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
$ lscpu
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1400.0000
CPU min MHz:         600.0000
BogoMIPS:            38.40
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
$ file /lib/systemd/systemd
/lib/systemd/systemd: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=4c7dce94827834e44793facac5459c2a1b3614ae, stripped
```

**Comment by kittaakos** [comment]
It works now. See the details [here](https://community.theia-ide.org/t/theia-build-on-raspbian-hangs-at-deprecationwarning-tapable-apply/51).
