### ISSUE TITLE
[TS] Uncaught Error: <semantic> TypeScript Server Error (3.6.3) Debug Failure. False expression.

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7486]
### Description
 
I got this with the electron example. I do not know exactly how it has happened, I was undoing/redoing in the `os.ts` module from Theia.

```
Error: <semantic> TypeScript Server Error (3.6.3)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at doChange (tsserver.js:120056:22)
    at tsserver.js:120047:96
    at Function.ChangeTracker.with (tsserver.js:114831:17)
    at Object.getCodeActions (tsserver.js:120047:64)
    at tsserver.js:115852:121
    at Object.flatMap (tsserver.js:583:25)
    at Object.getFixes (tsserver.js:115852:23)
    at tsserver.js:125866:35
    at Object.flatMap (tsserver.js:583:25)
    at Object.getCodeFixesAtPosition (tsserver.js:125864:23)
    at IOSession.Session.getCodeFixes (tsserver.js:135063:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:133850:61)
    at tsserver.js:135256:88
    at IOSession.Session.executeWithRequestId (tsserver.js:135247:28)
    at IOSession.Session.executeCommand (tsserver.js:135256:33)
    at IOSession.Session.onMessage (tsserver.js:135279:35)
    at Interface.<anonymous> (tsserver.js:136594:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Function.create (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:63406)
    at h.dispatchResponse (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:56561)
    at h.dispatchMessage (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:55459)
    at _reader.onData.e (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:54935)
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:160:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:175:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:262:29)
    at t.Reader.onLengthData (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:61626)
    at Socket.e.on.e (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:61274)
    at Socket.emit (events.js:182:13)
    at doChange (tsserver.js:120056:22)
    at tsserver.js:120047:96
    at Function.ChangeTracker.with (tsserver.js:114831:17)
    at Object.getCodeActions (tsserver.js:120047:64)
    at tsserver.js:115852:121
    at Object.flatMap (tsserver.js:583:25)
    at Object.getFixes (tsserver.js:115852:23)
    at tsserver.js:125866:35
    at Object.flatMap (tsserver.js:583:25)
    at Object.getCodeFixesAtPosition (tsserver.js:125864:23)
    at IOSession.Session.getCodeFixes (tsserver.js:135063:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:133850:61)
    at tsserver.js:135256:88
    at IOSession.Session.executeWithRequestId (tsserver.js:135247:28)
    at IOSession.Session.executeCommand (tsserver.js:135256:33)
    at IOSession.Session.onMessage (tsserver.js:135279:35)
    at Interface.<anonymous> (tsserver.js:136594:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
We should upgrade to latest typescript built-in and also to latest typescript for Theia repo

**Comment by akosyakov** [comment]
I cannot reproduce it. We switched to latest typescript and built-in vscode extension.
