### ISSUE TITLE
Uncaught Exception:  Error: Not a valid zip file on `yarn theia download:plugins`

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7501]
### Description
 

I can see an error logged to the console. App starts, I do not see any issues. Maybe one of the extension archives is corrupted.

Steps to reproduce:
```
rm -rf ./plugins && yarn theia download:plugins
```

Error:
```
Uncaught Exception:  Error: Not a valid zip file
Error: Not a valid zip file
    at UnzipStream.processDataChunk (/Users/akos.kitta/Desktop/theia/node_modules/unzip-stream/lib/unzip-stream.js:155:40)
    at UnzipStream._parseOrOutput (/Users/akos.kitta/Desktop/theia/node_modules/unzip-stream/lib/unzip-stream.js:651:28)
    at UnzipStream._transform (/Users/akos.kitta/Desktop/theia/node_modules/unzip-stream/lib/unzip-stream.js:718:10)
    at UnzipStream.Transform._read (_stream_transform.js:190:10)
    at UnzipStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at UnzipStream.Writable.write (_stream_writable.js:294:11)
    at Extract._transform (/Users/akos.kitta/Desktop/theia/node_modules/unzip-stream/lib/extract.js:30:22)
    at Extract.Transform._read (_stream_transform.js:190:10) 
```

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
I believe it has to do with `node-debug`, it has been removed from `open-vsx` due to an incorrect version and has yet to be successfully published:

- https://github.com/open-vsx/publish-extensions/issues/19

Ideally the script should handle such cases better and report the actual name of the failed download.

**Comment by akosyakov** [comment]
@vince-fugnitto Are we going to publish the proper version?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Are we going to publish the proper version?

There looks to have been an issue which you commented on (adding the comment for traceability):
- https://github.com/open-vsx/publish-extensions/issues/19#issuecomment-609592928
- https://github.com/open-vsx/publish-extensions/issues/20

**Comment by kittaakos** [comment]
I  can still see the same error when running `yarn download:plugins`, plus it is not clear which has failed.
See output:
```
akos.kitta@Akoss-MacBook-Pro theia % yarn download:plugins 
yarn run v1.21.1
$ theia download:plugins
Downloading plugins...
- vscode-builtin-bat: already downloaded - skipping
- vscode-builtin-clojure: already downloaded - skipping
- vscode-builtin-coffeescript: already downloaded - skipping
- vscode-builtin-configuration-editing: already downloaded - skipping
- vscode-builtin-cpp: already downloaded - skipping
- vscode-builtin-csharp: already downloaded - skipping
- vscode-builtin-css: already downloaded - skipping
- vscode-builtin-debug-auto-launch: already downloaded - skipping
- vscode-builtin-docker: already downloaded - skipping
- vscode-builtin-emmet: already downloaded - skipping
- vscode-builtin-fsharp: already downloaded - skipping
- vscode-builtin-go: already downloaded - skipping
- vscode-builtin-groovy: already downloaded - skipping
- vscode-builtin-grunt: already downloaded - skipping
- vscode-builtin-gulp: already downloaded - skipping
- vscode-builtin-handlebars: already downloaded - skipping
- vscode-builtin-hlsl: already downloaded - skipping
- vscode-builtin-html: already downloaded - skipping
- vscode-builtin-ini: already downloaded - skipping
- vscode-builtin-jake: already downloaded - skipping
- vscode-builtin-java: already downloaded - skipping
- vscode-builtin-javascript: already downloaded - skipping
- vscode-builtin-json: already downloaded - skipping
- vscode-builtin-less: already downloaded - skipping
- vscode-builtin-log: already downloaded - skipping
- vscode-builtin-lua: already downloaded - skipping
- vscode-builtin-make: already downloaded - skipping
- vscode-builtin-markdown: already downloaded - skipping
- vscode-builtin-markdown-language-features: already downloaded - skipping
- vscode-builtin-merge-conflict: already downloaded - skipping
- vscode-builtin-npm: already downloaded - skipping
vscode-builtin-node-debug: downloading from http://open-vsx.org/api/ms-vscode/node-debug/1.44.2/file/ms-vscode.node-debug-1.44.2.vsix
- vscode-builtin-node-debug2: already downloaded - skipping
- vscode-builtin-objective-c: already downloaded - skipping
- vscode-builtin-perl: already downloaded - skipping
- vscode-builtin-powershell: already downloaded - skipping
- vscode-builtin-pug: already downloaded - skipping
- vscode-builtin-python: already downloaded - skipping
- vscode-builtin-r: already downloaded - skipping
- vscode-builtin-razor: already downloaded - skipping
- vscode-builtin-ruby: already downloaded - skipping
- vscode-builtin-rust: already downloaded - skipping
- vscode-builtin-scss: already downloaded - skipping
- vscode-builtin-shaderlab: already downloaded - skipping
- vscode-builtin-shellscript: already downloaded - skipping
- vscode-builtin-sql: already downloaded - skipping
- vscode-builtin-swift: already downloaded - skipping
- vscode-builtin-theme-abyss: already downloaded - skipping
- vscode-builtin-theme-defaults: already downloaded - skipping
- vscode-builtin-theme-kimbie-dark: already downloaded - skipping
- vscode-builtin-theme-monokai: already downloaded - skipping
- vscode-builtin-theme-monokai-dimmed: already downloaded - skipping
- vscode-builtin-theme-quietlight: already downloaded - skipping
- vscode-builtin-theme-red: already downloaded - skipping
- vscode-builtin-theme-solarized-dark: already downloaded - skipping
- vscode-builtin-theme-tomorrow-night-blue: already downloaded - skipping
- vscode-builtin-typescript: already downloaded - skipping
- vscode-builtin-typescript-language-features: already downloaded - skipping
- vscode-builtin-vb: already downloaded - skipping
- vscode-builtin-icon-theme-seti: already downloaded - skipping
- vscode-builtin-xml: already downloaded - skipping
- vscode-builtin-yaml: already downloaded - skipping
- vscode-editorconfig: already downloaded - skipping
- vscode-eslint: already downloaded - skipping
- vscode-references-view: already downloaded - skipping
Uncaught Exception:  Error: Not a valid zip file
Error: Not a valid zip file
    at UnzipStream.processDataChunk (/Users/akos.kitta/git/theia/node_modules/unzip-stream/lib/unzip-stream.js:155:40)
    at UnzipStream._parseOrOutput (/Users/akos.kitta/git/theia/node_modules/unzip-stream/lib/unzip-stream.js:651:28)
    at UnzipStream._transform (/Users/akos.kitta/git/theia/node_modules/unzip-stream/lib/unzip-stream.js:718:10)
    at UnzipStream.Transform._read (_stream_transform.js:190:10)
    at UnzipStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at UnzipStream.Writable.write (_stream_writable.js:294:11)
    at Extract._transform (/Users/akos.kitta/git/theia/node_modules/unzip-stream/lib/extract.js:30:22)
    at Extract.Transform._read (_stream_transform.js:190:10)
+ vscode-builtin-node-debug: downloaded successfully
✨  Done in 1.57s.
akos.kitta@Akoss-MacBook-Pro theia % 

```

**Comment by vince-fugnitto** [comment]
@kittaakos the script output you referenced looks old, for example just looking at the first console.log (`--- downloading plugins ---`) which is not part of your output. I think `npx run build @theia/cli` is required first. For example, please take a look at my output from `master`:

```
┌─[±][master ✓][theia][]
└─▪ yarn download:plugins
yarn run v1.22.4
$ theia download:plugins
--- downloading plugins ---
+ vscode-builtin-clojure: downloaded successfully
+ vscode-builtin-coffeescript: downloaded successfully
+ vscode-builtin-fsharp: downloaded successfully
+ vscode-builtin-css: downloaded successfully
+ vscode-builtin-groovy: downloaded successfully
+ vscode-builtin-go: downloaded successfully
+ vscode-builtin-csharp: downloaded successfully
+ vscode-builtin-bat: downloaded successfully
+ vscode-builtin-debug-auto-launch: downloaded successfully
+ vscode-builtin-html: downloaded successfully
+ vscode-builtin-shaderlab: downloaded successfully
+ vscode-builtin-java: downloaded successfully
+ vscode-builtin-cpp: downloaded successfully
+ vscode-builtin-configuration-editing: downloaded successfully
+ vscode-builtin-json: downloaded successfully
+ vscode-builtin-gulp: downloaded successfully
+ vscode-builtin-javascript: downloaded successfully
+ vscode-builtin-grunt: downloaded successfully
+ vscode-builtin-hlsl: downloaded successfully
+ vscode-builtin-lua: downloaded successfully
+ vscode-builtin-merge-conflict: downloaded successfully
+ vscode-builtin-ini: downloaded successfully
+ vscode-builtin-less: downloaded successfully
+ vscode-builtin-jake: downloaded successfully
x vscode-builtin-node-debug: failed to download
+ vscode-builtin-npm: downloaded successfully
+ vscode-builtin-handlebars: downloaded successfully
+ vscode-builtin-python: downloaded successfully
+ vscode-builtin-make: downloaded successfully
+ vscode-builtin-r: downloaded successfully
+ vscode-builtin-razor: downloaded successfully
+ vscode-builtin-powershell: downloaded successfully
+ vscode-builtin-markdown: downloaded successfully
+ vscode-builtin-perl: downloaded successfully
+ vscode-builtin-log: downloaded successfully
+ vscode-builtin-theme-kimbie-dark: downloaded successfully
+ vscode-builtin-scss: downloaded successfully
+ vscode-builtin-rust: downloaded successfully
+ vscode-builtin-shellscript: downloaded successfully
+ vscode-builtin-typescript: downloaded successfully
+ vscode-builtin-xml: downloaded successfully
+ vscode-builtin-theme-tomorrow-night-blue: downloaded successfully
+ vscode-builtin-ruby: downloaded successfully
+ vscode-builtin-theme-monokai: downloaded successfully
+ vscode-builtin-theme-red: downloaded successfully
+ vscode-builtin-theme-abyss: downloaded successfully
+ vscode-builtin-theme-monokai-dimmed: downloaded successfully
+ vscode-builtin-vb: downloaded successfully
+ vscode-builtin-pug: downloaded successfully
+ vscode-builtin-markdown-language-features: downloaded successfully
+ vscode-builtin-sql: downloaded successfully
+ vscode-builtin-objective-c: downloaded successfully
+ vscode-builtin-icon-theme-seti: downloaded successfully
+ vscode-builtin-theme-solarized-dark: downloaded successfully
+ vscode-builtin-theme-defaults: downloaded successfully
+ vscode-eslint: downloaded successfully
+ vscode-builtin-swift: downloaded successfully
+ vscode-builtin-yaml: downloaded successfully
+ vscode-builtin-docker: downloaded successfully
+ vscode-builtin-theme-quietlight: downloaded successfully
+ vscode-editorconfig: downloaded successfully
+ vscode-builtin-emmet: downloaded successfully
+ vscode-references-view: downloaded successfully
+ vscode-builtin-node-debug2: downloaded successfully
+ vscode-builtin-typescript-language-features: downloaded successfully
✨  Done in 3.38s.
```

**Comment by kittaakos** [comment]
Nice catch, let me check.

**Comment by kittaakos** [comment]
Yes, you're right:
```
x vscode-builtin-node-debug: failed to download 
✨  Done in 0.83s.
```

The failure is quite hidden, but it's there.

**Comment by vince-fugnitto** [comment]
> The failure is quite hidden, but it's there.

I can do a small follow-up to make it more visible, did you have something in mind?

**Comment by marechal-p** [comment]
Just make it red.
