### ISSUE TITLE
[search-in-workspace] Workspace search does not work in Electron with asar packaging

### ISSUE THREAD

**Issue by Livven** [eclipse-theia/theia#7528]
### Description

Workspace search does not work in Electron with asar packaging enabled because `rg` cannot be spawned. The following message is shown when launching the Electron executable via a console:

```
process ERROR Error: spawn C:\path\to\application\resources\app.asar\node_modules\vscode-ripgrep\bin\rg.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

In the above path, `app.asar` should be replaced with `app.asar.unpacked`, as binaries cannot be in the asar file and have to be unpacked instead in order to be executable. However, the `rg` path (created [here](https://github.com/microsoft/vscode-ripgrep/blob/87c3967649706b2f82caa98facfadf7105192f71/lib/index.js#L5) and used [here](https://github.com/eclipse-theia/theia/blob/ed22584e956f8cafbb222d7918e9de8a366becaa/packages/search-in-workspace/src/node/search-in-workspace-backend-module.ts#L32)) does not take this into account.

See also https://github.com/electron/electron/issues/6262 for a general discussion about this issue.

### Reproduction Steps

1. Enter anything in the workspace search box. No search results are shown.

**OS and Theia version:** Windows 10 1803, Theia 0.16.1.

**Diagnostics:** See above.

**Comment by Livven** [comment]
By the way I think a simple fix would be to unpack the full `vscode-ripgrep` folder, which should cause the correct path to be resolved. However that would require additional configuration from the user.

Considering that for example [electron-builder](https://www.electron.build/configuration/configuration#overridable-per-platform-options) can do smart detection of what needs to be unpacked it would be nicer if Theia would play along with that and handle this automatically as well.

**Comment by ngfelixl** [comment]
As @Livven said, unpacking `@vscode/ripgrep` works fine. Here is the __electron-builder.yml__ configuration

```
electronVersion: 36.4.0
asar: true
asarUnpack:
  - "**/@vscode/ripgrep/**"
```

This looks much better to me than disabling asar completely.

**Comment by ngfelixl** [comment]
It also does not find the built-in extensions when using asar.

**Comment by msujew** [comment]
Since Theia supports backend bundling for quite a while already (which alleviates most of the reasons why you would want to use asar packaging in the first place), I would simply say that asar packaging is unsupported in Theia. There are too many features/dependencies that expect that some binaries/extensions/plugins are available on the file system.

I'm inclined to close this issue, since this isn't something that we want to support (and even if we do support it, adopters can easily break the asar packaging themselves).
