### ISSUE TITLE
VSCODE VIM plugin not working

### ISSUE THREAD

**Issue by tavoda** [eclipse-theia/theia#7587]
### Description
After #7539 merge to master, VSCODE VIM plugin basic commands like 'hjkl' stop working. CTRL + F for 'PageDown' is working. When you press 'j', instead of moving down one line letter 'j' appear in text (it looks like always in insert mode &lt;ESC> is not working)

### Reproduction Steps
git clone https://github.com/eclipse-theia/theia.git
cd theia/
yarn
cd examples/browser/
cp ~/Downloads/vscodevim.vim-1.13.1.vsix ../../plugins/
yarn run start
Open http://localhost:3000 in browser
Open some file
Press CTRL+F -> it's working
Press j, letter 'j' appear in text instead of moving one line down

**OS and Theia version:**
Linux xxx 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
e2dfc1adf of master branch

**Diagnostics:** 
Errors in console after yarn run start:
root ERROR [hosted-plugin: 4054265] Promise rejection not handled in one second: TypeError: r.languages.registerSelectionRangeProvider is not a function , reason: TypeError: r.languages.registerSelectionRangeProvider is not a function                                                                                                                  
root ERROR [hosted-plugin: 4054265] With stack trace: TypeError: r.languages.registerSelectionRangeProvider is not a function                                                 
    at s.VersionDependentRegistration [as _doRegister] (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165355)      
    at s.update (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12010)                                              
    at t.VersionDependentRegistration.update (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12479)                 
    at new t.VersionDependentRegistration (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12278)                    
    at Object.t.register (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165289)                                    
    at Promise.all.Promise.resolve.then.then.t (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:122868)              
    at process._tickCallback (internal/process/next_tick.js:68:7)                                                                                                             
root ERROR [hosted-plugin: 4054265] Promise rejection not handled in one second: TypeError: r.languages.registerSelectionRangeProvider is not a function , reason: TypeError: r.languages.registerSelectionRangeProvider is not a function                                                                                                                  
With stack trace: TypeError: r.languages.registerSelectionRangeProvider is not a function                                                                                     
    at s.VersionDependentRegistration [as _doRegister] (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165355)      
    at s.update (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12010)                                              
    at t.VersionDependentRegistration.update (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12479)                 
    at new t.VersionDependentRegistration (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12278)                    
    at Object.t.register (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:165289)                                    
    at Promise.all.Promise.resolve.then.then.t (/home/tavoda/opt/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:122868)              
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by akosyakov** [comment]
Please reopen if you find anything else broken.

**Comment by tavoda** [comment]
It's working now :+1:, thanks for fast fix.

**Comment by timonbimon** [comment]
just quick question (I have the vscodevim Extension installed) => when I enter Insert-Mode and then hit <Esc> to exit, it just unfocuses the tab, but does not actually exit Insert-Mode. Any ideas on how to resolve this? Is there a setting I need to change?
