### ISSUE TITLE
Closing a terminal generates an errror on the console log.

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7625]
### Description
 
Each time a user closes a terminal, an error is log on the console.

### Reproduction Steps

- Start Theia
- Open one or more terminal(s) ( From the menu or the short key)
- Close a terminal
--> An error is reported on the console

**OS and Theia version:**
Theia: latest ( commit 983644d7a483a34656afc69a33e44df7b0c5eabb )
OS: Ubuntu 18.04
Chrome , electron

**Diagnostics:** 

root ERROR Error: Widget is not attached.
    at Function.detach (http://localhost:3000/bundle.js:27136:19)
    at TerminalSearchWidget.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.dispose (http://localhost:3000/bundle.js:26274:20)
    at TerminalSearchWidget.../../packages/core/lib/browser/widgets/widget.js.BaseWidget.dispose (http://localhost:3000/bundle.js:133164:34)
    at TerminalSearchWidget.disposable.dispose (http://localhost:3000/bundle.js:134485:13)
    at DisposableCollection.../../packages/core/lib/common/disposable.js.DisposableCollection.dispose (http://localhost:3000/bundle.js:134462:40)
    at TerminalWidgetImpl.../../packages/core/lib/browser/widgets/widget.js.BaseWidget.dispose (http://localhost:3000/bundle.js:133165:24)
    at TerminalWidgetImpl.push.../../packages/terminal/lib/browser/terminal-widget-impl.js.TerminalWidgetImpl.dispose (http://localhost:3000/37.bundle.js:1519:34)
    at TerminalWidgetImpl.../../packages/core/lib/browser/widgets/widget.js.BaseWidget.onCloseRequest (http://localhost:3000/bundle.js:133169:14)
    at TerminalWidgetImpl.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (http://localhost:3000/bundle.js:26746:22)
    at TerminalWidgetImpl.push.../../packages/terminal/lib/browser/terminal-widget-impl.js.TerminalWidgetImpl.processMessage (http://localhost:3000/37.bundle.js:1347:41)

**Comment by balajiv113** [comment]
I would like to work on this issue.

**Comment by vince-fugnitto** [comment]
Closed by #7882
