### ISSUE TITLE
[git] git submodule changes not handled gracefully

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#7643]
### Description
In our git view, it looks like we do not correctly handle changes to a git submodule. 

When using a git repo that has a submodule, if the submodule has been altered, e.g. checking-out a different commit, it will then show-up as a git difference in the containing git repo:
```
vscode-builtin-extensions$ git status
On branch openvsx-publish
Your branch is up to date with 'origin/openvsx-publish'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   vscode (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
```

In Theia's git view, uncommitted changes are shown. Clicking on an entry opens it in a diff editor, showing changes vs HEAD. However for the git submodule entry this fails. See the error below.

VS Code handles the same case gracefully, showing in a read-only editor what looks to be the result of `git diff vscode`:
```
diff --git a/vscode b/vscode
index 88f15d1..7f87a64 160000
--- a/vscode
+++ b/vscode
@@ -1 +1 @@
-Subproject commit 88f15d17dca836346e787762685a40bb5cce75a8
+Subproject commit 7f87a64621b010ed8a7e171d07583921e8c1e8ac
```

### Reproduction Steps

0) setup a test repo that has a git submodule, make a change in it
```
$> git clone https://github.com/theia-ide/vscode-builtin-extensions.git
$> cd vscode-builtin-extensions; git submodule init; git submodule update
$> cd vscode; git checkout HEAD~1; cd ..
```
1) open `vscode-builtin-extensions` in Theia as workspace
2) go to the git view
3) click on the `vscode` entry
4) check the backend log for the error below. 

**OS and Theia version:**
Theia master, Ubuntu 18.04

**Diagnostics:** 

```
root ERROR The command `git show HEAD:vscode` exited with an unexpected code: 128. The caller should either handle this error, or expect that exit code.
root ERROR fatal: bad object HEAD:vscode

root ERROR Request show failed with error: fatal: bad object HEAD:vscode
 GitError: fatal: bad object HEAD:vscode

    at new GitError (/opt/teal/resources/app/node_modules/dugite-extra/lib/core/git.js:87:28)
    at Object.<anonymous> (/opt/teal/resources/app/node_modules/dugite-extra/lib/core/git.js:262:27)
    at step (/opt/teal/resources/app/node_modules/dugite-extra/lib/core/git.js:56:23)
    at Object.next (/opt/teal/resources/app/node_modules/dugite-extra/lib/core/git.js:37:53)
    at fulfilled (/opt/teal/resources/app/node_modules/dugite-extra/lib/core/git.js:28:58)
```

Which is the same fundamental error I get running in a terminal: 
```
vscode-builtin-extensions$ git show HEAD:vscode
fatal: bad object HEAD:vscode
``

**Comment by sgraband** [comment]
`@theia/git` is officially deprecated per README.
