### ISSUE TITLE
investigate integration tests log output against latest built-in

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7800]
There are some worrying messages although tests are not failing. We should make sure that tests fail and then fix them.

- [ ] TextEditor has been disposed
```
root ERROR [hosted-plugin: 22803] { DISPOSED: TextEditor: vs.editor.ICodeEditor:11,$model20 has been disposed
    at Object.disposed (http://127.0.0.1:3000/42.bundle.js:48:18)
    at TextEditorsMainImpl.push.../../packages/plugin-ext/lib/main/browser/text-editors-main.js.TextEditorsMainImpl.$trySetOptions (http://127.0.0.1:3000/58.bundle.js:9545:44)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (http://127.0.0.1:3000/42.bundle.js:875:23)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.invokeHandler (http://127.0.0.1:3000/42.bundle.js:860:41)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.receiveRequest (http://127.0.0.1:3000/42.bundle.js:824:31)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.receiveOneMessage (http://127.0.0.1:3000/42.bundle.js:793:22)
    at http://127.0.0.1:3000/42.bundle.js:685:109
    at http://127.0.0.1:3000/42.bundle.js:900:17
    at http://127.0.0.1:3000/bundle.js:135578:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (http://127.0.0.1:3000/bundle.js:135593:39)
  name: 'DISPOSED',
  message:
   'TextEditor: vs.editor.ICodeEditor:11,$model20 has been disposed' }
```
- [x] Invalid Completion Item -> must be single line and on the same line
```
root ERROR [hosted-plugin: 22803] Invalid Completion Item -> must be single line and on the same line
root ERROR [hosted-plugin: 22803] Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
Invalid Completion Item -> must be single line and on the same line
```
- [x] TypeError: Converting circular structure to JSON
```
Error: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'PluginViewWidget'
    |     property '_layout' -> object with constructor 'PanelLayout'
    --- property '_parent' closes the circle
    at JSON.stringify (<anonymous>)
    at Function.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.MessageFactory.replyOK (http://127.0.0.1:3000/42.bundle.js:957:103)
    at http://127.0.0.1:3000/42.bundle.js:827:51
Error: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'PluginViewWidget'
    |     property '_layout' -> object with constructor 'PanelLayout'
    --- property '_parent' closes the circle
    at JSON.stringify (<anonymous>)
    at Function.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.MessageFactory.replyOK (http://127.0.0.1:3000/42.bundle.js:957:103)
    at http://127.0.0.1:3000/42.bundle.js:827:51
```
- [x] Failed to fetch children for 'references-view.tree' TypeError: Cannot destructure property `range` of 'undefined' or 'null'.
```
    at r.getTreeItem (/workspace/theia/plugins/vscode-references-view/extension/dist/extension.js:1:15402)
    at t.TreeDataProviderWrapper.getTreeItem (/workspace/theia/plugins/vscode-references-view/extension/dist/extension.js:1:18034)
    at TreeViewExtImpl.<anonymous> (/workspace/theia/packages/plugin-ext/lib/plugin/tree/tree-views.js:312:88)
    at step (/workspace/theia/packages/plugin-ext/lib/plugin/tree/tree-views.js:59:23)
    at Object.next (/workspace/theia/packages/plugin-ext/lib/plugin/tree/tree-views.js:40:53)
    at /workspace/theia/packages/plugin-ext/lib/plugin/tree/tree-views.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/theia/packages/plugin-ext/lib/plugin/tree/tree-views.js:30:12)
    at /workspace/theia/packages/plugin-ext/lib/plugin/tree/tree-views.js:308:80
    at Array.map (<anonymous>)
Error: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'PluginViewWidget'
    |     property '_layout' -> object with constructor 'PanelLayout'
    --- property '_parent' closes the circle
    at JSON.stringify (<anonymous>)
    at Function.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.MessageFactory.replyOK (http://127.0.0.1:3000/42.bundle.js:957:103)
    at http://127.0.0.1:3000/42.bundle.js:827:51
Error: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'PluginViewWidget'
    |     property '_layout' -> object with constructor 'PanelLayout'
    --- property '_parent' closes the circle
    at JSON.stringify (<anonymous>)
    at Function.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.MessageFactory.replyOK (http://127.0.0.1:3000/42.bundle.js:957:103)
    at http://127.0.0.1:3000/42.bundle.js:827:51
```
- [x] TypeError: Cannot read property 'addWidget' of null
```
Error: TypeError: Cannot read property 'addWidget' of null
    at PluginViewWidget.../../node_modules/@phosphor/widgets/lib/panel.js.Panel.addWidget (http://127.0.0.1:3000/bundle.js:21538:21)
    at PluginViewWidget.push.../../packages/plugin-ext/lib/main/browser/view/plugin-view-widget.js.PluginViewWidget.addWidget (http://127.0.0.1:3000/49.bundle.js:2400:36)
    at PluginViewRegistry.<anonymous> (http://127.0.0.1:3000/58.bundle.js:10313:40)
    at step (http://127.0.0.1:3000/58.bundle.js:9955:23)
    at Object.next (http://127.0.0.1:3000/58.bundle.js:9936:53)
    at fulfilled (http://127.0.0.1:3000/58.bundle.js:9927:58)
```

**Comment by akosyakov** [comment]
resolved in https://github.com/eclipse-theia/theia/pull/7957
