### ISSUE TITLE
GitLens support

### ISSUE THREAD

**Issue by jeluard** [eclipse-theia/theia#7816]
### Bug Description:

[GitLens](https://github.com/eamodio/vscode-gitlens) doesn't work with theia 1.1.0

### Steps to Reproduce:

1. Add GitLens as a theiaPlugins
2. Start theia

Some error messages are displayed and the extension can't be used:

```js
logger-protocol.ts:112 root ERROR Failed to fetch children for 'gitlens.views.repositories:gitlens' TypeError: Cannot read property 'similarityThreshold' of undefined
    at GitService.getStatusForRepo (/home/theia/theia-playground/plugins/vscode-gitlens/extension/dist/extension.js:1:191842)
    at GitService.h.value (/home/theia/theia-playground/plugins/vscode-gitlens/extension/dist/extension.js:1:548792)
    at Repository.getStatus (/home/theia/theia-playground/plugins/vscode-gitlens/extension/dist/extension.js:1:712461)
    at repositoryNode_RepositoryNode.refresh (/home/theia/theia-playground/plugins/vscode-gitlens/extension/dist/extension.js:1:321579)
    at repositoryNode_RepositoryNode.h.value (/home/theia/theia-playground/plugins/vscode-gitlens/extension/dist/extension.js:1:548792)
    at repositoryNode_RepositoryNode.o.value (/home/theia/theia-playground/plugins/vscode-gitlens/extension/dist/extension.js:1:17524)
    at repositoriesNode_RepositoriesNode.refresh (/home/theia/theia-playground/plugins/vscode-gitlens/extension/dist/extension.js:1:357938)
```

```js
TypeError: Cannot read property 'caching' of undefined
    at GitService.get useCaching [as useCaching] (home/theia/theia-playground/plugins/vscode-gitlens/extension/dist/extension.js:1)
    at GitService.getBlameForFile (home/theia/theia-playground/plugins/vscode-gitlens/extension/dist/extension.js:1)
    at process._tickCallback (internal/process/next_tick.js:68)
    at editor.main.js:30
```

### Additional Information

- Operating System: OSX
- Theia Version: 1.1.0

**Comment by akosyakov** [comment]
@jeluard Pleas try against latest master. The PR was landed only this week: https://github.com/eclipse-theia/theia/pull/6921 See `How to test` for configuration.

**Comment by jeluard** [comment]
Nice! Thanks
