### ISSUE TITLE
I cannot build Theia; vscode-ripgrep download fails with HTTP 401

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7837]
### Bug Description:

See title.

### Steps to Reproduce:

```
git clone --depth 1 https://github.com/eclipse-theia/theia.git \
cd theia \
yarn
```

Full log:
```
akos.kitta@Akoss-MacBook-Pro Desktop % git clone --depth 1 https://github.com/eclipse-theia/theia.git
Cloning into 'theia'...
remote: Enumerating objects: 2153, done.
remote: Counting objects: 100% (2153/2153), done.
remote: Compressing objects: 100% (1827/1827), done.
remote: Total 2153 (delta 786), reused 603 (delta 263), pack-reused 0
Receiving objects: 100% (2153/2153), 3.72 MiB | 4.28 MiB/s, done.
Resolving deltas: 100% (786/786), done.
akos.kitta@Akoss-MacBook-Pro Desktop % cd theia 
akos.kitta@Akoss-MacBook-Pro theia % yarn
yarn install v1.22.4
$ node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | darwin | x64
gyp http GET https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
10.15.3
gyp info ok 
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
warning monaco-languageclient@0.13.0: The engine "vscode" appears to be invalid.
warning vscode-languageclient@6.1.0: The engine "vscode" appears to be invalid.
[4/5] 🔗  Linking dependencies...
warning " > chai-string@1.5.0" has unmet peer dependency "chai@^4.1.2".
warning "workspace-aggregator-8f764eb6-9825-4e42-8cb0-72ccd0ddbc64 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-8f764eb6-9825-4e42-8cb0-72ccd0ddbc64 > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-8f764eb6-9825-4e42-8cb0-72ccd0ddbc64 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-8f764eb6-9825-4e42-8cb0-72ccd0ddbc64 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-8f764eb6-9825-4e42-8cb0-72ccd0ddbc64 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-8f764eb6-9825-4e42-8cb0-72ccd0ddbc64 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-8f764eb6-9825-4e42-8cb0-72ccd0ddbc64 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
warning Workspaces can only be enabled in private projects.
[5/5] 🔨  Building fresh packages...
[8/14] ⠈ nsfw
[10/14] ⠈ drivelist
[13/14] ⠈ vscode-ripgrep
[12/14] ⠈ oniguruma
error /Users/akos.kitta/Desktop/theia/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /Users/akos.kitta/Desktop/theia/node_modules/vscode-ripgrep
Output:
Finding release for v11.0.1-2
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v11.0.1-2
Deleting invalid download cache
Downloading ripgrep failed: Error: Request failed: 401
    at ClientRequest.https.get.response (/Users/akos.kitta/Desktop/theia/node_modules/vscode-ripgrep/lib/download.js:106:24)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)




^C
akos.kitta@Akoss-MacBook-Pro theia % 
```

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by kittaakos** [comment]
I have wiped the yarn cache and it works now; must have been an issue with my dev env.
