### ISSUE TITLE
[task] Task server tests are broken

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7838]
### Steps to Reproduce:

1. Clone the repo
2. `yarn`
3. `yarn test`

```
  7 failing

  1) Task server / back-end
       task running in terminal - expected data is received from the terminal ws server:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/akos.kitta/Desktop/theia/packages/task/lib/node/task-server.slow-spec.js)
  

  2) Task server / back-end
       task can successfully execute command found in system path using a terminal process:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/akos.kitta/Desktop/theia/packages/task/lib/node/task-server.slow-spec.js)
  

  3) Task server / back-end
       shell task should execute the command as a whole if not arguments are specified:

      AssertionError: expected 127 to equal 0
      + expected - actual

      -127
      +0
      
      at Context.<anonymous> (lib/node/task-server.slow-spec.js:557:51)
      at step (lib/node/task-server.slow-spec.js:48:23)
      at Object.next (lib/node/task-server.slow-spec.js:29:53)
      at fulfilled (lib/node/task-server.slow-spec.js:20:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  4) Task server / back-end
       shell task should be able to exec using simple arguments:

      AssertionError: expected 127 to equal 0
      + expected - actual

      -127
      +0
      
      at Context.<anonymous> (lib/node/task-server.slow-spec.js:591:51)
      at step (lib/node/task-server.slow-spec.js:48:23)
      at Object.next (lib/node/task-server.slow-spec.js:29:53)
      at fulfilled (lib/node/task-server.slow-spec.js:20:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  5) Task server / back-end
       shell task should be able to run using arguments containing whitespace:

      AssertionError: expected 127 to equal 0
      + expected - actual

      -127
      +0
      
      at Context.<anonymous> (lib/node/task-server.slow-spec.js:608:51)
      at step (lib/node/task-server.slow-spec.js:48:23)
      at Object.next (lib/node/task-server.slow-spec.js:29:53)
      at fulfilled (lib/node/task-server.slow-spec.js:20:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  6) Task server / back-end
       shell task should be able to run using arguments specifying which quoting method to use:

      AssertionError: expected 127 to equal 0
      + expected - actual

      -127
      +0
      
      at Context.<anonymous> (lib/node/task-server.slow-spec.js:642:51)
      at step (lib/node/task-server.slow-spec.js:48:23)
      at Object.next (lib/node/task-server.slow-spec.js:29:53)
      at fulfilled (lib/node/task-server.slow-spec.js:20:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  7) Task server / back-end
       shell task should be able to run using arguments with forbidden characters but no whitespace:

      AssertionError: expected 127 to equal 0
      + expected - actual

      -127
      +0
      
      at Context.<anonymous> (lib/node/task-server.slow-spec.js:659:51)
      at step (lib/node/task-server.slow-spec.js:48:23)
      at Object.next (lib/node/task-server.slow-spec.js:29:53)
      at fulfilled (lib/node/task-server.slow-spec.js:20:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Additional Information

- Operating System:
- Theia Version: bb43e9e

**Comment by kittaakos** [comment]
Hmm, the tests are green on Windows. Could this be a timing issue?
```
C:\Users\kittaakos\Desktop\theia>git rev-parse --short HEAD
bb43e9e
```

**Comment by kittaakos** [comment]
One of the tests fails on Gitpod (Linux) too:

```
gitpod /workspace/theia $ ^C
gitpod /workspace/theia $ ^C
gitpod /workspace/theia $ ^C
gitpod /workspace/theia $ yarn --cwd ./packages/task test
yarn run v1.22.4
$ theiaext test
$ nyc mocha --opts ../../configs/mocha.opts "./lib/**/*.*spec.js"


(node:2039) DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.
  provided-task-configurations
    ✓ provided-task-search

  TaskDefinitionRegistry
    register function
      ✓ should transform the task definition contribution and store it in memory
    getDefinitions function
      ✓ should return all definitions associated with the given type
    getDefinition function
      ✓ should return undefined if the given task configuration does not match any registered definitions
      ✓ should return the best match if there is one or more registered definitions match the given task configuration

  removeAnsiEscapeCodes function
    ✓ should remove all end line and color codes

  ProblemCollector
    ✓ should find problems from start-stop task when problem matcher is associated with one problem pattern
    ✓ should find problems from start-stop task when problem matcher is associated with more than one problem pattern
    ✓ should search and find defined problems from watch task's output
    ✓ should return an empty array if no problems are found

  Task server / back-end
Theia app listening on http://localhost:38303.
Backend MessagingContribution.onStart took: 1.3 ms
Backend TaskBackendApplicationContribution.onStart took: 0.3 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 2049, context: /workspace/theia/packages/task/lib/node/../../test-resources
Opening channel for service path '/services/terminals/0'. [ID: 0]
    ✓ task running in terminal - expected data is received from the terminal ws server (1193ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Closing channel on service path '/services/terminals/0'. [ID: 0]
Theia app listening on http://localhost:42029.
Backend MessagingContribution.onStart took: 0.3 ms
Backend TaskBackendApplicationContribution.onStart took: 0.2 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 2136, context: /workspace/theia/packages/task/lib/node/../../test-resources
    ✓ task using raw process - task server success response shall not contain a terminal id (1012ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:37869.
Backend MessagingContribution.onStart took: 0.3 ms
Backend TaskBackendApplicationContribution.onStart took: 0.2 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 2141, context: /workspace/theia/packages/task/lib/node/../../test-resources
    ✓ task is executed successfully with cwd as a file URI (178ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:35915.
Backend MessagingContribution.onStart took: 0.3 ms
Backend TaskBackendApplicationContribution.onStart took: 0.2 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 2211, context: /workspace/theia/packages/task/lib/node/../../test-resources
    ✓ task is executed successfully using terminal process (185ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:38685.
Backend MessagingContribution.onStart took: 0.3 ms
Backend TaskBackendApplicationContribution.onStart took: 0.1 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 2283, context: undefined
    ✓ task is executed successfully using raw process
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:42701.
Backend MessagingContribution.onStart took: 0.3 ms
Backend TaskBackendApplicationContribution.onStart took: 0.1 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 2285, context: /workspace/theia/packages/task/lib/node/../../test-resources
    ✓ task without a specific runner is executed successfully using as a process
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:34859.
Backend MessagingContribution.onStart took: 0.2 ms
Backend TaskBackendApplicationContribution.onStart took: 0.1 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 2287, context: /workspace/theia/packages/task/lib/node/../../test-resources
    ✓ task can successfully execute command found in system path using a terminal process (177ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:34385.
Backend MessagingContribution.onStart took: 0.2 ms
Backend TaskBackendApplicationContribution.onStart took: 0.1 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 2364, context: /workspace/theia/packages/task/lib/node/../../test-resources
    ✓ task can successfully execute command found in system path using a raw process
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:33497.
Backend MessagingContribution.onStart took: 0.2 ms
Backend TaskBackendApplicationContribution.onStart took: 0.1 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 2366, context: /workspace/theia/packages/task/lib/node/../../test-resources
task INFO Killing task id 0
    ✓ task using type "shell" can be killed
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
(node:2039) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit
(node:2039) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
(node:2039) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added. Use emitter.setMaxListeners() to increase limit
Theia app listening on http://localhost:43087.
Backend MessagingContribution.onStart took: 0.4 ms
Backend TaskBackendApplicationContribution.onStart took: 0.1 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 2369, context: /workspace/theia/packages/task/lib/node/../../test-resources
task INFO Killing task id 0
    ✓ task using type "process" can be killed
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
(node:2039) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
Theia app listening on http://localhost:39335.
Backend MessagingContribution.onStart took: 0.3 ms
Backend TaskBackendApplicationContribution.onStart took: 0.1 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 2371, context: /workspace/theia/packages/task/lib/node/../../test-resources
    ✓ task using terminal process can handle command that does not exist (173ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:39271.
Backend MessagingContribution.onStart took: 0.3 ms
Backend TaskBackendApplicationContribution.onStart took: 0.3 ms
    ✓ task using raw process can handle command that does not exist
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
process ERROR Error: ENOENT
    at EventEmitter.<anonymous> (/workspace/theia/packages/process/lib/node/terminal-process.js:81:33)
    at EventEmitter.emit (events.js:198:13)
    at UnixTerminal.Terminal.emit (/workspace/theia/node_modules/@theia/node-pty/lib/terminal.js:132:42)
    at /workspace/theia/node_modules/@theia/node-pty/lib/unixTerminal.js:117:23
    at process._tickCallback (internal/process/next_tick.js:61:11)
task ERROR Error occurred while creating task: Error: Error starting process (ENOENT)
process WARN This process was not registered or was already unregistered. [ID: 0]
Theia app listening on http://localhost:44813.
Backend MessagingContribution.onStart took: 0.3 ms
Backend TaskBackendApplicationContribution.onStart took: 0.1 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 2443, context: aContext
task INFO Created new task, id: 1, process id: 1, OS PID: 2448, context: anotherContext
task INFO Created new task, id: 2, process id: 2, OS PID: 2455, context: aContext
task INFO Created new task, id: 3, process id: 3, OS PID: 2470, context: anotherContext
task INFO Created new task, id: 4, process id: 4, OS PID: 2481, context: aContext
task INFO Created new task, id: 5, process id: 5, OS PID: 2486, context: aContext
task INFO Killing task id 0
task INFO Killing task id 1
task INFO Killing task id 2
task INFO Killing task id 3
task INFO Killing task id 4
task INFO Killing task id 5
    ✓ getTasks(ctx) returns tasks according to created context (87ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:33723.
Backend MessagingContribution.onStart took: 0.2 ms
Backend TaskBackendApplicationContribution.onStart took: 0.2 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 2500, context: undefined
task INFO Created new task, id: 1, process id: 1, OS PID: 2515, context: undefined
task INFO Created new task, id: 2, process id: 2, OS PID: 2519, context: undefined
task INFO Created new task, id: 3, process id: 3, OS PID: 2530, context: undefined
task INFO Created new task, id: 4, process id: 4, OS PID: 2541, context: undefined
task INFO Created new task, id: 5, process id: 5, OS PID: 2554, context: undefined
task INFO Created new task, id: 6, process id: 6, OS PID: 2568, context: undefined
task INFO Created new task, id: 7, process id: 7, OS PID: 2576, context: undefined
task INFO Created new task, id: 8, process id: 8, OS PID: 2595, context: undefined
task INFO Created new task, id: 9, process id: 9, OS PID: 2611, context: undefined
task INFO Created new task, id: 10, process id: 10, OS PID: 2628, context: undefined
task INFO Created new task, id: 11, process id: 11, OS PID: 2650, context: undefined
task INFO Created new task, id: 12, process id: 12, OS PID: 2671, context: undefined
task INFO Created new task, id: 13, process id: 13, OS PID: 2687, context: undefined
task INFO Created new task, id: 14, process id: 14, OS PID: 2715, context: undefined
task INFO Created new task, id: 15, process id: 15, OS PID: 2741, context: undefined
task INFO Created new task, id: 16, process id: 16, OS PID: 2763, context: undefined
task INFO Created new task, id: 17, process id: 17, OS PID: 2784, context: undefined
task INFO Created new task, id: 18, process id: 18, OS PID: 2817, context: undefined
task INFO Created new task, id: 19, process id: 19, OS PID: 2871, context: undefined
task INFO Killing task id 0
    1) creating and killing a bunch of tasks works as expected
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
process WARN This process was not registered or was already unregistered. [ID: 8]
process WARN This process was not registered or was already unregistered. [ID: 0]
process WARN This process was not registered or was already unregistered. [ID: 9]
process WARN This process was not registered or was already unregistered. [ID: 14]
process WARN This process was not registered or was already unregistered. [ID: 2]
process WARN This process was not registered or was already unregistered. [ID: 15]
process WARN This process was not registered or was already unregistered. [ID: 6]
process WARN This process was not registered or was already unregistered. [ID: 12]
process WARN This process was not registered or was already unregistered. [ID: 11]
process WARN This process was not registered or was already unregistered. [ID: 10]
process WARN This process was not registered or was already unregistered. [ID: 3]
process WARN This process was not registered or was already unregistered. [ID: 7]
process WARN This process was not registered or was already unregistered. [ID: 5]
process WARN This process was not registered or was already unregistered. [ID: 4]
process WARN This process was not registered or was already unregistered. [ID: 1]
process WARN This process was not registered or was already unregistered. [ID: 16]
process WARN This process was not registered or was already unregistered. [ID: 19]
process WARN This process was not registered or was already unregistered. [ID: 18]
process WARN This process was not registered or was already unregistered. [ID: 17]
process WARN This process was not registered or was already unregistered. [ID: 13]
Theia app listening on http://localhost:38705.
Backend MessagingContribution.onStart took: 0.4 ms
Backend TaskBackendApplicationContribution.onStart took: 0.2 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 3443, context: undefined
    ✓ shell task should execute the command as a whole if not arguments are specified (381ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:46781.
Backend MessagingContribution.onStart took: 0.2 ms
Backend TaskBackendApplicationContribution.onStart took: 0.2 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 3518, context: undefined
    ✓ shell task should fail if user defines a full command line and arguments (194ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:35167.
Backend MessagingContribution.onStart took: 0.3 ms
Backend TaskBackendApplicationContribution.onStart took: 0.2 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 3589, context: undefined
    ✓ shell task should be able to exec using simple arguments (403ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:45593.
Backend MessagingContribution.onStart took: 0.5 ms
Backend TaskBackendApplicationContribution.onStart took: 0.2 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 3664, context: undefined
    ✓ shell task should be able to run using arguments containing whitespace (418ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:38601.
Backend MessagingContribution.onStart took: 0.3 ms
Backend TaskBackendApplicationContribution.onStart took: 0.2 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 3739, context: undefined
    ✓ shell task will fail if user specify problematic arguments (186ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:43717.
Backend MessagingContribution.onStart took: 0.3 ms
Backend TaskBackendApplicationContribution.onStart took: 0.1 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 3810, context: undefined
    ✓ shell task should be able to run using arguments specifying which quoting method to use (392ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Theia app listening on http://localhost:43419.
Backend MessagingContribution.onStart took: 0.2 ms
Backend TaskBackendApplicationContribution.onStart took: 0.1 ms
task INFO Created new task, id: 0, process id: 0, OS PID: 3885, context: undefined
    ✓ shell task should be able to run using arguments with forbidden characters but no whitespace (1423ms)
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.


  30 passing (17s)
  1 failing

  1) Task server / back-end
       creating and killing a bunch of tasks works as expected:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/workspace/theia/packages/task/lib/node/task-server.slow-spec.js)
  



>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
>>> Stopping backend contributions...
<<< All backend contributions have been stopped.
Exit with failure status (1): nyc mocha --opts ../../configs/mocha.opts "./lib/**/*.*spec.js"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
gitpod /workspace/theia $ 
```

**Comment by kittaakos** [comment]
@marechal-p, I did some further investigation, and as I [wrote](https://github.com/eclipse-theia/theia/pull/6836#issuecomment-633586546) on your PR, it seems it breaks the task tests.

 1. Checkout your PR and run the tests. They fail:
  ```
git clone https://github.com/eclipse-theia/theia.git \
&& cd theia \
&& git checkout origin/mp/shell-escape -b mp/shell-escape \
&& yarn \
&& yarn --cwd ./packages/task test
  ```

 2. Go back one in time and re-run the tests, they're green:
  ```
git reset --hard HEAD~1 \
&& yarn \
&& yarn --cwd ./packages/task test
  ```

Can you please look into them?

**Comment by kittaakos** [comment]
OK, it seems like this problem is related to the default shell. I will look into it.
