### ISSUE TITLE
[TS] VS Code TS extension throws various errors

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7840]
### Bug Description:

I can see various errors when I run Theia and open `os.ts`:

```
root ERROR [hosted-plugin: 26264] Promise rejection not handled in one second: TypeError: i.workspace.onDidRenameFiles is not a function , reason: TypeError: i.workspace.onDidRenameFiles is not a function
root ERROR [hosted-plugin: 26264] With stack trace: TypeError: i.workspace.onDidRenameFiles is not a function
    at new e (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:56306)
    at s.u.VersionDependentRegistration [as _doRegister] (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:59522)
    at s.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:13813)
    at t.VersionDependentRegistration.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:14282)
    at new t.VersionDependentRegistration (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:14081)
    at Object.t.register (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:59468)
    at Promise.resolve.then.then.e (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:104770)
    at process._tickCallback (internal/process/next_tick.js:68:7)
root ERROR [hosted-plugin: 26264] Promise rejection not handled in one second: TypeError: r.SemanticTokensLegend is not a constructor , reason: TypeError: r.SemanticTokensLegend is not a constructor
With stack trace: TypeError: r.SemanticTokensLegend is not a constructor
    at a.getLegend (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:183036)
    at s.i.VersionDependentRegistration [as _doRegister] (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:182876)
    at s.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:13813)
    at t.VersionDependentRegistration.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:14282)
    at new t.VersionDependentRegistration (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:14081)
    at Object.t.register (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:182733)
    at Promise.all.Promise.resolve.then.then.t (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:130528)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Promise rejection not handled in one second: TypeError: r.SemanticTokensLegend is not a constructor , reason: TypeError: r.SemanticTokensLegend is not a constructor
With stack trace: TypeError: r.SemanticTokensLegend is not a constructor
    at a.getLegend (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:183036)
    at s.i.VersionDependentRegistration [as _doRegister] (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:182876)
    at s.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:13813)
    at t.VersionDependentRegistration.update (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:14282)
    at new t.VersionDependentRegistration (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:14081)
    at Object.t.register (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:182733)
    at Promise.all.Promise.resolve.then.then.t (/Users/akos.kitta/git/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:130528)
    at process._tickCallback (internal/process/next_tick.js:68:7)
root INFO [nsfw-watcher: 26261] Started watching: /Users/akos.kitta/git/theia/tsconfig.json
root ERROR [hosted-plugin: 26264] Promise rejection not handled in one second: undefined , reason: undefined
root INFO [nsfw-watcher: 26261] Stopped watching: /Users/akos.kitta/git/theia/tsconfig.json
```

It happened on macOS, but I had the same issue on Windows too.

### Steps to Reproduce:

1. Clone Theia (bb43e9e).
2. Open `theia` in the workspace.
3. Open `os.ts`.

### Additional Information

- Operating System:
- Theia Version:

**Comment by akosyakov** [comment]
They are tracked in https://github.com/eclipse-theia/theia/issues/7171 and https://github.com/eclipse-theia/theia/issues/7697
