### ISSUE TITLE
"Delete Line" Keybinding does not work

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#7888]
### Bug Description:
The default shortcut for "delete line" (ctrl-shift-k) does not work

### Steps to Reproduce:

1. Open any editor
2. Press shift-ctrl-k
3. Observe: nothing happens

### Additional Information
- Operating System: Windows 10, FF and chromium
- Theia Version: master

**Comment by tsmaeder** [comment]
I can rebind the command to another keybinding and it works, so it seem it's not the command that's broken.

**Comment by kittaakos** [comment]
I tried it on macOS to see whether itΩ is a Windows-only issue; it isn't. We incorrectly execute the `Run Last Task` command which fails, by the way:

```
root ERROR Failed to execute command: Error: The command 'task:run:last' cannot be executed. There are no active handlers available for the command. (args: [null])
    at CommandRegistry.<anonymous> (http://localhost:3000/bundle.js:134855:45)
    at step (http://localhost:3000/bundle.js:134624:23)
    at Object.next (http://localhost:3000/bundle.js:134605:53)
    at http://localhost:3000/bundle.js:134599:71
    at new Promise (<anonymous>)
    at ../../packages/core/lib/common/command.js.__awaiter (http://localhost:3000/bundle.js:134595:12)
    at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (http://localhost:3000/bundle.js:134837:16)
    at KeybindingRegistry.../../packages/core/lib/browser/keybinding.js.KeybindingRegistry.executeKeyBinding (http://localhost:3000/bundle.js:111915:38)
    at KeybindingRegistry.../../packages/core/lib/browser/keybinding.js.KeybindingRegistry.run (http://localhost:3000/bundle.js:112007:22)
    at HTMLDocument.<anonymous> (http://localhost:3000/bundle.js:110218:35)
```

**Comment by akosyakov** [comment]
The task extension depends on the monaco extension, so it registers keybindings afterwards. Since we aligned with VS Code for keybindings resolution, a keybinding registered later for the same scope has a higher priority now. The fix is to add a proper `when` closure or remove a keybinding in the task extension. I will do the former.

It was working before because we treated keybindings with `context` property to be of higher priority regardless of order registration or scopes.

**Comment by tsmaeder** [comment]
The keybinding for "run last task" shows up as "ctrlcmd+k", not "ctrl+k" in the keybindings UI. Not sure what the difference is.

**Comment by akosyakov** [comment]
> The keybinding for "run last task" shows up as "ctrlcmd+shift+k", not "ctrl+shift+k" in the keybindings UI. Not sure what the difference is.

I think it is correct, we detect your keyboard layout and then resolves the keybinding against it.

**Comment by tsmaeder** [comment]
Hmh...I don't see a "ctrlcmd" key on my keyboard. Is that like "Alt-Gr"?

**Comment by akosyakov** [comment]
> Hmh...I don't see a "ctrlcmd" key on my keyboard. Is that like "Alt-Gr"?

It is `ctrl` on linux and windows, and `cmd` on mac.
