### ISSUE TITLE
[debug][quick-pick] Cannot cancel "Attach by process ID" 

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7915]
### Bug Description:

Start the "Attach by process ID" launch config, try to cancel it by pressing `Esc` when the _Command Pallette_ is open. It results in an error.

![screencast 2020-05-28 15-18-09](https://user-images.githubusercontent.com/1405703/83146829-1cdf8b80-a0f7-11ea-91f5-b206ec58526b.gif)

```
root ERROR Failed to resolved 'command:PickProcess' variable Error: The command 'PickProcess' cannot be executed. There are no active handlers available for the command.
    at CommandRegistry.<anonymous> (http://localhost:3000/bundle.js:134849:45)
    at step (http://localhost:3000/bundle.js:134618:23)
    at Object.next (http://localhost:3000/bundle.js:134599:53)
    at http://localhost:3000/bundle.js:134593:71
    at new Promise (<anonymous>)
    at ../../packages/core/lib/common/command.js.__awaiter (http://localhost:3000/bundle.js:134589:12)
    at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (http://localhost:3000/bundle.js:134831:16)
    at CommonVariableContribution.<anonymous> (http://localhost:3000/96.bundle.js:149:76)
    at step (http://localhost:3000/96.bundle.js:67:23)
    at Object.next (http://localhost:3000/96.bundle.js:48:53)
```

### Steps to Reproduce:

1. Start the "Attach by process ID"
2. Change your mind and press `Esc`, I had to press three times, then got the error.

### Additional Information

- Operating System:
- Theia Version:

**Comment by FernandoAscencio** [comment]
This seems to have changed. I think a previous version had an error appear in the terminal.
In both cases, cancelling the "Attach Process By ID" happens by clicking out of the quick-input or by `esc`.

![Issue7915](https://user-images.githubusercontent.com/48699277/226692653-2e1a9773-057f-4705-94b2-a64219f4bbeb.gif)
