### ISSUE TITLE
[debug] Undoing in editor when the debugger runs throws an error.

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7939]
### Bug Description:

Undoing in a file during a debug session throws an error:
```
root ERROR Error: Illegal value for lineNumber
    at TextModel.getLineFirstNonWhitespaceColumn (http://localhost:3000/vs/editor/editor.main.js:70430:23)
    at DebugEditorModel.push.../../packages/debug/lib/browser/editor/debug-editor-model.js.DebugEditorModel.createCurrentBreakpointDecoration (http://localhost:3000/47.bundle.js:3199:104)
    at http://localhost:3000/47.bundle.js:3192:69
    at Array.map (<anonymous>)
    at DebugEditorModel.push.../../packages/debug/lib/browser/editor/debug-editor-model.js.DebugEditorModel.createCurrentBreakpointDecorations (http://localhost:3000/47.bundle.js:3192:28)
    at DebugEditorModel.push.../../packages/debug/lib/browser/editor/debug-editor-model.js.DebugEditorModel.renderCurrentBreakpoints (http://localhost:3000/47.bundle.js:3186:32)
    at DebugEditorModel.push.../../packages/debug/lib/browser/editor/debug-editor-model.js.DebugEditorModel.render (http://localhost:3000/47.bundle.js:3144:14)
    at DebugEditorService.push.../../packages/debug/lib/browser/editor/debug-editor-service.js.DebugEditorService.render (http://localhost:3000/47.bundle.js:3622:19)
    at http://localhost:3000/47.bundle.js:3600:23
    at http://localhost:3000/bundle.js:135565:33
```

### Steps to Reproduce:

1. Have a valid JS file. Modify the module content to have a valid JS file with different content.
2. Start debugger. Hit a breakpoint in the module.
3. Do several undos.

### Additional Information

- Operating System:
- Theia Version:

**Comment by kittaakos** [comment]
> 1. Have a valid JS file.

```js
let sum = 0;
for (let i = 0; i < 10; i++) {
    sum = sum + 0;
}

console.log();
```

> Modify the module content to have a valid JS file with different content.
```js
let sum = 0;
for (let i = 0; i < 10; i++) {
    sum = sum + 0;
    console.log(sum);
    for (let j = 0; j < 10; j++) {
        sum += i;
    }
}

console.log(sum); // <---- Set the breakpoint here and start debbugging.
```

> 3\. Do several undos.

It's fine to do one, and revert the longer module to the initial one. The trick is that the breakpoint's line number exceeds the module content.
