### ISSUE TITLE
[native-keymap node-gyp ubuntu] Failed to install dependencies on master branch

### ISSUE THREAD

**Issue by sombreroEnPuntas** [eclipse-theia/theia#8009]
### Bug Description:
Just checked-out current master and tried to install deps with `yarn`, but it fails.

### Already tried

- Different versions of node, npm & yarn
- nsfw resolution as suggested [here](https://github.com/eclipse-theia/theia/issues/7510#issuecomment-610398175)

### Steps to Reproduce:

1. Open a terminal console
2. Run `git clone https://github.com/eclipse-theia/theia && cd theia && yarn`
3. Installation fails

### Additional Information
- OS Ubuntu 18.04.4
- node v10.20.1
- yarn v1.22.4
- npm v6.14.4

### Logs
```
$ yarn
yarn install v1.22.4
$ node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.20.1 | linux | x64
gyp http GET https://nodejs.org/download/release/v10.20.1/node-v10.20.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.20.1/node-v10.20.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.20.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.20.1/SHASUMS256.txt
10.20.1
gyp info ok 
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "nsfw@1.2.7" is incompatible with requested version "nsfw@^1.2.9"
[3/5] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
warning monaco-languageclient@0.13.0: The engine "vscode" appears to be invalid.
warning vscode-languageclient@6.1.0: The engine "vscode" appears to be invalid.
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > chai-string@1.5.0" has unmet peer dependency "chai@^4.1.2".
warning "workspace-aggregator-4d251d7d-eace-4744-ad32-20f99072d887 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-4d251d7d-eace-4744-ad32-20f99072d887 > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-4d251d7d-eace-4744-ad32-20f99072d887 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-4d251d7d-eace-4744-ad32-20f99072d887 > @theia/messages > react-perfect-scrollbar@1.5.3" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-4d251d7d-eace-4744-ad32-20f99072d887 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-4d251d7d-eace-4744-ad32-20f99072d887 > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-4d251d7d-eace-4744-ad32-20f99072d887 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
[1/13] ⠂ command-join
[7/13] ⠂ nsfw
[6/13] ⠂ native-keymap
[4/13] ⠂ puppeteer
error ~/Projects/theia/node_modules/native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: ~/Projects/theia/node_modules/native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.20.1 | linux | x64
gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [ '~/Projects/theia/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '~/Projects/theia/node_modules/native-keymap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '~/Projects/theia/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '~/.cache/node-gyp/10.20.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=~/.cache/node-gyp/10.20.1',
gyp info spawn args   '-Dnode_gyp_dir=~/Projects/theia/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=~/.cache/node-gyp/10.20.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=~/Projects/theia/node_modules/native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config x11 xkbfile --cflags | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (~/Projects/theia/node_modules/electron-rebuild/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.0.0-1059-oem-osp1
gyp ERR! command "~/.nvm/versions/node/v10.20.1/bin/node" "~/Projects/theia/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd ~/Projects/theia/node_modules/native-keymap
```

**Comment by sombreroEnPuntas** [comment]
@akosyakov wow! fast response time :)

> :thinking: needs more info

What extra info could I add to clarify?

**Comment by kittaakos** [comment]
@sombreroEnPuntas, please see the requirements here: https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites

`pkg-config` is missing on your env as I see. Please check and get back to us if it still does not work. Thanks!

**Comment by sombreroEnPuntas** [comment]
ahá, thanks a lot!
Followed the instructions and it works :tada: 
A good'ol case of RTFM :)

**Note:**
I am a bit surprised tho: installing dependencies (`yarn` command) should not build the project...
Might be a matter of personal taste, but build step should be explicitly separated from install.

**Comment by sombreroEnPuntas** [comment]
Shall I open a suggestion or another issue for splitting install and build steps?
Can also contribute with a PR if that's an accepted proposal :scroll:

**Comment by akosyakov** [comment]
> Shall I open a suggestion or another issue for splitting install and build steps?

Probably it is matter of the taste, but i don't want to change it.
