### ISSUE TITLE
[python]Problems with starting ms-python VSCode extension

### ISSUE THREAD

**Issue by svor** [eclipse-theia/theia#8022]
### Bug Description:
I tried to use latest [Python extension for Visual Studio Code](https://github.com/microsoft/vscode-python). For this moment it's [2020.5.86806](https://github.com/microsoft/vscode-python/releases/tag/2020.5.86806).
But got some issues during the initialization and as a result latest python extension doesn't work with theia:

- [x] **Unsupported activation events**
depends on  `CustomEditor API` https://github.com/eclipse-theia/theia/issues/6636
```log
root ERROR [hosted-plugin: 16582] Unsupported activation events: onCustomEditor:NativeEditorProvider.ipynb, please open an issue: https://github.com/eclipse-theia/theia/issues/new
root ERROR [hosted-plugin: 16582] ms-python.python extension will be activated eagerly.
```

- [x] **Cannot read property 'Web' of undefined**
depends on `UIKind API` https://github.com/eclipse-theia/theia/pull/8038
```log
root ERROR [hosted-plugin: 20967] Error Python Extension: 2020-06-16 15:27:22: Failure during activation. TypeError: Cannot read property 'Web' of undefined
    at e.getCommonProperties (/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:16:117498)
    at e.createAppInsightsClient (/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:16:116688)
    at e.updateUserOptIn (/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:16:116164)
    at new e (/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:16:115806)
    at /tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:1:11232
    at Object.l [as sendTelemetryEvent] (/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:1:11263)
    at Function.getInstance (/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:16:246621)
    at f.getSettings (/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:46:497842)
    at /tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:39:6106
```

- [x] **No available file system provider for schema file**
depends on `vscode.workspace.fs API` https://github.com/eclipse-theia/theia/pull/7908
```log
root ERROR [hosted-plugin: 20967] Error Python Extension: 2020-06-16 15:27:22: stat() failed for "/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js.map.disabled" { Error: 'No available file system provider for schema file
    at FileSystemMainImpl.push.../../packages/plugin-ext/lib/main/browser/file-system-main.js.FileSystemMainImpl.getHandle (http://localhost:3000/57.bundle.js:4718:19)
    at FileSystemMainImpl.<anonymous> (http://localhost:3000/57.bundle.js:4728:31)
    at step (http://localhost:3000/57.bundle.js:4665:23)
    at Object.next (http://localhost:3000/57.bundle.js:4646:53)
    at http://localhost:3000/57.bundle.js:4640:71
    at new Promise (<anonymous>)
    at push.../../packages/plugin-ext/lib/main/browser/file-system-main.js.__awaiter (http://localhost:3000/57.bundle.js:4636:12)
    at FileSystemMainImpl.push.../../packages/plugin-ext/lib/main/browser/file-system-main.js.FileSystemMainImpl.$stat (http://localhost:3000/57.bundle.js:4724:16)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (http://localhost:3000/41.bundle.js:875:23)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.invokeHandler (http://localhost:3000/41.bundle.js:860:41)
  name: 'Error',
  message: '\'No available file system provider for schema file' }
```

### Steps to Reproduce:

1. Download latest python extension from https://github.com/microsoft/vscode-python/releases and put it into plugins folder
2. Start Theia and try to open simple python file

### Additional Information

- Operating System: Linux Mint 19.3 Cinnamon
- Theia Version: @theia/example-browser 1.2.0

**Comment by kittaakos** [comment]
Same as https://github.com/eclipse-theia/theia/issues/7999?

>  No available file system provider for schema file

Here is the  WIP PR for the VS Code FS API: https://github.com/eclipse-theia/theia/pull/7908

**Comment by akosyakov** [comment]
First issue is tracked in https://github.com/eclipse-theia/theia/issues/6636. Second issue is new. The last is being worked on in https://github.com/eclipse-theia/theia/pull/7908.

**Comment by azatsarynnyy** [comment]
I've updated the description with the corresponding issues.
We (at Red Hat) are going to start working on `CustomEditor API` https://github.com/eclipse-theia/theia/issues/6636

**Comment by azatsarynnyy** [comment]
> Cannot read property 'Web' of undefined

this one should be fixed by https://github.com/eclipse-theia/theia/pull/8038

**Comment by nickboldt** [comment]
When do we think this will be fixed? Looking for a Che milestone so we can map that to a CRW release. Ideally, Che-theia 7.20, if possible?

**Comment by azatsarynnyy** [comment]
I updated the description with these two API already implemented:
- `UIKind` API - Cannot read property 'Web' of undefined
- `vscode.workspace.fs` API - No available file system provider for schema file

**Comment by azatsarynnyy** [comment]
> Unsupported activation events

About this one, I haven't seen it when I was trying the plugin here https://github.com/eclipse-theia/theia/issues/3186#issuecomment-701375009

**Comment by djmaze** [comment]
As the `CustomEditor API` [is now implemented](https://github.com/eclipse-theia/theia/pull/8910), does the extension now work?

**Comment by azatsarynnyy** [comment]
> As the `CustomEditor API` [is now implemented](https://github.com/eclipse-theia/theia/pull/8910), does the extension now work?

Hello @djmaze, when I tried it [here](https://github.com/eclipse-theia/theia/issues/3186#issuecomment-701375009) it was working well. In Google Chrome at least.

**Comment by azatsarynnyy** [comment]
I'm closing this one. Feel free to reopen if more work should be done here.
