### ISSUE TITLE
[test][git][windows] Flaky git test on windows.

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8023]
### Bug Description:

The Windows CI has failed for a completely unrelated [PR](https://github.com/eclipse-theia/theia/pull/8013):
```
  1) git
       branch
         should list the branch in chronological order:
      AssertionError: expected [ 'a', 'b', 'c', 'master' ] to deeply equal [ 'master', 'c', 'b', 'a' ]
      + expected - actual
       [
      +  "master"
      +  "c"
      +  "b"
         "a"
      -  "b"
      -  "c"
      -  "master"
       ]
      
      at Suite.<anonymous> (lib\node\dugite-git.spec.js:1331:126)
      at step (lib\node\dugite-git.spec.js:48:23)
      at Object.next (lib\node\dugite-git.spec.js:29:53)
      at fulfilled (lib\node\dugite-git.spec.js:20:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    at Promise.all.then.arr (C:\Users\travis\build\eclipse-theia\theia\node_modules\execa\index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  killed: false,
  stdout:
```

Build: https://travis-ci.com/github/eclipse-theia/theia/jobs/349708817

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by kittaakos** [comment]
The Git version has changed on Travis from `2.25.0.windows.1` to `2.27.0.windows.1`.

**Comment by kittaakos** [comment]
I had `2.24.1.windows.2` locally, the tests passed, then I installed `2.27.0.windows.1`, ran the tests, they still passed. I am not sure if this is related to the Git version.

**Comment by kittaakos** [comment]
> I am not sure if this is related to the Git version.

It is, finally, I managed to reproduce it manually.

**Comment by vince-fugnitto** [comment]
@kittaakos do we close the issue or do we keep it open to track fixing the actual test?

**Comment by kittaakos** [comment]
> do we keep it open to track fixing the actual test?

+1 for keeping it open; it won't hurt. What do you think, @vince-fugnitto?

**Comment by vince-fugnitto** [comment]
> > do we keep it open to track fixing the actual test?
> 
> +1 for keeping it open; it won't hurt. What do you think, @vince-fugnitto?

Sounds good to me :)

**Comment by marcdumais-work** [comment]
Hummm - just noticed this issue. For me it's happening on my Ubuntu 16.04 desktop, with similar git version:
```
$ git --version
git version 2.27.0
```

```
43 passing (17s)
  3 pending
  1 failing

  1) git
       branch
         should list the branch in chronological order:

      AssertionError: expected [ 'a', 'b', 'c', 'master' ] to deeply equal [ 'master', 'c', 'b', 'a' ]
      + expected - actual

       [
      +  "master"
      +  "c"
      +  "b"
         "a"
      -  "b"
      -  "c"
      -  "master"
       ]
      
      at Context.<anonymous> (lib/node/dugite-git.spec.js:1336:130)
      at step (lib/node/dugite-git.spec.js:48:23)
      at Object.next (lib/node/dugite-git.spec.js:29:53)
      at fulfilled (lib/node/dugite-git.spec.js:20:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

So maybe just version-related and not Windows-specific?

**Comment by sgraband** [comment]
`@theia/git` is officially deprecated per README.
