### ISSUE TITLE
The first stackframe response is very slow during plugin debugging. 

### ISSUE THREAD

**Issue by xieyuanhuata** [eclipse-theia/theia#8062]
### Bug Description:
When I add a debugging breakpoint to the scaffolding build plug-in and use Debug Instance to debug the plug-in, the breakpoint cannot be accessed for a long time and CALL STACK is empty until 5 minutes later. 
During the debugging, the following error information is displayed on the background for multiple times: 
root ERROR [hosted-plugin: 14390] ApplicationInsights:CorrelationIdManager [ { Error: connect ETIMEDOUT 52.231.18.241:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '52.231.18.241',
    port: 443 } ]
root ERROR [hosted-plugin: 14403] ApplicationInsights:CorrelationIdManager [ { Error: connect ETIMEDOUT 52.231.18.241:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '52.231.18.241',
    port: 443 } ]
root ERROR [hosted-plugin: 14521] ApplicationInsights:CorrelationIdManager [ { Error: connect ETIMEDOUT 52.231.18.241:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '52.231.18.241',
    port: 443 } ]
root ERROR TypeError: Failed to fetch
root ERROR [hosted-plugin: 15320] ApplicationInsights:CorrelationIdManager [ { Error: connect ETIMEDOUT 52.231.18.241:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '52.231.18.241',
    port: 443 } ]

### Steps to Reproduce:

1.npm install -g yo @theia/generator-plugin
2.mkdir theia-hello-world-plugin
3.cd theia-hello-world-plugin
4.yo @theia/plugin
5.add breakpoint
6.F1--->Select "Hosted Plugin: Debug Instance"

The breakpoint takes effect after about 5 minutes.

### Additional Information

- Operating System:
ubuntu18.0
- Theia Version:
1.1.0

**Comment by xieyuanhuata** [comment]
The result is that vscode-node-debug2 uses telemetry for message interaction when debugging TS code. When Telemetry is enabled, TypeScript reports information to the Microsoft ApplicationInsights service. Is there a switch to control the Telemetry function in theia? 

https://code.visualstudio.com/docs/supporting/FAQ#_how-to-disable-telemetry-reporting

**Comment by xieyuanhuata** [comment]
This problem greatly affects user experience and may cause user privacy leakage.

**Comment by marcdumais-work** [comment]
Hi @xieyuanhuata ,

Thanks for reporting this and updating with subsequent findings. Someone would need to look-into the `node-debug2` extension to try to understand how to disable its telemetry. There are a few other VS Code built-ins that might also need to be investigated. 

Something that might work at least as a temporary work-around would be try as suggested in [this post](https://github.com/eclipse-theia/theia/issues/8062#issuecomment-647244758) and add something like the following to your hosts file:
```
0.0.0.0 dc.services.visualstudio.com
0.0.0.0 marketplace.visualstudio.com
0.0.0.0 dc.trafficmanager.net
0.0.0.0 vortex.data.microsoft.com
0.0.0.0 weu-breeziest-in.cloudapp.net
```

Note: we do not have the VS Code Telemetry service in Theia, so I expect that the related preferences suggested in the same post would not help for a Theia application.

**Comment by danarad05** [comment]
Hi @xieyuanhuata 
I'm working on this issue and trying to reproduce issue - trying to find requests to dc.services.visualstudio.com when debugging - till now unsuccessfully - can't find any request to that url.

Could you elaborate exactly what steps you are taking in reproducing issue? any screen caps, network log, anything that would help me reproduce issue (I saw your steps above but till now not able to reproduce issue following them). 

Thanks
