### ISSUE TITLE
VS Code Extension hashicorp.terraform can't launch language server

### ISSUE THREAD

**Issue by meysholdt** [eclipse-theia/theia#8064]
The VS Code Extension hashicorp.terraform can't start it's language server.

### Steps to Reproduce:

1. install the extension in theia
2. trigger command: "Terraform: activate language server"
3. find the following stack trace in the logs:

```
"[hosted-plugin: 1661] TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
    at checkListener (events.js:54:11)
    at ClientRequest.once (events.js:290:3)
    at new ClientRequest (_http_client.js:151:10)
    at Object.request (https.js:281:10)
    at Object.request (/tmp/vscode-extensions/vscode.@theia!vscode-builtin-npm@0.2.1/package/dist/main.js:1:37885)
    at Promise (/tmp/vscode-extensions/hashicorp.terraform@2.0.1/extension/out/languageServerInstaller.js:81:35)
    at new Promise (<anonymous>)
    at LanguageServerInstaller.checkCurrent (/tmp/vscode-extensions/hashicorp.terraform@2.0.1/extension/out/languageServerInstaller.js:80:16)
    at cp.exec (/tmp/vscode-extensions/hashicorp.terraform@2.0.1/extension/out/languageServerInstaller.js:30:30)
    at ChildProcess.exithandler (child_process.js:301:5)"
```

see [LanguageServerInstaller.checkCurrent](https://github.com/hashicorp/vscode-terraform/blob/7fd81ed6d40c93cfb9129515d58f2a0ac6216fa0/src/languageServerInstaller.ts#L64).ts
see [languageServerInstaller.js:81](https://github.com/hashicorp/vscode-terraform/blob/v2.0.1/out/languageServerInstaller.js#L81)

### Additional Information

- Extension Version: `hashicorp.terraform@2.0.1:xJnAlwGKsLYCzp4WPmt7UQ==`
- Theia Version: `"name": "@theia/core",  "version": "1.2.0-next.99a7aa3c"`

**Comment by vince-fugnitto** [comment]
@meysholdt looking at the repo's history and opened issues it looks like the extension itself has a lot of problems at the moment (language server crashes, extension failing to work), so maybe it is expected that it does not work correctly right now.

**Comment by jylenhof** [comment]
This plugin is now managed by hashicorp, so it's working again with vscode.

But I do have quite the same message when trying it again :
Activating extension 'HashiCorp Terraform' failed: The "listener" argument must be of type function. Received an instance of Object

**Comment by WillBeebe** [comment]
I'm getting the same error.

**Comment by zhongwaw** [comment]
I'm getting same message when trying hashicorp.terraform in theia:
Activating extension 'HashiCorp Terraform' failed: The "listener" argument must be of type function.
Does anyone know what causes this issue and how to fix it?

**Comment by vince-fugnitto** [comment]
Which version of the [`hashicorp.terraform`](https://open-vsx.org/extension/hashicorp/terraform) extension are you using in your case?
I verified with version `v2.14.0` (latest compatible) and after manually installing the `terraform-ls` and `terraform` cli the language server correctly started and worked.
