### ISSUE TITLE
[electron] Error when executing `core.close.main.tab` command without opened editors

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8127]
### Bug Description:

I do not know if this is an error in the browser. In electron, I get an error when I try to close all editors with `CtrCmd+W` on macOS when there are not opened editors.

```
root ERROR Failed to execute command: Error: The command 'core.close.main.tab' cannot be executed. There are no active handlers available for the command. (args: [null])
    at CommandRegistry.<anonymous> (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:125121:45)
    at step (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:124890:23)
    at Object.next (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:124871:53)
    at file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:124865:71
    at new Promise (<anonymous>)
    at ../../packages/core/lib/common/command.js.__awaiter (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:124861:12)
    at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:125103:16)
    at KeybindingRegistry.../../packages/core/lib/browser/keybinding.js.KeybindingRegistry.executeKeyBinding (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:102713:38)
    at KeybindingRegistry.../../packages/core/lib/browser/keybinding.js.KeybindingRegistry.run (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:102805:22)
    at HTMLDocument.<anonymous> (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:101040:35)
```

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by mikael-desharnais** [comment]
I confirm that this bug can be reproduced in the browser (chrome in my case) on Windows 10

**Comment by mikael-desharnais** [comment]
This problem is not limited to the close tab command, any command that can be enabled/disabled according to the application state may end up in this case.
In my opinion, there are two solutions this problem :
First :  to change the Error into a Warning or even an Info so that a call to command without a Handler would simply result in a message in the console instead of an error
Second : throw an Error if a command has no handlers at all but display an Info or Warning if a command has handlers but none of them are enabled.

**Comment by FernandoAscencio** [comment]
This does not occur on windows electron at the moment. Seems to have been fixed.

**Comment by sgraband** [comment]
Command has proper `isEnabled` guard.
