### ISSUE TITLE
The Theia explorer stops creating and deleting files or folders

### ISSUE THREAD

**Issue by anavarre** [eclipse-theia/theia#8140]
### Bug Description:

I have a Cypress test that does something very simple: it creates a file, then checks the code highlights within the file in the source code editor, then deletes the file. It works great, until **Theia stops creating or deleting any file / folder in the explorer, either via the test or manually**. I tried via the menu item or via the contextual menu and it always fails after clicking okay on the dialog window. Only creating/deleting files/folder via the terminal works. Every time I don't have a choice but to delete the IDE and create another one because it became unusable.

I can't find any related error in the console, the one below happens even when NOT trying to create/delete files/folders.

```
logger-protocol.ts:112 root ERROR TypeError: Cannot read property 'nextSibling' of null
    at https://mytest.ide/bundle.js:1:931030
    at Object.e [as updateContent] (https://mytest.ide/bundle.js:1:931051)
    at Object.e.render (https://mytest.ide/bundle.js:1:930068)
    at t.onUpdateRequest (https://mytest.ide/bundle.js:49:112633)
    at t.e.processMessage (https://mytest.ide/bundle.js:1:158323)
    at h (https://mytest.ide/bundle.js:1:164714)
    at n (https://mytest.ide/bundle.js:1:163766)
    at g (https://mytest.ide/bundle.js:1:164946)
e.log @ css.js:1
(anonymous) @ reconnecting-websocket-mjs.js:17
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
Promise.then (async)
e.log @ bundle.js:1
n @ bundle.js:1
l @ bundle.js:1
h @ bundle.js:1
n @ bundle.js:1
g @ bundle.js:1
requestAnimationFrame (async)
m @ bundle.js:1
t.postMessage @ bundle.js:1
e.update @ bundle.js:1
set @ Reflect.js:15
t._evtMouseMove @ Reflect.js:15
t.handleEvent @ Reflect.js:15
```

### Steps to Reproduce:

1. Try to create / delete a `test.php` file in the explorer. Repeat 10-20 times. Ideally try it with Cypress so it's automated.
2. Observe at some point creating / deleting the file will stop working
3. Taking it from there, do it manually to confirm it applies for not only files but folders as well

### Additional Information

![theia-file-folder-creation-deletion-issue](https://user-images.githubusercontent.com/293478/86565003-68435000-bf67-11ea-96b1-76940ac88c20.gif)

- Operating System: KDE Neon
- Theia Version: Theia 1.2.0

**Comment by akosyakov** [comment]
It would be helpful if someone adds an integration test reproducing it.

**Comment by datou0412** [comment]
I have encountered this situation many times, restart theia server works.
