### ISSUE TITLE
[core] Unregistering a command should automatically remove all UI contributions, such as menu actions

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8175]
### Bug Description:

When I unregister a command but do not explicitly unregister the corresponding menu action, an error is thrown at the app startup. It should not. Unregistering a command should remove all UI contributions.

Error:
```
root ERROR Error: A command with id 'file.saveAs' does not exist.
    at ActionMenuNode.get (file:///Users/akos.kitta/git/arduino-editor/electron-app/lib/bundle.js:59493:23)
    at ActionMenuNode.get (file:///Users/akos.kitta/git/arduino-editor/electron-app/lib/bundle.js:59513:46)
    at file:///Users/akos.kitta/git/arduino-editor/electron-app/lib/bundle.js:59423:36
    at Array.sort (native)
    at CompositeMenuNode.../node_modules/@theia/core/lib/common/menu.js.CompositeMenuNode.addNode (file:///Users/akos.kitta/git/arduino-editor/electron-app/lib/bundle.js:59415:24)
    at MenuModelRegistry.../node_modules/@theia/core/lib/common/menu.js.MenuModelRegistry.registerMenuAction (file:///Users/akos.kitta/git/arduino-editor/electron-app/lib/bundle.js:59299:23)
    at WorkspaceFrontendContribution.push.../node_modules/@theia/workspace/lib/browser/workspace-frontend-contribution.js.WorkspaceFrontendContribution.registerMenus (file:///Users/akos.kitta/git/arduino-editor/electron-app/lib/8.bundle.js:2146:15)
    at MenuModelRegistry.../node_modules/@theia/core/lib/common/menu.js.MenuModelRegistry.onStart (file:///Users/akos.kitta/git/arduino-editor/electron-app/lib/bundle.js:59285:25)
    at file:///Users/akos.kitta/git/arduino-editor/electron-app/lib/bundle.js:33762:109
    at ArduinoFrontendApplication.<anonymous> (file:///Users/akos.kitta/git/arduino-editor/electron-app/lib/bundle.js:33856:46)
```

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by akosyakov** [comment]
I don't think we should remove, but code should be tolerant that if a command is missing then menu action just should be ignored. It can be a general issue then commands are registered dynamically, for example via VS Code extensions.

**Comment by kittaakos** [comment]
> but code should be tolerant that if a command is missing then menu action just should be ignored.

Thanks, yes, this is exactly what I meant. We should handle it gracefully when a command was removed due to app customizations.

**Comment by kittaakos** [comment]
It does not work even if I have an explicit `registry.unregisterMenuAction(WorkspaceCommands.SAVE_AS)`.

This is what's happening:
 ->  my extension unregisters the `SAVE_AS` command,
 -> `@theia/workspace` contribution starts and tries to register the menu action, but the `SAVE_AS` command is missing,
 -> later would come the `registry.unregisterMenuAction(WorkspaceCommands.SAVE_AS)` from my extension, but it's already too late the app has crashed at startup.

Doing something like this does not work either:
```ts
    @postConstruct()
    protected async init(): Promise<void> {
        this.commandRegistry.unregisterCommand(WorkspaceCommands.SAVE_AS);
        this.menuModelRegistry.unregisterMenuAction(WorkspaceCommands.SAVE_AS);
    }
```

The only viable solution is to subclass the frontend contribution from `@theia/workspace`, copy-paste a bunch of code and remove the menu action I do not need 😞

**Comment by kittaakos** [comment]
> The only viable solution is to subclass the frontend contribution from `@theia/workspace`, copy-paste a bunch of code and remove the menu action I do not need 😞

Example:
```ts
import { injectable } from 'inversify';
import { isOSX } from '@theia/core/lib/common/os';
import { environment } from '@theia/application-package/lib/environment';
import { CommonMenus } from '@theia/core/lib/browser';
import { CommandRegistry } from '@theia/core/lib/common/command';
import { MenuModelRegistry } from '@theia/core/lib/common/menu';
import { WorkspaceCommands } from '@theia/workspace/lib/browser/workspace-commands';
import { WorkspaceFrontendContribution } from '@theia/workspace/lib/browser/workspace-frontend-contribution';

@injectable()
export class MyWorkspaceFrontendContribution extends WorkspaceFrontendContribution {

    registerCommands(registry: CommandRegistry): void {
        super.registerCommands(registry);
        registry.unregisterCommand(WorkspaceCommands.SAVE_AS);
    }

    registerMenus(registry: MenuModelRegistry): void {
        if (isOSX || !environment.electron.is()) {
            registry.registerMenuAction(CommonMenus.FILE_OPEN, {
                commandId: WorkspaceCommands.OPEN.id,
                order: 'a00'
            });
        }
        if (!isOSX && environment.electron.is()) {
            registry.registerMenuAction(CommonMenus.FILE_OPEN, {
                commandId: WorkspaceCommands.OPEN_FILE.id,
                label: `${WorkspaceCommands.OPEN_FILE.dialogLabel}...`,
                order: 'a01'
            });
            registry.registerMenuAction(CommonMenus.FILE_OPEN, {
                commandId: WorkspaceCommands.OPEN_FOLDER.id,
                label: `${WorkspaceCommands.OPEN_FOLDER.dialogLabel}...`,
                order: 'a02'
            });
        }
        registry.registerMenuAction(CommonMenus.FILE_OPEN, {
            commandId: WorkspaceCommands.OPEN_WORKSPACE.id,
            order: 'a10'
        });
        registry.registerMenuAction(CommonMenus.FILE_OPEN, {
            commandId: WorkspaceCommands.OPEN_RECENT_WORKSPACE.id,
            order: 'a20'
        });
        registry.registerMenuAction(CommonMenus.FILE_OPEN, {
            commandId: WorkspaceCommands.SAVE_WORKSPACE_AS.id,
            order: 'a30'
        });

        registry.registerMenuAction(CommonMenus.FILE_CLOSE, {
            commandId: WorkspaceCommands.CLOSE.id
        });

        // `Save As`
        // menus.registerMenuAction(CommonMenus.FILE_SAVE, {
        //     commandId: WorkspaceCommands.SAVE_AS.id,
        // });
    }

}
```

In your frontend module:
```ts
rebind(WorkspaceFrontendContribution).to(MyWorkspaceFrontendContribution).inSingletonScope();
```

**Comment by akosyakov** [comment]
that's indeed very fragile

**Comment by vince-fugnitto** [comment]
I believe the goal is not to automatically un-register other contributions if a command is un-registered.
We should instead make contributions more robust, something achieved in https://github.com/eclipse-theia/theia/pull/9886.
