### ISSUE TITLE
[ci] Publishing to npmjs is down

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8181]
### Bug Description:

After 9afc819182ae94cd44f19efe42828ce704d9fecc.

```
npm ERR! Response timeout while trying to fetch https://registry.yarnpkg.com/@theia%2ftask (over 30000ms)
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-07-16T07_20_59_364Z-debug.log
child_process.js:669
    throw err;
    ^
Error: Command failed: npm view @theia/task@1.4.0-next.9afc8191 version --json
npm ERR! Response timeout while trying to fetch https://registry.yarnpkg.com/@theia%2ftask (over 30000ms)
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-07-16T07_20_59_364Z-debug.log
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.<anonymous> (/home/travis/build/eclipse-theia/theia/scripts/check-publish.js:31:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Script failed with status 1
```

I do not know yet why we do anything with `@theia/json`, it was removed.

Also, check why we have
https://github.com/eclipse-theia/theia/blob/9afc819182ae94cd44f19efe42828ce704d9fecc/examples/api-tests/src/typescript.spec.js#L115

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by kittaakos** [comment]
> o anything with `@theia/json`, it was removed.

It wasn't; I am blind for sure. The problem was with  `@theia/task` and not `@theia/json`. I still do not understand how does the typescript spec test run without `@theia/json`.

**Comment by kittaakos** [comment]
The publishing is back. A follow-up for `@theia/json` is [here](https://github.com/eclipse-theia/theia/issues/8183).
