### ISSUE TITLE
Reconnect not always triggers activation due to exception

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#8219]
### Bug Description:

On websocket brief disconnections after reconnect there should be activation of all extensions. Without that they stop working.
It seems that not always this happen. Sometime there is this failure:
```
root ERROR Failed to load plugins: Error: Request 'getHostLogPath' failed
    at Proxy.<anonymous> (https://3000-af7cdfe6-64f1-4923-bdd8-1fdf8d30e6e7.ws-eu01.gitpod.io/bundle.js:134498:33)
    at HostedPluginSupport.<anonymous> (https://3000-af7cdfe6-64f1-4923-bdd8-1fdf8d30e6e7.ws-eu01.gitpod.io/57.bundle.js:1012:57)
    at step (https://3000-af7cdfe6-64f1-4923-bdd8-1fdf8d30e6e7.ws-eu01.gitpod.io/57.bundle.js:601:23)
    at Object.next (https://3000-af7cdfe6-64f1-4923-bdd8-1fdf8d30e6e7.ws-eu01.gitpod.io/57.bundle.js:582:53)
    at https://3000-af7cdfe6-64f1-4923-bdd8-1fdf8d30e6e7.ws-eu01.gitpod.io/57.bundle.js:576:71
    at new Promise (<anonymous>)
    at push.../../packages/plugin-ext/lib/hosted/browser/hosted-plugin.js.__awaiter (https://3000-af7cdfe6-64f1-4923-bdd8-1fdf8d30e6e7.ws-eu01.gitpod.io/57.bundle.js:572:12)
    at HostedPluginSupport.push.../../packages/plugin-ext/lib/hosted/browser/hosted-plugin.js.HostedPluginSupport.startPlugins (https://3000-af7cdfe6-64f1-4923-bdd8-1fdf8d30e6e7.ws-eu01.gitpod.io/57.bundle.js:1002:16)
    at HostedPluginSupport.<anonymous> (https://3000-af7cdfe6-64f1-4923-bdd8-1fdf8d30e6e7.ws-eu01.gitpod.io/57.bundle.js:847:51)
    at step (https://3000-af7cdfe6-64f1-4923-bdd8-1fdf8d30e6e7.ws-eu01.gitpod.io/57.bundle.js:601:23)
```
On the backend I see something like this:
```
root ERROR Request getHostLogPath failed with error: Connection got disposed. Error: Connection got disposed.
    at Object.dispose (/theia/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at connection.onClose (/theia/node_modules/vscode-ws-jsonrpc/lib/socket/connection.js:14:41)
    at CallbackList.invoke (/theia/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/theia/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/theia/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/theia/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/theia/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at WebSocketMessageReader.fireClose (/theia/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at WebSocketMessageReader.fireClose (/theia/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:67:19)
    at WebSocketMessageReader.socket.onClose (/theia/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:24:18)
```

### Steps to Reproduce:

1. Open gitpod with wifi connection
2. Open the theia run there in a separate tab following the notification
3. Install some extensiosn from extension pane
4. Switch between wifi connections
5. Every other time you get the error above in browser console
6. Then no activation is done and extensions do not work anymore

### Additional Information

- Operating System: Gitpod
- Theia Version: master

**Comment by amiramw** [comment]
Closing as it does not reproduce anymore.
