### ISSUE TITLE
Searching in files breaks for large workspaces

### ISSUE THREAD

**Issue by csweichel** [eclipse-theia/theia#8242]
### Bug Description:
When searching in too large a workspace the search can silently fail. In the logs there's an error message that may be related:
```
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded\n    at Socket.onChildStdout (child_process.js:348:14)\n    at Socket.emit (events.js:189:13)\n    at addChunk (_stream_readable.js:284:12)\n    at readableAddChunk (_stream_readable.js:261:13)\n    at Socket.Readable.push (_stream_readable.js:220:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
```

### Steps to Reproduce:

1. Open a large workspace
2. Search for a string in all files

### Additional Information

- Operating System:
- Theia Version: latest in Gitpod

**Comment by akosyakov** [comment]
Node.js imposes max buffer constraints on child processes. I've noticed during the fs refactoring that VS Code refactors search to streaming because of this reason. We should do the same to support search in large workspaces.

**Comment by FernandoAscencio** [comment]
This seems to have been addressed.
Latest commit does **not** log the error and yields
![image](https://user-images.githubusercontent.com/48699277/226743212-1f338716-d390-472a-8e6e-8e787d5f7996.png)
