### ISSUE TITLE
[ts] ERROR TypeScript: UnhandledPromiseRejectionWarning: Error: geterr timeout

### ISSUE THREAD

**Issue by garyo** [eclipse-theia/theia#8461]
I'm seeing the same issue as #4366 occasionally. I'm using emacs 28 nightly with lsp-mode, running tsserver. Typescript 3.8.3. I thought it was due to out-of-memory errors, which I was also seeing, but now that I'm passing the env var `NODE_OPTIONS="--max-old-space-size=8192"` the memory errors are gone, but these `geterr timeout` errors still happen from time to time. Once they happen, the server seems to be stuck (it gives no more replies to requests) and I have to restart it.
```
(node:366) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/home/garyo/.config/yarn/global/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:366) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

tsserver log starts like this:
```
Info 0    [10:21:50.229] Starting TS Server
Info 1    [10:21:50.231] Version: 4.0.2
Info 2    [10:21:50.231] Arguments: /home/garyo/.fnm/node-versions/v10.17.0/installation/bin/node /home/garyo/.yarn/bin/tsserver --logFile /c/dss/Product/Horizon/horizon/.log/tsserver.log --logVerbosity normal --cancellationPipeName /tmp/0d6679f81a7ded0f4ad5394cb463fa84/tscancellation*
Info 3    [10:21:50.231] Platform: linux NodeVersion: 10 CaseSensitive: true
Info 4    [10:21:50.231] ServerMode: undefined syntaxOnly: false hasUnknownServerMode: undefined
Info 5    [10:21:50.261] Search path: /c/dss/Product/Horizon/horizon/packages/front-end/functions/src
Info 6    [10:21:50.263] For info: /c/dss/Product/Horizon/horizon/packages/front-end/functions/src/instances.ts :: Config file name: /c/dss/Product/Horizon/horizon/packages/front-end/functions/tsconfig.json
Info 7    [10:21:50.264] Opened configuration file /c/dss/Product/Horizon/horizon/packages/front-end/functions/tsconfig.json
```

**Comment by akosyakov** [comment]
Which version of Theia? How do you consume typescript ls? via built-in VS Code extensions?

**Comment by garyo** [comment]
Hi! I'm using emacs 28 and lsp-mode (latest as of a few days ago) to consume the language server. 
```
% typescript-language-server -V
0.4.0
% realpath $(which tsserver)
/home/garyo/.config/yarn/global/node_modules/typescript/bin/tsserver
% grep version ~/.config/yarn/global/node_modules/typescript/package.json
    "version": "4.0.2",
```

**Comment by akosyakov** [comment]
Not sure what is have to do with Theia. We dropped support of typescript-language-server.

**Comment by nahuel** [comment]
Hi @garyo , see: https://github.com/theia-ide/typescript-language-server/issues/82

**Comment by tsmaeder** [comment]
There is no typescript-langauge-server in Theia anymore. Closing.
