### ISSUE TITLE
LS restart causes possible memory leak

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8474]
### Bug Description:

When I restart the LS from a VS Code extension enough times (175), then I get this warning indicating a resource leak:
```
root WARN Possible Emitter memory leak detected. 176 listeners added. Use event.maxListeners to increase the limit (175). MOST frequent listener (1):
root WARN     at PluginContributionHandler._event.Object.assign.maxListeners [as onDidRegisterCommandHandler] (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:132875:57)
    at HostedPluginSupport.push.../../packages/plugin-ext/lib/hosted/browser/hosted-plugin.js.HostedPluginSupport.ensureCommandHandlerRegistration (file:///Users/akos.kitta/git/theia/examples/electron/lib/54.bundle.js:1563:49)
    at file:///Users/akos.kitta/git/theia/examples/electron/lib/54.bundle.js:936:76
    at file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:132813:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:132828:39)
    at Emitter.../../packages/core/lib/common/event.js.Emitter.fire (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:132955:29)
    at Object.<anonymous> (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:133043:37)
    at step (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:132698:23)
```

I see a lot from these errors too, maybe my sample is wrong:
```
plugin-contribution-handler.ts:361 Uncaught (in promise) Error: command 'go.languageserver.restart' not found
    at PluginContributionHandler.<anonymous> (plugin-contribution-handler.ts:361)
    at step (plugin-contribution-handler.ts:15)
    at Object.next (plugin-contribution-handler.ts:15)
    at plugin-contribution-handler.ts:15
    at new Promise (<anonymous>)
    at push.../../packages/plugin-ext/lib/main/browser/plugin-contribution-handler.js.__awaiter (plugin-contribution-handler.ts:15)
    at Object.execute (plugin-contribution-handler.ts:358)
    at CommandRegistry.<anonymous> (command.ts:294)
    at step (command.ts:15)
    at Object.next (command.ts:15)
```

### Steps to Reproduce:

1. Check out the [`on-did-change-configuration--leak`](https://github.com/eclipse-theia/theia/tree/on-did-change-configuration--leak) branch and start the app. (The diff is [here](https://github.com/eclipse-theia/theia/compare/on-did-change-configuration--leak).)
2. Execute the `Start: Auto Restart Go LS` command. (This command restarts the Go LS every second.)
3. Check the console output, it will fail after 175 restarts.

Besides these:

### Additional Information

- Operating System:
- Theia Version:

**Comment by kittaakos** [comment]
@akosyakov, what do you think, is this a quality issue or a bug? Being able to restart the LS and or reload a VS Code extension arbitrary times seems to be a valid requirement. Thanks!

**Comment by akosyakov** [comment]
If it works in VS Code, but no in Theia then it is a bug.
