### ISSUE TITLE
[vscode] css code completion doesn't work - Cannot read property 'Deprecated' of undefined

### ISSUE THREAD

**Issue by shahar-h** [eclipse-theia/theia#8475]
### Bug Description:
There are no completion results when working on css file.

### Steps to Reproduce:

1. Create an empty css file.
2. Hit ctrl + space.  

There are no results:
![css-theia](https://user-images.githubusercontent.com/16555289/92353946-04b1dc00-f0ea-11ea-8a63-1626ed2447b9.png)

In addition the following error appears in browser console:
```
TypeError: Cannot read property 'Deprecated' of undefined
    at y (c:\SAPDevelop\repos\theia\plugins\vscode-builtin-css-language-features\extension\client\dist\cssMain.js:1:163850)
    at c:\SAPDevelop\repos\theia\plugins\vscode-builtin-css-language-features\extension\client\dist\cssMain.js:1:163962
    at C (c:\SAPDevelop\repos\theia\plugins\vscode-builtin-css-language-features\extension\client\dist\cssMain.js:1:163998)
    at Array.map (<anonymous>)
    at asCompletionResult (c:\SAPDevelop\repos\theia\plugins\vscode-builtin-css-language-features\extension\client\dist\cssMain.js:1:170409)
    at http://localhost:3000/vs/editor/editor.main.js:1607:31
```

vscode:
![css-vscode](https://user-images.githubusercontent.com/16555289/92354088-5195b280-f0ea-11ea-8c96-55b39848a02e.png)

### Additional Information

- Operating System: Windows 10
- Theia Version: master

**Comment by zouyi100** [comment]
I think the file with preprocessor style language like scss, less has the same problem.
