### ISSUE TITLE
cant build theia while working on extension

### ISSUE THREAD

**Issue by infoprogrammr** [eclipse-theia/theia#8477]
### Bug Description:
I am trying build an custom theia extension using "yo" generator.
While building I am getting the following errors:

```
ERROR in ../node_modules/vscode-languageclient/lib/configuration.js
Module not found: Error: Can't resolve 'vscode' in '/home/ubuntu/theia2/theia/programmr_popup_v6/node_modules/vscode-languageclient/lib'
 @ ../node_modules/vscode-languageclient/lib/configuration.js 7:17-34
 @ ../node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ../node_modules/monaco-languageclient/lib/index.js
 @ ../node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ../node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ../node_modules/vscode-languageclient/lib/progressPart.js
Module not found: Error: Can't resolve 'vscode' in '/home/ubuntu/theia2/theia/programmr_popup_v6/node_modules/vscode-languageclient/lib'
 @ ../node_modules/vscode-languageclient/lib/progressPart.js 7:17-34
 @ ../node_modules/vscode-languageclient/lib/client.js
 @ ../node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ../node_modules/monaco-languageclient/lib/index.js
 @ ../node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ../node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ../node_modules/vscode-languageclient/lib/codeConverter.js
Module not found: Error: Can't resolve 'vscode' in '/home/ubuntu/theia2/theia/programmr_popup_v6/node_modules/vscode-languageclient/lib'
 @ ../node_modules/vscode-languageclient/lib/codeConverter.js 7:13-30
 @ ../node_modules/vscode-languageclient/lib/client.js
 @ ../node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ../node_modules/monaco-languageclient/lib/index.js
 @ ../node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ../node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ../node_modules/vscode-languageclient/lib/protocolConverter.js
Module not found: Error: Can't resolve 'vscode' in '/home/ubuntu/theia2/theia/programmr_popup_v6/node_modules/vscode-languageclient/lib'
 @ ../node_modules/vscode-languageclient/lib/protocolConverter.js 7:13-30
 @ ../node_modules/vscode-languageclient/lib/client.js
 @ ../node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ../node_modules/monaco-languageclient/lib/index.js
 @ ../node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ../node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ../node_modules/vscode-languageclient/lib/protocolCompletionItem.js
Module not found: Error: Can't resolve 'vscode' in '/home/ubuntu/theia2/theia/programmr_popup_v6/node_modules/vscode-languageclient/lib'
 @ ../node_modules/vscode-languageclient/lib/protocolCompletionItem.js 7:13-30
 @ ../node_modules/vscode-languageclient/lib/codeConverter.js
 @ ../node_modules/vscode-languageclient/lib/client.js
 @ ../node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ../node_modules/monaco-languageclient/lib/index.js
 @ ../node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ../node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ../node_modules/vscode-languageclient/lib/protocolCodeLens.js
Module not found: Error: Can't resolve 'vscode' in '/home/ubuntu/theia2/theia/programmr_popup_v6/node_modules/vscode-languageclient/lib'
 @ ../node_modules/vscode-languageclient/lib/protocolCodeLens.js 7:13-30
 @ ../node_modules/vscode-languageclient/lib/codeConverter.js
 @ ../node_modules/vscode-languageclient/lib/client.js
 @ ../node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ../node_modules/monaco-languageclient/lib/index.js
 @ ../node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ../node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ../node_modules/vscode-languageclient/lib/protocolDocumentLink.js
Module not found: Error: Can't resolve 'vscode' in '/home/ubuntu/theia2/theia/programmr_popup_v6/node_modules/vscode-languageclient/lib'
 @ ../node_modules/vscode-languageclient/lib/protocolDocumentLink.js 7:13-30
 @ ../node_modules/vscode-languageclient/lib/codeConverter.js
 @ ../node_modules/vscode-languageclient/lib/client.js
 @ ../node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ../node_modules/monaco-languageclient/lib/index.js
 @ ../node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ../node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js


    at Promise.all.then.arr (/home/ubuntu/theia2/theia/programmr_popup_v6/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8050) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:8050) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
```

### Steps to Reproduce:
 yo theia-extension extension_name

### Additional Information

**- Operating System:** Ubuntu
**- Yo vesrion:** 3.1.1
**-NodeJS:** 10.15.3
**-NPM:** 6.4.1

**Comment by kittaakos** [comment]
You have to remove the dead `@theia/languages` extension. See [here](https://community.theia-ide.org/t/render-html-inside-theia-application/988/16).

If it does not work, let us know. Otherwise, please close the issue. Thanks!

**Comment by kittaakos** [comment]
> **-NodeJS:** 10.15.3

You have to use Node.js 12.

**Comment by vince-fugnitto** [comment]
@infoprogrammr please upgrade the extension generator, the recent version has been fixed to not include the deprecated extensions. In addition, please use `node 12` as mentioned.

**Comment by infoprogrammr** [comment]
Thanks,
it's working now!
