### ISSUE TITLE
Activating extension 'Remote - SSH' failed

### ISSUE THREAD

**Issue by kaustav-aarish** [eclipse-theia/theia#8493]
### Bug Description:

After importing [SSH-remote](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) onto Theia, and yarn start on electron-app:

This is the error which pops up when I try to create a new ssh connection to a remote host:

```
root INFO [hosted-plugin: 40145] PLUGIN_HOST(40145): PluginManagerExtImpl/loadPlugin(/Users/kdassharma1/Documents/GitHub/ToolChain/theia/plugins/remote-ssh/extension/out/extension)
root ERROR [hosted-plugin: 40145] Activating extension 'Remote - SSH' failed: TypeError: n.workspace.registerRemoteAuthorityResolver is not a function
    at t.activate (/Users/kdassharma1/Documents/GitHub/ToolChain/theia/plugins/remote-ssh/extension/out/extension.js:127:146365)
    at PluginManagerExtImpl.<anonymous> (/Users/kdassharma1/Documents/GitHub/ToolChain/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:553:87)
    at step (/Users/kdassharma1/Documents/GitHub/ToolChain/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:48:23)
    at Object.next (/Users/kdassharma1/Documents/GitHub/ToolChain/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:29:53)
    at /Users/kdassharma1/Documents/GitHub/ToolChain/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kdassharma1/Documents/GitHub/ToolChain/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:19:12)
    at PluginManagerExtImpl.startPlugin (/Users/kdassharma1/Documents/GitHub/ToolChain/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:526:16)
    at PluginManagerExtImpl.<anonymous> (/Users/kdassharma1/Documents/GitHub/ToolChain/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:445:63)
    at step (/Users/kdassharma1/Documents/GitHub/ToolChain/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:48:23)
```

### Steps to Reproduce:

These are the plugins that I used:

```
  "theiaPlugins": {
    "remote-ssh": "https://www.cs.mcgill.ca/~kdassh/plugins/ms-vscode-remote.remote-ssh-0.51.0.vsix",
    "remote-wsl": "https://www.cs.mcgill.ca/~kdassh/plugins/ms-vscode-remote.remote-wsl-0.44.5.vsix",
    "remote-containers": "https://www.cs.mcgill.ca/~kdassh/plugins/ms-vscode-remote.remote-containers-0.140.1.vsix",
    "remote-ssh-edit": "https://www.cs.mcgill.ca/~kdassh/plugins/ms-vscode-remote.remote-ssh-edit-0.51.0.vsix",
    }
```

As you can probably tell, these are not conventional links. These extensions are not available on open-vsx and the link on the vscode marketplace doesn't follow the same format that yarn expects, so I downloaded copies and uploaded them to a server that I have running from my university. 

### Additional Information

- Operating System: macOS Catalina 10.15.6
- Theia Version: 1.5.0

**Comment by vince-fugnitto** [comment]
@kaustav-aarish thank you for the issue, the `workspace. registerRemoteAuthorityResolver` API is not yet finalized (`proposed`) and it is currently not yet implemented in the framework.

- [vscode workspace.registerRemoteAuthorityResolver proposed api](https://github.com/microsoft/vscode/blob/371f6306f9de7e704870e7d7263a96ebc5eb2c88/src/vs/vscode.proposed.d.ts#L265-L268)

```ts
export namespace workspace {
  export function registerRemoteAuthorityResolver(authorityPrefix: string, resolver: RemoteAuthorityResolver): Disposable;
  export function registerResourceLabelFormatter(formatter: ResourceLabelFormatter): Disposable;
}
```

Generally, extensions should only use proposed APIs when they are targeting [vscode insiders](https://code.visualstudio.com/api/advanced-topics/using-proposed-api), and there is a note about their use:

> They are subject to change, only available in Insiders distribution and cannot be used in published extensions

At this time, I don't believe the framework should prioritize their implementation in the framework, but we can track when the APIs is finalized and implement it then.

**Comment by msujew** [comment]
Due to it's architecture, we're unable to use the `Remote - SSH` extension from vscode directly (aside from the various legal issues). It effectively downloads a vscode server instance and connects to it - given that the vscode backend isn't compatible with Theia, using it in Theia doesn't really make a lot of sense. I'll close this issue in favor of https://github.com/eclipse-theia/theia/issues/12390.
