### ISSUE TITLE
explorer: activate error thrown without a workspace present

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#8506]
#### Bug Description:

There is an error thrown when the `explorer` is activated without a workspace present:

```
logger-protocol.ts:112 root ERROR TypeError: Cannot use 'in' operator to search for 'uri' in undefined
    at file:///home/evinfug/workspaces/theia/examples/electron/lib/37.bundle.js:984:51
    at file:///home/evinfug/workspaces/theia/examples/electron/lib/bundle.js:133356:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (file:///home/evinfug/workspaces/theia/examples/electron/lib/bundle.js:133371:39)
    at Emitter.../../packages/core/lib/common/event.js.Emitter.fire (file:///home/evinfug/workspaces/theia/examples/electron/lib/bundle.js:133498:29)
    at SelectionService.set (file:///home/evinfug/workspaces/theia/examples/electron/lib/bundle.js:137698:44)
    at FileNavigatorWidget.../../packages/core/lib/browser/tree/tree-widget.js.TreeWidget.updateGlobalSelection (file:///home/evinfug/workspaces/theia/examples/electron/lib/bundle.js:127180:41)
    at FileNavigatorWidget.../../packages/core/lib/browser/tree/tree-widget.js.TreeWidget.doFocus (file:///home/evinfug/workspaces/theia/examples/electron/lib/bundle.js:127291:18)
    at HTMLDivElement.<anonymous> (file:///home/evinfug/workspaces/theia/examples/electron/lib/bundle.js:127879:78)
    at FileNavigatorWidget.../../packages/core/lib/browser/tree/tree-widget.js.TreeWidget.onActivateRequest (file:///home/evinfug/workspaces/theia/examples/electron/lib/bundle.js:127277:19)
    at FileNavigatorWidget.widget.onActivateRequest (file:///home/evinfug/workspaces/theia/examples/electron/lib/bundle.js:118348:13)
```

#### Steps to Reproduce:

1. start the example application without a workspace present
2. click inside the explorer
3. the error should be thrown on the console

**Comment by vince-fugnitto** [comment]
I'm unable to reproduce the issue any longer, I'll re-open if the issue ever resurfaces.
