### ISSUE TITLE
Cannot open files when changing default encoding to utf8bom

### ISSUE THREAD

**Issue by fgreinacher** [eclipse-theia/theia#8524]
### Bug Description

No files can be opened after changing the default encoding in the settigns to "utf8bom". 

### Steps to Reproduce:

![image](https://user-images.githubusercontent.com/1540469/93593286-1e89d380-f9b4-11ea-9fb7-9ec68df5ecbd.png)

### Additional Information

Local log files show the following error:

```
root ERROR Request resolveContent failed with error: Encoding not recognized: 'utf8bom' (searched as: 'utf8bom') Error: Encoding not recognized: 'utf8bom' (searched as: 'utf8bom')
    at Object.getCodec (<app>\resources\app.asar\node_modules\@theia\filesystem\node_modules\iconv-lite\lib\index.js:106:23)
    at Object.getDecoder (<app>\resources\app.asar\node_modules\@theia\filesystem\node_modules\iconv-lite\lib\index.js:127:23)
    at Object.decode (<app>\resources\app.asar\node_modules\@theia\filesystem\node_modules\iconv-lite\lib\index.js:40:25)
    at FileSystemNode.<anonymous> (<app>\resources\app.asar\node_modules\@theia\filesystem\lib\node\node-filesystem.js:177:41)
    at step (<app>\resources\app.asar\node_modules\@theia\filesystem\lib\node\node-filesystem.js:60:23)
    at Object.next (<app>\resources\app.asar\node_modules\@theia\filesystem\lib\node\node-filesystem.js:41:53)
    at fulfilled (<app>\resources\app.asar\node_modules\@theia\filesystem\lib\node\node-filesystem.js:32:58)
```

**Comment by kittaakos** [comment]
Thanks for logging, @fgreinacher. I am going to close this issue as it works in Theia. I've just tried it. Gitpod has to be updated to use a more decent version of Theia to support it.

Feel free to open a follow-up issue in Gitpod. Thank you!

If you have any concerns, please let me know, and I can reopen this.

**Comment by fgreinacher** [comment]
Thanks @kittaakos! We're actually hitting this in our IDE based on Theia 1.14. Let's see whether 1.15 solves it. Will post an update here!
