### ISSUE TITLE
build process can't find  some vscode-languageclient files.

### ISSUE THREAD

**Issue by H91011** [eclipse-theia/theia#8533]
I cant build theia desktop application. 

here is my package.json

```
{
  "name": "yangster-electron",
  "version": "0.1.1",
  "description": "Yangster Electron",
  "main": "src-gen/frontend/electron-main.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/theia-ide/yangster-electron.git"
  },
  "theia": {
    "target": "electron"
  },
  "scripts": {
    "build": "theia build",
    "package": "yarn run build && electron-builder",
    "package:all": "yarn run build && electron-builder -lmw"
  },
  "keywords": [],
  "author": "typefox <npm@typefox.io>",
  "license": "Apache-2.0",
  "bugs": {
    "url": "https://github.com/theia-ide/yangster-electron/issues"
  },
  "homepage": "https://github.com/theia-ide/yangster-electron#readme",
  "//": [
    "See why `yargs` is an explicit dependency: https://github.com/theia-ide/theia/issues/934",
    "See why `xterm` is an explicit dependency: https://github.com/theia-ide/theia/issues/737"
  ],
  "dependencies": {
    "@theia/core": "latest",
    "@theia/editor": "latest",
    "@theia/filesystem": "latest",
    "@theia/file-search": "latest",
    "@theia/git": "latest",
    "@theia/languages": "latest",
    "@theia/markers": "latest",
    "@theia/monaco": "latest",
    "@theia/navigator": "latest",
    "@theia/preferences": "latest",
    "@theia/process": "latest",
    "@theia/terminal": "latest",
    "@theia/workspace": "latest",
    "theia-yang-extension": "^0.1.7",
    "yargs": "^9.0.1",
    "xterm": "^2.9.2"
  },
  "devDependencies": {
    "@theia/electron@1.5.0":"1.5.0",
    "@theia/cli": "latest",
    "xterm-addon-search":"latest",
    "xterm-addon-fit":"latest",
    "electron-builder": "^19.30.2"
  }
}
```
I add only this packages to package.json file : 
```
    "@theia/electron@1.5.0":"1.5.0",
    "xterm-addon-search":"latest",
    "xterm-addon-fit":"latest",
```

here is the error output: 
<details>
<summary>output</summary>
<br />

```
yarn run v1.22.4
$ theia build
Hash: 48eff29eccdb30a69b5c
Version: webpack 4.44.2
Time: 42908ms
Built at: 09/19/2020 10:57:18 PM
 14 assets
Entrypoint main = bundle.js bundle.js.map
 [133] external "electron" 42 bytes {0} [built]
 [292] ./node_modules/jsonc-parser/lib/esm/main.js + 4 modules 57.9 KiB {0} [built]
       |    5 modules
 [306] external "path" 42 bytes {0} [built]
 [443] external "crypto" 42 bytes {0} [built]
 [459] external "net" 42 bytes {0} [built]
 [545] (webpack)/buildin/module.js 497 bytes {0} [built]
 [848] ./node_modules/react-virtualized/dist/es/index.js + 70 modules 352 KiB {0} [built]
       |    71 modules
 [849] ./node_modules/snabbdom/es/snabbdom.js + 5 modules 16.5 KiB {0} [built]
       |    6 modules
 [852] ./src-gen/frontend/index.js 4.85 KiB {0} [built]
[1035] external "buffer" 42 bytes {0} [built]
[1054] external "stream" 42 bytes {0} [optional] [built]
[1091] ./node_modules/@theia/core/src/common/keyboard/layouts sync ^\.\/.*\.json$ 1.39 KiB {0} [built]
[1256] ./node_modules/moment/locale sync ^\.\/.*$ 3 KiB {0} [optional] [built]
[1605] ./node_modules/@theia/languages/node_modules/uuid/dist/esm-browser/index.js + 14 modules 19 KiB {0} [built]
       |    15 modules
[1606] ./node_modules/idb/build/esm/index.js + 1 modules 10.1 KiB {0} [built]
       |    2 modules
    + 1592 hidden modules

WARNING in ./node_modules/vscode-textmate/release/main.js 23:15-27
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-service.js
 @ ./node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-frontend-bindings.js
 @ ./node_modules/@theia/monaco/lib/browser/monaco-frontend-module.js
 @ ./node_modules/@theia/monaco/lib/electron-browser/monaco-electron-module.js
 @ ./src-gen/frontend/index.js

WARNING in ./node_modules/vscode-textmate/release/main.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'main.js.map': Error: Can't resolve './main.js.map' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-textmate/release'
 @ ./node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-service.js 76:24-50
 @ ./node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-frontend-bindings.js
 @ ./node_modules/@theia/monaco/lib/browser/monaco-frontend-module.js
 @ ./node_modules/@theia/monaco/lib/electron-browser/monaco-electron-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/theia-yang-extension/lib/frontend/language/yang-language-client-contribution.js
Module not found: Error: Can't resolve '@theia/editor/lib/browser/semantic-highlight/semantic-highlighting-service' in '/home/makine/Desktop/yangster-electron/node_modules/theia-yang-extension/lib/frontend/language'
 @ ./node_modules/theia-yang-extension/lib/frontend/language/yang-language-client-contribution.js 36:38-123
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/declaration.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/declaration.js 7:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/foldingRange.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/foldingRange.js 7:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/client.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/client.js 10:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/colorProvider.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/colorProvider.js 7:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/implementation.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/implementation.js 7:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/configuration.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/configuration.js 7:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/typeDefinition.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/typeDefinition.js 7:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/workspaceFolders.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/workspaceFolders.js 8:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/progressPart.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/progressPart.js 7:17-34
 @ ./node_modules/vscode-languageclient/lib/client.js
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/protocolConverter.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/protocolConverter.js 7:13-30
 @ ./node_modules/vscode-languageclient/lib/client.js
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/codeConverter.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/codeConverter.js 7:13-30
 @ ./node_modules/vscode-languageclient/lib/client.js
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/protocolDocumentLink.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/protocolDocumentLink.js 7:13-30
 @ ./node_modules/vscode-languageclient/lib/protocolConverter.js
 @ ./node_modules/vscode-languageclient/lib/client.js
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/protocolCodeLens.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/protocolCodeLens.js 7:13-30
 @ ./node_modules/vscode-languageclient/lib/codeConverter.js
 @ ./node_modules/vscode-languageclient/lib/client.js
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/protocolCompletionItem.js
Module not found: Error: Can't resolve 'vscode' in '/home/makine/Desktop/yangster-electron/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/protocolCompletionItem.js 7:13-30
 @ ./node_modules/vscode-languageclient/lib/codeConverter.js
 @ ./node_modules/vscode-languageclient/lib/client.js
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/index.js
 @ ./node_modules/theia-yang-extension/lib/frontend/language/frontend-extension.js
 @ ./src-gen/frontend/index.js

Error: webpack exited with an unexpected code: 2.
    at ChildProcess.<anonymous> (/home/makine/Desktop/yangster-electron/node_modules/@theia/application-manager/lib/application-process.js:67:28)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
</details>

- Operating System: Ubuntu 18.04 LTS

**Comment by vince-fugnitto** [comment]
@H91011 you are currently using deprecated extensions as part of your application, mixing and matching different versions of `latest` dependencies. The `@theia/languages` extension is deprecated and should be removed for instance.

**Comment by H91011** [comment]
I download project from  GettingStarted -> Package a desktop Theia application with Electronthis page -> https://github.com/theia-ide/yangster-electron so how we know which package is nor deprecated ?  I want to try desktop app but but I can't.

I wonder that who use this ide ?
May be eclipse develop this ide for some small user group ?

**Comment by vince-fugnitto** [comment]
> I wonder that who use this ide ?
> May be eclipse develop this ide for some small user group ?

The repository is quite old, ~3 years was the last commit (it was likely used as an example at one point but it is outdated).
If you are looking into providing your own application we have many examples, but you should choose extensions which satisfy your requirements and are not deprecated.

You can take a look at:
- https://github.com/theia-ide/theia-apps/tree/master/theia-electron
- https://github.com/eclipse-theia/theia/tree/master/examples/electron

These examples are up-to-date and maintained by the community.
