### ISSUE TITLE
Uncaught (in promise) Error: Connection got disposed.

### ISSUE THREAD

**Issue by habibali95** [eclipse-theia/theia#8545]
Im using k8s ingress to run theia, ive tried many version and i always get these errors, is there any reasons why could this happen? 

root ERROR Uncaught Exception:  Error: Connection got disposed.
root ERROR Error: Connection got disposed.
    at Object.dispose (/home/theia/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at /home/theia/node_modules/vscode-ws-jsonrpc/lib/socket/connection.js:14:41
    at CallbackList.invoke (/home/theia/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/theia/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/home/theia/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/home/theia/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/theia/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at WebSocketMessageReader.fireClose (/home/theia/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at WebSocketMessageReader.fireClose (/home/theia/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:67:19)
    at /home/theia/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:24:18

**Comment by habibali95** [comment]
and the status goes offline for some time..
