### ISSUE TITLE
Can't build @theia/json extension

### ISSUE THREAD

**Issue by dmt0** [eclipse-theia/theia#8571]
### Bug Description:

Can't build Theia app with the JSON extension.

### Steps to Reproduce:

Here's my `package.json`

```json
{
    "private": true,
    "theia": {
        "frontend": {
            "config": {
                "applicationName": "IDE",
                "preferences": {
                    "files.enableTrash": false,
                    "python.pythonPath": "/app/.heroku/python/bin/python",
                    "python.linting.enabled": false,
                    "workbench.colorTheme": "light"
                }
            }
        }
    },
    "dependencies": {
        "@theia/callhierarchy": "latest",
        "@theia/file-search": "latest",
        "@theia/git": "latest",
        "@theia/json": "latest",
        "@theia/markers": "latest",
        "@theia/messages": "latest",
        "@theia/mini-browser": "latest",
        "@theia/navigator": "latest",
        "@theia/outline-view": "latest",
        "@theia/plugin-ext-vscode": "latest",
        "@theia/preferences": "latest",
        "@theia/preview": "latest",
        "@theia/search-in-workspace": "latest",
        "@theia/terminal": "latest",
        "@types/vscode": "1.41.0"
    },
    "resolutions": {
        "@theia/**/@theia/terminal/xterm": "4.7.0"
    },
    "devDependencies": {
        "@theia/cli": "latest"
    },
    "theiaPluginsDir": "plugins",
    "theiaPlugins": {
        "vscode-builtin-python": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/python-1.39.1-prel.vsix",
        "vscode-builtin-r": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/r-1.39.1-prel.vsix",
        "vscode-python": "https://github.com/microsoft/vscode-python/releases/download/2020.1.58038/ms-python-release.vsix",
        "vscode-builtin-json": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/json-1.39.1-prel.vsix",
        "vscode-builtin-shellscript": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/shellscript-1.39.1-prel.vsix",
        "vscode-builtin-css": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/css-1.39.1-prel.vsix",
        "vscode-builtin-javascript": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/javascript-1.39.1-prel.vsix",
        "vscode-builtin-html": "https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/html-1.39.1-prel.vsix",
        "vscode-julia": "https://github.com/julia-vscode/julia-vscode/releases/download/v0.15.22/language-julia-insider-0.15.22.vsix"
    }
}
```

`yarn theia build` output:

```
yarn theia build
yarn run v1.22.5
$ /Users/***/work/theiaish/node_modules/.bin/theia build
Failed to resolve module: filenamify
(node:28480) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
(Use `node --trace-deprecation ...` to show where the warning was created)

Hash: ebd9fbea244c14dbbb7d
Version: webpack 4.44.2
Time: 94968ms
Built at: 2020-09-29 11:26:34 a.m.
 16 assets
Entrypoint main = bundle.js bundle.js.map
  [80] (webpack)/buildin/global.js 472 bytes {0} [built]
 [146] ./node_modules/jsonc-parser/lib/esm/main.js + 4 modules 57.9 KiB {0} [built]
       |    5 modules
 [376] ./node_modules/react-virtualized/dist/es/index.js + 69 modules 344 KiB {0} [built]
       |    70 modules
 [429] (webpack)/buildin/module.js 497 bytes {0} [built]
[1020] ./src-gen/frontend/index.js 6.24 KiB {0} [built]
[1224] stream (ignored) 15 bytes {0} [optional] [built]
[1261] ./node_modules/@theia/core/src/common/keyboard/layouts sync ^\.\/.*\.json$ 1.39 KiB {0} [built]
[1414] ./node_modules/moment/locale sync ^\.\/.*$ 3 KiB {0} [optional] [built]
[1474] ./node_modules/vscode-textmate/release sync 160 bytes {0} [built]
[1637] ./node_modules/@theia/languages/node_modules/@theia/core/src/common/keyboard/layouts sync ^\.\/.*\.json$ 1.39 KiB {0} [built]
[1831] ./node_modules/@theia/json/node_modules/@theia/core/src/common/keyboard/layouts sync ^\.\/.*\.json$ 1.39 KiB {0} [built]
[2367] ./node_modules/uuid/dist/esm-browser/index.js + 14 modules 19 KiB {0} [built]
       |    15 modules
[2368] ./node_modules/idb/build/esm/index.js + 1 modules 10.1 KiB {0} [built]
       |    2 modules
    + 2356 hidden modules

WARNING in ./node_modules/vscode-textmate/release/main.js 23:15-27
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-service.js
 @ ./node_modules/@theia/monaco/lib/browser/textmate/index.js
 @ ./node_modules/@theia/plugin-ext/lib/main/browser/plugin-contribution-handler.js
 @ ./node_modules/@theia/plugin-ext/lib/main/browser/plugin-ext-frontend-module.js
 @ ./node_modules/@theia/plugin-ext/lib/plugin-ext-frontend-module.js
 @ ./src-gen/frontend/index.js

WARNING in ./node_modules/vscode-textmate/release/main.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'main.js.map': Error: Can't resolve './main.js.map' in '/Users/dima/work/theiaish/node_modules/vscode-textmate/release'
 @ ./node_modules/@theia/monaco/lib/browser/textmate/monaco-textmate-service.js 76:24-50
 @ ./node_modules/@theia/monaco/lib/browser/textmate/index.js
 @ ./node_modules/@theia/plugin-ext/lib/main/browser/plugin-contribution-handler.js
 @ ./node_modules/@theia/plugin-ext/lib/main/browser/plugin-ext-frontend-module.js
 @ ./node_modules/@theia/plugin-ext/lib/plugin-ext-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/declaration.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/declaration.js 7:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/foldingRange.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/foldingRange.js 7:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/colorProvider.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/colorProvider.js 7:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/client.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/client.js 10:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/implementation.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/implementation.js 7:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/typeDefinition.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/typeDefinition.js 7:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/configuration.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/configuration.js 7:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/workspaceFolders.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/workspaceFolders.js 8:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/progressPart.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/progressPart.js 7:17-34
 @ ./node_modules/vscode-languageclient/lib/client.js
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/protocolConverter.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/protocolConverter.js 7:13-30
 @ ./node_modules/vscode-languageclient/lib/client.js
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/langua
ge-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/codeConverter.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/codeConverter.js 7:13-30
 @ ./node_modules/vscode-languageclient/lib/client.js
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/protocolDocumentLink.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/protocolDocumentLink.js 7:13-30
 @ ./node_modules/vscode-languageclient/lib/protocolConverter.js
 @ ./node_modules/vscode-languageclient/lib/client.js
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/protocolCodeLens.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/protocolCodeLens.js 7:13-30
 @ ./node_modules/vscode-languageclient/lib/protocolConverter.js
 @ ./node_modules/vscode-languageclient/lib/client.js
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./node_modules/vscode-languageclient/lib/protocolCompletionItem.js
Module not found: Error: Can't resolve 'vscode' in '/Users/dima/work/theiaish/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/protocolCompletionItem.js 7:13-30
 @ ./node_modules/vscode-languageclient/lib/protocolConverter.js
 @ ./node_modules/vscode-languageclient/lib/client.js
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-factory.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js
Child worker:
     2 assets
    Entrypoint main = worker-ext.282125f06d918a955537.js worker-ext.282125f06d918a955537.js.map
     [18] (webpack)/buildin/global.js 472 bytes {0} [built]
     [32] ./node_modules/uuid/dist/esm-browser/index.js + 14 modules 19 KiB {0} [built]
          |    15 modules
    [118] stream (ignored) 15 bytes {0} [optional] [built]
    [186] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 201 hidden modules

Error: webpack exited with an unexpected code: 2.
    at ChildProcess.<anonymous> (/Users/dima/work/theiaish/node_modules/@theia/application-manager/lib/application-process.js:67:28)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1047:16)
    at Socket.<anonymous> (internal/child_process.js:438:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:672:12)
error Command failed with exit code 1.
```

Builds fine when `@theia/json` is removed. 
Built fine a month or so ago when all packages were set to `"^1.0.0"`

### Additional Information

- Operating System: macOS
- Theia Version: latest - 1.6

**Comment by vince-fugnitto** [comment]
@dmt0 the `@theia/json` extension is among other extensions which have been deprecated.

In order to use it you will need to downgrade your other extensions to a version which matches that last `latest` release of `@theia/json`.
