### ISSUE TITLE
TypeError: Cannot read property 'activeNotebookEditor' of undefined

### ISSUE THREAD

**Issue by tekumara** [eclipse-theia/theia#8649]
### Bug Description:

```
root ERROR [hosted-plugin: 17328] TypeError: Cannot read property 'activeNotebookEditor' of undefined
    at u.get activeNotebookEditor [as activeNotebookEditor] (/Users/tekumara/.theia/extensions/ms-python.python-2020.9.112786/extension/out/client/extension.js:54:383170)
    at d.update (/Users/tekumara/.theia/extensions/ms-python.python-2020.9.112786/extension/out/client/extension.js:56:255172)
    at Timeout._onTimeout (/Users/tekumara/.theia/extensions/ms-python.python-2020.9.112786/extension/out/client/extension.js:56:254465)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

### Steps to Reproduce:

1. Install ms-python.python
2. Open a python file
3. Check logs

### Additional Information

- Operating System: macOS
- Theia Version: master fe4062e66

**Comment by vince-fugnitto** [comment]
@tekumara the `activeNotebookEditor` and corresponding APIs are [`proposed`](https://github.com/microsoft/vscode/blob/0ea7e1ca9425b3814c9d0a3c0aa719daad92a53a/src/vs/vscode.proposed.d.ts#L1886-L1893) (not yet finalized). If I understand correctly, only the **insiders** version is able to use proposed APIs and extensions only: https://code.visualstudio.com/api/advanced-topics/using-proposed-api. 

For the framework, we can either wait until these APIs are finalized in VS Code, or attempt to add support for them but it may be subject to change frequently.

**Comment by sgraband** [comment]
`activeNotebookEditor` property properly implemented.
