### ISSUE TITLE
Debug editor model initialization could fail when restoring the breakpoints between app sessions

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8708]
### Bug Description:

Let assume you have  the following source file opened in editor:
```
// comment in line 1
// comment in line 2
callSomeMethod(); // this is line 3
// comment in line 4
```

Put a breakpoint to like 3; you will see the new breakpoint item in the _Breakpoints_ view and the editor. Delete lines 1 and 2.
```
callSomeMethod(); // this was line 3 but it's line 1 now.
// comment in line 2, used to be in line 4
```

Restart the app. The debug editor model tries to restore the sate, and put the breakpoint back to line 3, but it does not exist anymore:

```
root ERROR Error: @postConstruct error in class DebugEditorModel: Illegal value for lineNumber
    at _postConstruct (file:///Users/akos.kitta/git/my-app/electron-app/lib/bundle.js:81412:19)
    at Object.resolveInstance (file:///Users/akos.kitta/git/my-app/electron-app/lib/bundle.js:81429:5)
    at file:///Users/akos.kitta/git/my-app/electron-app/lib/bundle.js:81516:42
    at Object.resolve (file:///Users/akos.kitta/git/my-app/electron-app/lib/bundle.js:81540:12)
    at file:///Users/akos.kitta/git/my-app/electron-app/lib/bundle.js:80562:37
    at Container.../node_modules/inversify/lib/container/container.js.Container._get (file:///Users/akos.kitta/git/my-app/electron-app/lib/bundle.js:80553:44)
    at Container.../node_modules/inversify/lib/container/container.js.Container.get (file:///Users/akos.kitta/git/my-app/electron-app/lib/bundle.js:80473:21)
    at Function.push.../node_modules/@theia/debug/lib/browser/editor/debug-editor-model.js.DebugEditorModel.createModel (file:///Users/akos.kitta/git/my-app/electron-app/lib/30.bundle.js:2964:67)
    at DebugEditorService.factory (file:///Users/akos.kitta/git/my-app/electron-app/lib/57.bundle.js:86:58)
    at DebugEditorService.push.../node_modules/@theia/debug/lib/browser/editor/debug-editor-service.js.DebugEditorService.push (file:///Users/akos.kitta/git/my-app/electron-app/lib/30.bundle.js:3531:31)
```

There are no breakpoints in the editor, but there is still one in the breakpoint view referring to a non-existing line. Click on that; nothing happens.

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by colin-grant-work** [comment]
I'm no longer able to reproduce this. The debug editor model updates breakpoint locations when the content changes, so it is no longer stuck with the breakpoints / decorations defined at their old location.
