### ISSUE TITLE
Dracula At Night Theme extension doesn't work

### ISSUE THREAD

**Issue by rayakoren** [eclipse-theia/theia#8890]
### Bug Description:
Dracula At Night theme appears to be light and transparent, making it hard to read the menu commands because the text overlaps. 

### Steps to Reproduce:

1. Install Dracula At Night extension from Open VSX Registry.
2. Click File -> Settings -> Color Theme -> Dracula At Night
3. Open any menu (for example: 'Selection')

![image](https://user-images.githubusercontent.com/49866055/102982674-987dab80-4513-11eb-954f-f80ff5d9082f.png)

### Additional Information

- Operating System: mac OS 11.0.1
- Theia Version: 1.22.5

Error stacktrace: 
TypeError: Cannot read property 'length' of null
    at Object.parseHex (http://localhost:3000/vs/editor/editor.main.js:1305:38)
    at Function.Color.fromHex (http://localhost:3000/vs/editor/editor.main.js:1072:37)
    at StandaloneTheme.getColors (http://localhost:3000/vs/editor/editor.main.js:127144:50)
    at StandaloneTheme.getColor (http://localhost:3000/vs/editor/editor.main.js:127159:30)
    at DecorationCSSRules.resolveValue (http://localhost:3000/vs/editor/editor.main.js:102921:41)
    at DecorationCSSRules.collectCSSText (http://localhost:3000/vs/editor/editor.main.js:102911:34)
    at DecorationCSSRules.getCSSTextForModelDecorationClassName (http://localhost:3000/vs/editor/editor.main.js:102840:18)
    at DecorationCSSRules._buildCSS (http://localhost:3000/vs/editor/editor.main.js:102786:40)
    at new DecorationCSSRules (http://localhost:3000/vs/editor/editor.main.js:102738:18)
    at createCSSRules (http://localhost:3000/vs/editor/editor.main.js:102637:29)

**Comment by vince-fugnitto** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/8536.
