### ISSUE TITLE
Error: Connection got disposed on exit the browser

### ISSUE THREAD

**Issue by odeliat** [eclipse-theia/theia#8939]
### Bug Description:
When a user close the browser we get this error:

`
Error: Connection got disposed.
    at Object.dispose (/theia/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at /theia/node_modules/vscode-ws-jsonrpc/lib/socket/connection.js:14:41
    at CallbackList.invoke (/theia/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/theia/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/theia/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/theia/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/theia/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at WebSocketMessageReader.fireClose (/theia/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at WebSocketMessageReader.fireClose (/theia/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:67:19)
    at /theia/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:24:18
`

I found this [issue on the vscode-jsonrpc package](https://github.com/microsoft/vscode-languageserver-node/issues/639) that may be connected.

### Steps to Reproduce:

1. Run server locally
2. Open theia in the browser
3. Close theia browser
4. See the error on the server logs

### Additional Information

- Operating System: Local
- Theia Version: master

**Comment by vince-fugnitto** [comment]
@odeliat thank you for reporting the issue, besides the log is there any loss of functionality?
I am also unable to reproduce the issue (both `browser` and `electron` example applications) using the steps you provided.

**Comment by odeliat** [comment]
@vince-fugnitto 
There is no functionality loss, it's just the log.
I've added a screen video of the bug, hope it will help.


https://user-images.githubusercontent.com/14539932/104445653-06ad0f80-55a2-11eb-9fee-b968238335ae.mp4

**Comment by vince-fugnitto** [comment]
@odeliat thank you for providing the screenshare, I was unable to reproduce the log consistently (it's likely that it logs the disconnection during a specific lifecycle hook or operation). Since the log is intermittent, and there is no loss of functionality, I'll mark the issue as `minor`.

**Comment by odeliat** [comment]
@vince-fugnitto Is it ok if we change this message to warning?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Is it ok if we change this message to warning?

@odeliat pull-requests are welcome if you'd like to fix the log by adding error handling (likely cannot change the error to warning itself since its not part of our sources).
