### ISSUE TITLE
Cannot start the electron app from the launch config

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#9052]
### Bug Description:

The electron app does not start.

### Steps to Reproduce:

1. Build the project. I am on f1d469033.
2. Launch the electron app with the _Launch Electron Backend_ config.

```
root ERROR Failed to start the electron application.
root ERROR Error: Failed to get cookie domain
    at ElectronSecurityTokenService.<anonymous> (/Users/akos.kitta/git/theia/packages/core/lib/electron-main/electron-security-token-service.js:74:92)
    at step (/Users/akos.kitta/git/theia/packages/core/lib/electron-main/electron-security-token-service.js:57:23)
    at Object.next (/Users/akos.kitta/git/theia/packages/core/lib/electron-main/electron-security-token-service.js:38:53)
    at /Users/akos.kitta/git/theia/packages/core/lib/electron-main/electron-security-token-service.js:32:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/akos.kitta/git/theia/packages/core/lib/electron-main/electron-security-token-service.js:28:12)
    at ElectronSecurityTokenService.setElectronSecurityTokenCookie (/Users/akos.kitta/git/theia/packages/core/lib/electron-main/electron-security-token-service.js:71:16)
    at MiniBrowserElectronMainContribution.<anonymous> (/Users/akos.kitta/git/theia/packages/mini-browser/lib/electron-main/mini-browser-electron-main-contribution.js:85:80)
    at step (/Users/akos.kitta/git/theia/packages/mini-browser/lib/electron-main/mini-browser-electron-main-contribution.js:57:23)
    at Object.next (/Users/akos.kitta/git/theia/packages/mini-browser/lib/electron-main/mini-browser-electron-main-contribution.js:38:53)
```

### Additional Information

- Operating System:
- Theia Version:

**Comment by vince-fugnitto** [comment]
I confirm that I can also reproduce the issue when starting the _Launch Electron Backend_ configuration.
