### ISSUE TITLE
Support Rust-Analyzer Plugin

### ISSUE THREAD

**Issue by RodogInfinite** [eclipse-theia/theia#9136]
### Bug Description:
No rust-analyzer functionality. Appears in settings and commands, but doesn't work.

**Terminal output:**

> ERROR [hosted-plugin: 32685] Activating extension 'rust-analyzer' failed: Error: Text Content Document Provider for scheme 'rust-analyzer' is already registered
>     at WorkspaceExtImpl.registerTextDocumentContentProvider (/node_modules/@theia/plugin-ext/lib/plugin/workspace.js:274:19)
>     at Object.registerTextDocumentContentProvider (/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:488:37)
>     at expandMacro (/plugins/rust-analyzer/extension/out/src/main.js:15024:58)
>     at Ctx.registerCommand (/plugins/rust-analyzer/extension/out/src/main.js:15541:21)
>     at tryActivate (/plugins/rust-analyzer/extension/out/src/main.js:17612:11)
>     at async activate (/plugins/rust-analyzer/extension/out/src/main.js:17540:5)

**Notifications:**
![image](https://user-images.githubusercontent.com/22568404/109397284-02477680-7904-11eb-9f2b-bc28c9dcadf0.png)

### Steps to Reproduce:

1. Add the following line to the theiaPlugins in the package.json
`"rust-analyzer":"https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-11-16/rust-analyzer.vsix"`

- This is the latest version that will install without failing on VS Code version conflict. Example of the failure https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-11-23/rust-analyzer.vsix notifies:
![image](https://user-images.githubusercontent.com/22568404/109397458-a5988b80-7904-11eb-8a4a-0ed1f41cedaa.png)
- The current fix is a bit hacky for this, see: https://github.com/eclipse-theia/theia/issues/8828

2. Build and Start Theia
3. Install Language server version 0.2.384 for rust-analyzer from notification prompt
![image](https://user-images.githubusercontent.com/22568404/109397276-f3f95a80-7903-11eb-9d3a-5c53b3cf81da.png)

### Additional Information

- Operating System: Debian Buster 
- Theia Version: 1.12.0-next.8d5e12ac
- Node Version: v12.14.1-linux-x64
- Yarn Version: v1.22.10
- "@theia/monaco" : "next" in package.json dependencies
- Happens with or without "@theia/vscode-builtin-rust" : "next" in package.json dependencies

**Comment by vince-fugnitto** [comment]
I do not think we support _virtual documents_ or their APIs from the plugin system, including `registerTextDocumentContentProvider`.

**Comment by RodogInfinite** [comment]
I tried to use `"rust-analyzer": "https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-03-30/rust-analyzer.vsix"` in the theiaPlugins section in the package.json because it was mentioned in https://github.com/eclipse-theia/theia/issues/7608 as giving the following error message, but still working:
![image](https://user-images.githubusercontent.com/22568404/110023476-3acbc380-7cfb-11eb-8daa-2382148347be.png)

I also receive that error message, but do not get any functionality; however, my method of installing it is different.

For this particular version of the plugin I'm asked to download the following Language server:
![image](https://user-images.githubusercontent.com/22568404/110023773-8d0ce480-7cfb-11eb-86c4-daf5bb0b4153.png)

**The terminal output is:**

> ERROR [hosted-plugin: 15765] Activating extension 'rust-analyzer' failed: Error: Text Content Document Provider for scheme 'rust-analyzer' is already registered
>     at WorkspaceExtImpl.registerTextDocumentContentProvider (/node_modules/@theia/plugin-ext/lib/plugin/workspace.js:285:19)
>     at Object.registerTextDocumentContentProvider (/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:491:37)
>     at expandMacro (/plugins/rust-analyzer/extension/out/main.js:13071:40)
>     at Ctx.registerCommand (/plugins/rust-analyzer/extension/out/main.js:13783:21)
>     at activate (/plugins/rust-analyzer/extension/out/main.js:17545:11)

### Newest version with the same error:

The latest version of the plugin that doesn't give the double notification is `"rust-analyzer": "https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-06-29/rust-analyzer.vsix"` with the same message displayed when theia is running:

**Language server version is:** 
![image](https://user-images.githubusercontent.com/22568404/110035587-dd8b3e80-7d09-11eb-8e9b-b7cd8310da8b.png)

Otherwise 

After that version it looks like `activate (/plugins/rust-analyzer/extension/out/main.js:17545:11)` was changed to be asynchronously activated with `tryActivate (/plugins/rust-analyzer/extension/out/src/main.js:17612:11)` and
`async activate (/plugins/rust-analyzer/extension/out/src/main.js:17540:5)` implemented as can be seen from the terminal outputs.

**Comment by RodogInfinite** [comment]
Starting to compare the [VSCode registerTextDocumentContentProvider](https://github.com/microsoft/vscode/blob/a699ffaee62010c4634d301da2bbdb7646b8d1da/src/vs/workbench/api/common/extHostDocumentContentProviders.ts ) and the [Theia registerTextDocumentContentProvider](https://github.com/eclipse-theia/theia/blob/b972e2b21/packages/plugin-ext/src/plugin/workspace.ts#L55) though I don't have any TypeScript experience nor do I know how the plugin system works under the hood for Theia.

**Comment by RodogInfinite** [comment]
For a currently unknown reason, when I use `"rust-analyzer": "https://open-vsx.org/api/matklad/rust-analyzer/0.2.497/file/matklad.rust-analyzer-0.2.497.vsix"` in the package.json I get syntax highlighting and the run and debug buttons in my main.rs file: 
![image](https://user-images.githubusercontent.com/22568404/110531804-06d11380-80ea-11eb-8d22-57a41c955664.png)

However, neither of those buttons work. The same two error notifications occur as shown in the initial issue. 

Status output from the `Rust Analyzer: Status` command after clicking the Run button:

>  workspaces:
> 11 packages loaded
> 
> analysis:
> 705 (7mb) files
> 0 (0b) index symbols
> 367 trees, 128 retained
> 12473 trees, 128 retained (macros)
> 175mb total
> 
> counts:
> all counts are zero
> 
> file info:
> crate: hello(CrateId(10))
> deps: core=CrateId(1), alloc=CrateId(0), std=CrateId(6)
> 
> 
> requests:
>   255 textDocument/codeLens               124ms
>   258 textDocument/hover                  0ms
> *   3 textDocument/semanticTokens/full    0ms
>     4 textDocument/codeLens               1298ms
>     5 textDocument/hover                  0ms
>   193 textDocument/hover                  0ms
>   252 textDocument/foldingRange           0ms
>   250 textDocument/codeAction             142ms
>   251 textDocument/semanticTokens/full    142ms
>   253 textDocument/codeLens               0ms

## Note: This open-vsx package is _not_ searchable in the "Extensions: OPEN VSX REGISTRY" search

![image](https://user-images.githubusercontent.com/22568404/110532786-477d5c80-80eb-11eb-94c5-bce21891d464.png)

![image](https://user-images.githubusercontent.com/22568404/110532886-667bee80-80eb-11eb-8918-0aa3ba0c882f.png)
It doesn't appear when scrolling further down

**Comment by RodogInfinite** [comment]
@vince-fugnitto what would be the latest `vscode.engines` version that would need to be available to be searchable from within Theia? There's an ongoing effort in the rust-analyzer community to support open-vsx and it might be possible to get that version published, see: https://github.com/rust-analyzer/rust-analyzer/issues/7284

**Comment by jeluard** [comment]
@vince-fugnitto I have the same issue highlighted in the original comment (` Error: Text Content Document Provider for scheme 'rust-analyzer' is already registered`)

Is it a know issue that is being worked on?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I have the same issue highlighted in the original comment (` Error: Text Content Document Provider for scheme 'rust-analyzer' is already registered`)
> 
> Is it a know issue that is being worked on?

@jeluard feel free to pick up the issue :+1:

**Comment by vince-fugnitto** [comment]
@RodogInfinite  @jeluard the documentation states the following, do you perhaps have both installed at the same time:

> Provides support for rust-analyzer: novel LSP server for the Rust programming language.
>
> **Note** the extension may cause conflicts with the official Rust extension. It is recommended to disable the Rust extension when using the rust-analyzer extension.
>
> **Note** the project is in alpha status: it is already useful in practice, but can't be considered stable.

**Comment by jeluard** [comment]
@vince-fugnitto I do not, no. 

Also note that I can see the following log twice when starting theia, not sure if expected:

```js
root INFO [hosted-plugin: 24611] PLUGIN_HOST(24611): PluginManagerExtImpl/init()
root INFO [hosted-plugin: 24611] PLUGIN_HOST(24611): initializing(rust-analyzer@0.2.497 with /Users/julien/Documents/Projects/jeluard/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
...
```

**Comment by RodogInfinite** [comment]
@vince-fugnitto I also do not have the official Rust extension installed simultaneously with Rust-Analyzer. I can successfully get it running in VSCode with no issues

**Comment by jeluard** [comment]
Also note that I can see this error, unsure if relevant:

```js
root ERROR [ad35fa06-5576-40ac-b57a-3ee6f24ac816][matklad.rust-analyzer]: Failed to load 'configuration' contribution. TypeError: Cannot create property 'scope' on boolean 'false'
    at Object.fromPreferenceSchemaProperty (http://localhost:3000/bundle.js:144722:31)
    at PreferenceSchemaProvider.../../packages/core/lib/browser/preferences/preference-contribution.js.PreferenceSchemaProvider.doSetSchema (http://localhost:3000/bundle.js:120041:82)
    at PreferenceSchemaProvider.../../packages/core/lib/browser/preferences/preference-contribution.js.PreferenceSchemaProvider.setSchema (http://localhost:3000/bundle.js:120122:28)
    at http://localhost:3000/56.bundle.js:7781:103
    at pushContribution (http://localhost:3000/56.bundle.js:7772:32)
    at _loop_1 (http://localhost:3000/56.bundle.js:7781:17)
    at PluginContributionHandler.push.../../packages/plugin-ext/lib/main/browser/plugin-contribution-handler.js.PluginContributionHandler.handleContributions (http://localhost:3000/56.bundle.js:7786:21)
    at _loop_2 (http://localhost:3000/56.bundle.js:969:63)
    at HostedPluginSupport.push.../../packages/plugin-ext/lib/hosted/browser/hosted-plugin.js.HostedPluginSupport.loadContributions (http://localhost:3000/56.bundle.js:990:17)
    at HostedPluginSupport.<anonymous> (http://localhost:3000/56.bundle.js:836:52)
```

**Comment by statictype** [comment]
I am playing with Theia locally to see if it fits for a Rust project and i also do not have any other Rust extensions installed. I was not able to get `rust-analyzer` to work properly.

However, there is this line in `package.json`

`"vscode-builtin-rust": "https://open-vsx.org/api/vscode/rust/1.45.1/file/vscode.rust-1.45.1.vsix",`

Is that the official extension? do i need to remove it?

**Comment by vince-fugnitto** [comment]
> However, there is this line in `package.json` 
> `"vscode-builtin-rust": "https://open-vsx.org/api/vscode/rust/1.45.1/file/vscode.rust-1.45.1.vsix",`
> Is that the official extension? do i need to remove it?

@statictype that extension is the official rust builtin extension packaged with vscode, it related to the following:
- https://github.com/microsoft/vscode/tree/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/rust

It mainly contributes syntax-highlighting and snippets for the rust programming language.

**Comment by vince-fugnitto** [comment]
Despite the initial error, I do see that `rust-analyzer` works (potentially partially) it indexes, reports correct language-client/language-server communication, produces error markers, commands, preferences:

![image](https://user-images.githubusercontent.com/40359487/111325898-81e27e80-8642-11eb-9090-1819b337fbd4.png)

It may help narrow down your issues and investigations. I'm using the following version (which is API compatible): 
- https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-11-16/rust-analyzer.vsix

**Comment by statictype** [comment]
i'm not a rust developer myself, will have to check back with the team to see if it works entirely or partially.
But, version `2020-11-16` seems to be working despite the initial errors. 
thanks, that really helped!

**Comment by jeluard** [comment]
@vince-fugnitto Indeed this version looks better, although there is still the original issue.

The [other issue](https://github.com/eclipse-theia/theia/issues/9136#issuecomment-800266599) I encountered disappeared, it might be the one preventing the plugin to work at all.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Indeed this version looks better, although there is still the original issue.
> 
> The [other issue](https://github.com/eclipse-theia/theia/issues/9136#issuecomment-800266599) I encountered disappeared, it might be the one preventing the plugin to work at all.

The log is also present in vscode when investigating their devtools console:

![image](https://user-images.githubusercontent.com/40359487/111345412-a5fa8b80-8653-11eb-9bd3-5e5f1dae14ff.png)

**Comment by jeluard** [comment]
@vince-fugnitto Nice find! I will follow up with the `rust-analyzer` team.

Somehow it's working ok for me on regular VSCode (on OSX). It might be more resilient to those issues?

**Comment by RodogInfinite** [comment]
> 
> 
> i'm not a rust developer myself, will have to check back with the team to see if it works entirely or partially.
> But, version `2020-11-16` seems to be working despite the initial errors.
> thanks, that really helped!

@statictype & @jeluard 
Does the run button appear for you, pictured below, and when you click it does it run as if you typed `cargo run` in the terminal?
![image](https://user-images.githubusercontent.com/22568404/110531804-06d11380-80ea-11eb-8d22-57a41c955664.png)

**Comment by jeluard** [comment]
@RodogInfinite Nice catch too! No it doesn't, and I get the following error:

```js
ERROR Error: Command with id 'rust-analyzer.runSingle' is not registered.
```

**Comment by RodogInfinite** [comment]
I'm unable to look at this deeply at the moment, but one thing to look for is which version first implemented the "run" and "debug" buttons. It may have appeared after the `2020-11-16` release. If no one else finds this before I'm able to look, I'll edit this post with the information when I locate it so as to reduce the number of comments.

**Comment by jeluard** [comment]
I meant that the buttons are there, but broken.

**Comment by RodogInfinite** [comment]
So the official Rust plugin is tracking to merge with rust-analyzer (https://github.com/rust-lang/vscode-rust/issues/812) and when "rust-lang" is installed, rust-analyzer can be selected as the server from the settings; however, I don't get syntax highlighting nor the ` run | debug` buttons when I select that option. I'm not sure how much will change by the time the merging is finalized, but it might be worth focusing on the official rust plugin to get the rust-analyzer functionality for the long-term

**Comment by jeluard** [comment]
With latest theia 1.12.0 and latest `rust-analyzer` I now get the following exception:

```js
root ERROR [hosted-plugin: 11849] Activating extension 'rust-analyzer' failed: TypeError: Class extends value undefined is not a constructor or null
    at /Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/rust-analyzer/extension/out/src/main.js:12905:63
    at createCommonjsModule (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/rust-analyzer/extension/out/src/main.js:66:9)
    at Object.<anonymous> (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/rust-analyzer/extension/out/src/main.js:11119:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.module._load (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js:67:33)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
root ERROR [hosted-plugin: 11849] Activating extension 'Git (built-in)' failed: TypeError: n.window.registerFileDecorationProvider is not a function
    at new c (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/vscode-builtin-git/extension/dist/main.js:10:472547)
    at new t.GitDecorations (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/vscode-builtin-git/extension/dist/main.js:10:474947)
    at _ (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/vscode-builtin-git/extension/dist/main.js:1:79118)
    at async T (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/vscode-builtin-git/extension/dist/main.js:1:80865)
    at async t.activate (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/vscode-builtin-git/extension/dist/main.js:1:81734)
```

@vince-fugnitto maybe this rings a bell?

**Comment by jeluard** [comment]
FWIW the line triggering the error is:

```js
class LSPCancellationError extends vscode__default['default'].CancellationError {
```

**Comment by jeluard** [comment]
More context: this has been introduced in VSCode `1.53.0`: https://code.visualstudio.com/updates/v1_53#_adding-cancellationerror-type

It looks like recent [vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node) depend on it.

**Comment by jeluard** [comment]
Moving back to an older version, `489`, I still get the infamous error:

```js
root ERROR [hosted-plugin: 62023] Activating extension 'rust-analyzer' failed: Error: Text Content Document Provider for scheme 'rust-analyzer' is already registered
    at WorkspaceExtImpl.registerTextDocumentContentProvider (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/node_modules/@theia/plugin-ext/lib/plugin/workspace.js:285:19)
    at Object.registerTextDocumentContentProvider (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:497:37)
    at viewHir (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/rust-analyzer/extension/out/src/main.js:18678:58)
    at Ctx.registerCommand (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/rust-analyzer/extension/out/src/main.js:19264:21)
    at tryActivate (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/rust-analyzer/extension/out/src/main.js:21340:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async activate (/Users/julien/Documents/Projects/paritytech/substrate-playground/templates/theia-playground/plugins/rust-analyzer/extension/out/src/main.js:21268:5)
```

Not sure how to debug that.

**Comment by jeluard** [comment]
When adding some traces, I can see that `TextContentResourceResolver.prototype.registerContentProvider` is called multiple times with the same `scheme`:

```
root INFO [3bd595d9-13df-4f5d-b139-c7d85011624c] Start of 18 plugins took: 694.3 ms
root INFO [hosted-plugin: 74351] Registering rust-analyzer-status [object Object]
root INFO [hosted-plugin: 74351] Registering rust-analyzer-memory [object Object]
root INFO [hosted-plugin: 74351] Registering rust-analyzer [object Object]
root INFO [hosted-plugin: 74351] Registering rust-analyzer [object Object]
root INFO [hosted-plugin: 74351] Registering rust-analyzer [object Object]
root INFO [4f0a4b9d-6ca9-457c-bb2c-e7dea13faa7b][matklad.rust-analyzer]: Started plugin.
```

Not clear why.

If I remove the check so that this function doesn't fail anymore, I then hit another error:

```js
root ERROR [hosted-plugin: 74313] Promise rejection not handled in one second: Error: Text Content Resource Provider for scheme 'rust-analyzer' is already registered , reason: Error: Text Content Resource Provider for scheme 'rust-analyzer' is already registered
root ERROR [hosted-plugin: 74313] With stack trace: Error: Text Content Resource Provider for scheme 'rust-analyzer' is already registered
    at TextContentResourceResolver.push.../node_modules/@theia/plugin-ext/lib/main/browser/workspace-main.js.TextContentResourceResolver.registerContentProvider (http://localhost:3000/48.bundle.js:19659:19)
    at WorkspaceMainImpl.<anonymous> (http://localhost:3000/48.bundle.js:19606:39)
    at step (http://localhost:3000/48.bundle.js:19302:23)
    at Object.next (http://localhost:3000/48.bundle.js:19283:53)
    at http://localhost:3000/48.bundle.js:19277:71
    at new Promise (<anonymous>)
    at push.../node_modules/@theia/plugin-ext/lib/main/browser/workspace-main.js.__awaiter (http://localhost:3000/48.bundle.js:19273:12)
    at WorkspaceMainImpl.push.../node_modules/@theia/plugin-ext/lib/main/browser/workspace-main.js.WorkspaceMainImpl.$registerTextDocumentContentProvider (http://localhost:3000/48.bundle.js:19603:16)
    at RPCProtocolImpl.push.../node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (http://localhost:3000/39.bundle.js:1373:23)
    at RPCProtocolImpl.push.../node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.invokeHandler (http://localhost:3000/39.bundle.js:1358:41)
Promise rejection not handled in one second: Error: Text Content Resource Provider for scheme 'rust-analyzer' is already registered , reason: Error: Text Content Resource Provider for scheme 'rust-analyzer' is already registered
With stack trace: Error: Text Content Resource Provider for scheme 'rust-analyzer' is already registered
    at TextContentResourceResolver.push.../node_modules/@theia/plugin-ext/lib/main/browser/workspace-main.js.TextContentResourceResolver.registerContentProvider (http://localhost:3000/48.bundle.js:19659:19)
    at WorkspaceMainImpl.<anonymous> (http://localhost:3000/48.bundle.js:19606:39)
    at step (http://localhost:3000/48.bundle.js:19302:23)
    at Object.next (http://localhost:3000/48.bundle.js:19283:53)
    at http://localhost:3000/48.bundle.js:19277:71
    at new Promise (<anonymous>)
    at push.../node_modules/@theia/plugin-ext/lib/main/browser/workspace-main.js.__awaiter (http://localhost:3000/48.bundle.js:19273:12)
    at WorkspaceMainImpl.push.../node_modules/@theia/plugin-ext/lib/main/browser/workspace-main.js.WorkspaceMainImpl.$registerTextDocumentContentProvider (http://localhost:3000/48.bundle.js:19603:16)
    at RPCProtocolImpl.push.../node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (http://localhost:3000/39.bundle.js:1373:23)
    at RPCProtocolImpl.push.../node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.invokeHandler (http://localhost:3000/39.bundle.js:1358:41)
```


Also the following error happens sometimes:

```js
root ERROR Error: Text Content Resource Provider for scheme 'rust-analyzer' has not been registered
    at TextContentResourceResolver.push.../node_modules/@theia/plugin-ext/lib/main/browser/workspace-main.js.TextContentResourceResolver.unregisterContentProvider (http://localhost:3000/48.bundle.js:19680:19)
    at Object.<anonymous> (http://localhost:3000/48.bundle.js:19607:112)
    at Object.disposable.dispose (http://localhost:3000/bundle.js:61019:13)
    at DisposableCollection.../node_modules/@theia/core/lib/common/disposable.js.DisposableCollection.dispose (http://localhost:3000/bundle.js:60996:40)
    at WorkspaceMainImpl.push.../node_modules/@theia/plugin-ext/lib/main/browser/workspace-main.js.WorkspaceMainImpl.dispose (http://localhost:3000/48.bundle.js:19376:24)
    at WorkspaceMainImpl.disposable.dispose (http://localhost:3000/bundle.js:61019:13)
    at DisposableCollection.../node_modules/@theia/core/lib/common/disposable.js.DisposableCollection.dispose (http://localhost:3000/bundle.js:60996:40)
    at RPCProtocolImpl.push.../node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.dispose (http://localhost:3000/39.bundle.js:1211:24)
    at RPCProtocolImpl.disposable.dispose (http://localhost:3000/bundle.js:61019:13)
    at DisposableCollection.../node_modules/@theia/core/lib/common/disposable.js.DisposableCollection.dispose (http://localhost:3000/bundle.js:60996:40)
```

This implies `TextContentResourceResolver.unregisterContentProvider` is called before any registration is done, for some reason.

**Comment by jeluard** [comment]
@vince-fugnitto Where should I look if I want to add CancellationError ? A bit lost here :)

**Comment by vince-fugnitto** [comment]
@jeluard I haven't investigated the issue further or verified what changes might be necessary in the framework for it to work correctly.

The `CancellationError` was introduced in `1.53.0` and we are not currently at that API level. It's possible that you might get it to work but it will likely fail due to other compatibility errors. If interested in adding support you can take a look at previous pull-requests that introduce support for plugin APIs to get a better understanding of the plugin-system. 

The API will need to be defined in `theia.d.ts` and you can inspire yourself from the implementation present in vscode which will be similar to changes required in the framework (in this case it looks like a simple extension of `Error`).

**Comment by colin-grant-work** [comment]
Some current issues here:
 - [ ] Failed to activate because `"Text Content Document Provider for scheme 'rust-analyzer' is already registered"`. The plugin registers several `textContentDocumentProviders`, and the registration is called multiple times for the `rust-analyzer` scheme. Probably should not be fatal, but investigation required to see whether the plugin is registering different providers or the same one repeatedly, and how VSCode handles analogous registrations.
 - [ ] When activating the `vscode-lldb` plugin for debugging, error is thrown for call to `NetServer.listen` with neither `port` nor `path` field. Problem occurs [here](https://github.com/vadimcn/vscode-lldb/blob/54d4fbb2dead83e98bd44d07057b67efc4305531/extension/main.ts#L204-L205) where Theia's preference access system returns `{}` and VSCode's returns `null`. As a consequence, RPC is not started in VSCode but is in Theia.

**Comment by msujew** [comment]
As far as I can tell, both `rust-analyzer` and `vscode-lldb` are now working pretty well in Theia. Closing this. Please create a new issue in case any new problems with the plugin comes up.
