### ISSUE TITLE
TypeError: Cannot read property 'defaultValue' of undefined when uninstalling a VS Code extension

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#9241]
### Bug Description:

This happened when I have uninstalled the Red Hat Java VSX and the Grade Tasks VSX.

```
Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
root ERROR The above error occurred in the <SinglePreferenceWrapper> component:
    in SinglePreferenceWrapper
    in div
    in div
```
This 👆  was logged roughly 70 times.

```
root ERROR TypeError: Cannot read property 'defaultValue' of undefined
    at SinglePreferenceWrapper.push.../../packages/preferences/lib/browser/views/components/single-preference-wrapper.js.SinglePreferenceWrapper.render (file:///Users/akos.kitta/git/theia/examples/electron/lib/66.bundle.js:3867:146)
    at finishClassComponent (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:68428:31)
    at updateClassComponent (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:68378:24)
    at beginWork (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:69888:16)
    at HTMLUnknownElement.callCallback (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:51456:14)
    at Object.invokeGuardedCallbackDev (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:51505:16)
    at invokeGuardedCallback (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:51560:31)
    at beginWork$1 (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:74471:7)
    at performUnitOfWork (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:73425:12)
    at workLoopSync (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:73398:22)
```

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by colin-grant-work** [comment]
@kittaakos, how were you uninstalling these plugins? Using the Extensions widget, or some other method?

**Comment by kittaakos** [comment]
> Using the Extensions widget, or some other method?

Yes, I clicked on the _Uninstall_ from the view.
