### ISSUE TITLE
rebuild electron error

### ISSUE THREAD

**Issue by JohnsenZhou** [eclipse-theia/theia#9274]
#### Bug:

<details>
<summary>yarn rebuild:electron error</summary>

<br />

```
➜  theia git:(master) yarn run rebuild:electron
yarn run v1.22.10
$ theia rebuild:electron
Processing @theia/node-pty
Processing nsfw
Processing native-keymap
Processing find-git-repositories
Processing drivelist
✖ Rebuild Failed
Uncaught Exception:  Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.19.0 | darwin | x64
gyp info find Python using Python version 3.8.2 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/didi/didi/theia/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/didi/didi/theia/node_modules/drivelist/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/didi/didi/theia/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/didi/.electron-gyp/9.4.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/didi/.electron-gyp/9.4.4',
gyp info spawn args   '-Dnode_gyp_dir=/Users/didi/didi/theia/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/didi/.electron-gyp/9.4.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/didi/didi/theia/node_modules/drivelist',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/drivelist/src/drivelist.o
In file included from ../src/drivelist.cpp:17:
In file included from ../../nan/nan.h:56:
In file included from /Users/didi/.electron-gyp/9.4.4/include/node/node.h:63:
/Users/didi/.electron-gyp/9.4.4/include/node/v8.h:10255:3: error: unterminated /* comment
  /**
  ^
/Users/didi/.electron-gyp/9.4.4/include/node/v8.h:15:2: error: unterminated conditional directive
#ifndef INCLUDE_V8_H_
 ^
/Users/didi/.electron-gyp/9.4.4/include/node/v8.h:10207:17: error: missing '}' at end of definition of 'v8::Context'
class V8_EXPORT Context {
                ^
/Users/didi/.electron-gyp/9.4.4/include/node/v8-platform.h:16:1: note: still within definition of 'v8::Context' here
namespace v8 {
^
In file included from ../src/drivelist.cpp:17:
In file included from ../../nan/nan.h:56:
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:116:13: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
NODE_EXTERN v8::Local<v8::Value> ErrnoException(v8::Isolate* isolate,
            ^~~~~~~~~
            Local
/Users/didi/.electron-gyp/9.4.4/include/node/v8.h:186:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/drivelist.cpp:17:
In file included from ../../nan/nan.h:56:
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:116:27: error: no member named 'Value' in namespace 'v8::v8'
NODE_EXTERN v8::Local<v8::Value> ErrnoException(v8::Isolate* isolate,
                      ~~~~^
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:121:13: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
NODE_EXTERN v8::Local<v8::Value> UVException(v8::Isolate* isolate,
            ^~~~~~~~~
            Local
/Users/didi/.electron-gyp/9.4.4/include/node/v8.h:186:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/drivelist.cpp:17:
In file included from ../../nan/nan.h:56:
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:121:27: error: no member named 'Value' in namespace 'v8::v8'
NODE_EXTERN v8::Local<v8::Value> UVException(v8::Isolate* isolate,
                      ~~~~^
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:129:24: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                inline v8::Local<v8::Value> ErrnoException(
                       ^~~~~~~~~
                       Local
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/didi/.electron-gyp/9.4.4/include/node/v8.h:186:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/drivelist.cpp:17:
In file included from ../../nan/nan.h:56:
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:129:38: error: no member named 'Value' in namespace 'v8::v8'
                inline v8::Local<v8::Value> ErrnoException(
                                 ~~~~^
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:134:29: error: incomplete type 'v8::v8::Isolate' named in nested name specifier
  return ErrnoException(v8::Isolate::GetCurrent(),
                        ~~~~^~~~~~~~~
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/didi/.electron-gyp/9.4.4/include/node/v8-platform.h:18:7: note: forward declaration of 'v8::v8::Isolate'
class Isolate;
      ^
In file included from ../src/drivelist.cpp:17:
In file included from ../../nan/nan.h:56:
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:142:24: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                inline v8::Local<v8::Value> UVException(int errorno,
                       ^~~~~~~~~
                       Local
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/didi/.electron-gyp/9.4.4/include/node/v8.h:186:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/drivelist.cpp:17:
In file included from ../../nan/nan.h:56:
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:142:38: error: no member named 'Value' in namespace 'v8::v8'
                inline v8::Local<v8::Value> UVException(int errorno,
                                 ~~~~^
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:146:26: error: incomplete type 'v8::v8::Isolate' named in nested name specifier
  return UVException(v8::Isolate::GetCurrent(),
                     ~~~~^~~~~~~~~
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/didi/.electron-gyp/9.4.4/include/node/v8-platform.h:18:7: note: forward declaration of 'v8::v8::Isolate'
class Isolate;
      ^
In file included from ../src/drivelist.cpp:17:
In file included from ../../nan/nan.h:56:
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:161:29: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                            ^~~~~~~~~
                            Local
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/didi/.electron-gyp/9.4.4/include/node/v8.h:186:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/drivelist.cpp:17:
In file included from ../../nan/nan.h:56:
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:161:43: error: no member named 'Value' in namespace 'v8::v8'
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                      ~~~~^
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:163:21: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                    v8::Local<v8::Object> recv,
                    ^~~~~~~~~
                    Local
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/didi/.electron-gyp/9.4.4/include/node/v8.h:186:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/drivelist.cpp:17:
In file included from ../../nan/nan.h:56:
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:163:35: error: no member named 'Object' in namespace 'v8::v8'
                    v8::Local<v8::Object> recv,
                              ~~~~^
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:166:21: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                    v8::Local<v8::Value>* argv));
                    ^~~~~~~~~
                    Local
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/didi/.electron-gyp/9.4.4/include/node/v8.h:186:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/drivelist.cpp:17:
In file included from ../../nan/nan.h:56:
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:166:35: error: no member named 'Value' in namespace 'v8::v8'
                    v8::Local<v8::Value>* argv));
                              ~~~~^
/Users/didi/.electron-gyp/9.4.4/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/drivelist/src/drivelist.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/didi/didi/theia/node_modules/electron-rebuild/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/Users/didi/didi/theia/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=9.4.4" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/didi/didi/theia/node_modules/drivelist
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
error Command failed with exit code 255.
```

</details>

#### Additional Information

- Operating System:
- Theia Version: 1.12.0
- System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm

**Comment by JohnsenZhou** [comment]
when i use the yarn.lock of version 1.11.0 and reinstall dependencies，everything is ok

**Comment by vince-fugnitto** [comment]
@JohnsenZhou thank you for reporting the issue, I have a couple of questions:
- Did you reproduce the issue on `master` without a `yarn.lock` or your own application? 
- Did you update any dependencies which would then be pinned by the `yarn.lock` from a previous version? (ex: electron)

**Comment by vince-fugnitto** [comment]
For additional information, using the following commit 71f762c59580670a3ae1f661bc10010f0d5581f1 (master) I verified the following on macOS:
- I was able to build without a `yarn.lock` present.
- I was able to run `yarn rebuild:electron` successfully.
- I was able to start the `example-electron` application.

**Comment by JohnsenZhou** [comment]
@vince-fugnitto thank you for your reply. I try to delete the cache of the `.electron-gyp` folder in the root directory, and then reinstall the dependencies,  it worked.

**Comment by vince-fugnitto** [comment]
Thank you for following up on the issue!

I believe the issue is closeable, we confirmed it worked (https://github.com/eclipse-theia/theia/issues/9274#issuecomment-811864979), and confirmed that building without a `yarn.lock` also works (https://github.com/eclipse-theia/theia/issues/9274#issuecomment-811458944). If you have additional information please don't hesitate to comment on the issue :+1:
