### ISSUE TITLE
It doesn't build on FreeBSD

### ISSUE THREAD

**Issue by helioloureiro** [eclipse-theia/theia#9279]
### Bug Description:
One of the npm dependencies, puppeteer,  doesn't have support for FreeBSD.

After git repository clone:
helio@freebsd ~/theia (master)> yarn
yarn install v1.22.10
$ node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.21.0 | freebsd | x64
gyp http GET https://nodejs.org/download/release/v12.21.0/node-v12.21.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.21.0/node-v12.21.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.21.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.21.0/SHASUMS256.txt
12.21.0
gyp info ok 
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "freebsd" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.2: The platform "freebsd" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "freebsd" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > chai-string@1.5.0" has unmet peer dependency "chai@^4.1.2".
warning "workspace-aggregator-d3d88c46-8bec-49d3-85ea-e658927167f8 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-d3d88c46-8bec-49d3-85ea-e658927167f8 > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-d3d88c46-8bec-49d3-85ea-e658927167f8 > @theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-d3d88c46-8bec-49d3-85ea-e658927167f8 > @theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-d3d88c46-8bec-49d3-85ea-e658927167f8 > @theia/scm > react-autosize-textarea@7.1.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-d3d88c46-8bec-49d3-85ea-e658927167f8 > @theia/scm > react-autosize-textarea@7.1.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-d3d88c46-8bec-49d3-85ea-e658927167f8 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
[5/5] Building fresh packages...
[6/15] ⠁ native-keymap
[2/15] ⠁ command-join
[8/15] ⠁ drivelist
[4/15] ⠂ puppeteer
error /usr/home/helio/theia/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /usr/home/helio/theia/node_modules/puppeteer
Output:
/usr/home/helio/theia/node_modules/puppeteer/lib/helper.js:283
    throw new Error(message);
    ^

Error: Unsupported platform: freebsd
    at assert (/usr/home/helio/theia/node_modules/puppeteer/lib/helper.js:283:11)
    at new BrowserFetcher (/usr/home/helio/theia/node_modules/puppeteer/lib/BrowserFetcher.js:96:7)
    at module.exports.createBrowserFetcher (/usr/home/helio/theia/node_modules/puppeteer/lib/Puppeteer.js:102:12)
    at Object.<anonymous> (/usr/home/helio/theia/node_modules/puppeteer/install.js:41:34)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)

### Steps to Reproduce:

1. git clone https://github.com/eclipse-theia/theia
2. cd theia
3. yarn

helio@freebsd ~/theia (master)> uname -a
FreeBSD freebsd 13.0-RC1 FreeBSD 13.0-RC1 #0 releng/13.0-n244639-60e8939aa85: Fri Mar  5 05:01:01 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
helio@freebsd ~/theia (master)> node --version
v12.21.0
helio@freebsd ~/theia (master)> npm --version
6.14.8
helio@freebsd ~/theia (master)> yarn --version
1.22.10

### Additional Information

- Operating System: FreeBSD-13.0-RC1
- Theia Version: latest from master

**Comment by vince-fugnitto** [comment]
@helioloureiro thank you for reporting the issue, I feel as though this should be something fixed in `puppeteer` itself (perhaps there are workarounds). I do not believe the framework wants to migrate from `puppeteer` for testing at this time.

**Comment by kittaakos** [comment]
Can you skip it with the following?
```
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
yarn
```

**Comment by helioloureiro** [comment]
Almost...

helio@freebsd ~/theia (master)> yarn
yarn install v1.22.10
$ node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.21.0 | freebsd | x64
gyp http GET https://nodejs.org/download/release/v12.21.0/node-v12.21.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.21.0/node-v12.21.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.21.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.21.0/SHASUMS256.txt
12.21.0
gyp info ok 
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "freebsd" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.2: The platform "freebsd" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "freebsd" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > chai-string@1.5.0" has unmet peer dependency "chai@^4.1.2".
warning "workspace-aggregator-5db5c7c8-3191-4637-b97f-541b8dcc7e64 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-5db5c7c8-3191-4637-b97f-541b8dcc7e64 > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-5db5c7c8-3191-4637-b97f-541b8dcc7e64 > @theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-5db5c7c8-3191-4637-b97f-541b8dcc7e64 > @theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-5db5c7c8-3191-4637-b97f-541b8dcc7e64 > @theia/scm > react-autosize-textarea@7.1.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-5db5c7c8-3191-4637-b97f-541b8dcc7e64 > @theia/scm > react-autosize-textarea@7.1.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-5db5c7c8-3191-4637-b97f-541b8dcc7e64 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
[5/5] Building fresh packages...
[9/15] ⡀ nsfw
[2/15] ⡀ command-join
[6/15] ⡀ native-keymap
[8/15] ⡀ drivelist
error /usr/home/helio/theia/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /usr/home/helio/theia/node_modules/electron
Output:
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-freebsd-x64.zip
    at EventEmitter.<anonymous> (/usr/home/helio/theia/node_modules/@electron/get/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:314:20)
    at module.exports (/usr/home/helio/theia/node_modules/@electron/get/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/usr/home/helio/theia/node_modules/@electron/get/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.origin.emit (/usr/home/helio/theia/node_modules/@szmarczak/http-timer/source/index.js:37:11)


Now it complains regarding electron for download.  I've electron7 installed via ports/pkg.  Is there a parameter to point it to use this local electron installation?

**Comment by helioloureiro** [comment]
Found a way.

helio@freebsd ~/theia (master)> set -x ELECTRON_SKIP_BINARY_DOWNLOAD true
helio@freebsd ~/theia (master)> yarn
yarn install v1.22.10
$ node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.21.0 | freebsd | x64
gyp http GET https://nodejs.org/download/release/v12.21.0/node-v12.21.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.21.0/node-v12.21.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.21.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.21.0/SHASUMS256.txt
12.21.0
gyp info ok 
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "freebsd" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.2: The platform "freebsd" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "freebsd" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > chai-string@1.5.0" has unmet peer dependency "chai@^4.1.2".
warning "workspace-aggregator-cb6f1a04-ed0c-4eab-b472-731745e7a2f3 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-cb6f1a04-ed0c-4eab-b472-731745e7a2f3 > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-cb6f1a04-ed0c-4eab-b472-731745e7a2f3 > @theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react@>=16.3.3".
warning "workspace-aggregator-cb6f1a04-ed0c-4eab-b472-731745e7a2f3 > @theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react-dom@>=16.3.3".
warning "workspace-aggregator-cb6f1a04-ed0c-4eab-b472-731745e7a2f3 > @theia/scm > react-autosize-textarea@7.1.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-cb6f1a04-ed0c-4eab-b472-731745e7a2f3 > @theia/scm > react-autosize-textarea@7.1.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-cb6f1a04-ed0c-4eab-b472-731745e7a2f3 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
[5/5] Building fresh packages...
[8/15] ⠂ drivelist
[2/15] ⠂ command-join
[9/15] ⠄ nsfw
[7/15] ⠄ native-keymap
error /usr/home/helio/theia/dev-packages/eslint-plugin/node_modules/nsfw: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /usr/home/helio/theia/dev-packages/eslint-plugin/node_modules/nsfw
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.21.0 | freebsd | x64
gyp info find Python using Python version 3.7.9 found at "/usr/local/bin/python3.7"
gyp info spawn /usr/local/bin/python3.7
gyp info spawn args [
gyp info spawn args   '/usr/home/helio/theia/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/home/helio/theia/dev-packages/eslint-plugin/node_modules/nsfw/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/home/helio/theia/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/helio/.cache/node-gyp/12.21.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/helio/.cache/node-gyp/12.21.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/home/helio/theia/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/helio/.cache/node-gyp/12.21.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/home/helio/theia/dev-packages/eslint-plugin/node_modules/nsfw',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gmake: Entering directory '/usr/home/helio/theia/dev-packages/eslint-plugin/node_modules/nsfw/build'
  CXX(target) Release/obj.target/nsfw/src/NSFW.o
gyp info spawn gmake
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
In file included from ../src/NSFW.cpp:1:
In file included from ../src/../includes/NSFW.h:5:
In file included from ../includes/NativeInterface.h:11:
In file included from ../includes/../includes/linux/InotifyService.h:4:
../includes/../includes/linux/InotifyEventLoop.h:7:10: fatal error: 'sys/inotify.h' file not found
#include <sys/inotify.h>
         ^~~~~~~~~~~~~~~
1 error generated.
gmake: *** [nsfw.target.mk:126: Release/obj.target/nsfw/src/NSFW.o] Error 1
gmake: Leaving directory '/usr/home/helio/theia/dev-packages/eslint-plugin/node_modules/nsfw/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/home/helio/theia/node_modules/electron-rebuild/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System FreeBSD 13.0-RC1
gyp ERR! command "/usr/local/bin/node" "/usr/home/helio/theia/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/home/helio/theia/dev-packages/eslint-plugin/node_modules/nsfw


Now it is internal error.  Libnotify is a Linux only system call.

**Comment by kittaakos** [comment]
Thanks for letting us know. I found a [patch](https://gist.github.com/prash-wghats/89be1ee069d2acf23c289e9c606616e1),  a [port](https://github.com/tagattie/FreeBSD-VSCode), and a [request](https://github.com/microsoft/vscode/issues/74857) for VS Code. Without some patching, Theia won't run on FreeBSD either.

**Comment by marechal-p** [comment]
@helioloureiro so far most issues you are having are dependency related. That last error concerns NSFW which doesn't build on freebsd because of the `sys/inotify` include you saw... So like @kittaakos said it will be as difficult to run Theia on freebsd as it will be difficult patching our native dependencies to build on that system.
