### ISSUE TITLE
root ERROR [hosted-plugin: 51547] With stack trace: TypeError: s.workspace.onDidRenameFile is not a function

### ISSUE THREAD

**Issue by davewthompson** [eclipse-theia/theia#9296]
Looks like we're missing an implementation of the 'onDidRenameFile' function in Theia:

```
root ERROR [hosted-plugin: 51547] With stack trace: TypeError: s.workspace.onDidRenameFile is not a function
    at new m (/Users/XXX/Projects/git/XXX/theia-testbed/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:67536)
    at s._doRegister (/Users/XXX/Projects/git/XXX/theia-testbed/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:69739)
    at s.update (/Users/XXX/Projects/git/XXX/theia-testbed/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12010)
    at t.VersionDependentRegistration.update (/Users/XXX/Projects/git/XXX/theia-testbed/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12479)
    at new t.VersionDependentRegistration (/Users/XXX/Projects/git/XXX/theia-testbed/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:12278)
    at Object.t.register (/Users/XXX/Projects/git/XXX/theia-testbed/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:69685)
    at /Users/XXX/Projects/git/XXX/theia-testbed/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:1:97526
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Steps to Reproduce:

1. Use the same 'package.json' as the Dockerfile for Python (https://github.com/theia-ide/theia-apps/tree/master/theia-python-docker)
2. Start locally or in Docker.
3. You will see the exception thrown inside 'vscode-builtin-typescript-language-features' when the plugins start.

### Additional Information

- Operating System: macOS Big Sur
- Theia Version: 1.12.1

**Comment by vince-fugnitto** [comment]
@davewthompson thank you for reporting the issue, I verified the behavior using the `package.json` of `theia-python-docker` and on `master` and could not reproduce the problem. In addition, the _rename_ functionality worked correctly.

![image](https://user-images.githubusercontent.com/40359487/113709309-576b6a80-96b0-11eb-96de-4817efcf9143.png)

**Comment by davewthompson** [comment]
I can't replicate it now - sorry to waste your time. Let me close this and raise it again if I find it. Thank you!
