### ISSUE TITLE
[vscode] Support onDidWriteTerminalData

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#9320]
### Steps to Reproduce:

1. Download the https://marketplace.visualstudio.com/items?itemName=genuitecllc.codetogether VS Code extension,
2. See the error:
```
root INFO [hosted-plugin: 536] TypeError: e.onDidWriteTerminalData is not a function
    at i.listenTerminalData (/Users/path/to/project/plugins/genuitecllc.codetogether/extension/out/extension.js:3:307941)
    at /Users/path/to/project/plugins/genuitecllc.codetogether/extension/out/extension.js:3:305889
    at /Users/path/to/project/plugins/genuitecllc.codetogether/extension/out/extension.js:3:191286
    at invoke (/Users/path/to/project/plugins/genuitecllc.codetogether/extension/out/extension.js:3:191375)
    at s.fire (/Users/path/to/project/plugins/genuitecllc.codetogether/extension/out/extension.js:3:192472)
    at Timeout._onTimeout (/Users/path/to/project/plugins/genuitecllc.codetogether/extension/out/extension.js:3:293890)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

### Additional Information

- Operating System:
- Theia Version:

**Comment by eneufeld** [comment]
@ndoschek can you check

**Comment by ndoschek** [comment]
I think this can be closed. onDidWriteTerminalData is a proposed API (https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.terminalDataWriteEvent.d.ts).
The functionality has been superseded by the https://github.com/microsoft/vscode/issues/145234, finalized in August 2024. The CodeTogether extension that originally triggered this no longer throws the error either on activation.
