### ISSUE TITLE
[vscode] Add support for 'vscode.executeCodeActionProvider' command

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#9321]
### Steps to Reproduce:

1. Download the https://marketplace.visualstudio.com/items?itemName=genuitecllc.codetogether VS Code extension,
2. Create a session, join it. see the errors in the log:
```
root ERROR [hosted-plugin: 536] Promise rejection not handled in one second: Error: Command with id 'vscode.executeCodeActionProvider' is not registered. , reason: Error: Command with id 'vscode.executeCodeActionProvider' is not registered.
root ERROR [hosted-plugin: 536] With stack trace: Error: Command with id 'vscode.executeCodeActionProvider' is not registered.
    at CommandRegistryMainImpl.<anonymous> (file:///Users/path/to/project/electron-app/lib/42.bundle.js:3135:35)
    at step (file:///Users/path/to/project/electron-app/lib/42.bundle.js:3045:23)
    at Object.next (file:///Users/path/to/project/electron-app/lib/42.bundle.js:3026:53)
    at file:///Users/path/to/project/electron-app/lib/42.bundle.js:3020:71
    at new Promise (<anonymous>)
    at push.../node_modules/@theia/plugin-ext/lib/main/browser/command-registry-main.js.__awaiter (file:///Users/path/to/project/electron-app/lib/42.bundle.js:3016:12)
    at CommandRegistryMainImpl.push.../node_modules/@theia/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (file:///Users/path/to/project/electron-app/lib/42.bundle.js:3128:16)
    at RPCProtocolImpl.push.../node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (file:///Users/path/to/project/electron-app/lib/36.bundle.js:1373:23)
    at RPCProtocolImpl.push.../node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.invokeHandler (file:///Users/path/to/project/electron-app/lib/36.bundle.js:1358:41)
    at RPCProtocolImpl.push.../node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.receiveRequest (file:///Users/path/to/project/electron-app/lib/36.bundle.js:1322:31)
root ERROR [hosted-plugin: 536] Promise rejection not handled in one second: Error: Command with id 'vscode.executeCodeActionProvider' is not registered. , reason: Error: Command with id 'vscode.executeCodeActionProvider' is not registered.
root ERROR [hosted-plugin: 536] With stack trace: Error: Command with id 'vscode.executeCodeActionProvider' is not registered.
    at CommandRegistryMainImpl.<anonymous> (file:///Users/path/to/project/electron-app/lib/42.bundle.js:3135:35)
    at step (file:///Users/path/to/project/electron-app/lib/42.bundle.js:3045:23)
    at Object.next (file:///Users/path/to/project/electron-app/lib/42.bundle.js:3026:53)
    at file:///Users/path/to/project/electron-app/lib/42.bundle.js:3020:71
    at new Promise (<anonymous>)
    at push.../node_modules/@theia/plugin-ext/lib/main/browser/command-registry-main.js.__awaiter (file:///Users/path/to/project/electron-app/lib/42.bundle.js:3016:12)
    at CommandRegistryMainImpl.push.../node_modules/@theia/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (file:///Users/path/to/project/electron-app/lib/42.bundle.js:3128:16)
    at RPCProtocolImpl.push.../node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (file:///Users/path/to/project/electron-app/lib/36.bundle.js:1373:23)
    at RPCProtocolImpl.push.../node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.invokeHandler (file:///Users/path/to/project/electron-app/lib/36.bundle.js:1358:41)
    at RPCProtocolImpl.push.../node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.receiveRequest (file:///Users/path/to/project/electron-app/lib/36.bundle.js:1322:31)
```

### Additional Information

- Operating System:
- Theia Version:

**Comment by sgraband** [comment]
Command registered in `plugin-vscode-commands-contribution.ts`.
