### ISSUE TITLE
[git] Error message when discarding all changes

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#9327]
### Steps to Reproduce:

1. Change a file,
2. Select `Discard All Changes`, confirm the dialog.
3. See the error message.

![Screen Shot 2021-04-12 at 09 34 55](https://user-images.githubusercontent.com/1405703/114357872-897a4200-9b72-11eb-858d-a99bd98f57ef.jpg)

![Screen Shot 2021-04-12 at 09 35 12](https://user-images.githubusercontent.com/1405703/114357885-8da65f80-9b72-11eb-87d3-7ef104a1ff2b.jpg)

I found this when I was reviewing #9324.

Error from the backend:
```
root ERROR The command `git checkout-index -f -u HEAD -- CHANGELOG.md` exited with an unexpected code: 1. The caller should either handle this error, or expect that exit code.
root ERROR git checkout-index: HEAD is not in the cache

root ERROR Request unstage failed with error: git checkout-index: HEAD is not in the cache
 GitError: git checkout-index: HEAD is not in the cache

    at new GitError (/workspace/theia/node_modules/dugite-extra/lib/core/git.js:87:28)
    at Object.<anonymous> (/workspace/theia/node_modules/dugite-extra/lib/core/git.js:262:27)
    at step (/workspace/theia/node_modules/dugite-extra/lib/core/git.js:56:23)
    at Object.next (/workspace/theia/node_modules/dugite-extra/lib/core/git.js:37:53)
    at fulfilled (/workspace/theia/node_modules/dugite-extra/lib/core/git.js:28:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

### Additional Information

- Operating System:
- Theia Version:

**Comment by FinnChen** [comment]
I submitted a PR to fix this issue. Anyone can help to review the PR? https://github.com/theia-ide/dugite-extra/pull/57
