### ISSUE TITLE
[git][Windows] Repository locator test failure on Windows

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#933]
The test does not fail on Appveyor but on the local Windows image:
```
@theia/git:   git
@theia/git:     repositories
@theia/git:       √ should discover only first repository (3219ms)
@theia/git:       √ should discover all nested repositories (375ms)
@theia/git:       1) should discover all nested repositories and the root repository which is at the workspace root
@theia/git:       √ should discover all nested repositories and the container repository (375ms)
@theia/git:     status
@theia/git: Started watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114-8300-1
1qld28.ucnm
@theia/git: Stopped watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114-8300-1
1qld28.ucnm
@theia/git:       √ modifying a staged file should result in two changes (328ms)
@theia/git:     WorkingDirectoryStatus#equals
@theia/git:       √ staged change should matter
@theia/git:     show
@theia/git:       √ modified in working directory
@theia/git:       √ modified in working directory (nested)
@theia/git: Started watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114-8300-y
12dri.d4qsm
@theia/git: Stopped watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114-8300-y
12dri.d4qsm
@theia/git:       √ modified in index (78ms)
@theia/git: Started watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114-8300-1
q537mv.d1km
@theia/git: Stopped watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114-8300-1
q537mv.d1km
@theia/git:       √ modified in index and in working directory (218ms)
@theia/git:     remote
@theia/git:       √ remotes are not set by default (141ms)
@theia/git:       √ origin is the default after a fresh clone (1500ms)
@theia/git:       √ remotes can be added and queried (219ms)
@theia/git:   12 passing (8s)
@theia/git:   1 failing
@theia/git:   1) git repositories should discover all nested repositories and the root repository which is at the worksp
ace root:
@theia/git:       AssertionError: expected [ 'A', 'B', 'BASE', 'BASE', 'C' ] to deeply equal [ 'A', 'B', 'BASE', 'C' ]
@theia/git:       + expected - actual
@theia/git:        [
@theia/git:          "A"
@theia/git:          "B"
@theia/git:          "BASE"
@theia/git:       -  "BASE"
@theia/git:          "C"
@theia/git:        ]
@theia/git:
@theia/git:       at Proxy.assertEqual (C:\Users\kittaakos\dev\theia\node_modules\chai\lib\chai\core\assertions.js:1020:
19)
@theia/git:       at Proxy.methodWrapper (C:\Users\kittaakos\dev\theia\node_modules\chai\lib\chai\utils\addMethod.js:57:
25)
@theia/git:       at Suite.<anonymous> (src\node\dugite-git.spec.ts:87:101)
@theia/git:       at step (src\node\dugite-git.spec.ts:38:23)
@theia/git:       at Object.next (src\node\dugite-git.spec.ts:19:53)
@theia/git:       at fulfilled (src\node\dugite-git.spec.ts:10:58)
@theia/git:       at <anonymous>
@theia/git: npm ERR! code ELIFECYCLE
@theia/git: npm ERR! errno 1
@theia/git: npm ERR! @theia/git@0.2.3 test: `theiaext test`
@theia/git: npm ERR! Exit status 1
@theia/git: npm ERR!
@theia/git: npm ERR! Failed at the @theia/git@0.2.3 test script.
@theia/git: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@theia/git: npm ERR! A complete log of this run can be found in:
@theia/git: npm ERR!     C:\Users\kittaakos\AppData\Roaming\npm-cache\_logs\2017-12-04T09_52_24_494Z-debug.log
lerna ERR! execute Error: Command failed: npm run test
lerna ERR! execute
lerna ERR! execute ┌────────────────────────────────────────────────────────────────┐
lerna ERR! execute │                    npm update check failed                     │
lerna ERR! execute │              Try running with sudo or get access               │
lerna ERR! execute │              to the local update config store via              │
lerna ERR! execute │ sudo chown -R $USER:$(id -gn $USER) C:\Users\kittaakos\.config │
lerna ERR! execute └────────────────────────────────────────────────────────────────┘
lerna ERR! execute npm ERR! code ELIFECYCLE
lerna ERR! execute npm ERR! errno 1
lerna ERR! execute npm ERR! @theia/git@0.2.3 test: `theiaext test`
lerna ERR! execute npm ERR! Exit status 1
lerna ERR! execute npm ERR!
lerna ERR! execute npm ERR! Failed at the @theia/git@0.2.3 test script.
lerna ERR! execute npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR! execute
lerna ERR! execute npm ERR! A complete log of this run can be found in:
lerna ERR! execute npm ERR!     C:\Users\kittaakos\AppData\Roaming\npm-cache\_logs\2017-12-04T09_52_24_494Z-debug.log
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute > @theia/git@0.2.3 test C:\Users\kittaakos\dev\theia\packages\git
lerna ERR! execute > theiaext test
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute   git
lerna ERR! execute     repositories
lerna ERR! execute       √ should discover only first repository (3219ms)
lerna ERR! execute       √ should discover all nested repositories (375ms)
lerna ERR! execute       1) should discover all nested repositories and the root repository which is at the workspace ro
ot
lerna ERR! execute       √ should discover all nested repositories and the container repository (375ms)
lerna ERR! execute     status
lerna ERR! execute Started watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114
-8300-11qld28.ucnm
lerna ERR! execute Stopped watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114
-8300-11qld28.ucnm
lerna ERR! execute       √ modifying a staged file should result in two changes (328ms)
lerna ERR! execute     WorkingDirectoryStatus#equals
lerna ERR! execute       √ staged change should matter
lerna ERR! execute     show
lerna ERR! execute       √ modified in working directory
lerna ERR! execute       √ modified in working directory (nested)
lerna ERR! execute Started watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114
-8300-y12dri.d4qsm
lerna ERR! execute Stopped watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114
-8300-y12dri.d4qsm
lerna ERR! execute       √ modified in index (78ms)
lerna ERR! execute Started watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114
-8300-1q537mv.d1km
lerna ERR! execute Stopped watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114
-8300-1q537mv.d1km
lerna ERR! execute       √ modified in index and in working directory (218ms)
lerna ERR! execute     remote
lerna ERR! execute       √ remotes are not set by default (141ms)
lerna ERR! execute       √ origin is the default after a fresh clone (1500ms)
lerna ERR! execute       √ remotes can be added and queried (219ms)
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute   12 passing (8s)
lerna ERR! execute   1 failing
lerna ERR! execute
lerna ERR! execute   1) git repositories should discover all nested repositories and the root repository which is at the
 workspace root:
lerna ERR! execute
lerna ERR! execute       AssertionError: expected [ 'A', 'B', 'BASE', 'BASE', 'C' ] to deeply equal [ 'A', 'B', 'BASE',
'C' ]
lerna ERR! execute       + expected - actual
lerna ERR! execute
lerna ERR! execute        [
lerna ERR! execute          "A"
lerna ERR! execute          "B"
lerna ERR! execute          "BASE"
lerna ERR! execute       -  "BASE"
lerna ERR! execute          "C"
lerna ERR! execute        ]
lerna ERR! execute
lerna ERR! execute       at Proxy.assertEqual (C:\Users\kittaakos\dev\theia\node_modules\chai\lib\chai\core\assertions.j
s:1020:19)
lerna ERR! execute       at Proxy.methodWrapper (C:\Users\kittaakos\dev\theia\node_modules\chai\lib\chai\utils\addMethod
.js:57:25)
lerna ERR! execute       at Suite.<anonymous> (src\node\dugite-git.spec.ts:87:101)
lerna ERR! execute       at step (src\node\dugite-git.spec.ts:38:23)
lerna ERR! execute       at Object.next (src\node\dugite-git.spec.ts:19:53)
lerna ERR! execute       at fulfilled (src\node\dugite-git.spec.ts:10:58)
lerna ERR! execute       at <anonymous>
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute     at Promise.all.then.arr (C:\Users\kittaakos\dev\theia\node_modules\execa\index.js:236:11)
lerna ERR! execute     at <anonymous>
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:188:7)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: Command failed: npm run test
lerna ERR! execute
lerna ERR! execute ┌────────────────────────────────────────────────────────────────┐
lerna ERR! execute │                    npm update check failed                     │
lerna ERR! execute │              Try running with sudo or get access               │
lerna ERR! execute │              to the local update config store via              │
lerna ERR! execute │ sudo chown -R $USER:$(id -gn $USER) C:\Users\kittaakos\.config │
lerna ERR! execute └────────────────────────────────────────────────────────────────┘
lerna ERR! execute npm ERR! code ELIFECYCLE
lerna ERR! execute npm ERR! errno 1
lerna ERR! execute npm ERR! @theia/git@0.2.3 test: `theiaext test`
lerna ERR! execute npm ERR! Exit status 1
lerna ERR! execute npm ERR!
lerna ERR! execute npm ERR! Failed at the @theia/git@0.2.3 test script.
lerna ERR! execute npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR! execute
lerna ERR! execute npm ERR! A complete log of this run can be found in:
lerna ERR! execute npm ERR!     C:\Users\kittaakos\AppData\Roaming\npm-cache\_logs\2017-12-04T09_52_24_494Z-debug.log
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute > @theia/git@0.2.3 test C:\Users\kittaakos\dev\theia\packages\git
lerna ERR! execute > theiaext test
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute   git
lerna ERR! execute     repositories
lerna ERR! execute       √ should discover only first repository (3219ms)
lerna ERR! execute       √ should discover all nested repositories (375ms)
lerna ERR! execute       1) should discover all nested repositories and the root repository which is at the workspace ro
ot
lerna ERR! execute       √ should discover all nested repositories and the container repository (375ms)
lerna ERR! execute     status
lerna ERR! execute Started watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114
-8300-11qld28.ucnm
lerna ERR! execute Stopped watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114
-8300-11qld28.ucnm
lerna ERR! execute       √ modifying a staged file should result in two changes (328ms)
lerna ERR! execute     WorkingDirectoryStatus#equals
lerna ERR! execute       √ staged change should matter
lerna ERR! execute     show
lerna ERR! execute       √ modified in working directory
lerna ERR! execute       √ modified in working directory (nested)
lerna ERR! execute Started watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114
-8300-y12dri.d4qsm
lerna ERR! execute Stopped watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114
-8300-y12dri.d4qsm
lerna ERR! execute       √ modified in index (78ms)
lerna ERR! execute Started watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114
-8300-1q537mv.d1km
lerna ERR! execute Stopped watching the git repository: file:///c%3A/Users/KITTAA~1/AppData/Local/Temp/status-test117114
-8300-1q537mv.d1km
lerna ERR! execute       √ modified in index and in working directory (218ms)
lerna ERR! execute     remote
lerna ERR! execute       √ remotes are not set by default (141ms)
lerna ERR! execute       √ origin is the default after a fresh clone (1500ms)
lerna ERR! execute       √ remotes can be added and queried (219ms)
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute   12 passing (8s)
lerna ERR! execute   1 failing
lerna ERR! execute
lerna ERR! execute   1) git repositories should discover all nested repositories and the root repository which is at the
 workspace root:
lerna ERR! execute
lerna ERR! execute       AssertionError: expected [ 'A', 'B', 'BASE', 'BASE', 'C' ] to deeply equal [ 'A', 'B', 'BASE',
'C' ]
lerna ERR! execute       + expected - actual
lerna ERR! execute
lerna ERR! execute        [
lerna ERR! execute          "A"
lerna ERR! execute          "B"
lerna ERR! execute          "BASE"
lerna ERR! execute       -  "BASE"
lerna ERR! execute          "C"
lerna ERR! execute        ]
lerna ERR! execute
lerna ERR! execute       at Proxy.assertEqual (C:\Users\kittaakos\dev\theia\node_modules\chai\lib\chai\core\assertions.j
s:1020:19)
lerna ERR! execute       at Proxy.methodWrapper (C:\Users\kittaakos\dev\theia\node_modules\chai\lib\chai\utils\addMethod
.js:57:25)
lerna ERR! execute       at Suite.<anonymous> (src\node\dugite-git.spec.ts:87:101)
lerna ERR! execute       at step (src\node\dugite-git.spec.ts:38:23)
lerna ERR! execute       at Object.next (src\node\dugite-git.spec.ts:19:53)
lerna ERR! execute       at fulfilled (src\node\dugite-git.spec.ts:10:58)
lerna ERR! execute       at <anonymous>
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute
lerna ERR! execute     at Promise.all.then.arr (C:\Users\kittaakos\dev\theia\node_modules\execa\index.js:236:11)
lerna ERR! execute     at <anonymous>
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by kittaakos** [comment]
Moved from #936:

@kittaakos wrote:
So this was ignored and removed [here](https://github.com/theia-ide/theia/pull/899/files#diff-69295d120802b4b29a7814968dc5de90L53).

My test fails currently, and I have the following path:
 - CONTAINING PATH c:\Users\kittaakos\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE
 - **CONTAINING PATH c:\Users\kittaakos\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE**
 - **REPOSITORY PATH c:\Users\KITTAA~1\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE**
 - CONTAINING PATH c:\Users\kittaakos\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE
 - REPOSITORY PATH c:\Users\KITTAA~1\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE\A
 - CONTAINING PATH c:\Users\kittaakos\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE
 - REPOSITORY PATH c:\Users\KITTAA~1\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE\B
 - CONTAINING PATH c:\Users\kittaakos\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE
 - REPOSITORY PATH c:\Users\KITTAA~1\AppData\Local\Temp\discovery-test-2117115-8020-as07s0.0uipf\BASE\C

The marked lines are pointing to the same location but the FS path (strings) are different.

 - I've replaced it with fs.realpath which should return a canonical name, i.e. resolve symlinks and normalize paths. It could be that it has bugs on Windows or I missed some places.

- Ohh, I wanted to post this to #933. I move everything there. Sorry. And thanks for the hint. I try fs-extra#realpath outside from Theia.

**Comment by kittaakos** [comment]
`fs.realpath` does not normalize the FAT 8.3 file names:
```js
const temp = require('temp');
const fs = require('fs-extra');

const track = temp.track();
const path = track.mkdirSync('foo');

console.log(path); // C:\Users\KITTAA~1\AppData\Local\Temp\foo117115-2972-11j4sb5.bro
console.log(fs.realpathSync(path)); // C:\Users\KITTAA~1\AppData\Local\Temp\foo117115-2972-11j4sb5.bro
```

**Comment by akosyakov** [comment]
and another way around? What does it do with `C:\Users\kittaakos\AppData\Local\Temp\foo117115-2972-11j4sb5.bro`?

**Comment by kittaakos** [comment]
Does nothing:
```js
const temp = require('temp');
const fs = require('fs-extra');

const track = temp.track();
const path = track.mkdirSync('foo');

console.log(path); // C:\Users\KITTAA~1\AppData\Local\Temp\foo117115-2972-11j4sb5.bro
console.log(fs.realpathSync(path)); // C:\Users\KITTAA~1\AppData\Local\Temp\foo117115-2972-11j4sb5.bro

const replaced = path.replace('KITTAA~1', 'kittaakos');
console.log(replaced, fs.existsSync(replaced)); // C:\Users\kittaakos\AppData\Local\Temp\foo117115-2972-11j4sb5.bro true
console.log(fs.realpathSync(replaced)); // C:\Users\kittaakos\AppData\Local\Temp\foo117115-2972-11j4sb5.bro
```

**Comment by kittaakos** [comment]
This problem is deeper than I have initially expected:
 - First off, one can workaround this issue with `temp` by passing in the [`AffixOptions`](https://github.com/bruce/node-temp#affixes). This did not work for me. It turned out the problem was somewhere else.
 - Simply calling `require('os').tmpdir()` returns with the [8.3 filename](https://en.wikipedia.org/wiki/8.3_filename) format instead of the long one.
 - I started to investigate the environment variables:
   - `@ECHO %TEMP%` prints the 8.3 format although that looks good in the UI:
   - Then, I have checked `@ECHO %USERPROFILE%`, which is correct and prints the long name. Also seems to be fine in the UI.

<img width="534" alt="screen shot 2017-12-05 at 16 53 34" src="https://user-images.githubusercontent.com/1405703/33616757-226ad498-d9de-11e7-810d-e2ffbc90f4dd.png">

<img width="584" alt="screen shot 2017-12-05 at 16 53 49" src="https://user-images.githubusercontent.com/1405703/33616797-430c03ca-d9de-11e7-8a60-384575c22c95.png">

I will also try to modify the [`NtfsDisable8dot3NameCreation`](https://technet.microsoft.com/en-us/library/cc959352.aspx) variable...

**Comment by JonasHelming** [comment]
@kittaakos Is this still relevant? Please close if not...
