### ISSUE TITLE
TerminalWidget prints Error for quickly finished Tasks

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#9350]
### Bug Description:
When creating a shell task with a command that is finished very quickly (I did `dir` on Windows), the TerminalWidget prints an error message to the log: 

```
root ERROR Request getCwdURI failed with error: terminal "4" does not exist Error: terminal "4" does not exist
    at ShellTerminalServer.<anonymous> (C:\Users\thomas\code\chedev\theia\packages\terminal\lib\node\base-terminal-server.js:158:27)
    at step (C:\Users\thomas\code\chedev\theia\packages\terminal\lib\node\base-terminal-server.js:60:23)
    at Object.next (C:\Users\thomas\code\chedev\theia\packages\terminal\lib\node\base-terminal-server.js:41:53)
    at C:\Users\thomas\code\chedev\theia\packages\terminal\lib\node\base-terminal-server.js:35:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\thomas\code\chedev\theia\packages\terminal\lib\node\base-terminal-server.js:31:12)
    at ShellTerminalServer.BaseTerminalServer.getCwdURI (C:\Users\thomas\code\chedev\theia\packages\terminal\lib\node\base-terminal-server.js:153:16)
    at JsonRpcProxyFactory.<anonymous> (C:\Users\thomas\code\chedev\theia\packages\core\lib\common\messaging\proxy-factory.js:213:73)
    at step (C:\Users\thomas\code\chedev\theia\packages\core\lib\common\messaging\proxy-factory.js:48:23)
    at Object.next (C:\Users\thomas\code\chedev\theia\packages\core\lib\common\messaging\proxy-factory.js:29:53)
```

Debugging through the scenario, I found that there is no real problem happening: it's just the process gets unregistered from the ProcessManager when it ends and the above request happens afterwards. The exception does not seem to have any negative effects on system behavior. I can see the stdout output from the process correctly.

### Steps to Reproduce:

1. Add a 'shell' task to tasks.json just doing `dir`
2. Execute it
3. Observe the exception in the back end log

### Additional Information

- Operating System: Windows.
- Theia Version:

**Comment by RomanNikitenko** [comment]
There is an issue https://github.com/eclipse-theia/theia/issues/2961
Maybe they both have the same cause.
