### ISSUE TITLE
root ERROR Uncaught Exception:  Error: Connection got disposed.

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#9606]
### Bug Description:
Hi,
Sometimes I am getting this error many times one after another until Theia stopped and needs restart.

### Steps to Reproduce:

Not sure but this could happen once I refresh the page while it still loading some plugins.

```
root ERROR Uncaught Exception:  Error: Connection got disposed.
root ERROR Error: Connection got disposed.
    at Object.dispose (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\main.js:904:25)
    at C:\home\k2view\webStudio\node_modules\vscode-ws-jsonrpc\lib\socket\connection.js:14:41
    at CallbackList.invoke (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at closeHandler (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\main.js:240:26)
    at CallbackList.invoke (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at WebSocketMessageReader.fireClose (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at WebSocketMessageReader.fireClose (C:\home\k2view\webStudio\node_modules\vscode-ws-jsonrpc\lib\socket\reader.js:67:19)
    at C:\home\k2view\webStudio\node_modules\vscode-ws-jsonrpc\lib\socket\reader.js:24:18
root ERROR Uncaught Exception:  Error: Connection got disposed.
root ERROR Error: Connection got disposed.
    at Object.dispose (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\main.js:904:25)
    at C:\home\k2view\webStudio\node_modules\vscode-ws-jsonrpc\lib\socket\connection.js:14:41
    at CallbackList.invoke (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at closeHandler (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\main.js:240:26)
    at CallbackList.invoke (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at WebSocketMessageReader.fireClose (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at WebSocketMessageReader.fireClose (C:\home\k2view\webStudio\node_modules\vscode-ws-jsonrpc\lib\socket\reader.js:67:19)
    at C:\home\k2view\webStudio\node_modules\vscode-ws-jsonrpc\lib\socket\reader.js:24:18
root ERROR Uncaught Exception:  Error: Connection got disposed.
root ERROR Error: Connection got disposed.
    at Object.dispose (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\main.js:904:25)
    at C:\home\k2view\webStudio\node_modules\vscode-ws-jsonrpc\lib\socket\connection.js:14:41
    at CallbackList.invoke (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at closeHandler (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\main.js:240:26)
    at CallbackList.invoke (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at WebSocketMessageReader.fireClose (C:\home\k2view\webStudio\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at WebSocketMessageReader.fireClose (C:\home\k2view\webStudio\node_modules\vscode-ws-jsonrpc\lib\socket\reader.js:67:19)
    at C:\home\k2view\webStudio\node_modules\vscode-ws-jsonrpc\lib\socket\reader.js:24:18
```

### Additional Information

- Operating System: Wondow 10
- Theia Version: 1.14 (latest)

**Comment by vince-fugnitto** [comment]
@safisa please see past discussions related to `vscode-jsonrpc` connection disposal logs:
- https://github.com/eclipse-theia/theia/discussions/8545
- https://github.com/eclipse-theia/theia/issues/8939
- https://github.com/TypeFox/vscode-ws-jsonrpc/issues/24

**Comment by vince-fugnitto** [comment]
Closing due to inactivity.
