### ISSUE TITLE
Install failed on Windows7

### ISSUE THREAD

**Issue by Luin-Li** [eclipse-theia/theia#9668]
use yarn@1.22.5 and node@12.14.1. I get the error.

I have installed the related windows sdk but it still not work.

```
[5/5] Building fresh packages...
[6/14] ⠄ drivelist
[10/14] ⡀ oniguruma
[3/14] ⡀ puppeteer
[9/14] ⡀ nsfw
error F:\chop\theia\theia\node_modules\native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: F:\chop\theia\theia\node_modules\native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@12.14.1 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\Administrator\.windows-build-tools\python27\python.exe"
gyp http GET https://nodejs.org/download/release/v12.14.1/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v12.14.1/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v12.14.1/win-x64/node.lib
gyp http GET https://nodejs.org/download/release/v12.14.1/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v12.14.1/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v12.14.1/SHASUMS256.txt
gyp http 404 https://nodejs.org/download/release/v12.14.1/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v12.14.1/win-x64/node.lib
gyp info find VS using VS2017 (15.9.28307.1525) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\Administrator\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'F:\\chop\\theia\\theia\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\chop\\theia\\theia\\node_modules\\native-keymap\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'F:\\chop\\theia\\theia\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\12.14.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\12.14.1',
gyp info spawn args   '-Dnode_gyp_dir=F:\\chop\\theia\\theia\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.14.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=F:\\chop\\theia\\theia\\node_modules\\native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'F:\\chop\\theia\\theia\\node_modules\\native-keymap\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  string_conversion.cc
  keymapping.cc
  keyboard_win.cc
  win_delay_load_hook.cc
LINK : fatal error LNK1104: cannot open file 'C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\12.14.1\\x64\\node.lib' [F:\chop\theia\theia\node_modules\native-keymap\build\keymapping.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (F:\chop\theia\theia\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\chop\\theia\\theia\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\chop\theia\theia\node_modules\native-keymap
```

**Comment by vince-fugnitto** [comment]
@Luin-Li I believe `node-gyp` errors are notoriously problematic on windows ([article](https://spin.atomicobject.com/2019/03/27/node-gyp-windows/))

Can you try performing the following:
- `npm install --global windows-build-tools --vs2017`
- `git clean -ffdx`
- `yarn`

Please also note limitations with `node-gyp`, highlighted in the build steps of vscode as well:
- https://github.com/nodejs/node-gyp/issues/297

**Comment by Luin-Li** [comment]
After I try the list of performing, check my pathname without Chinese(The user name is Administrator) and change my folder name from showing '用户' to 'Users', it still not work.

**Comment by Luin-Li** [comment]
I solved the problem.After I uninstall scoop and yarn (I installed yarn by scoop), I reinstall yarn by npm and delete the npm config of npm_config_tarball which I setted it to solve other problem.
