### ISSUE TITLE
vscode built in simple browser extension doesn't work

### ISSUE THREAD

**Issue by swexler-coursera** [eclipse-theia/theia#9767]
### Bug Description:
The vscode built-in simple browser extension doesn't work.  I see the following error during startup:

```
root ERROR [hosted-plugin: 223] Unsupported activation events: onOpenExternalUri:http, onOpenExternalUri:https, please open an issue: https://github.com/eclipse-theia/theia/issues/new
```

and when trying to run the extension, see this error:

```
root ERROR [hosted-plugin: 223] Activating extension 'Simple Browser (built-in)' failed: TypeError: o.window.registerExternalUriOpener is not a function
    at t.activate (/home/theia/plugins/vscode-builtin-simple-browser/extension/dist/extension.js:1:7819)
    at PluginManagerExtImpl.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:556:87)
    at step (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:48:23)
    at Object.next (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:29:53)
    at /home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:19:12)
    at PluginManagerExtImpl.startPlugin (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:523:16)
    at PluginManagerExtImpl.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:445:63)
    at step (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:48:23)
```

### Steps to Reproduce:

1. Add the following to the theiaPlugins section of package.json to install
` "vscode-builtin-simple-browser": "https://open-vsx.org/api/vscode/simple-browser/1.57.1/file/vscode.simple-browser-1.57.1.vsix" `
2. Install plugins with 
`RUN yarn --cache-folder ./ycache && rm -rf ./ycache && \
     NODE_OPTIONS="--max_old_space_size=4096" yarn theia build && yarn theia download:plugins `
3. Run theia
3. View -> Find Command -> Simple Browser: Show

### Additional Information

- Operating System: Built on MacOS into a docker container based on theiaide/theia-full:1.15.0
- Theia Version: 1.15.0

**Comment by vince-fugnitto** [comment]
@swexler-coursera thank you for reporting the issue.

The API referenced (`registerExternalUriOpener`) including the activation events tied to it are currently `proposed` and not yet finalized (only available to insiders versions of vscode for the moment).

- https://github.com/microsoft/vscode/blob/b9c8788542ae696d872eb14cf9b68bfd1fe9bf42/src/vs/vscode.proposed.d.ts#L2111-L2125

I do not believe there is a version of `simple-browser` yet supported by the framework for this reason, and the fact that there is no version known to be compatible on open-vsx based on the supported level by the framework (currently `1.50.0`). You are free however to try and implement the API if you're interested, but note it may be changed as it is only `proposed`.

**Comment by vince-fugnitto** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/12523.
