### ISSUE TITLE
Command with id 'vscode.openWith' is not registered

### ISSUE THREAD

**Issue by ishche** [eclipse-theia/theia#9865]
### Steps to Reproduce:

1. Install the custom-editor-sample extension from https://github.com/microsoft/vscode-extension-samples
2. Issue a "Create new Paw Draw Document" command

Expected:
Custom editor window
Observed:
The custom editor is not open and there is an exception:
```
root ERROR [hosted-plugin: 51252] Promise rejection not handled in one second: Error: Command with id 'vscode.openWith' is not registered. , reason: Error: Command with id 'vscode.openWith' is not registered.
root ERROR [hosted-plugin: 51252] With stack trace: Error: Command with id 'vscode.openWith' is not registered.
    at CommandRegistryMainImpl.<anonymous> (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.bundle.js:2289:35)
    at step (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.bundle.js:2199:23)
    at Object.next (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.bundle.js:2180:53)
    at http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.bundle.js:2174:71
    at new Promise (<anonymous>)
    at push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.__awaiter (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.bundle.js:2170:12)
    at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.bundle.js:2282:16)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (http://localhost:3000/packages_plugin-ext_lib_common_plugin-api-rpc_js.bundle.js:963:23)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.invokeHandler (http://localhost:3000/packages_plugin-ext_lib_common_plugin-api-rpc_js.bundle.js:948:41)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.RPCProtocolImpl.receiveRequest (http://localhost:3000/packages_plugin-ext_lib_common_plugin-api-rpc_js.bundle.js:912:31)
```

### Additional Information

- Operating System: MacOs
- Theia Version: master (7e09e93a7a741137a9581125e8df39bcfeb05ee5)

**Comment by vince-fugnitto** [comment]
@ishche thank you for reporting the issue, is it something you're interested in implementing? 
We can provide assistance if necessary :+1:

**Comment by ishche** [comment]
Hello @vince-fugnitto! Could you describe on a high level what should be done here?

**Comment by vince-fugnitto** [comment]
> Hello @vince-fugnitto! Could you describe on a high level what should be done here?

Sure. at a high-level the issue should be resolved by implementing a mapping of the vscode command `vscode.openWith` with either an existing command present in the framework already to support opening resources with different providers, or by implementing it yourself.

The idea will be to add the `vscode.openWith` command to `plugin-vscode-command-contribution.ts`:

https://github.com/eclipse-theia/theia/blob/19ace46f5dadc3345cc14a7edf9f85a9a025a9b0/packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts#L225-L227

And map it (in the `execute`) to a known framework command (you may want to try the following as it supports opening resources with different providers):

https://github.com/eclipse-theia/theia/blob/19ace46f5dadc3345cc14a7edf9f85a9a025a9b0/packages/workspace/src/browser/workspace-commands.ts#L95-L97
